### ISSUE TITLE
Bonuses Spam

### ISSUE THREAD

**Issue by BruceFradgLee** [Rocologo/MobHunting#102]
Hiya,

Just wondering if there's an option to disable the bonuses text from displaying as have not found anything in the config file. When killing multiple mobs it can become very spammy and i want to disable this while keeping the bonuses feature active.

Cheers

**Comment by Rocologo** [comment]
Please be more specific, Im not sure about which text messages you are taking about?

**Comment by BruceFradgLee** [comment]
The text appears in the chat (personal to player) after each kill. "You gained $7.50! with x1.5. Difficulty. Brawler"
This changes depending on how the mob is killed sometimes with 4 or 5 bonuses showing.

**Comment by Rocologo** [comment]
You could install titlemanager this plugin mobs alot of the text messages to titlebar or actionbar.
https://www.spigotmc.org/resources/titlemanager.1049/

**Comment by BruceFradgLee** [comment]
I wasn't really wanting the text moved location. I was more wondering if there was an option to disable it in the config? (Or whether this would be optional in a future update)

On 13 Nov 2016, at 23:41, Rocologo <notifications@github.com<mailto:notifications@github.com>> wrote:


You could install titlemanager this plugin mobs alot of the text messages to titlebar or actionbar.
https://www.spigotmc.org/resources/titlemanager.1049/

-

**Comment by Rocologo** [comment]
Have you tried "/mh mute" ?
