### ISSUE TITLE
Double Payments

### ISSUE THREAD

**Issue by XxDILBERTxX** [Rocologo/MobHunting#107]
When using "drop-money-on-groud: true" you also still get the direct deposit
using MobHunting V4.2.6 w/ Spigot/Bukkit 1.11

Update:
Its just the chat message that you gained $ its not depositing.. Sorry

**Comment by XxDILBERTxX** [comment]
i guess a better thing to Bug about would be the fact that you can't disable individual messages ..
Can it be set so if there is no line or if its blank in the .lang it disables the message?

As of now i have a costume .lang
with blank lines:
mobhunting.moneygain.bonuses=
mobhunting.moneypickup=

Only problem is that it post the blank lines to the chat.

**Comment by Rocologo** [comment]
If you dont want to see the messages, you just mute them.

**Comment by XxDILBERTxX** [comment]
Sorry maybe im missing something but what exactly do i mute?
Im assuming anything i could mute would hit the entire plugin?,
I would still like to get the achievements and other notifications. just not the stuff that spams the chat when in combat..

And thanks for the Great plugin By the way!

**Comment by Rocologo** [comment]
Ah, then I recommend TitleManager, it reduces then information send to the chat

**Comment by Rocologo** [comment]
Also check /mh learn

**Comment by XxDILBERTxX** [comment]
Ok, only "TitleManager"s i see are just to add a Tidle/Rank to players
And /mh learn just told me that "the admin disabled Mobhunt" after 3-4 normal kills.

But its ok the blank lang lines are good enough.
Thanx again..

**Comment by Rocologo** [comment]
1. The link to TitleManager is in the plugin description. 
2. Strange message, Ill look at this but  my guess is that you are missing permisstion to the learn command. ( mobhunting.learn )

**Comment by XxDILBERTxX** [comment]
Thanks again, TitleManager is a great addition.. 
That +the blank lang lines is exactly what i was going for..
