### ISSUE TITLE
MH:enabled is false

### ISSUE THREAD

**Issue by ItsFricco** [Rocologo/MobHunting#115]
Can't get it to work, says **MH:enabled is false** and **Hunting is disabled for player** when debug is turned on. What should i do?

**Comment by ItsFricco** [comment]
im stupid...

**Comment by ItsFricco** [comment]
Thought i had it but i did not, help appreciated.

**Comment by ItsFricco** [comment]
Developer?

**Comment by Rocologo** [comment]
It means that that the player has no permission to do mobhunting

**Comment by Rocologo** [comment]
hello?
