### ISSUE TITLE
Fishing issue

### ISSUE THREAD

**Issue by 00petar00** [Rocologo/MobHunting#118]
Any time i manage to catch something with a rod, doesn't matter what it is even if it is junk, it displays command text as if i found a head, while no head was given nor found. I use mcmmo so it may be a plugin conflict, i'll do some further testing when i can. 

Pastebin:
http://pastebin.com/KThRtNPc

EDIT: Forgot to add that money earned when you manage to catch a fish isn't really working at all.

**Comment by Sikatsu** [comment]
Same issue. I also use McMMO, however sometimes a head is given, sometimes it isn't.

**Comment by Rocologo** [comment]
Please test build 264

**Comment by Sikatsu** [comment]
Unfixed, I just catched a ghast tear and wooden axe and it still said I received a salmon head.

**Comment by Rocologo** [comment]
This should not be possible in build 267

**Comment by Sikatsu** [comment]
That is incorrect. While I do not receive any heads, the message still appears at all costs.

**Comment by Rocologo** [comment]
Sorry - V4.3.9 should fix it this time ....

**Comment by Sikatsu** [comment]
This issue is fixed in my case - I do no longer receive the message about ''You got a fish head''.
