### ISSUE TITLE
Fishing heads issue

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#119]
It still says ''You got a fish head'' even while the chance is set to 0.0.

**Comment by Sikatsu** [comment]
It seems when I set money reward from fishing to 0, to disable money rewards for fishing, this issue is fixed. But ofcourse that's not the way it should be fixed, as I want money but not the heads ^^

**Comment by Rocologo** [comment]
You should remove the /mobhunt head give player fish from the fishing section in your config.yml

**Comment by Sikatsu** [comment]
Ah, I see. Slightly different from mobs then? Not that I mind, just maybe nice to add an extra line of information in the config?

**Comment by Rocologo** [comment]
No its not different from mobs.

**Comment by Sikatsu** [comment]
For mobs I just have the chance set to 0.0, and the heads don't drop anymore, didn't remove anything there

**Comment by Sikatsu** [comment]
@Rocologo 

And how exactly do you want me to remove it? '' nor [] works to disable that line. Leaving it blank also doesn't work.

**Comment by Sikatsu** [comment]
This issue is fixed in my case, I do no longer receive fishing heads nor the message when the chance is set to 0.0. If this is correct (as you first said to remove the command) then this may be marked as solved, I guess.
