### ISSUE TITLE
Fishing gives a reward for junk

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#120]
Fishing doesn't only give money for fishes, but also for every other item I catch.

As you see, running MobHunting 4.3.8, catched a fish, a salmon and an iron legging. The iron legging gave cash + the message it gives a fish head. (http://prntscr.com/e3sokt)

**Comment by Rocologo** [comment]
This should be fixed in build 264.

**Comment by Sikatsu** [comment]
Awesome! I will test the build and let you know once I wake up.

**Comment by Sikatsu** [comment]
I just catched a wooden axe and ghast tear and it was registered as a ''Salmon''. So this remains unfixed.

**Comment by Rocologo** [comment]
I need the debug information from the console when this happens.

**Comment by Sikatsu** [comment]
Let me get this, moment.

**Comment by Sikatsu** [comment]
This is the item I catched: http://prntscr.com/e4ewrh

This is the debug: http://pastebin.com/9kgsq5Dz

I received cash + head message (but no head)

**Comment by Rocologo** [comment]
Please use newest build
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Sikatsu** [comment]
I will test this. Give me a moment.

**Comment by Sikatsu** [comment]
@Rocologo 

This is not fixed in B266.

Debug: http://pastebin.com/dvDk45a4
It was a stone pickaxe.

**Comment by Sikatsu** [comment]
Debug: http://pastebin.com/ayryCXis
It was a golden boots.

(I also just catched an iron pickaxe, without money reward, neither any debug)

**Comment by Sikatsu** [comment]
@Rocologo 

This remains unfixed.

Debug: http://pastebin.com/tDxHsE9W
It was a golden sword.

(I also just catched an enchanted stone spade, and it didn't reward money, so it seems to work half)

**Comment by Rocologo** [comment]
Hey... Its okay to catch "droped_items" thats standard Minecraft, its not something I have made :-)

You just dont get any MobHuntning(Fishing rewards) Niether money nor a runCommand.

I dont thing I should cancel these items, since its standard Minecraft.

But I could add it as a new feature if you wanted that???

**Comment by Rocologo** [comment]
I saw the pastebin AFTER I wrote the answer

But the console log says you caught fishes

Sikatsu caught a RAW_FISH(0) (State=CAUGHT_FISH) 

?????

**Comment by Sikatsu** [comment]
The problem is that I receive cash from MobHunting, for items. I would like to only receive cash for ''Fish''.

**Comment by Rocologo** [comment]
But it says you caught a fish??? RAW_FISH(0)

**Comment by Sikatsu** [comment]
Indeed. It says I caught a fish, but I didn't, I catched the items I mentioned. Somehow mobhunting registers every item I catch as a fish, and gives money for that.

**Comment by Rocologo** [comment]
I cant replicate this problem, but i will do some more fishing i the morning

**Comment by Sikatsu** [comment]
Maybe this is related to McMMO, you can test McMMO for free using the devbuilds: https://ci.drtshock.net/job/MCMMO/

Let me know whether you can replicate it using McMMO. (Would be weird though, it's still an item?)

**Comment by Sikatsu** [comment]
@Rocologo Did you find anything?

**Comment by Sikatsu** [comment]
Waiting for this one to be fixed before I can use it on my main server :P

**Comment by Sikatsu** [comment]
Or is it easier to add items within the config with an option to set rewards for items really low?

**Comment by Rocologo** [comment]
I just tested this on my own test server with mcmmo installed. And yes I caught a record although in the log it said I caught a fish. This could happen if mcmmo changes the item after I have given the reward for the fish.

Then I checked the item (record) in this list http://minecraft.gamepedia.com/Fishing
This also indicates that it is mcmmo who is doing something.

I will try lowing the priority on my PlayerFishEvent and see if this error still occurs.

**Comment by Sikatsu** [comment]
Awesome :)

**Comment by Rocologo** [comment]
I just did lowering the priority made it verse. Now I caught fish without getting a reward.

**Comment by Sikatsu** [comment]
Hmm that's not good.

**Comment by Sikatsu** [comment]
Maybe add McMMO support?

**Comment by Rocologo** [comment]
I changed the priority from Low to Normal to High. When its Normal and High my event seems to work, except that mcmmo seems to change the item from a fish to something else after I pay the reward.

So yes, the solution is to add support for mcmmo, so I will have to check if they have an API and if they have made an alternative fishing event.

**Comment by Sikatsu** [comment]
Awesome, let me know once I need to test something. I do know that the plugin ''DreamFish'' added McMMO support, which is all about fishing. I don't use the plugin though.

**Comment by Sikatsu** [comment]
Not sure if this helps, but I guess this is their API? 

https://github.com/mcMMO-Dev/mcMMO/tree/master/src/main/java/com/gmail/nossr50/api

**Comment by Rocologo** [comment]
Yes, and they have a fishing event too

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/events/skills/fishing/McMMOPlayerFishingEvent.java

This means that there is hope :-) it will take some time for me to do, I have to examine if they have a Maven MCMMO repository too (this is preferable) or if I need to use the the jar. (less preferable)

**Comment by Rocologo** [comment]
And yes it is nice that you help me finding stuff!

**Comment by Sikatsu** [comment]
Glad theres hope, would love to do my economy update soon. ^^

I understand! Let me know if I can help you with anything.

**Comment by Rocologo** [comment]
Status is now. I have added a hook into McMMO and has created the two McMMO fishing events. And I can see that it IS McMMO who is changing the caught fish to an item, sometimes TNT so you have to run away!!!! :-) 

I still not sure how handle the situation, but I am alot closer now :-)

**Comment by Sikatsu** [comment]
Awesome news! Indeed TnT is part of McMMO haha!

Perfect, really exciting for this one to be fixed. :)

**Comment by Rocologo** [comment]
Unfortunately I ran in to new problems so I did not fix this today.

**Comment by Sikatsu** [comment]
Damn, alright

**Comment by Sikatsu** [comment]
Any news perhaps? :)

**Comment by Rocologo** [comment]
I have created a ticket at McMMO hoping that he has an idea on how to catch when McMMO changes the fish to something else.

**Comment by Sikatsu** [comment]
Kinda afraid the developer is not going to answer - he only keeps McMMO up-to-date for new minecraft versions, but is actually seeking for someone to take over the project.

**Comment by Rocologo** [comment]
I will unfortunate need his help to make MobHunting work with McMMO :-(

**Comment by Sikatsu** [comment]
Shit. Guess that's going to take quite some months :/

**Comment by Rocologo** [comment]
I think this is fixed, just waiting for your test?

**Comment by Rocologo** [comment]
You answered in the other ticket. It seems to work now.

**Comment by Sikatsu** [comment]
Correct :)
