### ISSUE TITLE
HappyHour status not updating correctly

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#122]
./mh happyhour is not updating correctly. I started the event on 17:03 for 1 hour, at 18:11 it said there where still 7 minutes left. Now it's 18:18, and it says there are 15 minutes left. What? o_O

**Comment by Rocologo** [comment]
I could not replicate this error, but I changes some minor details. Please install build 270 or newer and try again.

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Sikatsu** [comment]
Thanks. Once I do another event on my main server, I will test this. :)

**Comment by Rocologo** [comment]
I think this is fixed in V4.4.2
