### ISSUE TITLE
Missing placeholders

### ISSUE THREAD

**Issue by M9GLiquid** [Rocologo/MobHunting#123]
In the language file I'd like these placeholders to work:
mobhunting.moneygain.bonuses=&a${mob} dropped &6${prize} x ${multiplier}!

With this it only shows the prize correclty but not the rest...
I don't like the ${bonuses} placeholder since it's very unspecific * Difficulty is just wierd so for me I removed it altho I still want the multiplier to show up.

Removing the bonuses name will result in still having the * char left in there, Example:
Mob dropped $4.45 x x x x!

If you were to leave one of the bonuses names in it would display as:
Mob dropped $4.45 x x Difficulty x Sniper!

So add placeholders to this text:
${mob}
${multiplier}
Possibly others but these are the ones I use :)

**Comment by Rocologo** [comment]
I have updated the messages and you can now use 

"multipliers" to get the number
"killed" to get the mobname / playername
"basic_prize" to get the basic reward (without multipliers)
"prize" to get the number including multipliers
"bonuses" to get the multipliers as text.

this should work in Build 265
http://jenkins.lindegaard.one:8180/job/MobHunting/

This is the standard messages i a newly generated lang file
mobhunting.moneygain.bonuses=You gained ${prize}! With: ${bonuses}
mobhunting.moneygain.bonuses.drop=&a${killed} dropped &6${prize} &a! With: ${bonuses})!
mobhunting.moneylost.bonuses=You lost ${prize}! With: ${bonuses}
mobhunting.moneygain=You gained ${prize}!
mobhunting.moneygain.drop=${killed} dropped ${prize} on the ground!
mobhunting.moneypickup=You found ${money}
mobhunting.moneygain-for-killing=You got ${money} for killing ${killed}.
mobhunting.moneylost=You lost ${prize}!
mobhunting.moneygain.assist=Assist! You got ${prize}
mobhunting.moneygain.assist.bonuses=Assist! You got ${prize} With: ${bonuses}
