### ISSUE TITLE
Fishing error

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#125]
Hey,

Just saw that I have 2 fishing errors in my console. http://pastebin.com/yYNVGZHF

**Comment by Rocologo** [comment]
Please use newest build
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Sikatsu** [comment]
Thanks for fixing. I test the versions on my test server until fishing is stable, however I do not know how to reproduce this error. Let me know once you need me to test something about the other errors on here.

**Comment by Rocologo** [comment]
You cant reproduce it. The bug is fixed. 

I was not aware the you could catch a Zombie or a player with a fishing rod. Which would cause this error. I now test if it is an Item. :-) 

I close this ticket.
