### ISSUE TITLE
Update settings dont work as intended

### ISSUE THREAD

**Issue by dutchy1001** [Rocologo/MobHunting#126]
After setting the update settings to false for both notify and auto update the plugin still notifies me for an update.
If set to false there should not be any notify for the update.

**Comment by Rocologo** [comment]
Hmm... a question. Why don't you update then? Using /mh update ?

**Comment by dutchy1001** [comment]
I'm so mush online I update almost everyday when I a notification from the resource that it's  updated, I don't need a reminder ingame as 9 out of 10 times I already have the file downloaded. 
(I'm a bit OCD that way lol)

**Comment by Rocologo** [comment]
This is fixed in V4.4.2 (will be released today)

You will still get the information in the console, but not when you join the server.

**Comment by dutchy1001** [comment]
thx 👍
