### ISSUE TITLE
Maven Repository for BattleArena

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#13]
Hi, I've found from my Web History the Maven repository of BattlePlugins... But I don't know anything about pom.xml :confused: 

It seems also like it's a Free Dynamic DNS service (Home Hosting?), so it's likely to be Slow and/or go down:
http://rainbowcraft.sytes.net/maven/repository/

(BattleArena is in mc/alk, BattlePluginsAPI is in mc/battleplugins)

**Comment by Rocologo** [comment]
Thank you. Sometimes its very hard to find the repositories. It seems to be almost updated - almost newest version, so for my plugin to work this is fine. The pom.xml is updated in next release.
