### ISSUE TITLE
Drop Money on Ground : Customize the money for each mob like CookieMonster.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#132]
Hello !

Do you know the plugin CookieMonster ? https://dev.bukkit.org/projects/cookiemonster
You can put money for each mob, between 10 and 20$ for killing a zombie, for example.

You should add something to customize the drop money on ground for each mob. :D

**Comment by Sikatsu** [comment]
This is already possible?

**Comment by TheIntelloBox** [comment]
How so ?

**Comment by Rocologo** [comment]
Prize: 10:20

And then get a random reward between 10 and 20

**Comment by Rocologo** [comment]
I hope this was what you were looking for. I close this ticket now. If any problems I will open it again.
