### ISSUE TITLE
Need help removing info when killing mobs.

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#134]
Hey!
I am using the "drop money on ground" setting - to minimaze spam in chat when not picking up money. But I dont find a way to remove these messages: 

mobhunting.moneygain.drop=${killed} dropped ${prize} on the ground!
mobhunting.moneygain.bonuses.drop=&a${killed} dropped &6${prize} &a! With: ${bonuses})!

(I might just be blind, but I really dont find  a way to not send these...)

Newest version.
config: http://pastebin.com/NppNMsTK

Thank you :)

**Comment by Rocologo** [comment]
I cant remember what happens if you delete the text after = ?
But you can also install the plugin called TitleManager that reduces the spam in the chat significantly

**Comment by Nesseley** [comment]
If I don't have anything after = it sends a blank line in chat instead :P

I will try the title manager plugin! Thanks :)

**Comment by Nesseley** [comment]
title manager solved this problem so nicely!
Thank you :)
