### ISSUE TITLE
Happyhour and fishing

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#136]
HappyHour doesn't apply on fishing using 4.4.1. (Neither shows the message x2.0 HappyHour)

**Comment by Rocologo** [comment]
Confirmed. The fishingevent is not stable yet because of the mcmmo problems, so I introduced a bug by mistake.

The bug is fixed in V4.4.2 (Will be released today)

**Comment by Sikatsu** [comment]
Thanks!
