### ISSUE TITLE
Fishing and happyhour not working well

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#138]
With happyhour enabled, it barely gives money. I've been catching 13 fishes, which 2 gave money and the other 11 didn't give money, neither a debug message.

**Comment by Rocologo** [comment]
As I have written many times 😀 there is a bug in the bukkit API so I don't get the information when a player catches a fish. I cant do anything about it than report to the Spigot Team.

**Comment by Rocologo** [comment]
And happyhour works fine when the above information is sendt.

This the same problem you have reported in an earlier ticket.

**Comment by Rocologo** [comment]
Duplicate ticket 127

**Comment by Sikatsu** [comment]
Yeah, it's indeed the same problem basically. Sorry for that. Maybe i'm to overhyped on this feature.

**Comment by Rocologo** [comment]
I happy about the tickets, this way I dont forget issues and i have an overview of the information related to the ticket. I cant get that in the forum.
