### ISSUE TITLE
unable to create npcs

### ISSUE THREAD

**Issue by mrrowley** [Rocologo/MobHunting#14]
Hi dude, just like to say thanks for the awesome plugin,

i have a problem though, i'm using mobhunting with citizens2 but when i type /mh npc create total_kills alltime 1    i get the error "unknown stat type" could you please tell me where i'm going wrong?

many thanks!

**Comment by Rocologo** [comment]
Try using <TAB>  complete 

Type /mh n<TAB> c<TAB> 

And see what happens. StatType is unfortunately case sensitive for the moment being.
