### ISSUE TITLE
Server crash with /mh reload

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#140]
Everytime when I use /mh reload the server crashes. Whether it's just one letter change in the language file or a value change within the config, it crashes anyway.

On my test server, it doesn't seem to crash however(?)

I hope this information can help you with this: http://pastebin.com/Q1p7RuGw0

**Comment by Rocologo** [comment]
I does not crash on my servers too...

The link does not work

**Comment by Sikatsu** [comment]
Really......

http://pastebin.com/SGqw8UQr

**Comment by Rocologo** [comment]
Yes, I cant provoke a crash ???? I have tried to change the config.yml serval times and used /mh reload.... on both my SqlLite and on my MySQL server. No crashes... We need to find exactly what triggers this, before I can solve it. 

I think it could be related to the PlayerSettingsManager which you also found some timings issues on yesterday.

**Comment by Sikatsu** [comment]
Well, on my main server /mh reload is so broken that even when you don't make changes it crashes. I don't know what else I can say about this issue, but it's really unstable.

**Comment by Rocologo** [comment]
I do believe that your server crashes, but since I cant trigger this, I need your help to find out what triggers this.

**Comment by Sikatsu** [comment]
I would be more then glad to help. Point is I don't know how and crashes aren't really appreciated by the players as they give rollbacks. I have an average of 35-40 players online so it's kinda hard to use the main server, but on my test server the crashes do not happen..

I'm also not the only one that has problems with /mh reload crashing seen in the discussions.

The logs don't say the exact issue, I guess?

**Comment by Rocologo** [comment]
Nope, the log does unfortunately not tell me whats wrong... :-(

**Comment by Sikatsu** [comment]
Damn :/

**Comment by Rocologo** [comment]
This error is properly related to the PlayerSettingsManager, which i changed in v4.4.5 please tell me if you see this error again, assuming you are on v4.4.5+

**Comment by Sikatsu** [comment]
I will test this and let you know how it goes.

**Comment by Rocologo** [comment]
Have you seen this error recently?

**Comment by Sikatsu** [comment]
I didn't have to do an mh reload yet, will also test this tonight.

**Comment by Sikatsu** [comment]
I just did /mh reload without changing ANY value or even touching the config at all.

Server crash: http://pastebin.com/1FkLeN6t

**Comment by Rocologo** [comment]
Strange. It looks like a kind of sql problem, but i have not been able to reproduce the bug....

**Comment by Rocologo** [comment]
I notice that there is no debug information after you did mh reload? Was debug not enabled?

**Comment by Rocologo** [comment]
I have tried this many times today and has not been able to reproduce the crash yet. I don't know whats triggering the crash :-(

**Comment by Sikatsu** [comment]
Me neither, but it happens. I just stopped using /mh reload instead, sadly.

**Comment by datsme** [comment]
I can confirm this happens but only if I have the config file open in the multicraft config editor :)

**Comment by Rocologo** [comment]
You should of cause not reload before you have saved the file.

**Comment by Sikatsu** [comment]
That's not the case for me though

**Comment by Rocologo** [comment]
I cant fix something i cant reproduce. I have tried mh reload many times, but it never crashed. So I need your help, noticed and check the server log before the crash, and let me see the text from the serverlog for v4.6.1

**Comment by SucceededKiller** [comment]
I have the same issue.
Error log: https://paste.ee/p/D2R1L#8mGoJ3C7DQtb93CCZpMQvJ4Kh54h1Ta2

Console log: https://paste.ee/p/oDePj

I was on version MobHunting-3.4.7-B123.jar on 1.10
Updated to 1.11 and MobHunting-4.6.6.jar

Since then the server crashes when I use /mh reload.

**Comment by Rocologo** [comment]
Yes, you guys need to help me, to find whats triggering this. Every time I try myself my servers does not crash????

**Comment by Rocologo** [comment]
I got an idea. Maybe this problem is because of unsaved data??? So I made a change where I save all waiting data before reloading.

Could you guys try to install this version and the try reloading?
https://www.dropbox.com/s/zg41g40k8f562zq/MobHunting-4.6.8-SNAPSHOT-B009.jar?dl=0

**Comment by SucceededKiller** [comment]
Hey,

This doesn't appear to have fixed it for me, the server still crashed. 

I'll see if I can get reproduction steps for it on a test server and get back to you if I can.

**Comment by Rocologo** [comment]
No I tested this with only me online on my test server. 

1 i logged in
2 i killed a mob 
3 i toggled learn mode (/mh learn) because this create a second task , saving the change
4 then i typed /mh reload in the client interface (not the console) before the auto-saving started.

**Comment by Rocologo** [comment]
Maybe this is a windows/linux thing? I am on linux what are you on?

**Comment by SucceededKiller** [comment]
Running Linux, centOS 7. :)

I might have some more useful info for you now.

2 players on, myself and a test account on a test server.

Console log with both, kill-debug and sql debug from your config enabled:
https://paste.ee/p/cI5iw

Core dump and error log:
https://drive.google.com/drive/folders/0B8kuNDnJQWBXRXB5UDJHUXZ4X00?usp=sharing

Sorry, the core dump is almost 5GB, but hopefully in contains some helpful info for you. :)

**Comment by Rocologo** [comment]
Thank you for the log and the dumps. The dumps are really hard to read but it looks like the crash happened when the plugin tried to load PlayerSettings, and when I check the log I notice that first error happens when the plugins tries to save PlayerSettings. I am pretty sure that this is about database access while the plugin reloads. So I need to find a way to make sure that this does not happen :-)

**Comment by Rocologo** [comment]
I think I found the bug now, but I need you guys to help testing. Please try build 318 or newer on my jenkins server
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by SucceededKiller** [comment]
Hey,

I think you've fixed it! Nice work. :)

Tested it now, reloaded a few times and no crashes, thank you!

I'll let you know if that changes at all, but so far so good. :)

**Comment by Rocologo** [comment]
Perfect. I close the ticket now and reopen it if the issue reappears.

Thank you for helping with the testing. Especially this one which could have crashed your server :-|
