### ISSUE TITLE
Feature request for fishing message

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#141]
Hey, could you also add a message so it shows (x2.0 HappyHour) when happyhour is enabled? Just like you get from killing mobs with HappyHour?

**Comment by Rocologo** [comment]
Yes, you will get this in next release / build. I have made the changes.

**Comment by Sikatsu** [comment]
Thanks.

**Comment by Rocologo** [comment]
https://dl.dropboxusercontent.com/u/36067670/minecraft/Pictures/2017-02-10_15.58.25.png
