### ISSUE TITLE
Actionbar message time

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#142]
The actionbar messages dissapear a bit to quick.

You've mentioned earlier that this isn't possible to change, however I also have other plugins using the actionbar with a bit longer time atleast. Maybe something can be done in the future? Would be appreciated, as players currently prefer the text within the chat. I find it spammy however so prefer the actionbar.

**Comment by Rocologo** [comment]
Yes, its not possible according to the developers. If you can find an API which makes this possible I wil happily make the needed changes.

**Comment by Sikatsu** [comment]
I don't know anything about API's unfortunatly.

**Comment by Rocologo** [comment]
I mean if you can find any plugin like ActionBar or TitleManager, which can deliver what you want, then I can make it. I cant find a plugin which can give us this. I would too like to see the messages a bit longer

**Comment by Rocologo** [comment]
This will not be made....
