### ISSUE TITLE
Heavy event in timings

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#144]
Hey,

I just noticed MobHunting being high in my timings.

http://prntscr.com/e71jaq

40ms on average is pretty high.

**Comment by Rocologo** [comment]
Hmm PlayerQuitEvent should not need to do any hard stuff... I will take a look.

**Comment by Sikatsu** [comment]
I did another timings but that PlayerQuitEvent seems to be high still. 40ms is quite a lot, React says the same :P 

Alright!

**Comment by Rocologo** [comment]
Please test Build 281 or newer
http://jenkins.lindegaard.one:8180/job/MobHunting/

I have optimized the saving process for Player Settings when the player quits. Player Settings will now be stored together with PlayerStats

Let me know the result.

**Comment by Sikatsu** [comment]
I need to test this on my main server, unfortunatly I can't test that earlier then tomorrow. Will let you know!

**Comment by Rocologo** [comment]
No problem.  I dont have anymore time today.

**Comment by Sikatsu** [comment]
I ran 2 timings and this seems to be fixed now. :)
