### ISSUE TITLE
Multiplier message

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#145]
I tried to color the ${bonuses} placeholder using &3, however this doesn't seem to work correctly.

This only applies to 'x2.0' however the '*' stays white and the word 'Happy Hour' stays pink.

Also, in it's full sentence it says x2.0 * HappyHour, but where is the * needed for? Doesn't x2.0 HappyHour say enough? :P

**Comment by Rocologo** [comment]
If you want to change the Happy Hour from pink you need to change this line

bonus.happyhour.name=Happy Hour

I have changed the text to 

You caught a fish and earned $2.66 with: x1.6 ( Difficulty * Rank * Happy Hour )
