### ISSUE TITLE
NullPointerException with MythicMobs

### ISSUE THREAD

**Issue by Deathinflames** [Rocologo/MobHunting#148]
Spigot Server: 1.11.2
MythicMobs v2.5.11
MobHunting v4.4.5

http://pastebin.com/raw/A7hEVdig

**Comment by Rocologo** [comment]
You need to show me the full error text, including "cause by...... " the last part is actually the most important part.

**Comment by Rocologo** [comment]
Is there something special with this mob MythicMobs_NBlizzardAOE ?

**Comment by Deathinflames** [comment]
That is the whole error actually.
https://i.gyazo.com/91523287e674054ab07fc17f24f14618.png

I have a MythicMob named BlizzardAOE that is a zombie. On spawn of zombie it does invisibility potion effect and casts another skill that has snow particles. It then despawns after 340 ticks.

**Comment by Rocologo** [comment]
Could I have a copy of this MM mob, to see if I can provoke this error. If I can reproduce it, I can fix it.

**Comment by Deathinflames** [comment]
The MM Mob has been sent to you in a PM on Spigot site.

**Comment by Deathinflames** [comment]
Were you able to retrieve the MM Mob @Rocologo ?

**Comment by Rocologo** [comment]
I found the bug. fixed in next release
