### ISSUE TITLE
/mh update doesn't work.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#150]
Hello !

When a new version is available, it says type /mh update.
But this command doesn't work. I must do /mobhunt update.

Thanks !

**Comment by Rocologo** [comment]
Enable debug and show me the output in the console. I have tested the update feature recently and it worked fine. So I cant reproduce the error.

**Comment by Rocologo** [comment]
Mobhunt is the real command name mh is an alias. Mh conflicts with some othets plugins like mysterious halloween.  Which also uses mh. In that case you must use mobhunt.
