### ISSUE TITLE
Config regenerated without (user-inserted) comments

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#157]
Spigot 1.11.2 MH 4.4.8
I inserted a (useful) comment in config.yml (the second line below). It is removed on start-up (but not on reload). Please do not remove comments from config.yml on start-up.

>   [] This is the name of the reward
  [] Bag of gold: (https://mineskin.org/6875)
  drop-money-on-ground-skull-reward-name: Bag of Gold

[] for hash, since Markdown thinks I'm trying to embolden. :(

**Comment by Rocologo** [comment]
This is not possible to change. Congig works like the first dev. Made it. It has some advantages and some disadvantages. I have no plans of changing how it works for now. Sorry.

**Comment by Rocologo** [comment]
This is not possible to change. Congig works like the first dev. Made it. It has some advantages and some disadvantages. I have no plans of changing how it works for now. Sorry.
