### ISSUE TITLE
Entity Death Event - MyPet

### ISSUE THREAD

**Issue by zerafox** [Rocologo/MobHunting#162]
`18.02 21:16:55 [Server] INFO ... 24 more 18.02 21:16:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111] 18.02 21:16:55 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111] 18.02 21:16:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111] 18.02 21:16:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111] 18.02 21:16:55 [Server] INFO at one.lindegaard.MobHunting.compatibility.MyPetCompat.onMyPetKillMob(MyPetCompat.java:97) ~[?:?] 18.02 21:16:55 [Server] INFO Caused by: java.lang.NullPointerException 18.02 21:16:55 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityBat.A_(SourceFile:112) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2064) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1762) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:845) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.Entity.burn(Entity.java:980) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityBat.damageEntity(SourceFile:203) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:392) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom18.jar:git-Spigot-b4417b8-3c48711] 18.02 21:16:55 [Server] INFO org.bukkit.event.EventException 18.02 21:16:55 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v4.4.8`

**Comment by Rocologo** [comment]
Fixed in V4.5.0
