### ISSUE TITLE
No heads dropping

### ISSUE THREAD

**Issue by kingofthecogs** [Rocologo/MobHunting#167]
null

**Comment by Rocologo** [comment]
What have you set the drop change/frequency in the config.yml to?

**Comment by kingofthecogs** [comment]
Hi, thanks for the swift response.

The config is currently stock / untouched at present.

Thank you

**Comment by Rocologo** [comment]
Then you will have to check the chance/frequency for the mob you are testing on. For some mobs is rare (5%) that you get at head. (Not to spam the server with heads). You should read the config.yml there is alot of configuration you can, depending on how you want to use the plugin.

I was fast this time, but I go to sleep now, and do not have much time tomorrow.

**Comment by kingofthecogs** [comment]
Thanks,

Just concerned that console states the head is being given but is not received however?
