### ISSUE TITLE
Non Vanilla - Mob heads dont drop or spawn correctly

### ISSUE THREAD

**Issue by Stokykyle** [Rocologo/MobHunting#168]
Non Vanilla - Mob heads dont drop or spawn correctly since when trying to give them they just come out as a head in version 4.5.2

**Comment by Rocologo** [comment]
Try placing a head as a block and brake it again a couple of times?

**Comment by Stokykyle** [comment]
It doesn't come out with the actual name it comes out as head with nothing or than the name head

**Comment by Stokykyle** [comment]
Like a blank player head

**Comment by Rocologo** [comment]
Can i see your dropmoneyonground section in config.yml?

**Comment by Stokykyle** [comment]
I am currently in bed so I can't atm. Can do tomorrow morning since I'm from the UK

**Comment by Stokykyle** [comment]
Now it's fine with dropping money it doesn't even work doing mh head give {username} {mob}
Here is my config anyways http://pastebin.com/v29DDg7g

**Comment by Rocologo** [comment]
Please help me testing v4.5.4

**Comment by Stokykyle** [comment]
Link?

**Comment by Stokykyle** [comment]
Build 296 works texture wise but comes out named a bag of gold in the inventory when using the command

**Comment by Rocologo** [comment]
Yes, build is the new v4.5.4 version published on spigot.

Glad to hear that the texture works now. But you mention a command? Which command are we talking about?

**Comment by Stokykyle** [comment]
I get the same result with any head http://prntscr.com/ecwyyn

**Comment by Rocologo** [comment]
Agree this of cause a bug. I will find a solution to that. The it self okay, its only the text which is wrong?

**Comment by Stokykyle** [comment]
I believe so

**Comment by Rocologo** [comment]
Please test Build 297, I think it works.
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Rocologo** [comment]
V4.5.5 has fixed this error

**Comment by Stokykyle** [comment]
Still got an issue 

http://prntscr.com/ednty6

**Comment by Rocologo** [comment]
It took some time to fix this the best way, but I think it works now.

except the Ender dragon head which is very special. I will try to fix this tomorrow.

Please help me testing build 301 or newer:
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Rocologo** [comment]
The ender dragon works in build 302.

**Comment by Rocologo** [comment]
I think this is fixed in V4.5.7
