### ISSUE TITLE
Some display issue with latest update V4.5.3

### ISSUE THREAD

**Issue by mrho225** [Rocologo/MobHunting#170]
A bug i guess. Husk heads are named "Bag of gold $0"
![image](https://cloud.githubusercontent.com/assets/23705706/23324657/0ecd0e4e-fb2a-11e6-834e-a8503e8b51a9.png)

**Comment by Rocologo** [comment]
Yes, i know, this is fixed in build 297
http://jenkins.lindegaard.one:8180/job/MobHunting/

I wait for some more bugs before i release next version. ☺

**Comment by Rocologo** [comment]
And thank you for making a ticket.

**Comment by Rocologo** [comment]
Fixed in v4.5.6
