### ISSUE TITLE
Achievement broadcast when configured not to do

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#171]
Testing MH 4.5.5-b297 with debug:true

config.yml
>  broadcast-achievement: false
  broadcast-first-achievement: false

lang/en-US.yml
> achievements.axemurderer.description=
achievements.axemurderer.name=
achievements.bythebook.description=
achievements.bythebook.name=
achievements.creeperboxing.description=
achievements.creeperboxing.name=
achievements.creepercide.description=
achievements.creepercide.name=
achievements.electrifying.description=
achievements.electrifying.name=
achievements.fancypants.description=
achievements.fancypants.name=
achievements.fangmaster.description=
achievements.fangmaster.name=
achievements.huntbegins.description=
achievements.huntbegins.name=
achievements.hunter.1.description=
achievements.hunter.1.name=
achievements.hunter.2.description=
achievements.hunter.2.name=
achievements.hunter.3.description=
achievements.hunter.3.name=
achievements.hunter.4.description=
achievements.hunter.4.name=
achievements.hunter.5.description=
achievements.hunter.5.name=
achievements.hunter.6.description=
achievements.hunter.6.name=
achievements.hunter.7.description=
achievements.hunter.7.name=
achievements.infighting.description=
achievements.infighting.name=
achievements.itsmagic.description=
achievements.itsmagic.name=
achievements.master-sniper.description=
achievements.master-sniper.name=
achievements.justintime.description=
achievements.justintime.name=
achievements.recordhungry.description=
achievements.recordhungry.name=
achievements.load-fail=

> player has earned the achievement [Sniper-Duel]

was broadcast.

**Comment by Rocologo** [comment]
Are you sure this is a MobHunting achievement??? I cant find the text anywhere.....

**Comment by Rocologo** [comment]
Sniper Duel is a Minecraft achivement. I cant change how that work ☺

**Comment by SlimeDog** [comment]
Ah. OK, thanks.
