### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#172]
MH 4.5.5-b297 (and previous)

I have attempted to configure for integer-only values.
>  reward_rounding: 1.0
  minimum_reward: 1.0

How does MH apply those configuration values to money commands? I can perform
> /mh money drop 0.5

(or any other arbitrary decimal amount}. Should that be allowed, should it drop 1.0, or should it generate an error message?

Drops are reported as decimal value

**Comment by Rocologo** [comment]
The amounts will be rounded in next release/snapshot.

**Comment by SlimeDog** [comment]
Thank you. You are always responsive. It's much appreciated.

**Comment by Rocologo** [comment]
Fixed in v4.5.6

**Comment by SlimeDog** [comment]
MH 4.5.6

Drops are reported as decimal value:
> You dropped 1.0

**Comment by Rocologo** [comment]
Did you mean 1) "/mh money drop...." or 2) drops when mobs are killed? 

1) should be fixed in V4.5.6
2) is fixed in next release/snapshot.

**Comment by SlimeDog** [comment]
> /mh money drop 1

> You dropped 1.0

**Comment by Rocologo** [comment]
Okay, I had not seen that.

**Comment by Rocologo** [comment]
Please help me testing build 299 (or newer)
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by SlimeDog** [comment]
Confirmed fixed: MH-4.5.7-b299.
