### ISSUE TITLE
Feature request: Log formatting

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#174]
Please introduce a configuration option to disable formatting codes in log entries. I prefer plain text, no colors or etc.

**Comment by Rocologo** [comment]
I only colorcode errors with red, because they are important and because you need to do something about it. Am I wrong?

I agree that to many colors would not be good.

**Comment by SlimeDog** [comment]
You are correct, insofar as my log scans show. I have an automatic error scanner, so I don't need colors to highlight errors (as though someone is watching the console full time). So long as they are identified by "ERROR" or "WARN", I find them. I am on a bit of a campaign to reduce the use of gratuitous console/log coloration. You are one of the best, as in so many things.

**Comment by Rocologo** [comment]
I will not spend the time to clean up this. This is not that important.
