### ISSUE TITLE
Animals who dont give money, still gives you killstreak.

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#178]
Hello! 

I am using you plugin on my server, before I only got killstreaks by killing mobs that gave money.
Now I get killstreaks from killing non-reward animals. Like sheep etc. This is horrible as they can spawn wither, kill a bunch of chickens then get x4 times the money. Just like that.. 

Is this is a problem? Im using 1-2 versions behind

**Comment by Rocologo** [comment]
You are the first one who notice this. I have made a new version I would like you to test. This is last release I will make for a while. I will take a break from this.

Please let me know if this works.

**Comment by Rocologo** [comment]
https://dl.dropboxusercontent.com/u/36067670/MobHunting/MobHunting-4.6.1-SNAPSHOT-B304.jar

**Comment by Nesseley** [comment]
Seems to be fixed, but I noticed killing animals also triggers the "penalty grinding"

**Comment by Nesseley** [comment]
Just a warning for anyone else: this build WILL reset parts of your config. It sets back to defaul % droprates. and resets the dropmessages.

Also: Mobs can pickup the money (and the lootbag) and will drop it so you can pick it up.
https://gyazo.com/62a4476f1f6285b05b0fe8f1f662267b

**Comment by Rocologo** [comment]
Fixed in v4.6.1.  

I think you need to write the warning in the forum.

second thing is a known "bug" which cant be fixed. The Bukkit/SpigotAPI cant handles this. Some users call it a bug, other users think it is fun. anyway - i cant change it.
