### ISSUE TITLE
MobHunting V4.6.0 errors

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#180]
I mentioned this error earlier, but since around 4.5.6 this error has been introduced: http://pastebin.com/skTCVkV2

The names are different each time, and I don't even know where it triggers that name from.

**Comment by mrho225** [comment]
R u running on old mc versions which dont have lastest mobs? If yes I think you have to remove some lines in config for new mob types

**Comment by Sikatsu** [comment]
I'm running 1.11.2

Op do 2 mrt. 2017 12:15 schreef mrho225 <notifications@github.com>:

**Comment by Rocologo** [comment]
This actually not an error, its only debug information to me. 

Yesterday I wrote that I will take a break, and i will, but one user found a critical mysql error which i need to fix, i use mysql myself.

So i decided to remove the debug information in next release and THEN i will take the announced break ☺
