### ISSUE TITLE
Error with Mysql 

### ISSUE THREAD

**Issue by Bossbirdyman51** [Rocologo/MobHunting#181]
Hi,
You have a very good plugin, i have update your plugin but now i have this error in the server :

17:06:20 CONSOLE: WARN]: one.lindegaard.MobHunting.storage.DataStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '200000' at line 1
17:06:20 CONSOLE: WARN]: at one.lindegaard.MobHunting.storage.MySQLDataStore.savePlayerStats(MySQLDataStore.java:286)
17:06:20 CONSOLE: WARN]: at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:47)
17:06:20 CONSOLE: WARN]: at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:13)
17:06:20 CONSOLE: WARN]: at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:445)
17:06:21 CONSOLE: WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '200000' at line 1
17:06:21 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
17:06:21 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
17:06:21 CONSOLE: WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
17:06:21 CONSOLE: WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
17:06:21 CONSOLE: WARN]: at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
17:06:21 CONSOLE: WARN]: at one.lindegaard.MobHunting.storage.MySQLDataStore.savePlayerStats(MySQLDataStore.java:273)
17:06:21 CONSOLE: WARN]: ... 3 more

**Comment by Rocologo** [comment]
Enable debug and show the killing information just before the sql error.

Use pastebin.com if there is alot of data

**Comment by Rocologo** [comment]
The same line works on my own mysql server,  but may this error could be triggered by a strange mobname/type?

**Comment by Rocologo** [comment]
Please test this snapshot and let me know if it fixes this error:

https://www.dropbox.com/s/saiwpjd6i5sq4hy/MobHunting-4.6.3-SNAPSHOT-Bnull.jar?dl=0

**Comment by Rocologo** [comment]
Fixed in v4.6.3
