### ISSUE TITLE
/mh command

### ISSUE THREAD

**Issue by krustymk** [Rocologo/MobHunting#183]
removing the rewards file cured this, though im not sure what it does or if will come back?

any command entered either in the server console or game resulted in a '/mh command' being displayed (inc /mh debug/reload'

the contents of the rewards file are http://pastebin.com/Lv63hA3P

**Comment by Rocologo** [comment]
Strange. I notice that the first 3 records in your rewards file is invalid because they are missing a location. Deleting these 3 is okay. The 4. Seems okay.

I have a hard time seeing how this can affect the /mh command...  please try /mobhunt inatead

**Comment by krustymk** [comment]
typed 'mh debug' then 'mobhunt debug', this is what showed in the console

12.03 20:59:51 [Server] INFO /mh command
12.03 20:59:59 [Server] INFO [Statz debug] Save Statz database.
12.03 21:00:03 [Server] INFO /mobhunt command
12.03 21:00:09 [Server] INFO [Statz debug] Save Statz database.
[rewards.txt](https://github.com/Rocologo/MobHunting/files/836873/rewards.txt)

Again, removing this file fixed the issue.. The plugin seems to crash and only return '/mh command' no matter what is entered

**Comment by krustymk** [comment]
http://pastebin.com/aQubZZtu
Just had this come up after the restart to remove the rewards file

**Comment by Rocologo** [comment]
Deleting the rewards.yml file cant cause this error. It looks like you have done something to your database?

**Comment by Rocologo** [comment]
And removing the rewards.yml file while the server is online might cause problems.

**Comment by krustymk** [comment]
i used plugman to disable the plugin, removed the rewards file then re-enabled the plugin... console spat some shit out that made me think.. oppps, so i restarted and got the above error.. need my hand slapped i  reckon lol.. soo.. that may have corrupted the .db file? 
Still doesnt explain whats goin on with the plugin freezing and only giving the /mh command response though, any ideas?

**Comment by Rocologo** [comment]
It looks like mh_Weekly is missing the column called TOTAL_CASH, I cant guess how you ended up in this situation. 

And no this does no explain the strange bug you have found...

**Comment by Rocologo** [comment]
I have made a change in V4.6.2 where rewards with a null location in the rewards.yml will be deleted when you restart / reload the server.

**Comment by Rocologo** [comment]
Ps. I still dont have any idea about how you end up with a situation where is says /mh command ???

**Comment by Rocologo** [comment]
Do you still see this error on your server?

**Comment by krustymk** [comment]
no, i deleted the folder and contents and let it regenerate, not seen it since

**Comment by Rocologo** [comment]
okay. create a new ticket if it happens again
