### ISSUE TITLE
Not sure as this error contains several plugin names

### ISSUE THREAD

**Issue by krustymk** [Rocologo/MobHunting#186]
http://pastebin.com/KCnWFizy

**Comment by Rocologo** [comment]
This is not an mobhunting error. You must have  made an error in the give command.

Have you tried
/mh head give [<toPlayer>] [<mobname|playername>]

**Comment by krustymk** [comment]
I didnt use the command, this was generated when a playing got given a head from a kill

**Comment by krustymk** [comment]
I think my server is haunted......
I deleted the folder and added the latest mobhunt prior to this error. So its all like new regarding mobhunt

**Comment by Rocologo** [comment]
Hmm,,, there must be a kind of bug when i generate the config.yml file. Maybe its a pvpv kill which trigger this error? Check the pvp run command ?

**Comment by Rocologo** [comment]
Do you still see this error in your log?

**Comment by krustymk** [comment]
No, i only ever see it the once, though i have been very busy with life recently so not checked as much as i should.. If i see it again ill let you know

**Comment by Rocologo** [comment]
if yes you have to set the 

pvp_kill_cmd = mobhunt head give {player} 397 1 3 {SkullOwner:\"{killed_player}\"} 1 silent|give {player} diamond 1
I found a bug, which happened when you recreated the config.yml

**Comment by Rocologo** [comment]
mobhunt head 

was missing

**Comment by Rocologo** [comment]
so i close this ticket now

**Comment by krustymk** [comment]
Thanks for all your help :) ill check and update that if necessary 
absolute legend
