### ISSUE TITLE
[HELP]Localize some of the problems.

### ISSUE THREAD

**Issue by xyblues** [Rocologo/MobHunting#187]
Hello, sorry for my poor English, I do not know if you can understand what I mean.

![image](https://cloud.githubusercontent.com/assets/15712089/24027922/ffebd55e-0b05-11e7-88ab-df45ed217496.png)
Where should I change this message?

![image](https://cloud.githubusercontent.com/assets/15712089/24027926/060a2f8a-0b06-11e7-9789-df4f7a7acdee.png)
Can the name of the mob head be localized?

**Comment by Rocologo** [comment]
You can change most of the messages in the lang file, but this one was hard coded until the release i made today. ☺

**Comment by xyblues** [comment]
![image](https://cloud.githubusercontent.com/assets/15712089/25083680/eeea5350-238a-11e7-8f31-66f3f76c62b9.png)
![image](https://cloud.githubusercontent.com/assets/15712089/25083698/043514b6-238b-11e7-96c9-0ac0aabe795d.png)
Mob name can not be localized.

**Comment by Rocologo** [comment]
I opened this ticket again because I realized that it was not fixed.

I have now tested that I can translate 

mob.spider.name=&2SpIdEr&r

and it seems to work now, both for /mh head give and drop, placing and breaking heads and in the inventory. Please help me testing.

Try build 361 or newer.
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by xyblues** [comment]
Work very well, thank you.

**Comment by Rocologo** [comment]
Thank you. Is it Chinese? I would be very happy if you wanted to share your translation, so i can use it in the plugin?

**Comment by xyblues** [comment]
I only use some of the features so I only translated a little bit.
`mobs.Bat.name=蝙蝠
mobs.Blacksmith.name=铁匠
mobs.Blaze.name=烈焰人
mobs.BonusMob.name=Bonus Mob
mobs.Butcher.name=屠夫
mobs.Cartographer.name=制图室
mobs.CaveSpider.name=洞穴蜘蛛
mobs.Chicken.name=鸡
mobs.Clownfish.name=小丑鱼
mobs.Cow.name=牛
mobs.Creeper.name=苦力怕
mobs.Donkey.name=驴
mobs.ElderGuardian.name=远古守卫者
mobs.EnderDragon.name=末影龙
mobs.Enderman.name=末影人
mobs.Endermite.name=末影螨
mobs.Evoker.name=唤魔者
mobs.Farmer.name=农民
mobs.Ghast.name=恶魂
mobs.Giant.name=巨人
mobs.Guardian.name=守护者
mobs.Horse.name=马
mobs.Husk.name=尸壳
mobs.IronGolem.name=铁傀儡
mobs.KillerRabbit.name=杀手兔
mobs.Librarian.name=图书管理员
mobs.Llama.name=羊驼
mobs.MagmaCube.name=岩浆怪
mobs.Mule.name=骡
mobs.MushroomCow.name=蘑菇牛
mobs.Nitwit.name=绿袍村民
mobs.Ocelot.name=豹猫
mobs.PassiveRabbit.name=兔子
mobs.Pig.name=猪
mobs.PolarBear.name=北极熊
mobs.Priest.name=牧师
mobs.Pufferfish.name=河豚
mobs.PvpPlayer.name=玩家
mobs.RawFish.name=生鱼
mobs.RawSalmon.name=生鲑鱼
mobs.Sheep.name=羊
mobs.Shulker.name=潜影贝
mobs.Silverfish.name=蠹虫
mobs.Skeleton.name=骷髅
mobs.SkeletonHorse.name=骷髅马
mobs.Slime.name=史莱姆
mobs.Snowman.name=雪人
mobs.Spider.name=蜘蛛
mobs.Squid.name=鱿鱼
mobs.Stray.name=幽灵骷髅
mobs.Vex.name=恼鬼
mobs.Villager.name=村民
mobs.Vindicator.name=卫道士
mobs.Witch.name=女巫
mobs.Wither.name=凋零
mobs.WitherSkeleton.name=凋灵骷髅
mobs.Wolf.name=狼
mobs.Zombie.name=僵尸
mobs.ZombieHorse.name=僵尸马
mobs.ZombiePigman.name=僵尸猪人
mobs.ZombieVillager.name=僵尸村民`

**Comment by Rocologo** [comment]
Okay, but this is better than nothing ☺. Is it Chinese?
