### ISSUE TITLE
LogBlock does not register heads

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#188]
When a head generated by the mobhunting is placed on the ground, logblock records its placement but does not record when it breaks. 
Heads not generated with mobhunting (example, the head of creeper drawn from the creative). LogBlock if you can log events.
If I disable the mobhunting the heads that have been generated by this if they leave logs both when placing them and when breaking them.

Greetings and thanks.

**Comment by Rocologo** [comment]
On my first try the MH heads was actually logged, but they were logged as "normal" skulls. I was able to break a head and then do rollback with logblock. But the CustomSkin did not work. 

I think this is a "problem" in LogBlock that it does not log the skin used at player heads and I  don't think its possible for me to change this behavior. Hmm....

**Comment by Mundo-Minecraft** [comment]
I have not translated well. I will try to explain myself.
The behavior of the logblock that you indicate is logical, always worked well in previous versions of mobhunting.
Currently placing a head generated by the mobhunting logblock registers it, but breaking logblock does not record anything.
With the heads of the creative logblock logs to break and settle, and when disabling mobhunting the heads generated by the mobhunting re-register them when placing and breaking. (Similar behavior to the report on the worldguard)

Thank you.

**Comment by Mundo-Minecraft** [comment]
As it is something difficult to explain I recorded a quick video. https://youtu.be/Zx1hrF3pyYc

After uploading the video I realized that the ids of the heads change
https://subefotos.com/ver/?dd89c055ada61f3108f2bd184535aaa3o.png#codigos
https://subefotos.com/ver/?5907ac771f4b6fc9d39b8f234734502do.png#codigos

By the change of id the logblock does not register the heads generated by the mobhunting

**Comment by Rocologo** [comment]
Ok, I think i understod this time, and I think I know why it does not work, so now I just need to find a solution. :-)

**Comment by Rocologo** [comment]
And then I might have found a solution but I need your help to test:

https://www.dropbox.com/s/goopoh129xm09da/MobHunting-4.6.5-SNAPSHOT-B006.jar?dl=0

**Comment by Mundo-Minecraft** [comment]
It is a good advance, now when breaking a head logblock records "did an unspecified action" we know who breaks heads.
It is curious that previous versions of mobhunting did not have this problem with the logblock.

Greetings.

**Comment by Rocologo** [comment]
When you write previous versions which version are you then talking about?

**Comment by Mundo-Minecraft** [comment]
Do not tell yourself exactly which, but the first time I tested the plugin in November / December 2016 the operation was correct.
One detail is that when you drop your head to the ground, you never get the name on top of it, and when you have the name above it is when the logblock does not register well (as seen in the video).

**Comment by Rocologo** [comment]
Ahh. This was before I added a value to the skulls. They were basically all a steve head with a skin. This is of cause handled by LogBlock. I dont think it is possible for me to add these data to LogBlock. This is some  the LogBlock developer must do in LogBlock through my API.

**Comment by Rocologo** [comment]
I guess I can close this ticket now.
