### ISSUE TITLE
Worldguard can not prevent it from breaking mobhunting heads

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#189]
This problem consists of the following. A head generated by the mobhunting puts it in a place with worldguard. No matter what flags you put any user can break.
With heads not generated by mobhunting (example, skeleton head drawn from the creative) this does not happen.
If the mobhunting is disabled the worldguard perfectly blocks those heads.

Greetings and thanks.

**Comment by Rocologo** [comment]
You are actually the first one which noticed that the heads did not respect WorldGuard. 

I think this is fixed in this snapshot

https://www.dropbox.com/s/76tat3vax3k0gas/MobHunting-4.6.4-SNAPSHOT-B002.jar?dl=0

Please tell me if it works on your server.

**Comment by Mundo-Minecraft** [comment]
Problem solved, thank you very much
