### ISSUE TITLE
MobHunting config.yml cannot be modified for Chinese

### ISSUE THREAD

**Issue by BenLiHao** [Rocologo/MobHunting#190]
Hello, everyone, I changed the language file into Chinese, after the restart the server garbled! Please click to view my question，Here's my screenshot：[https://twitter.com/BenLi_hao](https://twitter.com/BenLi_hao)。

Request the author to add Chinese documents to go in, thank you! I try to change myself to Chinese, every time I restart the server automatically garbled.

I want to test it on Windows, and then upload it to Linux (because my server is on the Linux system)

**Comment by Rocologo** [comment]
Is the file garbeled on both Windows and  Linux?

**Comment by Mundo-Minecraft** [comment]
I have not translated well. I will try to explain myself. 
The behavior of the logblock that you indicate is logical, always worked well in previous versions of mobhunting. 
Currently placing a head generated by the mobhunting logblock registers it, but breaking logblock does not record anything.
With the heads of the creative logblock logs to break and settle, and when disabling mobhunting the heads generated by the mobhunting re-register them when placing and breaking. (Similar behavior to the report on the worldguard)

Thank you.

**Comment by BenLiHao** [comment]
TAT help!

**Comment by BenLiHao** [comment]
Is the file garbeled on both Windows ,I did not test on Linux

**Comment by Rocologo** [comment]
Please test V4.6.7 and check if Chinese works. I have tested Chinese on Linux and had no problems. Everything worked.

**Comment by Rocologo** [comment]
Please try newest snapshot an see if it stil happens.

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by BenLiHao** [comment]
Thank you, no problem, I put the Chinese language to provide you with reference. I do not know how to share zh_CN.lang files.

**Comment by Rocologo** [comment]
Drag the fileinto here or email to rocologo@hotmail.com

**Comment by Rocologo** [comment]
Example

**Comment by Rocologo** [comment]
Do you still have this issue?
