### ISSUE TITLE
MobHunting and Towny

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#191]
This time I'm going to talk about towny. This I suppose is a compatibility issue (I think it does not have). 

A user who is not a citizen can not break anything, except heads generated by the mobhunting. Towny indicates that he is not allowed to break anything, but still gives him the head and logblock does not register anything (although towny sends a message to the player that he can not break anything).

If the user is a citizen of the city, logblock records when he breaks his head.

Thank you.

**Comment by Rocologo** [comment]
I have never tried Towny and I cant find the Towny API???

**Comment by Rocologo** [comment]
This might actually be related to both the LogBlock and WorldGuard problem.

**Comment by Mundo-Minecraft** [comment]
The official towny page is this http://towny.palmergames.com http://palmergames.com/javadoc/towny-bukkit/ Towny is one of the most used systems of regions with all the respect to worldguard :)

True, these latest reports are very similar.

**Comment by Rocologo** [comment]
I think I made a minor bug. I have changed my BlockBreakEvent to Highest priority, should work for both WorldGuard and for Towny too. Maybe even LogBlock.

Please test this snapshot:
https://www.dropbox.com/s/sz7219rpyaz1uyd/MobHunting-4.6.5-SNAPSHOT-B007.jar?dl=0

**Comment by Rocologo** [comment]
I suppose you use Towny? Can you tell me if the players has a safezone area where mobs can damage the players?

**Comment by Mundo-Minecraft** [comment]
The worldGuard still works well, protects the heads. Towny now also correctly guards the heads :).
LogBlock continues to indicate "did an unspecified action" but I think it serves perfectly. There is not much benefit in indicating skull.

**Comment by Rocologo** [comment]
Okay that was 2½ out of 3 issues :-)

**Comment by Rocologo** [comment]
I suppose you use Towny? Can you tell me if the players has a safezone area where mobs can't damage the players?

**Comment by Mundo-Minecraft** [comment]
Yes, my server uses towny. It depends on the configuration of each server, in my case in the cities the mobs do not hurt the players. But there are areas for pvp and areas where mobs do damage players (areas with mobspawners).

**Comment by Rocologo** [comment]
Aha, this means that you are able to kill mobs in your town and get rewards without the risk. This must be changed :-D

**Comment by Mundo-Minecraft** [comment]
In my case it works fine since it detects grinding (I have set a low value).

**Comment by Rocologo** [comment]
Hi again, I tried Towny on my test-server. Creating a town was no problem, but I dont know how to create the town, so I am protected against damage from mobs??? (I found the mob spawning flag, but this is only about spawning, not against damage)?

**Comment by Rocologo** [comment]
Basic support for Towny added in V4.6.5 :-)

**Comment by Rocologo** [comment]
I guess we can close this issue now?

**Comment by Mundo-Minecraft** [comment]
The flag that you are actually commenting is to prevent the appearance of mobs, it has nothing to do with the damage. Just do not express myself well, the only way to kill mobs easily in towny is to allow mobs to appear with that flag and place mobspawners or that users make the city on top of a natural mobspawner. Anyway there is no problem since it detects grinding.

http://towny.palmergames.com/towny/towny-commands/

I take longer in the week to respond for work, the problem with the towny is solved.


Thx.
