### ISSUE TITLE
New Error since 1.6.4

### ISSUE THREAD

**Issue by Abyssmael** [Rocologo/MobHunting#192]
Hi there, this is the new one:

[12:19:26 ERROR]: [MobHunting] Unhandled exception occured in onPacketSending(PacketEvent) for MobHu
nting
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_101]
> at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_101]
> at one.lindegaard.MobHunting.compatibility.ProtocolLibHelper$1.onPacketSending(ProtocolLibHe
lper.java:58) ~[MobHunting-4.6.4.jar:?]
> at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPack
etListenerList.java:195) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacket
ListenerList.java:149) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java
:608) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManag
er.java:584) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java
:309) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.j
ava:269) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java
:396) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77)
[ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.j
ava:362) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjecto
r.java:330) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java
:127) [ProtocolLib.jar:4.2.0]
> at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [Pro
tocolLib.jar:4.2.0]
> at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.8-R0.1
-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.8
-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spig
ot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at de.robingrether.idisguise.management.channel.InjectedPlayerConnection183.sendPacket(Injec
tedPlayerConnection183.java:65) [iDisguise.jar:?]
> at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:766) [spigot-1.8.8-R0.1-SNA
PSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at net.minecraft.server.v1_8_R3.EntityPlayer.updateInventory(EntityPlayer.java:762) [spigot-
1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.updateInventory(CraftPlayer.java:509) [
spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at me.BukkitPVP.Lobby.Module.LobbyAPI.reset(LobbyAPI.java:345) [Lobby.jar:?]
> at me.BukkitPVP.Lobby.Events.LobbyEnterEvent$1.run(LobbyEnterEvent.java:38) [Lobby.jar:?]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8-R
0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedule
r.java:350) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8-R0
.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0
.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0
.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-
R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[12:19:26 ERROR]: Parameters:
net.minecraft.server.v1_8_R3.PacketPlayOutWindowItems@7fbe15cd[
a=0
b={<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<n
ull>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<nul
l>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,<null>,1xitem.blazeRod@0,<null>,1x
item.compass@0,<null>,1xitem.paper@0,<null>,<null>}
]

**Comment by Rocologo** [comment]
Fixed in V4.6.5

**Comment by Rocologo** [comment]
Thank you for reporting this.
