### ISSUE TITLE
Problem with new function for towny

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#194]
In towny you can create pvp zones, with the new functions of mobhunting for towny something strange happens. A user from that city kills another in the pvp zone, and the dead's inventory disappears.
It does not fall to the ground, it disappears completely.
When I disable integration with towny everything returns to normal.

There is also a small problem with the option "disable-naturally-drops-and-xp-in-home-town: false" although disabled this is still working and mobs do not give items or xp.

Greetings.

**Comment by Rocologo** [comment]
Okay, this is of cause because towny is new to me. What do you call the area inside the town? Is it a plot?

**Comment by Rocologo** [comment]
This should be fixed in V4.6.7

**Comment by Mundo-Minecraft** [comment]
I just tried it and solved it. But I see another small mistake. The "disable-rewards-in-home-town: true" option does not work. It continues giving rewards to the citizens.

**Comment by Rocologo** [comment]
Its okay. Im out of work for the moment, so I have plenty of time. ☺

When you write citizens do you then mean residents other than the owner of the town? I thought i tested this myself?  Buy i only have one town on my test server and i am the owner

**Comment by Mundo-Minecraft** [comment]
Mmm it seems like I have been reported wrong. I was told that the mayors did not receive rewards, but the citizens did.
Now I have looked more carefully, several cities and several users and receive nothing.

Thanks, everything works right :)

**Comment by Rocologo** [comment]
Never the less I have made a change, because I still think that it was only the Mayor of the town which didnt get rewards :-)

This is how the code works now :-)
1) I find the town the resident stand in.
2) I get a list of all residents in that town
3) I check if the list of residents contain the resident

I got my Jenkins server to work again:
Please test newest build:
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Mundo-Minecraft** [comment]
Works correctly.

Thx :)

**Comment by Rocologo** [comment]
Thank you
