### ISSUE TITLE
Mobs spawned from dispensers give bounty, even if the config setting for spawn eggs giving bounty is false.

### ISSUE THREAD

**Issue by SucceededKiller** [Rocologo/MobHunting#195]
Some players have apparently been able to bypass the denying of bounty from spawned mobs by using dispensers.

Video if it helps:
https://youtu.be/zWovnzkSxbg

**Comment by Rocologo** [comment]
Thank for making a ticket! And thank you for the two video, yes they helped me to see what was wrong. 

I have made a fix for the egg dispenser. I didnt know that it was possible to dispense mobs this way :-)

I have also addedthe posibility to Whitelist the area if you want the player to actually get rewards from one special dispenser/spawer.

Please help me test this snapshot:
https://www.dropbox.com/s/mvdx56m8kk9zii6/MobHunting-4.6.8-SNAPSHOT-B008.jar?dl=0

And tell me if it works?

**Comment by SucceededKiller** [comment]
Hey,

No problem. :) And yeah, seems the players on my server are very creative with how they can try and get some bounty. :P 

I tested the MobHunting-4.6.8-SNAPSHOT-B009 you gave for the crash (I assume it includes the fix from 008 too?) and I no longer get bounty from dispensed mobs, thank you!

**Comment by Rocologo** [comment]
Perfect. Yes B009 include the fix from B008 ☺

**Comment by Rocologo** [comment]
J
