### ISSUE TITLE
Money drop on ground - Angry pigmen

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#196]
**Gamebreaking bug!!**

When using a goldfarm like this: 
https://gyazo.com/6be947d4da9d0118b6d1a8f4b68dbd3e

Where you anger the pigzombies and they run off the platform to die of falldmg.
= They will drop money, and you will get a killstreak.

This doesnt affect grinding penalty eighter, so they can farm like this forever.

This means a user will earn SO much money while beeing afk/not doing anything! It really needs to be fixed ASAP!

- Nesseley

**Comment by Rocologo** [comment]
Hi Nesseley, 

You have to explain more detailed, if I am going to find a cure. 

1) i dont know what a gold farm is? and how i build one on my test server?
2) where do the pigzombies come from?

**Comment by Nesseley** [comment]
This is the farm my players built: https://www.youtube.com/watch?v=jQWG9Q7HoUA

The mobs spawn naturally, 
the player angers 1, this makes all the others agressive too
Thay will all try to run to the player, but fall and die
Thats when the money drops

**Comment by Nesseley** [comment]
He explains it at 1:00 in the video too

**Comment by Rocologo** [comment]
Good video, but it looks like a creative world? Have your players build this in survival ?

**Comment by Rocologo** [comment]
I wonder why the grindind detection does not kick in.... hmm... but this is maybe the best way to catch this. 

I think it will be difficult to catch this.

**Comment by Rocologo** [comment]
And i dont understand why the mobs drop money to the player if he never hits the mobs? I mean the player does not seem to be the killer??? Just thinking loud here...

**Comment by Rocologo** [comment]
You should disable MobHunting in creative worlds.

**Comment by Nesseley** [comment]
It is not a creative world... It's in completly survival.

The pigzombies are agroed to the player, and your plugin probably thinks that the player have hit them all.
Hit one pigman = all agro you = mobhunting think you have hit them all

**Comment by Rocologo** [comment]
Okay, I wonder why this is.... i will have to study the code, and i will see if i can make a gold farm on my test server. But this is not something ican solve fast.

One thing i could is to make a new command for you /mh area blacklist .... to ban an area, this way they have to make another farm, and this takes time.

**Comment by Nesseley** [comment]
I temporaly solved it by setting reward for pigmen to 0 :)

**Comment by Rocologo** [comment]
Ahh, yes that an easy workround for now.

**Comment by Rocologo** [comment]
I just remembered. If you have worldguard, you can also use the command " /mh region [area] mobhunting deny. "

**Comment by Rocologo** [comment]
Am I able to logon to your server and see the farm?

**Comment by Rocologo** [comment]
I want to see how they dies, if the die when they hit the ground or something else?

**Comment by Nesseley** [comment]
Yep mc.Konsole.no, my ing is also Nesseley

**Comment by Rocologo** [comment]
I tried to find the download  link but didnt???

I will come online at some point to see if i can catch you.

**Comment by Nesseley** [comment]
http://snocrash.com/Best-AFK-XP-Gold/ You can find the download on this page

**Comment by Rocologo** [comment]
I had hoped for a schematic file, but I finally got some time for downloading and importing the world on my test server, unfortunately was not able to find the farm????

I will try to join your server now.

**Comment by Nesseley** [comment]
That is weird, when I logon into the world download in single player I get put into the farm.

To to teleport to coods: -163 192 683
That is where the farm is located in the worlddownload.

**Comment by Rocologo** [comment]
It probably because i use multiverse on my test server, i need to test alot, more than most can imagine ☺

Thanks for the coordinates this should do it.

**Comment by Rocologo** [comment]
Very strange it didnt help either. No farm at -163 192 683

Maybe I should try on the client....

**Comment by Rocologo** [comment]
Okay loading into the client helped now I can see the farm, now I just need to get it into my server.

**Comment by Nesseley** [comment]
I wish you luck finding out the problem! :) 
Il be gone for 4 days now, so sorry If I don't reply

**Comment by Rocologo** [comment]
I have made a workaround in Build 325 to protect servers against the gold farming. Its not perfect but it works against farms where the PigZombies dies from a FALL and only a FALL. This means that if the players change the way the PigZombie dies they will get the reward.

I have not disabled normal drops and xp drops, I think its a matter of taste if this is allowed.

**Comment by Rocologo** [comment]
This also means that you cant kill a pig zombie by pushing it down from something with your hands and get a reward. Which you could previously.

**Comment by Rocologo** [comment]
I still dont know why player is marked as the killer when a PigZombie dies from a fall. This might actually be a Spigot/Minecraft bug.

The reason why the grinding detections did not work was that all the zombies dies in 4 different areas, far away from each other. And the player was marked as killer for all of them. 

Maybe I could catch this by examine if there is a trap for above where the Pig Zombie dies? This would work for the NetherGoldFarm, but I have seen a "NetherPortalGoldFarm" made in the normal world, where this method does not work.

**Comment by Rocologo** [comment]
Dont spend time on testing buold 325, wait... I am almost finished with a new SNAPSHOT  which detects the gold xp farm and blacklist the areas where the Zombie Pigman falls.

**Comment by Rocologo** [comment]
Hi, when you are you can test newest snapshot now. I have improved the farm detection a lot. Try build 327 or newer. http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Nesseley** [comment]
Seems to be working, they are not dropping money! :D 
Only the first dropped and then it stopped, but will the area drop again after a restart? (like with grinding detection)

Is there a command to check if the spot is "blacklisted"? f.eks /mh blacklistedarea or something?

**Comment by Rocologo** [comment]
Yes I have done a lot of improvements in SNAPSHOT 328. 

I have add /mh blacklist (to add/remove) blacklist areas, /mh checkgrinding will show both you if the area is whitelisted and if not, if it is blacklisted. 

AND if you use ProtocolLib you will now SEE the area marked by small flames.

There is still a lot of testing to do, so I will need your help!!! But I think we are closer to the goal, - and make sure that the players can't cheat. :-)

**Comment by Rocologo** [comment]
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Nesseley** [comment]
Amazing! I will update and check things out!

**Comment by Nesseley** [comment]
As I see right now, everything seems to be working flawless! 

I will make sure to check things out and reopen if I see another issue!

Thank you for all your help!
