### ISSUE TITLE
Mobgrinding on animals with "0" money rewarded

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#199]
If you have a cowfarm (like this one https://gyazo.com/9978ec05f76d171fa7d3e72f4456b924)
And you kill alot of cows you will get grindingpenaly, even if money for cow is set to 0.

This grindingspot dont go away and you will loose your killstreaks for killing cows wich gives 0 money..
This will aply for every sigle mob that dont give money, not just cows

I've had this problem on a few versions and on your newest one  (https://gyazo.com/e97ae73ebb66498b1759a9000ecba1a6)

**Comment by Rocologo** [comment]
Notice that I test BOTH if the money is 0 AND if the run_cmd = "".

And please enable /mh debug and give the output from the log.

**Comment by Nesseley** [comment]
I do have run_cmd enabled so that is probably why it got detected as grindingspot. Didn't know that was a thing, thanks! :D (makes sense when I think about it)

**Comment by Nesseley** [comment]
Can't see this problem after updating to this mornings snapshot. 

Will reopen if I find this problem again.
