### ISSUE TITLE
Problem with monsterfarms not dropping items.

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#200]
Hey!

I see in the new config that you added:
disable-natural-item-drops-on-nether-gold-farms: true
disable-natural-xp-drops-on-nether-gold-farms: true
disable-natural-item-drops-on-other-farms: true
disable-natural-xp-drops-on-other-farms: true

Heres the problem; even when I set these to "false" the drops are stopped. They will drop til grinding hits, then they stop dropping the items.. 
I still want my players to get items/xp when in a grinding spot! 

Also, these options should be default "false" not "true". I don't see why anyone would block that on default and it will confuse alot of people using your plugin.

**Comment by Rocologo** [comment]
You would be amazed... everybody want to configure these things differently :-)  But its okay with me, in next build (329) the default value will be false. 

And the I need the /mh debug information to see whats going on :-)

**Comment by Nesseley** [comment]
After updating to newest snapshot the farms seems to be back to normal!
They drop both XP and items when in a grinding spot, awesome!

I still have the problem where I get Killstreaks in a grindingspot!
https://gyazo.com/56bbe6230d4800e7c85ee061e3b6a76e
https://pastebin.com/t8yTBujj

**Comment by Rocologo** [comment]
I understand the confusion :-) I have added specific settings to allow item and xp grinding when the player is grinding. Please notice that we are talking about PLAYER Grinding here :-) There are different kind of grinding areas. 

disable-natural-item-drops-on-player-grinding: false
disable-natural-xp-drops-on-player-grinding: false

Please try Build 330
http://jenkins.lindegaard.one:8180/job/MobHunting/

As for permissions please make sure that you have

mobhunting.whitelist or mobhunting.whitelist.show
and
mobhunting.blacklist or mobhunting.blacklist.show

**Comment by Nesseley** [comment]
I still don't understand.

When farming skeletons from a mobspawner(the block) i get drops, then they suddenly stop giving XP and items

Here is my config:
https://pastebin.com/BkqhptKH

Debug:
https://pastebin.com/tBaABLW6

I see that the kill is blocked, but I still want items and xp, Don't understand where in the config to enable this!! help :(

**Comment by Rocologo** [comment]
I found a bug in the MobSpawer detecting

Please test build 332 

And check these NEW settings after first run

* XP and Item drops will be disabled when the player is in god mode. (Check disable-natural-item-drops and disable-natural-xp-drops)
* New settings to disable money, normal item drops and normal xp drops from mob spawners (disabled_money-rewards_from_mobspawners_and_eggs, disable_naturally_dropped_items_from_mobspawners_and_eggs, disable_naturally_dropped_xp_from_mobspawners_and_egg)

**Comment by Rocologo** [comment]
We have another user helping with the testing :-) He reported this.... 
https://github.com/Rocologo/MobHunting/issues/198

**Comment by Nesseley** [comment]
Drops from mobspawners seems to be working in builld #333.
