### ISSUE TITLE
Add ability to allow drops from spawner mobs on a per world basis

### ISSUE THREAD

**Issue by DiscoveriesMC** [Rocologo/MobHunting#201]
I spawn mobs for custom dungeons in a few different worlds but also have a vanilla world. Players can kill mob from spawners but I disable the money rewards for the vanilla world. Currently there isn't a way for both of these settings I have to coexist without disabling/enabling money for the other worlds. By adding the ability to set worlds where money/item drops from mobs spawned via a spawner and disable money/item drops in others would solve this problem I'm having.

**Comment by Rocologo** [comment]
So looked at my code and saw that you are already able to whitelist and area where you want the players to get rewards from Mob Spawners. Try whitelisting the area.

**Comment by Rocologo** [comment]
In next release you can disable grinding detection in different worlds. Check disable-grinding-detection-in-worlds" I hope this helps you.
