### ISSUE TITLE
Add support for killing mobs in Adventure mode

### ISSUE THREAD

**Issue by DiscoveriesMC** [Rocologo/MobHunting#202]
Currently mobs killed in Survival mode is the only way to actually receive rewards from MobHunting. Adventure mode is currently blocking drops despite being in a "survival-like" gamemode. Adding support for Adventure mode would solve this issue.

**Comment by Rocologo** [comment]
I have checked my code and done some minor changes to make sure Adventure gamemode is supported. Please test Build 328 or newer

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by DiscoveriesMC** [comment]
Newest update allows me to kill them in Adventure mode. Thank you for supporting this.
