### ISSUE TITLE
question about grindingspots

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#203]
Are you supposed to have per-player-grindingspots?

Cause now if I farm alot of mobs and make a grinding spot, my friend can come over and get money until he makes a grindingspot too.

It wasnt like this before, thats why i'm asking

**Comment by Rocologo** [comment]
Actually the per-player-grinding is not new. This was made by the previous developer - so its more than two years old. I have of cause added a lot of new features / improvements, and while testing found some bug, which has been fixed. So if you have not noticed the player grinding areas before this must have been a bug :-) And YES this means that each player can kill 20 mobs before the grinding detection kicks in. 

Player grinding areas are NOT saved on server restart. 

But you can use /mh blacklist to add grinding area. /mh whitelist to allow Player Grinding in an area. 
Blacklisted and whitelied areas are saved in "blacklist.yml" and "whitelist.yml" so they will survive a server restart.

**Comment by Rocologo** [comment]
I still make many changes on the grinding features :-) Your reports help me to make the plugin better and better

I have new added a setting for you:
blacklist-player-grinding-spots-as-server-worldwide-spots: false

If you change this to true it works like you wanted :-)

Please try Build 331 or newer:
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Nesseley** [comment]
blacklist-player-grinding-spots-as-server-worldwide-spots: false

Works as intened! Thank you for adding this back to the plugin :D
