### ISSUE TITLE
Mobhunting dropping money on playerkill?

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#204]
I see that
 Set rob-from-victim=true to steal from the victim or 
  rob-from-victim=false to get the reward money from the server.
  rob-from-victim: false/true

I dont want them to get money at all, only headdrops, is it possible for you to add "none" here? for not dropping money at kills?

**Comment by Nesseley** [comment]
- might have solved this myself. Didnt read config good enough.

**Comment by Nesseley** [comment]
Edited the entire question* It is now a suggestion

**Comment by Rocologo** [comment]
If you have "rob-from-victim=false" they will not get money. But I think you will need to remove the reward for killing a player too (pvp-kill-prize=0), if you dont want them to get money for killing players.

rob-from-victim is about where the money come from. If true the money comes from the dead player, if false the money reward comes from the server.

Or May be you just set "pvp_allowed= false" :-) The config.yml says this should work.

**Comment by Rocologo** [comment]
Thanks for closing tickets when you think the issue is fixed and creating new ones when you find new issues! :-)

**Comment by Rocologo** [comment]
Anymore questions? Or can this be closed? :-)

**Comment by Nesseley** [comment]
I'l test it out after school today, then close when I get it right! :D

**Comment by Rocologo** [comment]
Just following up? :-)

**Comment by Nesseley** [comment]
Sorry for beeing slow.

It does not work like I want it to. 
With pvp= false it will not drop the playerheads.

I want it to only drop heads, no money. There is no option for this.

**Comment by Rocologo** [comment]
Okay, I will have to look at it again... 

But why dony you set the pvp_prize to 0 and then it should work?

**Comment by Nesseley** [comment]
When I set it to 0 it reset back to 1.5% (default)

**Comment by Nesseley** [comment]
I guess my problem was that i set 0% and not just 0.
Works like intended now, sorry! And thanks for your help :p
