### ISSUE TITLE
BlackListAreaCommand error

### ISSUE THREAD

**Issue by timr2000** [Rocologo/MobHunting#209]
Error @ startup
https://pastebin.com/Yz6L5uVb

**Comment by Rocologo** [comment]
Strange. Did you remember to delete the old mobhunting.jar?

**Comment by Rocologo** [comment]
And did you make a restart or reload of your server?

**Comment by timr2000** [comment]
I deleted the old mobhunting.jar, and i restarted the server

**Comment by Rocologo** [comment]
I must have done something wrong when I made the jar, I will build a new version 4.7.6

**Comment by timr2000** [comment]
Not getting the error anymore

**Comment by Rocologo** [comment]
Thank you. Case closed.
