### ISSUE TITLE
DropMoneyOnGround

### ISSUE THREAD

**Issue by falget** [Rocologo/MobHunting#215]
Hello, if mob drop money like item 'GOLD_NUGGET' and another nearby mob drop item, this two money item stacked and money not doubled.

**Comment by Rocologo** [comment]
Im on vacation without my computer i will look at this when i get back home.

**Comment by Rocologo** [comment]
Hi, please test build 346 or newer

https://jenkins.lindegaard.one:8181/job/MobHunting/

**Comment by falget** [comment]
Thank you, this help.
