### ISSUE TITLE
Grinder detection no longer working

### ISSUE THREAD

**Issue by FatherWh0** [Rocologo/MobHunting#219]
With version 1.7.7 grinder detection is no longer functioning. Mh is dropping rewards for grinder mobs. I've inspected with /mobhunt checkgrinding and the results is that no grinder is detected.
http://prnt.sc/eywabe
I tried /mh cleargrinding at one location to give it a fresh start to detect but after over 50 mobs kill rewards were still paying.

Config: https://pastebin.com/Bc6DaTPj
paper: 1.11.2 #1081

I reverted back to 1.6.3 and the issue went away.

*note* I saw that Mundo-Minecraft answered your question about creating spawners. Just in case it's helpful to you here is a schem file of a mob grinder. Simply load and paste it with worldedit then flip the light lever off. Mobs will spawn then traffic through the pipe system landing on a spot ready for killing. I thought it might be nice to play with as many players build similar grinders.
https://drive.google.com/file/d/0B4jJYrVOq7X5UXp0c2x6SEpJbU0/view?usp=sharing

**Comment by Rocologo** [comment]
Perfect. Thank you for the schematic, hopefully this will help me to reproduce the problem. And fix it 😀

**Comment by Rocologo** [comment]
I found the bug ... a missing "!" :-(

Please help me test build 351
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by FatherWh0** [comment]
It appears to be working. Build 351 is correctly detecting grinders.

**Comment by Rocologo** [comment]
Perfect. Thank you for the working schematic of your grinder. That helped a lot. It is now placed permanent on my test server. I will make a release later today.
