### ISSUE TITLE
Not working on 1.8 if LibDisguise 8.6.7 is installed

### ISSUE THREAD

**Issue by hsombini** [Rocologo/MobHunting#222]
I'm using LibDisguise for my antihack plugin and MobHunting is not working even with the setting disable-integration-libsdisguises set as true

StackTrace: https://hastebin.com/eweruxibeb.css

**Comment by Rocologo** [comment]
Im have not tested MobHunting against mc 1.8 for long time now, but i see i need to do some testing again.

**Comment by Rocologo** [comment]
Ps. Thank you for creating tickets.

**Comment by Rocologo** [comment]
I think this is basically the same error "java.lang.NoSuchFieldError: VEX" it looks like my version check does not work on your server... So I need a copy of your server.jar to see what version it reports????

**Comment by hsombini** [comment]
You're correct!

The issue was with my custom build, Bukkit.getVersion was returning "Unknow Version"

Thanks for your time, amazing job!
