### ISSUE TITLE
Llama problem on 1.8 EntityDeathEvent and CreatureSpawnEvent

### ISSUE THREAD

**Issue by hsombini** [Rocologo/MobHunting#223]
There're two erros caused by Llama entity that does not exists on 1.8,

StackTrace https://hastebin.com/ikeqotobaz.vbs

I don't know if this can prevent the drop of the bags of golds, because they're not dropping.

**Comment by Rocologo** [comment]
Its strange, I actually test for the minecraft version in y code 

`	public boolean matches(Entity entity) {
		if (Misc.isMC111OrNewer())
			if (this == Llama)
				return entity instanceof org.bukkit.entity.Llama;
`
And it works fine on my Spigot 1.8.8 test server ... but for some reason the version check give the wrong result when running on your server????

Which server do you use? I don't have a 1.8 Test server, only 1.8.8 but I look for "1.8" in the version number, so it should not matter....

Do you know where I can find the 1.8 jar, I will proberly need your version of libdisguises too... to do full testing.

**Comment by hsombini** [comment]
You're correct!

The issue was with my custom build, Bukkit.getVersion was returning "Unknow Version"

Thanks for your time, amazing job!
