### ISSUE TITLE
Error log every time a player gets a skull

### ISSUE THREAD

**Issue by Armek15** [Rocologo/MobHunting#225]
`05.05 01:07:52 [Server] INFO CONSOLE issued server command: /give Thuinky 397 1 3 {SkullOwner:"darkdevol3"} 1 silent
05.05 01:07:52 [Server] ERROR null
05.05 01:07:52 [Server] INFO net.minecraft.server.v1_11_R1.MojangsonParseException: Unbalanced curly brackets {}: SkullOwner:"darkdevol3"} 1 silen
05.05 01:07:52 [Server] INFO at net.minecraft.server.v1_11_R1.MojangsonParser.a(SourceFile:194) ~[spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at net.minecraft.server.v1_11_R1.MojangsonParser.b(SourceFile:162) ~[spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at net.minecraft.server.v1_11_R1.MojangsonParser.a(SourceFile:91) ~[spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at net.minecraft.server.v1_11_R1.MojangsonParser.parse(SourceFile:32) ~[spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.util.CraftMagicNumbers.modifyItemStack(CraftMagicNumbers.java:117) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at com.earth2me.essentials.MetaItemStack.parseStringMeta(MetaItemStack.java:122) [EssentialsX-2.0.1%20(1).jar:?]
05.05 01:07:52 [Server] INFO at com.earth2me.essentials.commands.Commandgive.run(Commandgive.java:68) [EssentialsX-2.0.1%20(1).jar:?]
05.05 01:07:52 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:156) [EssentialsX-2.0.1%20(1).jar:?]
05.05 01:07:52 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:469) [EssentialsX-2.0.1%20(1).jar:?]
05.05 01:07:52 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:381) [EssentialsX-2.0.1%20(1).jar:?]
05.05 01:07:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1618) [MobHunting-4.8.4.jar:?]
05.05 01:07:52 [Server] INFO at sun.reflect.GeneratedMethodAccessor589.invoke(Unknown Source) ~[?:?]
05.05 01:07:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
05.05 01:07:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
05.05 01:07:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:410) [spigot-1.11.jar:git-Spigot-f950f8e-655d840]
05.05 01:07:53 [Multicraft] Skipped 22 lines due to rate limit (30/s)`

**Comment by Rocologo** [comment]
Which version of MobHunting are you on?

**Comment by Rocologo** [comment]
And please show me you "pvp-kill-cmd" setting in config.yml?

**Comment by Armek15** [comment]
`pvp-kill-prize: 3.0%

  # One or more console commands to be run when a player kills another player.
  pvp-kill-cmd: give {player} 397 1 3 {SkullOwner:"{killed_player}"} 1 silent|give {player} diamond 1

  # Write the message to the killer, describing the reward / console commands
  pvp-kill-cmd-desc: You got {killed_player}'s skull

  # This is the chance for running the command. 1 = 100% (each time the player is killed), 0.5 ~ 50% and 0.001 = 0.1% (very rare) 
  pvp-kill-cmd-run-chance: 0.5

  # The Head price if you want playerheads to have a value like the bag of gold.
  pvp-head-prize: '10'
Im using the lastest version, but i think had that problem like 2 updates ago,... i really dont even remember when i started to see that error log xd , anyways thats the default config

**Comment by Armek15** [comment]
pvp-kill-prize: 3.0%

  # One or more console commands to be run when a player kills another player.
  pvp-kill-cmd: give {player} 397 1 3 {SkullOwner:"{killed_player}"} 1 silent|give {player} diamond 1

  # Write the message to the killer, describing the reward / console commands
  pvp-kill-cmd-desc: You got {killed_player}'s skull

  # This is the chance for running the command. 1 = 100% (each time the player is killed), 0.5 ~ 50% and 0.001 = 0.1% (very rare) 
  pvp-kill-cmd-run-chance: 0.5

  # The Head price if you want playerheads to have a value like the bag of gold.
  pvp-head-prize: '10'

**Comment by Armek15** [comment]
```
  pvp-kill-prize: 3.0%

  # One or more console commands to be run when a player kills another player.
  pvp-kill-cmd: give {player} 397 1 3 {SkullOwner:"{killed_player}"} 1 silent|give {player} diamond 1

  # Write the message to the killer, describing the reward / console commands
  pvp-kill-cmd-desc: You got {killed_player}'s skull

  # This is the chance for running the command. 1 = 100% (each time the player is killed), 0.5 ~ 50% and 0.001 = 0.1% (very rare) 
  pvp-kill-cmd-run-chance: 0.5

  # The Head price if you want playerheads to have a value like the bag of gold.
  pvp-head-prize: '10'
```

**Comment by Armek15** [comment]
i think i got this problem like 2 updates ago, i dont really remember when i started to see this error log :P i'm using the lastest version of mobhunting

**Comment by Rocologo** [comment]
It looks like you are missing something in the run cmd. The default value is:

mobhunt head give {player} 397 1 3 {SkullOwner:"{killed_player}"} 1 silent|give {player} diamond 1

You are missing "mobhunt head" ?

**Comment by Rocologo** [comment]
Did you make it work?

**Comment by Rocologo** [comment]
?

**Comment by Rocologo** [comment]
Hello?

**Comment by Rocologo** [comment]
Closed because of now answer
