### ISSUE TITLE
MythicMobs Reload Support

### ISSUE THREAD

**Issue by grdgyyr** [Rocologo/MobHunting#228]
I tested your dev build 366. reward price reloads but consoleRunCommand and chance are not affected

**Comment by Rocologo** [comment]
That sounds really strange. I will have to look at it again.

**Comment by grdgyyr** [comment]
thanks :D

**Comment by Rocologo** [comment]
I have looked at the code again, and I think it works. Maybe I need to explain how data is stored.

1) When a mob is spawned it is tagged with the reward data. These data will not be changed when you reload MobHunting.
2) But if you reload and then spawn a new MythicMob it should be tagged with the newly loaded data.

try again. Reload and then spawn a MM.

**Comment by Rocologo** [comment]
I have made change in how I find the reward data when a MM is killed. Maybe this will work better. 

Please test build 367 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

I have not had a lot of time to test my self.

**Comment by grdgyyr** [comment]
i'll look into it and test it out shortly. Thank you so much

**Comment by grdgyyr** [comment]
It works like a charm now. Thank you so much for the fast response and fix.
