### ISSUE TITLE
Language fixes

### ISSUE THREAD

**Issue by vilgrar** [Rocologo/MobHunting#232]
Hi,

I've been looking through en_US.lang and config.yml and found a few errors. Most are very minor errors or don't fit into uniformity of the plugin. I also looked at the achievements list (/mh kills) and found a few that didn't sound quite right.

Note that I don't speak English fluently. Make sure my suggestions are proper language =)

**en_US.lang**

12:
  achievements.fancypants.description=Complete a kill with a fully enchanted set of diamond armor and sword.
#Rephrased
  
16:
  achievements.huntbegins.description=Make your first hunt. There are more achievements to get for killing mobs in interesting and unique ways.
#Rephrased

35:
  achievements.itsmagic.name=It's Magic!
#Forgot the ' character
  
39
  achievements.master-sniper.description=Snipe a mob from over 40 blocks away while in a moving vehicle or on a moving horse.
#Added word 'from'
  
149:
  mobhunting.commands.head.you_got_a_head=You got the head of a ${mobname}
#Replaced 'a' with 'the'
  
187:
  mobhunting.commands.npc.unknown_rank=Rank (&b${rank}&f)must be greater than 0 and less than 26
#Fixed typo
  
207:
  mobhunting.commands.top.invalid-number=Count must be a whole number within the range of 1-100
#Replaced 'with' with 'within'

Open for debate:
86:
mobhunting.bounty.playeriswanted=There is a bounty on ${playername}, go get him!

87:
mobhunting.bounty.randombounty=A Random Bounty (${prize}) was put on ${playername}, go get him!

116:
mobhunting.commands.bounty.description=Put a bounty on your enemy and get him killed.

Is assuming gender ok? I doubt anyone will care, though. =)

**config.yml**

47:
  elder-guardian-cmd-desc: You got an Elder Guardian skull and an Iron ingot.
#Fixed grammar ('a' should be 'an')
  
52:
  enderman-cmd-desc: You got an Enderman skull and a Gold ingot.
#Fixed grammar ('a' should be 'an')
  
57:
  endermite-cmd-desc: You got an Endermite skull and an Iron ingot.
#Fixed grammar ('a' should be 'an')
    
67:
  giant-cmd-desc: You got a Giant head and an Iron Ingot.
#Replaced 'iron' with 'Iron'
  
72:
  iron-golem-cmd-desc: You got an Iron Golem skull and 4 Iron ingots.
#Added plural to the word ingot.

87:
killerrabbit-cmd-desc: You got a Killer Rabbit skull and an Iron Ingot.
#Added missing 'a' and replaced 'iron' with 'Iron'

121:
  silverfish-cmd-desc: You got a Silverfish head and an Iron ingot.
#Replaced 'SilverFish' with 'Silverfish' and 'iron' with 'Iron'
  
126
  skeleton-cmd-desc: You got a Skeleton skull and one Lapis Lazuli.
#Replaced '1' with 'a' and '1' with 'one'
  
146:
  vex-cmd-desc: You got a Vex skull and a Gold ingot.
#Fixed grammar ('an' should be 'a')
  
151:
  witch-cmd-desc: You got a Witch skull and a Gold ingot.
#Fixed grammar ('an' should be 'a')
  
156:
  wither-skeleton-cmd-desc: You got a Wither Skeleton skull and a Gold ingot.
#Replaced '1' with 'a' and '1' with 'a'
    
177:
  enderdragon-cmd-desc: You got an Enderdragon skull and ten Diamonds.
#Fixed grammar ('a' should be 'an') and replaced numbers with letters

193:
  butcher-cmd-desc: You got a Butcher skull  
#Replaced 'Skull' with 'skull'. Cosmetic change because small s in the word skull has been used so far in the config file
  
198:  
  cartographer-cmd-desc: You got a Cartographer skull
#Replaced 'Skull' with 'skull'
  
203:
  evoker-cmd-desc: You got an Evoker skull and an Iron ingot.
#Fixed grammar ('a' should be 'an')
  
208:
  farmer-cmd-desc: You got a Farmer skull
#Replaced 'Skull' with 'skull'
  
218:  
  librarian-cmd-desc: You got a Librarian skull
#Replaced 'Skull' with 'skull'
  
223:
  nitwit-cmd-desc: You got a Nitwit skull
#Replaced 'Skull' with 'skull'
  
228:
  priest-cmd-desc: You got a Priest skull
#Replaced 'Skull' with 'skull'
  
233:
  villager-cmd-desc: You got a Villager Skull
#Replaced 'Skull' with 'skull'

238:
  vindicator-cmd-desc: You got a Vindicator skull and a Gold ingot.
#Fixed grammar ('an' should be 'a')

EVERY PASSIVE MOB - Replace 'Skull' with 'skull'

296:
  ocelot-cmd-desc: 'You got an Ocelot skull'
#Added description
  
350:
  rawfish-cmd-desc: You got the head of a Raw Fish
#Replaced 'a' with 'the'

355:
  rawsalmon-cmd-desc: You got the head of a Raw Salmon
#Replaced 'a' with 'the'

360;
  pufferfish-cmd-desc: You got the head of a Pufferfish
#Replaced 'a' with 'the'

365:
  clownfish-cmd-desc: You got the head of a Clownfish
#Replaced 'a' with 'the'

446:
  itsmagic-cmd-desc: Enjoy your Gold Ingot
#Fixed typo

449:
  fancypants-cmd-desc: Enjoy your Gold Ingot
#Fixed typo and plural error

452:
  master-sniper-cmd-desc: Enjoy your Gold Ingot
#Fixed typo and plural error

455:
  justintime-cmd-desc: Enjoy your Gold Ingot
#Fixed typo and plural error

**Achievement mob names in plural**

Ender Dragons
Mushroom Cows
Endermen
Sheep
Skeleton Horses
Silverfish
Pufferfish
Raw Salmon
Wolves
Raw Fish
Clownfish

**Comment by Rocologo** [comment]
I think a fixed this in newest snapshot, but please remember that I dont change your lang file when it is generated. So you will have to delete the lang file and restart the server to see the changes.

**Comment by Rocologo** [comment]
Fixed in v4.9.3
