### ISSUE TITLE
President Master achievement causes Java error

### ISSUE THREAD

**Issue by vilgrar** [Rocologo/MobHunting#235]
Um, hi =p

I noticed that the leaderboard GUI doesn't approve of the last rank.

[http://picpaste.com/2017-05-31_09.27.03-1AxdjW23.png]
Up to rank 6 (Grandmaster) there are no problems at all.

[https://pastebin.com/2aWMquDH]
Whenever I complete a President Master achievement, /mh kills stops working and Java is complaining in the console.

Edit: This happened on both an old database and a brand new installation.

**Comment by Rocologo** [comment]
I like that you are testing in depth!!!! :-)

I have actually newer tried to achieve level 7 :-( but now I did and I found and fixed the bug.

Please help me test build 384 or newer.
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by vilgrar** [comment]
It's fixed!

**Comment by Rocologo** [comment]
Thank you, when I have fixed some more bugs today, I will make a release. 

I close this ticket now.
