### ISSUE TITLE
Bug on Fishing Mobhunting 4.9.3 on Spigot 1.11.2

### ISSUE THREAD

**Issue by comonier** [Rocologo/MobHunting#236]
Description: Just drop a Fish on the ground and use fishing pool on that. Repeat.
Mobhunting version: 4.9.3
Minecraft Version: Spigot 1.11.2 - build git-Spigot-3fb9445-2b6c9f4
Prove:   https://youtu.be/8-EVm7pt3rY

**Comment by Rocologo** [comment]
Hmm.. this is basically a Minecraft bug (that you are about to catch a fish this way) You can catch the fish the same way if MobHunting is not enabled. 

Unfortunately the Minecraft code is pretty buggy, and not consistent in the Event I can catch. So it will be hard to solve this problem.

I cant solve the problem with Minecraft, but I will see if can detech if the player is not fishing in water.... and then NOT pay a reward if this is the case.

**Comment by Rocologo** [comment]
Okay. I changed my code so that the player does only get rewards when fishing on Material.WATER or Material.STATIONARY_WATER.

Please help me test build 384 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
Fixed in V4.9.4
