### ISSUE TITLE
Too few achievements count

### ISSUE THREAD

**Issue by vilgrar** [Rocologo/MobHunting#237]
[http://picpaste.com/2017-06-04_11.13.56-D6dJU41r.png]

I think the picture says it all. Assuming there are 76 types of achievements and all of them (except The Hunt Begins) use 7 ranks, there should be 526 achievements in total.

**Comment by Rocologo** [comment]
I am pretty sure this is exactly because the 7 Chicken progress  achievements is could as 1. And times the number of mobs.... This also code from the originally dev, but I will check the code and see if I am able to do a smarter calculation.

Do you use a "special mob" plugins like MythicMobs / CItizens(+Sentinel) / TARDISWeepingAngels or one of the others?

**Comment by vilgrar** [comment]
We use MythicMobs, although we don't use it much.

**Comment by Rocologo** [comment]
Thats properly why you have not thought about MythicMobs and the achievements? 

The Progress Achievements for MythicMobs does not exists. Which is one the things I know I can make one of theses days where it rain all day like today ...

**Comment by Rocologo** [comment]
So I looked at the code: (I dont know if you can read this?)

'for (Achievement achievement : getAllAchievements()) {
'	if (achievement instanceof ProgressAchievement
'		&& ((ProgressAchievement) achievement).getMaxProgress() != 0) {
'		if (((ProgressAchievement) achievement).inheritFrom() == null)
'			++outOf;
'		} else
'			++outOf;
'}

I now see that it only counts achievements for mobs where the prize != 0 

But it should actually count progress achievements

**Comment by Rocologo** [comment]
So I looked the the code, I dont know if you can read this, but here is what it do:

`for (Achievement achievement : getAllAchievements()) {
					if (achievement instanceof ProgressAchievement
							&& ((ProgressAchievement) achievement).getMaxProgress() != 0) {
						if (((ProgressAchievement) achievement).inheritFrom() == null)
							++outOf;
					} else
						++outOf;
				}`

1) If the first level is set to 0 it is not counted. (That make sense - its a way of disabling the Progress achievements).
2) All progress achivements is counted as 1 per mob.  "_if (((ProgressAchievement) achievement).inheritFrom() == null)_" deleting this test will make the achievements count like you suggest.

I will try to remove the test an make a build which we can test, to see if we like the result.

**Comment by vilgrar** [comment]
I guess adding achievements support to MythicMobs would be a nice feature, although that's not what I had in mind when posting this issue =)

I'm not sure whether I'd prefer 76 achievements or 526. 
If 76, every achievement (rank 7) will be extremely tough to master. 
If 526, well... that's a big number.

I believe 526 is better. It's easier to compete with other players and feel a sense of accomplishment.

**Comment by Rocologo** [comment]
I have made the test
Try build 387
https://fractal.lindegaard.one:8181/job/MobHunting/

I think I prefer the big number, it also look better on the "Achievement Count leaderboard" 


I my test it said 454 achievements, but I'm pretty sure this is because some of my achievements is disabled with a prize = 0 $  

I agree it should be another ticket. ;-)

**Comment by Rocologo** [comment]
Update.. it is achievements with first level = 0 which is not counted. And I still get 454...

**Comment by vilgrar** [comment]
526 was a wild guess anyhow. 

I'm also getting 454 achievements.

**Comment by Rocologo** [comment]
Check build 389

You have got alot more achivements now...

**Comment by vilgrar** [comment]
Indeed, 509 achievements! I couldn't tell if that's the correct amount, but it should be close at least.

**Comment by Rocologo** [comment]
Fixed in V4.9.4
