### ISSUE TITLE
problems with bag of gold when inventory full

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#239]
when my inventory is full, Sometimes i can not pick up more bags of gold. even though i have one in my inventory
i think this is related to where my previous problems were coming from. maybe even the lagging
yep. confirmed. full inventories mess bags of gold up. please test confirm and fix

**Comment by Rocologo** [comment]
I agree I think the two problems is related to the space/missing space. 

I have worked on the code and tested the fix, but please help me testing. 

You should not see the bag of gold WITHOUT a space anymore. Try drop and pickup the bag if you have a bag in the inventory WITHOUT a space.

Please try build 397 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
Did you test this?

**Comment by Rocologo** [comment]
Can I close this ticket?

**Comment by Rocologo** [comment]
V4.9.5 Released.... with a fix for this. If you have any problems, please make a ticket again.
