### ISSUE TITLE
4.9.4 Config.yml typo

### ISSUE THREAD

**Issue by vilgrar** [Rocologo/MobHunting#240]
From a newly created installation:

Line 212:
  librarian-cmd: mobhunt head give {player} Libraian Librarian 1

Apparantly, Libraian uses a tiger head. Kinda cute, but not really a villager =)
I checked the rest of the mobs but found no other typos.

**Comment by Rocologo** [comment]
Stupid bug :-) 

Thanks for reporting this

**Comment by Rocologo** [comment]
Fixed in next release
