### ISSUE TITLE
Move the Achievement system to the Advancements implementation in 1.12

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#242]
Since 1.12 you can create custom achievements (advancements) and show them inside Minecraft's advancements "map", with custom icon, background, text, description, parent and (i think) a progress bar.

As for now, the only implementation of this is via [AdvancementAPI](https://www.spigotmc.org/threads/advancementapi-create-custom-advancements.240462/). Bukkit might implement it too, or maybe ProtocolLib.

I'll leave this enhancement here, low priority.

**Comment by Rocologo** [comment]
I have looked at this and I does not seem to hard to make something funny with this. 

To night I will release v4.9.5 which will be the last Java 7 release. 

Starting to use the above Advancement features forces me to compile against Java 8. 5% of my users still use Java 7, so they will have to upgrade to Java 8 to use MobHunting V5.0.0 +

**Comment by Rocologo** [comment]
Hi Maxetto, I have worked on this. It war very hard to make it work with just basic features. I have not moved from Achievements to Advancements. Both still work, so the player can choose what they want.

![2017-07-08_17 53 57](https://user-images.githubusercontent.com/1008133/27986949-9ff73dd2-6406-11e7-8f09-033e8963597b.png)

Unfortunately I don't like how it looks. I think it is hard to see ALL the achievements, and there is now way you can scroll from top to buttom easily.... 

If you want to see how it looks on your server, you can help me testing using build 428 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

Also it is not possible to show the ItemStacks, I can only show a png picture which will not work with all the rewards. In this beta release it only show a stone, I will try to make it look nicer later. First I need to do some testing.
