### ISSUE TITLE
CrackShot SUPPORT :D PLEASE!

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#244]
i'm shocked this hasn't been requested... Or maybe you decided not to do it?
The final straw was when I got a bonus for unarmed combat. There needs to be crackshot support in mobhunting. Please! You might also need to support CrackShotPlus btw, not sure but here's the link to the 2 plugins
https://dev.bukkit.org/projects/crackshot
https://www.spigotmc.org/resources/%E2%96%91-crackshotplus-%E2%96%91-1-8-x-1-12-x-%E2%96%91.18085/

**Comment by Rocologo** [comment]
Hi, I agree CrackShot should be supported BUT you need to help me complain to the dev of CrackShot

1) I dont have CrackShot and I dont want to pay for CrackShot - while MobHunting is free!
2) There is no API for CrackShot and the Source is not public, so even if I had 1) I would not be able to support it because of this.

So put pressure on the dev :-) and then I will add support

**Comment by Rocologo** [comment]
and the I found the API 
https://github.com/DeeCaaD/CrackShotPlus_V2/wiki/The-complete-guide-to-CrackShotPlus#crackshotplus-api

but I still dont have CrackShot so I cant add support

**Comment by Rocologo** [comment]
So... I found CrackShot.jar and the API, so I have started the integration/support.

It only Basic support at the moment but I think I got the bonus for Brawler (unarmed combat) removed, but I need your help testing.

I dont know CrackShot - so if you have more ideas to do/test, please tell me. Should the reward be smaller when i CrackShot weapon was used?

Please enable debug using /mh debug when you help me test, and give me the kill information in the console output,  when you find a bug.

Could I have a copy of your default-configuration files with working SOUNDS?

**Comment by Rocologo** [comment]
Try build 400
https://fractal.lindegaard.one:8181/

**Comment by Rocologo** [comment]
Im now able to check which CrackShot Weapon was used (see debug info)

[17:16:50 INFO]: [MobHunting][Debug] ======================== New kill ==========================
[17:16:50 INFO]: [MobHunting][Debug] Rocologo killed a Spider (Minecraft) using a **Bazooka**
[17:16:50 INFO]: [MobHunting][Debug] Permission 'mobhunting.mobs.*' or 'mobhunting.mobs.SPIDER' not set, defaulting to True.
[17:16:50 INFO]: [MobHunting][Debug] Basic Prize=$10 for killing a Spider
[17:16:50 INFO]: [MobHunting][Debug] Checking if player is grinding within a range of 15.0 blocks
[17:16:50 INFO]: [MobHunting][Debug] Last Kill Area Center was null. DampendKills reset to 0
[17:16:50 INFO]: [MobHunting][Debug] Multiplier: Rank = 1.05
[17:16:50 INFO]: [MobHunting][Debug] Multiplier: Sneaky! = 2.0
[17:16:50 INFO]: [MobHunting][Debug] Killstreak=1, level=0, multiplier=1.0 
[17:16:50 INFO]: [MobHunting][Debug] RecordAchievement: hunting-level5-spider has 1079 kills
[17:16:50 INFO]: [MobHunting][Debug] RecordKill: Rocologo killed a Spider (Minecraft) Cash=$21
[17:16:50 INFO]: [MobHunting][Debug] $21 was dropped on the ground as item SKULL (# of rewards=1)
[17:16:50 INFO]: [MobHunting][Debug] Command will be run if chance: 0.5 > 0.524686542074985 (random number)
[17:16:50 INFO]: [MobHunting][Debug] ======================= kill ended (37)=====================

**Comment by Rocologo** [comment]
Try build 401 or newer

**Comment by chillerkraft** [comment]
seems fine. im not really able to test if it gives that bonus still or not but i trust you. i'll let you know if i see anything in the future and run the debug for you if possible..
thanks so much! awesome work! :)

**Comment by chillerkraft** [comment]
looked in console, saw lots of errors
https://pastebin.com/JEEaKhXd here's one

**Comment by chillerkraft** [comment]
there doesn't seem to be any pattern of causes in the console before all these errors.

**Comment by Rocologo** [comment]
Stupid NPE bug. I forgot to test for null...

This should be fixed in B404
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by chillerkraft** [comment]
https://pastebin.com/NuyMqHvf

i think im still noticing unarmed stuff in the debug here

**Comment by Rocologo** [comment]
Yes, I can see you do damage with an Ak.... but when the spider dies it's not detected. Hmm.

Can I have your working weapon files so I can do better testing?

**Comment by chillerkraft** [comment]
my weapons only work with crackshotplus

**Comment by Rocologo** [comment]
Okay... I tried to do some more testing and bug fixing, using my Bazooka :-)

Please test build 405 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

And let me see the debug information in the console, if you find bugs.

**Comment by Rocologo** [comment]
I have added a "CrackShot" multiplier bonus/penalty in build 408
https://fractal.lindegaard.one:8181/

Default it is a penalty = x 0.7 because it is easier to kill the mobs using CrackShot.

What do you think about this?

**Comment by chillerkraft** [comment]
sounds good
ill give that a try
thanks!

**Comment by Rocologo** [comment]
Dont you Build 407-410. Go directly to Build 411. The others is causing big lag!!!

Build 411 is lag free on my main server.
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by chillerkraft** [comment]
thankyou

**Comment by Rocologo** [comment]
When you say go I will make an official release of V4.9.5 ?

**Comment by Rocologo** [comment]
V4.9.5 Is released. Please create a nerw ticket if you find any bugs or have a suggestion for the CrackShot support.
