### ISSUE TITLE
A biiiiiig BUG   /mh bounty gui

### ISSUE THREAD

**Issue by tygh78071388** [Rocologo/MobHunting#245]
/mh bounty gui

In GUI

Can take  out the Head skull   !!!!!!

OMG!!!!!

spigot-1.11.2

MobHunting-V4.9.4

**Comment by Rocologo** [comment]
This is the same bug as https://github.com/Rocologo/MobHunting/issues/84, please continue the discussion on this ticket. 

I CANT replicate this error. Not matter if i rightclick or leftclick the window closes immidiately

I close this ticket now, but please describe exactly what you do, and how you get a head out on the other ticket???

**Comment by Rocologo** [comment]
Unfortunately I cant replicate this error :-( so I need your help to see if changes works.

Please test build 398
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by tygh78071388** [comment]
not fix... 
![1](https://user-images.githubusercontent.com/28720564/27009304-14161a4e-4ebd-11e7-965b-f63f9807e33b.png)
![2](https://user-images.githubusercontent.com/28720564/27009305-141c6b60-4ebd-11e7-9f7d-72495d02be61.png)
![3](https://user-images.githubusercontent.com/28720564/27009306-141ef038-4ebd-11e7-9ca8-aed5d8d18065.png)
