### ISSUE TITLE
Money Problem

### ISSUE THREAD

**Issue by BlueGoldenKnight** [Rocologo/MobHunting#246]
I've installed the plugin correctly, and I also have the required plugins installed, but for some reason when I test out the money drops nothing happens.

I've set the region to mobhunting allow, and I want the mobs to drop moneybags but for some reason nothing is dropping every time I kill different mobs.

Am I doing something wrong in the config ? Everything is enabled to allow the money drop but it doesn't seem to be dropping anything.

**Comment by Rocologo** [comment]
Enable debug with /mh debug and let me see the kill information in the console

You can also try /mh learn

**Comment by BlueGoldenKnight** [comment]
It happens that I was in God mode, which disables money drops... but it seems to work now! 
Thank you :D

**Comment by Rocologo** [comment]
/mh debug and /mh learn are VERY use full, when you dont understand you dont get a reward :-)

And yes... NO CHEATING !!! You dont get money if you dont risk anything :-D

**Comment by BlueGoldenKnight** [comment]
Theres a problem now that when players sell the bag of gold, when they click the sign and have it in their hand it says to "hold the bag of gold in their hand", how do I fix ?

**Comment by Rocologo** [comment]
Strange...

If they have permission "mobhunting.bagofgoldsign.use" and they have the reward in their hand it should work??? 

Unless something wrong with the reward... Have you tried to give yourself a bagofgod and then sell it by clicking on the sign?

**Comment by Rocologo** [comment]
Please test Build 404 or newer on my jenkins server

https://fractal.lindegaard.one:8181/

**Comment by BlueGoldenKnight** [comment]
Yea they have permission, and they also have the bagofgold in their hand when clicking on the sign

**Comment by Rocologo** [comment]
Try build 404 with a new bag of gold

**Comment by Rocologo** [comment]
Do you need more help? I want to close the ticket....
