### ISSUE TITLE
lag when picking up bag of gold with full inventory

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#248]
title says it all

**Comment by Rocologo** [comment]
I dont see any lag, when the inventory is full?????

**Comment by Rocologo** [comment]
Make sure that you have /mh debug enabled and check the log for information when you see the lag

**Comment by Rocologo** [comment]
Or you could try build 404 or newer http://jenkins.lindegaard.one:8180/job/MobHunting/

I have actually worked on a bug on the BagOfGold today. Maybe these two bugs are releated?

**Comment by chillerkraft** [comment]
okay the lag might be fixed, i dont see it being a problem anymore
but why are arrows destroying the bags of gold? can i turn that off?

**Comment by Rocologo** [comment]
No, this is a standard Minecraft thing. It's not me removing the bags.

**Comment by Rocologo** [comment]
Case closed

**Comment by Rocologo** [comment]
I have re-opened this issue, because I see lag too... ????

**Comment by chillerkraft** [comment]
is it right when you pick up the bag? a little freeze before the bag gets picked up?

**Comment by Rocologo** [comment]
Actually it was when I wanted to record an Achievement.

It took me 3 hours to find a stupid bug I made this morning. 

Build 413 is lag free on my PROD server.
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by chillerkraft** [comment]
14.06 06:27:56 [Server] INFO [MobHunting] Enabling MobHunting v4.9.5-SNAPSHOT-B413
14.06 06:27:56 [Server] INFO [Mobhunting]==================WARNING=================================
14.06 06:27:56 [Server] INFO Potential error in your config.yml. pvp-kill-cmd contains SkullOwner,
14.06 06:27:56 [Server] INFO which indicates that pvp-kill-cmd is outdated. Check the head command
14.06 06:27:56 [Server] INFO or delete the line pvp-kill-cmd, and then reload the plugin. The 
14.06 06:27:56 [Server] INFO correct syntax to get a player head is:
14.06 06:27:56 [Server] INFO "mobhunt head give {player} {killed_player} {killed_player} 1 silent"
14.06 06:27:56 [Server] INFO [Mobhunting]=========================================================

**Comment by chillerkraft** [comment]
im on spigot 1.11.2 still btw

**Comment by Rocologo** [comment]
No problem. I do my best to support 1.7.10 - 1.12, but in near future I will have to compile against Java 8. So if you are not up to date with java, you should start thinking about upgrading!

About the warning, read what it says, it tells you what to do ;-) 

Explanation: One of the other MobHunting users found a bug and I realized that the head drops on pvp killings did not work, because of the wrong syntax mentioned above. My politics is that I never change the values you have entered in your config.yml, but in this case the error is important to fix, so I decided to make an alert instead of changing one of your settings in the config.yml

**Comment by chillerkraft** [comment]
o ok so if i dont have pvp on my server then it doesnt matter right? and if i want to fix it i just have to change one thing?

**Comment by Rocologo** [comment]
Correct. You dont have to.

Bu in this case I would recommend to delete the line pvp-kill-cmd and then the bug is fixed anyway - when ever you choose to restart your server. And then you will get rid of the warning too.

**Comment by Rocologo** [comment]
I will make a release tonight, when I get back from work. This will properly be the last Java 7 release.

**Comment by Rocologo** [comment]
Fixed in V4.9.5
