### ISSUE TITLE
Language file reset to defaults

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#257]
Spigot 1.11.2 and 1.12
MH 4.9.5

It's possible I'm mistaken (difficult to retrace my steps), but it looks like the language files were overwritten by defaults, on update from MH 4.9.4.

I edit the language files extensively, so losing my changes is a pain. Fortunately, I have backups, but still...

**Comment by Rocologo** [comment]
I cant replicate this and i typically run more than 20 updates while testing. I would know if the lang files was updated

**Comment by SlimeDog** [comment]
OK. I must have mistaken my sequence.  My error. In the current situation, I have to move my config.yml (heavily edited), generate the new one on startup, stop, compare it to a saved previous default version, then modify my version as necessary.

It would be great if you could include the default config.yml as a file in the jar. That would make it easier for me to compare.

**Comment by Rocologo** [comment]
I think we have discussed this before :-)

There is no default config.yml this is not how it works with MobHunting.

I normally dont change the values in your config.yml and IF i do, I will normally mention this in the release notes.
