### ISSUE TITLE
dragon head turned into square dragon head

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#258]
i dont know if this always happens, but a player of mine broke his enderdragon head and it turned into a flatface dragon head whenever he places it

**Comment by Rocologo** [comment]
Please test build 420 
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by chillerkraft** [comment]
not running into the issue anymore but unsure if fixed tbh, i think it was a uncommon occurance
thanks roco

**Comment by Rocologo** [comment]
I did rather major changes to fix this one, both on the EnderDragon head, but also on the displaynames on all the MobHunting rewards (incl Bag of Gold) 

I also tried to test pickup/drop/break/place item/block for both mob heads, player heads and Bag of Gold, so I think I found the bug.

If have not found any errors yet, this is good news. I close this ticket now.
