### ISSUE TITLE
problem fighting wither apparently

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#259]
https://pastebin.com/gdWRMXa0

**Comment by Rocologo** [comment]
Please explain what you are doing. 

There must be something with CrackShot I am not aware of. I need to replicate the bug to fix it.

**Comment by chillerkraft** [comment]
i'll let you know if i find out when it comes up
i just noticed it like 30 mins after it showed up in console.

**Comment by chillerkraft** [comment]
feel free to close my issues :)

**Comment by Rocologo** [comment]
Okay, i close it for now, I can easily open it again
