### ISSUE TITLE
Bounties needs to be translatable

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#26]
As in title, new bounties messages are hard coded in english.

I really like the idea of those new Bounties, however I need to translate the messages, otherwise 3/4 of my players won't understand how to do it.

P.S. `MobHunting.getInstance().getLogger().info("Compatability with arAPI in config.yml");`
"Compatibility with BarAPI in config.yml"

**Comment by Rocologo** [comment]
Ha ha, you are fast i havn't even publish a version with bounties yet! I am trying to find most of the bugs before i release first version. And yes I have to add the messages to the lang file. Where are you from? What language do you speak? If you have translated the lang file I would like to have a copy for the plugin. 

The basic Bounty features works almost now, except removing a bounty, so I hope I can release a new version tomorrow. 

I have also added support for BarAPI, BossBarAPI, TitleWelcomeMessage, VanishNoPacket. 

Im planning to add Bounty Gui, a Random Bounty every X time on an a online player if there are more than Y players on the server. (All configurable in config.yml)

I want to use TitleWelcomeMessages when the player get an achievement. But I have not added the code. It will only be showed the player, not broadcasted to everyone.

BossBarAPI or BarAPI is used for the learn feature. (As a test).

**Comment by Rocologo** [comment]
Also I want to add a feature where the reward is droped on the ground as gold and when the player pickup the gold, he get the money, but not the gold item. Like other RPG computer games.

**Comment by Maxetto** [comment]
I'm from Italy and I do have translated the language file. However I think it's not a good candidate as I've done some personal touches to Achievement names, so they are not objective anymore.

I'll try to pull a better and more faithful translation soon ;)

**Comment by Rocologo** [comment]
I will add support for TitleManager Immidiately, but ActionBar is a paid ressource, and I dont want to pay 5$ to add support for that one. I checked TitleMananger and it can write in the action line.

I will use the action bar for the "normal" mobhunting messages.

**Comment by Maxetto** [comment]
Yeah, sorry. I explained it badly. I exactly meant that TitleManager can also show ActionBar messages, so you're covered with every possible way to send messages :stuck_out_tongue:

**Comment by Rocologo** [comment]
I will release version 2.9.0 in 10 minutes. Please help me testing. :-)
