### ISSUE TITLE
Move from SLF4J to Bukkit's Logger

### ISSUE THREAD

**Issue by Rocologo** [Rocologo/MobHunting#263]
Why not using the Logger available in Bukkit?
https://github.com/Rocologo/MobHunting/blob/master/pom.xml#L765-L781

**Comment by Rocologo** [comment]
I removed the dependency from my pom.xml and discovered that I had already changed the code. I just forgot to remove the dependency :-(

**Comment by ysl3000** [comment]
@Rocologo I think  bukkit already has log4j as a dependency. Though double dependency,
