### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by bladen** [Rocologo/MobHunting#264]
Right now anything that is left blank in the lang file shows as a blank line in chat. Can it be made so that if line is blank don't send anything to change at all please?
Thanks!

**Comment by Rocologo** [comment]
I know it works on some of the strings, so I need you to be more specifik. I need the string name you want to clear?

**Comment by bladen** [comment]
mobhunting.commands.head.you_got_a_head

**Comment by Rocologo** [comment]
I next release there will not be printed a blank line if the message is removed. But if only works on "mobhunting.commands.head.you_got_a_head" for now. I dont have the time to make this change on ALL texts, but let me know if you have others you want to remove the same way.

**Comment by Rocologo** [comment]
Please test on build 426 or never, and let me know if it works.
https://fractal.lindegaard.one:8181/job/MobHunting/
