### ISSUE TITLE
random error i found idk how it happened

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#265]
https://pastebin.com/xMntChUj

**Comment by ysl3000** [comment]
Do you have Essentials installed?

https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/compatibility/EssentialsCompat.java#L53
 @Rocologo please check if user isn't null.

**Comment by Rocologo** [comment]
I will look at it, but I will rather find out why the user is null, instead of testing for that. 

It will be fixed anyway.

**Comment by Rocologo** [comment]
I think I have fixed this in build 427 or newer. Please help me testing. The bug was related to CrackShot, so you would only get this error on servers using CrackShot.

https://fractal.lindegaard.one:8181/job/MobHunting/
