### ISSUE TITLE
Killing yourself triggers MobHuntKillEvent

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#27]
Killing yourself by splash potions or arrows triggers MobHuntKillEvent. This seems to not apply by Essentials /suicide or /kill command (But it could by other plugins (?)).

This activates everything related to a kill: Achievements, Money loss/give from PvP and maybe Bounties.

**Comment by Rocologo** [comment]
Nice observation. I have not tried this myself, but this is something I have to look into.

**Comment by Rocologo** [comment]
In next release you dont get a reward if killer = killed player.

**Comment by Rocologo** [comment]
V2.9.2 is released. I hope I Fixed this issue.

**Comment by Rocologo** [comment]
Could I ask you to give me feedback if the problem persists or if is solved? :-)
