### ISSUE TITLE
Kill streak

### ISSUE THREAD

**Issue by WindUnwaken** [Rocologo/MobHunting#271]
Please add worldchange check, because I have two type of world can kill mob.
Example, easy world and ExtraHard mode, players can killstreak in easy world, 
then go to ExtradHard mode get more rewards

**Comment by Rocologo** [comment]
Thank you for creating a ticket, this helps me keeping track of the open tickets and makes sure that I don't forget something. 

I have work some hours today on this, it was not as easy as I thought :-( but I think it works now.

Please help me with the testing. 

You will need to test killstreaks in general, I had to do more changes than just listen for a PlayerWorldChangeEvent.

Please try buld 436 or newer on my Jenkins server:
https://fractal.lindegaard.one:8181/job/MobHunting

**Comment by Rocologo** [comment]
This should be fixed in v5.0.2
