### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by WindUnwaken** [Rocologo/MobHunting#273]
https://pastebin.com/fNZUMVZG

**Comment by Rocologo** [comment]
This is an error in your MySql configuration and not a bug in MobHunting. Check this one: https://stackoverflow.com/questions/10376725/how-do-i-resolve-a-mysql-thread-stack-overrun

You should use a performance MySQL toll to optimice your settings. I use this one: https://www.howtoforge.com/tuning-mysql-performance-with-mysqltuner

I will come with a lot of suggestions on how to optimize the settings in your database.

**Comment by WindUnwaken** [comment]
I have several plugins use database, so I change thread-stack:256k
I think it should be enough now.

**Comment by Rocologo** [comment]
MySQL Tuner will tell you what to do to uptimize performance

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
