### ISSUE TITLE
looks like duplicate code 

### ISSUE THREAD

**Issue by ysl3000** [Rocologo/MobHunting#274]
move to class and delegate the data in each event to an instance of this class.

https://github.com/Rocologo/MobHunting/blob/5078428dbd5fdcab229b5d7ec624530acbe7b68e/src/one/lindegaard/MobHunting/rewards/EntityPickupItemEventListener.java#L28-L125

https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/rewards/PlayerPickupItemEventListener.java#L29-L107

**Comment by Rocologo** [comment]
It is almost the same code but I have added a test in the new Listerner, to check if it is a player or a mob who picks up an item. 

I don't know if I understand what you suggest, but I will try to optimize my code.

**Comment by ysl3000** [comment]
Should I do a pr for that?

**Comment by Rocologo** [comment]
You are VERY welcome to do so!

**Comment by Rocologo** [comment]
I keept the code you made to fix this
