### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Hakkehify** [Rocologo/MobHunting#278]
The bug is almost equal to the previous report, pressing ctrl + left click is doubled, the previous one was with the left click , srry for my english :/

**Comment by Rocologo** [comment]
Are you on V5.0.3?

**Comment by Rocologo** [comment]
Please test V5.0.4

**Comment by Rocologo** [comment]
I have tested Ctrl+left click on both V5.0.4 and on V5.0.5 I can replicate the issue. 

Please try "/Mh version"  and check that you are up to date?

**Comment by Rocologo** [comment]
fixed in v5.0.6
