### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting v5.0.3

### ISSUE THREAD

**Issue by comonier** [Rocologo/MobHunting#280]
10.08 13:30:23 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v5.0.3
10.08 13:30:23 [Server] INFO org.bukkit.event.EventException: null
10.08 13:30:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1109) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.EntitySkeleton.die(EntitySkeleton.java:46) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.attack(EntityMyPet.java:339) [MyPet-2.3.0.jar:?]
10.08 13:30:23 [Server] INFO at de.Keyle.MyPet.compat.v1_12_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:115) [MyPet-2.3.0.jar:?]
10.08 13:30:23 [Server] INFO at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-2.3.0.jar:?]
10.08 13:30:23 [Server] INFO at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1012) [MyPet-2.3.0.jar:?]
10.08 13:30:23 [Server] INFO at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:936) [MyPet-2.3.0.jar:?]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1133) [MyPet-2.3.0.jar:?]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1640) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.World.h(World.java:1610) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1436) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-86aa17f]
10.08 13:30:23 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
10.08 13:30:23 [Server] INFO Caused by: java.lang.NullPointerException
10.08 13:30:23 [Server] INFO at one.lindegaard.MobHunting.HuntData.getHuntDataFromPlayer(HuntData.java:316) ~[?:?]
10.08 13:30:37 [Multicraft] Skipped 7 lines due to rate limit (30/s)

**Comment by Rocologo** [comment]
Please test V5.0.4
