### ISSUE TITLE
Additional Bounty permissions

### ISSUE THREAD

**Issue by Zoneman1972** [Rocologo/MobHunting#287]
Hi there. I would like to lodge a request for an extra permission node that can allow my admins to be bounty exempt. 
Also, an option to disable the auto bounty login notification for admins or vanished players. 
And finally, an admin command that allows us to remove the random bounties from players. 
Thanks heaps for all your hard work on this plugin. Me and my players absolutely love it!

**Comment by Rocologo** [comment]
Hi, thank you for creating a ticket. 

I have added some new features for you:

V5.0.7
* Added new features. Ticket 287 (https://github.com/Rocologo/MobHunting/issues/287)
* Vanished players is exempt from Random Bounties
* Players with permission "mobhunting.bounty.randombounty.exempt" is exempt from Random Bounties.
* Players with permission "mobhunting.bounty.admin" can delete random bounties

please test the snapshot on my jenkins server, build 453 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
So I spend two hours on fixing this... I did not have much time to test the stuff, but I hope I am almost there now.

Please test build 458
https://fractal.lindegaard.one:8181/job/MobHunting/

PS. 10000000 is the same as 1.0E7 - it is a scientific notification (1.0E7 = 1.0*10⁷). But now it is formatted (i hope)

**Comment by Rocologo** [comment]
I have released V5.0.7, with the above fixes included. Let me know if you find any bugs.

**Comment by Zoneman1972** [comment]
Hey there,
Thanks again for working so hard on this plugin.
I hate to say it but I am getting an error in the console.
This is the message that I am getting:

25.08 00:16:04 [Server] WARN [MobHunting] Plugin MobHunting v5.0.7
generated an exception while executing task 166 25.08 00:16:04 [Server] INFO
java.lang.NoClassDefFoundError: Could not initialize class
one.lindegaard.MobHunting.compatibility.HerobrineCompat 25.08 00:16:04
[Server] INFO at
one.lindegaard.MobHunting.MetricsManager$39.getValue(MetricsManager.java:406)
~[?:?] 25.08 00:16:04 [Server] INFO at
org.mcstats_mh.Metrics.postPlugin(Metrics.java:449) ~[?:?] 25.08 00:16:04
[Server] INFO at org.mcstats_mh.Metrics.access$400(Metrics.java:61)
~[?:?] 25.08
00:16:04 [Server] INFO at org.mcstats_mh.Metrics$1.run(Metrics.java:242)
~[?:?] 25.08 00:16:04 [Server] INFO at
org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 25.08 00:16:04 [Server] INFO at
org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e] 25.08 00:16:04 [Server] INFO at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[?:1.8.0_131] 25.08 00:16:04 [Server] INFO at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[?:1.8.0_131] 25.08 00:16:04 [Server] INFO at
java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Rocologo** [comment]
Do you have the Herobrine plugin installed on your server?

**Comment by Rocologo** [comment]
I think you can fix this by disable integration to the Herobrine plugin in config.yml.

I will fix this in v5.0.8

**Comment by Zoneman1972** [comment]
No I don't. I didn't even know there was a herobrine plugin

**Comment by Zoneman1972** [comment]
Ahhhhh ok I see. Let me check and get back to you

**Comment by Rocologo** [comment]
V5.0.8 is released. Try this instead.
