### ISSUE TITLE
Cant Create Master MobHunters

### ISSUE THREAD

**Issue by Spudkill** [Rocologo/MobHunting#289]
As the title states cant create Master MobHunters
I try to use the command /mh npc (and /mobhunter npc) and it get 'Unkown command' then a list of all the valid MobHunting commands

Clean Install of a Spigot 1.12.1 Server with completely new config files for every plugin
I tried changing 'disable-integration-citizens: false' to true just for laughs and and it disabled citizens integration like it should

The Plugins i'm running are:
MobHunting
Citizens2
EssentialsX
Vault
ProtocolLib

Here is a paste of my server Log
https://paste.ee/p/7DM81

**Comment by Rocologo** [comment]
The server log looks fine, except you server jar is outdated. 

You should check your permissions. Looks like if you are missing mobhunting.npc

**Comment by Rocologo** [comment]
Oh, I didnt notice that you did not have a permission plugin. 

Without a permission plugin you must be "OP" to be able to use the "/mh npc" the plugin should work without PermissionsEx, but I have not tested everything. 

I cant verify your permissions with the complete permissons.yml file. If you paste the complete file, I will have a look.

**Comment by Spudkill** [comment]
I was op in both instances and that was a complete past of my permissions file, this is a test server I have setup to try and figure out how to get these to work because I couldn't get them to work on my actual server

**Comment by Rocologo** [comment]
Wait, maybe it is citizens permissions you are missing? Have you tested if you can create a NPC at all?

Try if you can do "/npc create Spudkill" ?

if not you have to setup permissions for Citizens (npc)

**Comment by Spudkill** [comment]
That command works

**Comment by Rocologo** [comment]
I just tested /mh npc on my test server and I have the same problem :-( 

Something has broken in one of the latest updates. Its not a problem on your server as I thought. I will fix this fast!!!

**Comment by Rocologo** [comment]
This is fixed in V5.0.7
