### ISSUE TITLE
Cannot load Mobhunting 2.9.9 after the update

### ISSUE THREAD

**Issue by Pinjosi** [Rocologo/MobHunting#29]
Hi there

I have minecraft bukkit 1.9.4 but cant load your new mobhunting see the error below:

Severe: Could not load 'plugins\MobHunting2.9.9.jar' in folder 'plugins'
JavaStackTrace: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit.jar:git-Bukkit-c5e9a16]
JavaStackTrace: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit.jar:git-Bukkit-c5e9a16]
JavaStackTrace: at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Bukkit-c5e9a16]
JavaStackTrace: at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:293) [craftbukkit.jar:git-Bukkit-c5e9a16]
JavaStackTrace: at org.bukkit.craftbukkit.v1_9_R2.CraftServer.<init>(CraftServer.java:255) [craftbukkit.jar:git-Bukkit-c5e9a16]

**Comment by Rocologo** [comment]
Please try this new version:

[https://www.dropbox.com/s/cuql423t548qvdb/MobHunting3.0.0PRE4.jar?dl=0](url)

If you get any errors in the console I need the full error text thrown in the console. I need line numbers and file names an so to try to find the bug.

**Comment by Rocologo** [comment]
Closed because not answering my questions an no reaction at all.
