### ISSUE TITLE
An error in console maybe for MobHunting, just reporting.

### ISSUE THREAD

**Issue by TheZenKitteh** [Rocologo/MobHunting#291]
Usually when I spot an error in console, I try to figure out what plugin caused it and report it so the plugin can be improved even more. Saw this error this morning and I think it might be MobHunting but not entirely sure.

https://pastebin.com/raw/DPXTiAwT

**Comment by Rocologo** [comment]
You can see whic plugin causes the from this line starting with "Caused by"...

_Caused by: java.lang.NullPointerException
	at one.lindegaard.MobHunting.rewards.RewardListeners.onRewardBlockBreak(RewardListeners.java:289) ~[?:?]_

So in this case it is MobHunting. (And it is line 289 in the RewardListerners.java file.

I will try to fix it....

**Comment by Rocologo** [comment]
Please test build 464
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by TheZenKitteh** [comment]
Testing build 465. No errors on starting. If I spot anymore errors I will report them. Thank you.
