### ISSUE TITLE
console ERROR 5.0.8 on spigot 1.12

### ISSUE THREAD

**Issue by comonier** [Rocologo/MobHunting#295]
7.09 11:14:52 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v5.0.8
07.09 11:14:52 [Server] INFO org.bukkit.event.EventException: null
07.09 11:14:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1109) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPigZombie.damageEntity(SourceFile:148) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.e(EntityLiving.java:1204) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.Block.fallOn(Block.java:533) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.a(Entity.java:1026) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:190) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:808) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1806) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2117) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityZombie.n(EntityZombie.java:155) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1640) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.World.h(World.java:1610) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:14:52 [Server] INFO at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1436) [spigot.jar:git-Spigot-596221b-86aa17f]
07.09 11:15:00 [Multicraft] Skipped 16 lines due to rate limit (30/s)

**Comment by Rocologo** [comment]
I need The full error text to solve this issue: 07.09 11:15:00 [Multicraft] Skipped 16 lines due to rate limit (30/s)

I need the last 16 lines from the server log
