### ISSUE TITLE
Hologram-related messages are incorrect

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#297]
Message with variables inside single-quotes are not displayed correctly. The variable names are displayed, rather than the values. Here is the list:
```
mobhunting.commands.hologram.created=The hologram '${hologramid}' was created
mobhunting.commands.hologram.deleted=The hologram '${hologramid}' was deleted.
mobhunting.commands.hologram.hologram_exists=The hologram '${hologramid}' already exists, please use another name!
mobhunting.commands.hologram.unknown=The hologram '${hologramid}' does not exist.
```

This one is probably similar:
```
mobhunting.bagofgoldsign.line3.not_a_number=Line 3 must be a positive number or '${everything}'
```

**Comment by Rocologo** [comment]
I just tried "/mh hologram delete test4"  and it worked on my test server???
![2017-09-13_21 25 36](https://user-images.githubusercontent.com/1008133/30396507-2727d5c6-98ca-11e7-9811-06db6f37f077.png)

**Comment by SlimeDog** [comment]
I am getting different. For example:
```
The hologram ${hologramid} was updated.
```

**Comment by Rocologo** [comment]
Strange, maybe its a linux/windows think. Im on linux, are you on windows? 

I think i will solve this problem using colorcodes instead of ' '

**Comment by SlimeDog** [comment]
CentOS Linux.

**Comment by Rocologo** [comment]
I have now colorcoded the hologramname instead of using ' ' 

Please try build 466
https://fractal.lindegaard.one:8181/job/MobHunting/
