### ISSUE TITLE
HolographicDisplays ignores Essentials currency-symbol setting

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#298]
Spigot 1.12.1
MH 5.0.9-B464
HolographicDisplays 2.2.6

Essentials/config.yml
```
currency-symbol: ''
```
but $ is displayed for Total_Coins (for example). I do not see the amount dropped in the database.

**Comment by Rocologo** [comment]
Strange??? I Use Essentials format ...

`public String format(double amount) {
		return mEconomy.format(Misc.round(amount));
}
`
As you see I dont add the $ to the String............... hmmmm

**Comment by SlimeDog** [comment]
Yeah, I saw that. Maybe HolographicDisplays does. I think I didn't see it with Holograms, but that has other problems (like lack of persistence).

**Comment by Rocologo** [comment]
I tried to change 

Essentials/config.yml

currency-symbol: '£'

And it worked on my test server???

![2017-09-13_21 08 32](https://user-images.githubusercontent.com/1008133/30395888-0153f03e-98c8-11e7-8a3d-4509e4045eeb.png)

I use EssentialsX what do you use?

**Comment by SlimeDog** [comment]
Sheesh! It doesn't like an EMPTY string ''. It works fine with blank string ' '.
