### ISSUE TITLE
Dropped money not added to database.

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#299]
Spigot 1.12.1
MH 5.0.9-B464
HolographicDisplays 2.2.6

Display Total_Coins in hologram.
Drop and pick up moneybag.
Update hologram.
Total_Coins does not change.
No indication of added coins in database.

**Comment by Rocologo** [comment]
Total_Coins count the amount of money dropped from killed mobs, no matter if they are picked up or not. If you drop some money your self it is not counted.

**Comment by SlimeDog** [comment]
Hmmm. Unfortunately, I need to know the amount picked up. If it's dropped and left, someone else can pick it up. Or eventually, it will despawn? In any event, I want to display the player balance, so I guess I'll try [Holographic-Scoreboard](https://www.spigotmc.org/resources/holographic-scoreboard.2700/).
