### ISSUE TITLE
Some links broken on spigot page

### ISSUE THREAD

**Issue by TheZenKitteh** [Rocologo/MobHunting#300]
I was looking through what MobHunting can do and noticed I can't figure out how to make leaderboard signs because the links from the spigot page are broken. It is also broken on https://www.spigotmc.org/wiki/mobhunting-commands-permissions/

As well, I suggest a little more detail on the bounty command. What exactly is the "prize"? Thank you.

**Comment by Rocologo** [comment]
https://www.spigotmc.org/wiki/mobhunting-creating-leaderboards/

**Comment by Rocologo** [comment]
The prize is what ever amount of money the player chooses to put on his enemy.
