### ISSUE TITLE
Hologram update leaves ghost of previous value

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#302]
Spigot 1.12.1 latest
MH 5.0.9-b465
HolographicDisplays 2.2.6

Previous value: 89422
Updated value: 89547

![hologram](https://user-images.githubusercontent.com/17748923/30408131-a75ac58c-98b1-11e7-971d-6be19283f9b5.png)

When I delete the hologram, the old version is still present. Only way to remove it is to restart the server. :(

So the update isn't displayed in exactly the same location as the original.

**Comment by SlimeDog** [comment]
I don't see a way to configure how often a hologram is updated. What is the default?

**Comment by Rocologo** [comment]
Ahh, im sorry it seems i introduced a bug when i changed the manuel update command so it read the format string again. I will fix this tomorrow. 

The holograms is updated in the same cyklus as normal leaderboards so it is the same setting. I think the dafault time is 15 min

**Comment by Rocologo** [comment]
Is it the player balance i show??? It should be the amount of money dropped from killed mobs???

**Comment by SlimeDog** [comment]
It is possible to configure a different update cycle? Where can I set the configuration for "normal leaderboards"?

At present on my test server, player balance and money dropped from killed mobs are the same, since there have been no other transactions.

Curious though, what is
```
/mh hologram create test Minecraft_[$] AllTime 10
```
supposed to display?

**Comment by Rocologo** [comment]
It does not really make sense to have different settings for the leaderboards. The work done in the background is basically the same, (Queries to the database and so on). It is only the presentation which is different. 

Minecraft_[$] is a bug. Minecraft_Kills and Minecraft_Money should show the number of killed Minecraft Mobs and the money dropped. MythicMobs and other would not be counted then.

**Comment by SlimeDog** [comment]
I'm sure you're aware that Minecraft_money is not one of the listed variables.

**Comment by Rocologo** [comment]
Minecraft_[$] does now work as intended. It will show how much money is dropped from killing Minecraft mobs.

And /mh Hologram update holoramname

Does now delete the old hologram before it loads the new one from the file and update the values.

**Comment by SlimeDog** [comment]
Shouldn't Minecraft_[$] give the money balance? I realize that is not an MH thing, but ... placeholders. :)

**Comment by SlimeDog** [comment]
My server requires that the player pick up the bag of gold to earn the coins, thereby being exposed to more attacks from other mobs. In fact, the resultant bags of gold could be picked up by another player. So I don't care about the coins "earned" by killing the mobs. I really need a variable that is the amount of money picked up. I guess that isn't tracked presently in MH. Any bag of gold picked up is added into the player's money balance, although other transactions can change the balance, so it isn't a good track over time. Please think about a configuration option that tracks kills only if the bag of gold is picked up. By default, it could operate as it does now.

**Comment by Rocologo** [comment]
I dont know if there is a Minecraft placeholder called Minecraft_[$] , I was hard to give some of the StatTypes a meaningful name. 

Minecraft_Kills is the number of killed minecraft mobs
Minecraft_Assists is the number of assisted kills of Minecraft Mobs
Minecraft_[$] is the amount of money dropped from killed Minecraft mobs. Is Minecraft_cash better?

I have implemented basic intergration to Placeholders https://www.spigotmc.org/resources/placeholderapi.6245/ but I did not know which Placeholders would be useful?

**Comment by SlimeDog** [comment]
Minecraft_cash would be better.

Placeholders: It would be nice to be able to incorporate any placeholder, but that may be beyond the reasonable.

I would like either _money_ or _vault_eco_balance_, since Vault is required. :)

**Comment by Rocologo** [comment]
If you change Minecraft [$] in your lang file to "Minecraft cash" and restart your server, the holograms and leaderboards will be updated with the new name :-)

I next snapshot this is default, but you will have to update you lang file manually anyway.

At the money I dont want to add non-mobhunting related placeholdes, but if you take a look at PlacholderAPI you should be able to find what you seek?

**Comment by Rocologo** [comment]
Have you found more bugs or can I make a 5.0.9 release now?

**Comment by SlimeDog** [comment]
Yes, I use Placeholders extensively. The problem is that you have produced a useful holographic scoreboard. Others are severely lacking. :(

**Comment by SlimeDog** [comment]
I think 5.0.9 is a "go"
