### ISSUE TITLE
/mh kills - Inventory GUI 'Ongoing' bug

### ISSUE THREAD

**Issue by Waterman1001** [Rocologo/MobHunting#307]
Hey Rocologo :)

I have reported this bug before in the discussion section, but because this is the actual place I have to report bugs, I am reporting it here as well.

Sometimes achievements you have already gotten don't go away out of the GUI of '/mh kills' on the page of 'Ongoing'
So for example: I have killed 500 ZombiePigmans, and at the ongoing page it still says 'Hunt 100 ZombiePigmans'.
But at the completed page it shows that I have completed the achievement 'Hunt 250 ZombiePigmans'

![image](https://user-images.githubusercontent.com/19939623/31309876-f0483420-ab8d-11e7-99e6-2ae69e7f552b.png)

On this picture you can see that I already have got the 250 and the 500 ZombiePigmans.

![image](https://user-images.githubusercontent.com/19939623/31309885-1b9b5684-ab8e-11e7-927e-399ff1657e3f.png)

And on this picture you can see that I don't have the 'Hunt 100 ZombiePigmans' Achievement.

I hope you understand what I mean and that you can fix it :D

Despite that I still want to say that I really love this plugin, so keep up the good work! 👍

**Comment by Rocologo** [comment]
Hi, It's a hard one to fix, because the data in the database is wrong. It would be nice if I could have a copy of the database so I could find a fix. Do you use SQLite?

**Comment by Waterman1001** [comment]
Hii,

Okay, I don't use SQLite, but I can send you a copy of the database if you want to?
I'll do everything that you are saying, to help you fix the bug.

**Comment by Waterman1001** [comment]
This is the database. 
(Sorry for closing and reopening this issue. I clicked the wrong button.)

[mobhunting database.zip](https://github.com/Rocologo/MobHunting/files/1367183/mobhunting.database.zip)

**Comment by Rocologo** [comment]
Please help me test build 481 (or newer) I hope i found a fix.
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Waterman1001** [comment]
Yay! You fixed it. You're a hero :)
Thanks for helping me!!
