### ISSUE TITLE
[bug] Heads randomly turning into money bags

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#309]
I dont know why but sometimes heads are just chaining to money bags in my inventory, I disabled the money bag thing, I do not want to use money at all. I just want to use the plugin to collect heads. Why are the heads turning to money bags? Im not running commands either.

**Comment by Rocologo** [comment]
One thing is for sure, its not randomly, so if you help me discover when this happens, then I will fix it. 

But I cant fix this issue without your help, because I have never seen this...

**Comment by FrozenBeard** [comment]
We couldn't figure it out, we were testing it on our test server test.piratemc.com and killing mobs, placing heads, dropping them etc, and we just noticed that they all turned to money bags.

**Comment by Rocologo** [comment]
It can easily be a bug some where in the code, but without an example I cant fix this one. I have no idea about where the bug could be, and I have never seen it before on my own server, or heard about from other users. 

Until I get some more details about this bug, I can do anything. sorry...

**Comment by Rocologo** [comment]
I have seen this error too now :-( 

Unfortunately I don't know what trigger this error, so you will still need to help observe. 

It could be something with server restarts and/or changing game mode, but I don't know yet.

**Comment by Rocologo** [comment]
I think I found the error now. And release V5.1.6, as fast as possible because I think it is a critical bug.
