### ISSUE TITLE
[Question/Bug?] Insane reward amounts: how are they calculated?

### ISSUE THREAD

**Issue by Formula350** [Rocologo/MobHunting#311]
Here is the example I'm working from:
![image](https://user-images.githubusercontent.com/10291023/31579240-0f673438-b100-11e7-8e5a-49e752b0b325.png)

My config is set that Iron Golems can earn you between 20 and 40, set as `20:40`.
Obviously I have ConquestiaMobs installed and in the specific place this mob was killed, meant they were at level 150. My difficulty is set to "3" (Hard), but in F3 usually reports around 3.2 to 3.5.

I can't quite figure out where these numbers are coming from, so that I can try and fix this massive economy upset... Hopefully before players find out heh (a staff member reported this to me)
As a side note, that isn't the highest multiplier that was achieved either. The highest was x5477.2 on a Skeleton.

Specifically, I'm unable to determine where that multiplier comes from. Based on the wording it looks like it's...
x2872.3
multiplied by: Difficulty *(3.2 lets say)*
multiplied by: ConquestiaMob

However, the confusion comes in from dividing the awarded amount of 110-some thousand by that 2872.3, which leaves only 4.102077etc. Take the 3.2 from that and you're left with .90. If we consider 3.3 for difficulty, that'll leave 1.0 for Conquestia.

*NOW*... if that's the case, where'd the 20 to 40 $ for killing the Golem go? 😕

**EDIT:** Alright I just came back across the config entry about ConquestiaMobs and multipliers per level, along with the World Difficulty not being directly calculated, but equating to a defined multiplier. Taking that into account, beings it was a level 150 CQM Iron Golem, that means the multiplier would've been 1507.977. 
So far I'm hanging with the math!
Now we factor in the Hard Difficulty multi of 2 and... we get a multiplier of 3015.954?? Well that ain't right...
To get the oddball 2872.3 that is came to, from the 1507.977 that the CQM Level math results in, would mean we would a World Multi of 1.9.

That's not how it's configured... So I'm still a bit confused where these numbers are coming from :(

**Comment by Rocologo** [comment]
Use "/mh debug"  and then kill a mob, and then check the server log and you will see all the multiplicators

**Comment by Rocologo** [comment]
And show me the numbers, if you dont understand how to read the output

**Comment by Rocologo** [comment]
Do you need help with this one or can the ticket be closed ?
