### ISSUE TITLE
Goldbars are not being picked up if inventory is full

### ISSUE THREAD

**Issue by MrKiller01** [Rocologo/MobHunting#317]
Hiya! hey, i just used your latest plugin, and i thought that when the inventory is full, walking over dropped money would still be picked up... it does not...
So i had to make an issue, you told me, so i did...
I hope this fresh introduced bug will be gone for good....

Thanks man for the awesome work you bring us to have fun !!!! 
Keep up the good job....

**Comment by Rocologo** [comment]
Fixed in V5.1.6

I can't remember I have tested Items (Gold Ingot) before, only BagOfGold, and it makes a big difference :-)

**Comment by MrKiller01** [comment]
Thanks for the hard work again....
