### ISSUE TITLE
[bug] Heads turning into steve heads and not turning back

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#318]
I have only had the plugin live a small amount of time, but I have had a few reports from players that heads are getting picked up/dropped and are turning into steve heads and not turning back.
one of my Staff members & players created a video to show it happening (So you can try and figure out why)
https://www.youtube.com/watch?v=mGCKXPcnJxg&feature=youtu.be

He said that only some heads are affected, mostly those which we did not have previously, All fish heads, Wither Skeleton Skulls (A big one, as these are expensive for players).

We are asking around for players to see if any more are affected.

**Comment by Rocologo** [comment]
hmm... it seems to be something with the display name

Pufferfish works for me...

But the Raw fish did not work like on the video. It became a head... the i tried to rename the head using "/mh head rename rawfish" placed the head and broke it, and then the skin came back. 

I think I know what to do, but it will take me some time to fix this... so it dont depend on the displayname, but i hidden UUID instead.

**Comment by Rocologo** [comment]
thanks for the video, it actually helped me alot !!!!

**Comment by Rocologo** [comment]
Please let me know if this is fixed on your server?
