### ISSUE TITLE
NoSuchFieldError: metaTag on 1.8.8

### ISSUE THREAD

**Issue by hsombini** [Rocologo/MobHunting#319]
Hello,

After updating to MobHunting v5.1.6, I'm getting this stacktrace

https://hastebin.com/zohabugodi.vbs

**Comment by Rocologo** [comment]
Which version of StackMob are you ising?

**Comment by hsombini** [comment]
I belive it's the latest one, StackMob-2.1.1-SNAPSHOT

**Comment by hsombini** [comment]
I just relalized that another plugin that uses StackMob API has the same issue, maybe a problem with StackMob then?

**Comment by Rocologo** [comment]
I have reported the problem: https://www.spigotmc.org/threads/stackmob.184178/page-44#post-2725326

**Comment by Rocologo** [comment]
PS. You can disable the integration to StackMob in my config.yml until the bug is fixed

**Comment by hsombini** [comment]
Yeah thanks, I'll have to use an older version of StackMob, others plugins that can't disable the integration with StackMob will not work otherwise.

Thanks for the attention

**Comment by Nathat23** [comment]
#320 Should fix this.

**Comment by Rocologo** [comment]
It did not!!!

But I have fixed the code and made a snapshot which works with StackMob 2.0.9 and newer

Please test build 492
https://fractal.lindegaard.one:8181/job/MobHunting/
