### ISSUE TITLE
Spam in chat with killstreak?

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#32]
[http://i86.servimg.com/u/f86/19/36/36/04/2016-010.png](url)
this is a screen from one of my players :P
mobhunting.killstreak.activated=x${multiplier} Activé
mobhunting.killstreak.level.1=Bien!
mobhunting.killstreak.level.2=Super!
mobhunting.killstreak.lost=Killstreak perdu

**Comment by Rocologo** [comment]
I cant see the picture?

**Comment by FlashLight34** [comment]
![image](https://cloud.githubusercontent.com/assets/9997676/15276672/059f157c-1abd-11e6-80b3-1c14285c1c17.png)

**Comment by Rocologo** [comment]
Very strange, how did that happen?

**Comment by FlashLight34** [comment]
my player said only walking and that appear:(

**Comment by Rocologo** [comment]
How does your killstreak section look like in your config.yml? Have you tried to disable killstreak or something?

**Comment by FlashLight34** [comment]
killstreak:
  level1: 5
  level1-multiplier: 1.5
  level2: 10
  level2-multiplier: 2.0
  level3: 20
  level3-multiplier: 3.0
  level4: 40
  level4-multiplier: 4.0


assists:

  # Enabling assist allows the second last player to attack a mob to get some money from it
  enable: false

  # This should be a value that is multiplied against the mobs base kill value.
  # This is used to determine how much money an assister gets.
  multiplier: 0.25

  # Should killstreak be applied to assists
  allow-killstreak: false

  # Time in seconds after attacking a mob that can be counted as an assist
  timeout: 4

**Comment by Rocologo** [comment]
Hmm completely normal. I dont have a clue about what could provoke this error so I cant fix it for now.

**Comment by FlashLight34** [comment]
maybe with the database? i dont know how you program this, but the database i can reset this? What is saved in this database? because with 3.0.4 my player see that again in the chat :(

**Comment by Rocologo** [comment]
Killstreak doesnot use the database and the basic code is actually made by the previous developer. Resetting the database will not solve this bug.

If the player didnt kill any mobs i must be a kind of error where another player make a killstreak and maybe this is broadcasted to everyone. I will try to check that.

**Comment by FlashLight34** [comment]
oh thx for your effort :)

**Comment by Rocologo** [comment]
I have looked at the code again. And I now see that it has something to do with Grinding Mob and Dampened Kill. The only way this can happen is when there have been +14 damped kills. The the question is who killed 14 mobs??? 


https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/MobHunting.java#L962

**Comment by Rocologo** [comment]
Is it in the same area this happens all the time?

**Comment by krustymk** [comment]
Like in a mob farm.. make /mh mute kill these notifications as well?

**Comment by Rocologo** [comment]
I think this is fixed in V3.3.6
