### ISSUE TITLE
[Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v5.1.6

### ISSUE THREAD

**Issue by comonier** [Rocologo/MobHunting#322]
https://hastebin.com/roqiquneso.vbs

server crash

**Comment by comonier** [comment]
the mob-spawner slimes are no longer spliting, by dying regardless of the size they were fading

Why do not you create a page in github for us to open tickets or a server in the discord for us to ask for help? Do we pay for the plugin and do not have support?

**Comment by Rocologo** [comment]
This is because MobStacker was Updated in a bad which broke the compatibility. You will have to disable the integration to MobStacker in my configuration.yml until I release next release. Hopefully in a few days. Or you can downgrade MobStacker until I make next release

**Comment by Rocologo** [comment]
And NO you have no paid anything to use MobHunting not to me at least.... Please correct me if I'm wrong?

**Comment by Rocologo** [comment]
Fixed in V5.1.8
