### ISSUE TITLE
No rewards and errors

### ISSUE THREAD

**Issue by Someone-NEW** [Rocologo/MobHunting#323]
HEy i have a problem check my config and i see option for StackMobs but by me not working and give me spam errors in console and none rewards. Can you please fix this bug?
I have constantly spam with this on my console when i kill any mobs and MH stop working https://pastebin.com/rFWamLUH
Please checkand add more support for StackMob https://www.spigotmc.org/resources/stackmob.29999/
And this is from my config:
stackedmobs:

  # Disable integration with MobStacker.
  # https://www.spigotmc.org/resources/mobstacker.15596/
  disable-integration-mobstacker: false

  # Disable integration with StackMob.
  # https://www.spigotmc.org/resources/stackmob.29999/
  disable-integration-stackmob: false

  # Set to true if you want stacked mobs to pay a reward.
  get-reward-from-stacked-mobs: true

**Comment by Rocologo** [comment]
The dev from StackMob made an ugly update which broke comparability with MobHunting. You will either have to downgrade StackMob or disable integration until I make next release where it is solved. 

Or you can complain to the StackMob dev

**Comment by Someone-NEW** [comment]
Ok am already send this problem to StackMob dev but seems no response, thank you for look around of this problem and trying fix it tnx

**Comment by Someone-NEW** [comment]
Hey i see the link on his page and i try http://jenkins.lindegaard.one:8180/job/MobHunting/ this 5.1.8 and i test it and now work again tnx
I suggest you to add this link on your Site of MobHunting when not already there tnx

**Comment by Rocologo** [comment]
Well 5.1.8 is under strong development at The moment so there is a reason for why I did not ask you to use this.

**Comment by Someone-NEW** [comment]
Ok my server is only in development stage and for hobby so currently i dont have big player base and i can repair when something goes wrong in that cases i contact all developers for bugs and when devs will fixed all bugs than i can work on my server and continue with other stuff i think for now not see any bad things with usindg this one i hope you will release it soon tnx

**Comment by Rocologo** [comment]
Ok worst case you will have to delete the mobhunting database and let it recreate. Which will basically only delete the statistics, as long as you are okay with this you can easily use the 5.1.8 snapshots

**Comment by Someone-NEW** [comment]
Ok thanks i will wait for release come out but for now i use this tnx

**Comment by Rocologo** [comment]
Fixed in V5.1.8
