### ISSUE TITLE
MyPet Pickup skill issue

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#324]
If your MyPet picks up money, it will be a golden nugget and the money will not be transferred to your balance. Causing the money drops to be useless if you use a MyPet.

**Comment by Rocologo** [comment]
How do I make the Mypet to pickup items?

**Comment by Sikatsu** [comment]
./petpickup 

It's a pet skill

**Comment by Sikatsu** [comment]
Make sure to use like /petadmin exp 1000

So that he becomes the max level and then it should work I believe. You need to unlock the skill based on your level.

**Comment by Rocologo** [comment]
I got it I had to do 

/petadmin skilltree rocologo Farm

Now I can make the pet pickup items. I have never used that before :-) I have to do some testing now, and check what is possible. I will need some MyPetEvents to catch to change the behaior...

**Comment by Sikatsu** [comment]
Perfect :)

**Comment by Rocologo** [comment]
Well, not perfect, because I have found the events I need to solve this issue...

**Comment by Rocologo** [comment]
I have news :-)

The MyPet Developer @xXKeyleXx has made a new MyPetPickupItemEvent for me which I can use to fulfill this request. 

Next release V5.3.8 will integrate better to MyPet, and pickup BagOfGold and add the money directly to your balance.

**Comment by Sikatsu** [comment]
I assume this also works without the use of BagOfGold? For example currently the money directly goes in your balance. Also when the pet kills the mob?

**Comment by Rocologo** [comment]
Yes, It should work with
1) DropMoneyOnGroun=false
2) DropMoneyOnGrounp=true, DropMoneyUseAsCurrency=false
3) DropMoneyOnGround=true, DropmoneyUseAsCurrency=true
4) DropMoneyOnGround=true, DropmoneyUseAsCurrency=true + BagOfGOld plugin

I have mostly tested 2) because think this was what you wanted? and 4) because this is what I use myself. But I have also tried 1)+3) :-)
