### ISSUE TITLE
DataStoreException: org.sqlite.SQLiteException

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#326]
https://pastebin.com/1bzBQTkm

**Comment by Rocologo** [comment]
It looks like you are not on V5.1.8? Please check "/mh version"

**Comment by Rocologo** [comment]
No response....

**Comment by FrozenBeard** [comment]
Paste expired I cant remember what it was, I undated, Ill keep an eye on the configs.
