### ISSUE TITLE
mh bounty allows taking heads from gui

### ISSUE THREAD

**Issue by FatherWh0** [Rocologo/MobHunting#327]
You can type /mh bounty and remove a head, placing it in your inventory giving yourself a free head of another player. Pls see gif:
https://gyazo.com/9f6e031fe394eea46259d0b5f618e1bd
MH 5.1.8
paper 1.12.2 build 1248

**Comment by Rocologo** [comment]
I can't replicate this problem, and I have no idea why this happens on some servers only...

**Comment by FatherWh0** [comment]
Perhaps some servers have a plugin that others don't. For instance my server has slimefun which uses heads and a gui. I also have [Decoheads ](https://www.spigotmc.org/resources/decoheads.24655/)that allows pulling heads from a gui.

**Comment by Rocologo** [comment]
Im sorry I dont have the time to test all kind of plugins. If you find the conflicting plugin, I will see if I can replicate the error with the one. 

Also please update your spigot server... just in case....

**Comment by Rocologo** [comment]
The problem could easily be in Decoheads... if this is the case I cant fix the problem.... This will be the dev of Decoheads

**Comment by Rocologo** [comment]
Hi again. I looked at the gif again and noticed that the head has extra lores, where does these come from? This might be the problem.

**Comment by Rocologo** [comment]
Or related to the problem

**Comment by FatherWh0** [comment]
All of the data the head has appears added by the mobhunting plugin.
https://prnt.sc/hxblxx

**Comment by Rocologo** [comment]
Is this a problem i V 5.4.6 too?

**Comment by FatherWh0** [comment]
Yes, just tested with 5.4.6 and I can still steal player heads.

**Comment by Rocologo** [comment]
Oh no... i cant do it on my own servers :-( 

Please describe exactly which key / mouse button you use and how you do it.

**Comment by FatherWh0** [comment]
I simply type /mh bounty and when the gui opens I left-click the head, which picks it up, then I place it in my inventory. 
I've tried, on my test server, stripping the server of all but the base plugins but still the problem persists. 
One thought I have is if there was an alternative command to list bounties in text instead of using the gui that would circumvent this issue.

**Comment by Rocologo** [comment]
You can disable the gui in config.yml bur that doesnt really solve the problem. Is your server public, can i try myself?

**Comment by Rocologo** [comment]
Could you please test snatshot 600 or newer?  Im not sure of the status of this ticket?
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by FatherWh0** [comment]
Sry for the delay. I've been really busy. That link above isn't working atm.

**Comment by Rocologo** [comment]
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by bennyman123abc** [comment]
I know this is old, but could you give a complete list of plugins? There may simply be a cancellation override in another plugin that prevents the cancellation of an inventory interaction event for some items. I'd be happy to help look into this!

**Comment by Rocologo** [comment]
Ahh, yes if some one could find the root cause of this problem it would be a big help.

**Comment by bennyman123abc** [comment]
I can't really look further into this until I figure out which plugin is causing the issue because it doesn't seem like it's caused by this plugin, though a fix may be able to be implemented here.

**Comment by Rocologo** [comment]
I have very long time on trying to fix this, but I have not been able to fix it yet (or reproduce it) Im not able to take anything out of my inventory, which points in the direction that you are right @bennyman123abc I too think it is a plugin conflict. 

Its only a few users who has reported this problem.

**Comment by bennyman123abc** [comment]
@FatherWh0, could you please give a list of plugins you have installed on your affected server? If you can do this, it would allow Rocologo or I to attempt to fix the issue and assist others who are experiencing the issue too.

**Comment by MCTyler** [comment]
@Rocologo I have had Server Lag which has allowed me to take items from a Gui like that but they usually disappear and are not "real" items.

**Comment by FatherWh0** [comment]
Sorry for the delay. Life happens.
https://pastebin.com/jyS3eGyA

**Comment by FatherWh0** [comment]
Take two *clack*
https://pastebin.com/n9iYB50F

**Comment by bennyman123abc** [comment]
Oh boy... I'm going to have fun replicating this environment and nit-picking through the plugins...

**Comment by bennyman123abc** [comment]
Anyway, thanks. I will look into the issue you're having. Or if @Rocologo wants to replicate this environment and nit-pick himself, have at it!

**Comment by Rocologo** [comment]
Im sorry, I dont have the time to do it

**Comment by bennyman123abc** [comment]
It was a joke, I'm working on it now.

**Comment by Rocologo** [comment]
Hi Bennyman have you found out when it happens?

**Comment by bennyman123abc** [comment]
@FatherWh0 Could you repost your environment? The paste has expired and I seem to have lost the plugins for the environment on a drive that just failed.

**Comment by FatherWh0** [comment]
https://pastebin.com/2qrCnV26

**Comment by Rocologo** [comment]
Have you tested this on MC 1.13.1?

**Comment by FatherWh0** [comment]
No, I haven't updated to 1.13.1 yet.

**Comment by Rocologo** [comment]
I have given up on this
