### ISSUE TITLE
Issue with Player Heads

### ISSUE THREAD

**Issue by bjunited** [Rocologo/MobHunting#328]
Hello,

When my players are killing other players it doesn't give them a player head with a Skin, instead it just gives them a player head called the players name. 

Thank You
- Ben

**Comment by bjunited** [comment]
Also, my hologram leaderboards don't seem to update at all

**Comment by Rocologo** [comment]
Have you checked the server console for errors?

Also check the database.

**Comment by Rocologo** [comment]
I think I found the bug. Please test build 516 or newer

https://fractal.lindegaard.one:8181/job/MobHunting/

Please confirm :-)
