### ISSUE TITLE
CPU 100%+ with MH 3.0.0 and 3.0.1PRE1

### ISSUE THREAD

**Issue by jshacar** [Rocologo/MobHunting#33]
Updating from 2.9.9 to 3.0.0 caused my spigot java process to be 100%+ and will not go down. I have gone back and forth from 2.9.9 to 3.0.0 to confirm. Here is my management page with 2.9.9 - the cpu goes gown after everything loads:
![amp with 2 9 9](https://cloud.githubusercontent.com/assets/8880787/15288555/c202f28e-1b39-11e6-8053-bde0d13f150b.PNG)
Then when I update to 3.0.0 it looks like this:
![amp with 3 0 0](https://cloud.githubusercontent.com/assets/8880787/15288595/ed960ff8-1b39-11e6-81cb-617a8449271a.PNG)
and here is the result of the top command in ubuntu:
![ubuntu top](https://cloud.githubusercontent.com/assets/8880787/15288606/faeaf290-1b39-11e6-8af3-04e86082d0de.PNG)

I get the same results with 3.0.1PRE1.

**Comment by Rocologo** [comment]
I see the same problem on my test-server. This is a HIGH priority bug!

**Comment by Rocologo** [comment]
I think I solved the problem.

Check this version 
[https://www.dropbox.com/s/3qqj4n78mssda7z/MobHunting3.0.1PRE2.jar?dl=0](url)

**Comment by Rocologo** [comment]
Can I close this issue now?

**Comment by jshacar** [comment]
Dang it, I'm really sorry I've been busy at work. I will test first thing when I get home tonight.

**Comment by Rocologo** [comment]
No problem, I justed wanted to empty my issue list.


Sent from Samsung tablet

-------- Original message --------

**Comment by jshacar** [comment]
Yup, all fixed. Thank you!
