### ISSUE TITLE
Failure to give heads

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#331]
I have the latest version of plugin 5.2.2 and the default configuration. When using the command / mh head give "user" gives me $ 5 (I see the head fly, disappears and gives me $ 5).
Another mistake, happens when breaking a head for example of spider randomly gives me another.

Greetings.

**Comment by Rocologo** [comment]
Hmm... I think this happens when you have choosen NOT to use the bag as a currency. Could you please show me your DropMoneyOnGround section from your config.yml? So I am able to replicate this bug.

**Comment by Mundo-Minecraft** [comment]
That line is so drop-money-on-ground: false the weird thing is that when you break a head it gives you another randomly, besides not being able to use the give.

I changed that line to true but the errors continue

Greetings.

**Comment by Rocologo** [comment]
I have found the bug. You don't need to change drop-money-on-ground or   drop-money-use-item-as-currency, unless you want a different behavior :-) 

Please test Build 513 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

And if you use BagOfGold you should also use Build 27
https://fractal.lindegaard.one:8181/job/BagOfGold/

Please comfirm :-)

**Comment by Mundo-Minecraft** [comment]
The problem that was breaking the heads is solved, break a zombie and gives you a zombie.
When using the command head give me a head called "username ($ 5)" I put it on the ground I break it and then it is only called "username".

Greetings and thanks.

**Comment by Rocologo** [comment]
I think I found the bug. Please test build 516 or newer

https://fractal.lindegaard.one:8181/job/MobHunting/

Please confirm :-)

**Comment by Mundo-Minecraft** [comment]
It continues to happen as "user ($ 5) plus the skin does not come out unless the user is online." And the error that caused the ronper a head gave you another different to happen again.
One user broke a user's head and gave it a magma cube.

Thank you.

**Comment by Mundo-Minecraft** [comment]
Extensive information, now using the command / mh head give the head is called "user (5$)" and even if you put it on the ground and break it is still called the same (before breaking it changed the name to "user" without (5$)).
The skin of the head does not leave with the user online.

Apart the heads that are placed by the map to break them gives you a different one in a random way.

Greetings and thanks.

**Comment by Rocologo** [comment]
Please help me testing v5.2.4

**Comment by Mundo-Minecraft** [comment]
I have installed the latest version 5.2.4 and it is confusing. Give a head of an online user and leave without the skin, but if I drag it to the belt it gives me another user online with skin.

https://www.youtube.com/watch?v=6oJKYN46ruA

Greetings.

**Comment by Rocologo** [comment]
Hmm... the problem is that Minecraft/Mojang limit the number of requests for skins. This is what troubles me....

Maybe I need to make my own skin cache....

**Comment by Mundo-Minecraft** [comment]
I have also seen that the error in breaking heads still happens. A user broke a parrot's head and a wolf came out. And another broke another head and came out a bag of gold.

Thx.

**Comment by ysl3000** [comment]
A local cache or on a remote server via rest API.

**Comment by Rocologo** [comment]
@ysl3000  I didn't get that? 

But I could build a local skin cache for this and store the texture and the signature. This way it will be easy to make the playerheads, the same way I make the mobheads. 

I have some new changes. But I still think I will make a cache, I just need some time to make this.

Please help me testing:
Build 521 or newer: https://fractal.lindegaard.one:8181/job/MobHunting/
Build 32 or newer: https://fractal.lindegaard.one:8181/job/BagOfGold/

**Comment by Mundo-Minecraft** [comment]
I think I do not notice difference, I have done / mh head give lxuser mar9 and it gives me the head called "mar9 (5 $)" without skin. I place it, I take it and it goes by the name "mar9" but it still has no skin.

The BagOfGold plugin I do not have it installed. Why do I have the drop-money-on-ground option: false.

Greetings.

**Comment by Rocologo** [comment]
Strange... I have to work more on this. I think I will find some time to create a cache - this will solve the problem.

You should NOT set "drop-money-on-ground: false" unless you dont want want the money to go directly into your balance. If you want the money as a BagOfGold  or an Item you must set drop-money-on-ground : true

**Comment by Rocologo** [comment]
I have have some heads in my inventory for some days... without doing anything (and without changing the code) the skin suddenly was added ??? 

It tells me that this is a problem related to that Mojang limites how often I can download skins :-(

**Comment by Rocologo** [comment]
I have implemented a MobHunting Skin Cache. Please who have joined the server after installation of the two versions below, wil have the SKin stored in the MobHunting Skin Cache forever. If you try to give a haed of a player who have never joined MobHunting will try to get the Skin from the Mojang Player Database. The last part fails often because of Limitations at Microsoft/Mojang.

Please test Build 555
https://fractal.lindegaard.one:8181/job/MobHunting/

And build 49 if you use BagOfGold
https://fractal.lindegaard.one:8181/job/BagOfGold/

**Comment by Rocologo** [comment]
case closed... i hope
