### ISSUE TITLE
With full inventory you can't pickup money

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#332]
Players with a full inventory don't seem to be able to pickup money.
When I picked up the money, I received a golden_nugget in my inventory.

**Comment by Rocologo** [comment]
I need more details...

1) Do you use the BagOfGold plugin? 

2) Please paste the "DropMoneyOnGroud" section from your config.yml, so I can check your settings, and be able to reproduce your setup.
I need at least to see: 
  drop-money-on-ground-itemtype: SKULL
  drop-money-use-item-as-currency: true

**Comment by Sikatsu** [comment]
1. No I don't use the BagOfGold plugin.

2. https://pastebin.com/3SLnifpf

**Comment by Sikatsu** [comment]
I'm running on 1.12.2, latest spigot version (just freshly compiled) and updated to MobHunting 5.2.4. 
Using the latest protocollib aswell.

**Comment by Sikatsu** [comment]
Seems to happen after I updated btw.

**Comment by Sikatsu** [comment]
Plugin currently doesn't function at all in my case due to this.

**Comment by Sikatsu** [comment]
I disabled money drop on ground and it's solved. (money goes directly into their balance though)

**Comment by Rocologo** [comment]
Thats now solving the problem. Its a temporary. I will release V5.2.5 now and this should fix the reported problem.

Its very hard for me to test all combinations. But I hope I got it right now.

**Comment by WindUnwaken** [comment]
https://youtu.be/eAHMroccjkw

When you try to pick up money, it raise up the value with strangely , and don't pick up it!

**Comment by Rocologo** [comment]
Oh no... its so hard to test all combinations :-( 

I will have to look at this to morrow. Im going to bed now.

**Comment by Rocologo** [comment]
Ahhh. I see you are in Creative mode... I will have checked mostly in survival mode.... now I know what to look for.

**Comment by Rocologo** [comment]
Do you use the BagOfGold plugin?

**Comment by WindUnwaken** [comment]
I don't have BagofGold.
https://youtu.be/eAHMroccjkw?t=1m10s
You don't need to check survival mode, I also record it. OAO

**Comment by WindUnwaken** [comment]
I forgot to record survival mode first, good night.

**Comment by Rocologo** [comment]
I think this is fixed in V5.2.8

Let me know if I can close this ticket now.
