### ISSUE TITLE
issue with money pickup

### ISSUE THREAD

**Issue by mmuziek** [Rocologo/MobHunting#335]
The money we pickup does not get removed from ground this allows the player to pickup the money endlessly making endlessly money from a single zombie for example.

my spigot version 1.12.2
MH version : 5.2.6

To replicate
Kill zombie
Try to pickup money

my config : 
https://pastebin.com/buxnSJCt

**Comment by Rocologo** [comment]
Fixed in V5.2.8 which will be released in 10 minuets

**Comment by Rocologo** [comment]
Released.

**Comment by Rocologo** [comment]
Let me know if I can close this ticket now.

**Comment by mmuziek** [comment]
its solved thanks!
