### ISSUE TITLE
Mob Heads  no longer wearable

### ISSUE THREAD

**Issue by datsme** [Rocologo/MobHunting#337]
CraftBukkit version git-Spigot-b66ad9e-b5a10a9 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
MH: 5.2.6

I am not really sure when this changed but we just noticed that if you try to wear one of the mob heads it  gives an error and deletes the head.

**Comment by Rocologo** [comment]
This is fixed in V5.3.0
