### ISSUE TITLE
1.9 CraftBukkit Constant error keeps MobHunting 3 from loading.

### ISSUE THREAD

**Issue by tacogerbil** [Rocologo/MobHunting#34]
Ignore.. Trying Bukkit  Sorry...

**Comment by Rocologo** [comment]
Personally I use SpigotMC but I also support CraftBukkit,so I will test CraftBukkit 1.7.9-1.9.4 and make sure it works.

**Comment by tacogerbil** [comment]
UGH... I went from using CraftBukkit to Forge to Cauldron back to Forge now
back to CraftBukkit... But getting confused as to the whole
CraftBukkit/Spigot.. Not to mention where I download the prebuilt files
from also offer Bukkit jar files.  I'll see if Spigot works without causing
further crashes from other plugins :)

THANK YOU for the response as well :)
Have an awesome day! ;)

**Comment by Rocologo** [comment]
I just made a totally fresh CraftBukkit 1.9 and SpigotMC 1.9 with buildtools. I Agree when I run CraftBukkit+MobHunting it crashes (java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent)

If I use SpigotMC 1.9 + MobHunting 3.0.1 everything works.

I will look at the problem now, but you can use SpigotMC instead.

**Comment by tacogerbil** [comment]
I am using Spigot... Only drawback so far is it Neuters Worldedit a bit ..
Apparently not all functions work with Spigot.  All else seems to work with
no errors..

Thank you again :)

**Comment by Rocologo** [comment]
I use WorldEdit 6.1 without problems. V6.1.1 fails on my Server.

**Comment by Rocologo** [comment]
For your information.

MobHunting + CraftBukkit works again. I found the error. I have testet CraftBukkit 1.8.8, 1.9 and 1.9.4 but the other versions should works as well...

**Comment by tacogerbil** [comment]
AWESOME!!!!!!!!!  THANK YOU SO MUCH!! ;)
Have a wonderful weekend!!
