### ISSUE TITLE
(Bug) Change money

### ISSUE THREAD

**Issue by Fahles** [Rocologo/MobHunting#342]
The money I can share with 2 times right click. But if I take a moneybag and put it left-click on another, 2 moneybag remain and the other has the added value of the split moneybag. So I can infinitely multiply the money.

**Comment by Rocologo** [comment]
I need more information., to solve this issue

Which server and which version?

Survival or creative?

With or without the BagOfGold plugin?

**Comment by Fahles** [comment]
Spigot 1.11
Survival (no OP)
MobHunter V5.3.7

**Comment by Rocologo** [comment]
Okay, i will test om mc 1.11 then... i cant promise i have time tonight ...

**Comment by Rocologo** [comment]
Okay, this bug is confirmed and it does only exist on Minecraft 1.11, but not on MC1.12... 

I will fix this but why have you not upgraded to mc 1.12? :-)

**Comment by Rocologo** [comment]
The bug is fixed in next release v5.3.9

**Comment by Fahles** [comment]
thx ;)
