### ISSUE TITLE
[bug] Players cant drop heads, cant take them off thier head, permantly stuck.

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#343]
This is quite a major bug, players cant drop a head out of their inventory, if they shift+click it onto their head from a hotbar, it will go on their head, but they will not be able to remove it, they cant drag it off, they cant shift+click it off. you just cant drag the head anywhere.
 
Here is a gif showing it, I had to use a third party inventory plugin to remove it.
https://imgur.com/a/kFUhn

Version 5.3.7
Paper: 1.12.2 1298 (latest)

**Comment by Rocologo** [comment]
This bug is fixed in next release V5.3.9
