### ISSUE TITLE
[Bug] Error log & lag every time a player joins the server

### ISSUE THREAD

**Issue by Armek15** [Rocologo/MobHunting#346]
since 2 or 4 updates ago i started getting error logs from MobHunting every time a player joined my server.
It only happens when players join.

LOG:
`
18.01 20:06:02 [Server] INFO [MobHunting] Your server is running version v1_12_R1
18.01 20:06:02 [Server] WARN [MobHunting] Task #193093 for MobHunting v5.4.2 generated an exception
18.01 20:06:02 [Server] INFO java.util.NoSuchElementException: null
18.01 20:06:02 [Server] INFO at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at one.lindegaard.MobHunting.rewards.skins.Skins_1_12_R1.getSkin(Skins_1_12_R1.java:20) ~[MobHunting-5.4.2.jar:?]
18.01 20:06:02 [Server] INFO at one.lindegaard.MobHunting.rewards.CustomItems.getPlayerHead(CustomItems.java:103) ~[MobHunting-5.4.2.jar:?]
18.01 20:06:02 [Server] INFO at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:129) ~[MobHunting-5.4.2.jar:?]
18.01 20:06:02 [Server] INFO at one.lindegaard.MobHunting.PlayerSettingsManager$1.onCompleted(PlayerSettingsManager.java:113) ~[MobHunting-5.4.2.jar:?]
18.01 20:06:02 [Server] INFO at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:340) ~[MobHunting-5.4.2.jar:?]
18.01 20:06:02 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [custom.jar:git-Spigot-9b8bba4-bdcc7c7]
18.01 20:06:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by Rocologo** [comment]
I think this is solved in build 559
https://fractal.lindegaard.one:8181/job/MobHunting/

but I need some one to confirm. I have not seen this bug on my own server.

Could you please help with the testing?

**Comment by Rocologo** [comment]
Thank you. I will make a new release tonight when Im back from work.

**Comment by Rocologo** [comment]
Fixed in V5.4.3
