### ISSUE TITLE
Spawner (grinder) mobs not dropping any items even after enabling natural drops in the config

### ISSUE THREAD

**Issue by blazex224** [Rocologo/MobHunting#347]
Hello,
I would like to enable natural mob drops on my server alongside the rewards of MobHunting, because I want players to be able to create grinders. Even after enabling the proper settings in the config, it still doesn't seem to work. This may be a result of me missing something, but I appreciate the help.

https://pastebin.com/sCeCgybM

Thanks for the help and thanks for the plugin!

**Comment by Rocologo** [comment]
Have you tried to disable grinding detection per world?

  disable-grinding-detection-in-worlds:
  - worldname

**Comment by Rocologo** [comment]
Also set
detect-other-farms: true

to
detect-other-farms: false

finally you should enable debug using "/mh debug" and then kill some mobs and check the console, and then you will see if MobHunting removes the rewards...

**Comment by Rocologo** [comment]
Did it work?
