### ISSUE TITLE
Losing killstreak 

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#350]
Hey!

My players keep losing their killstreak when completing a achievement.
Example: "Hunt 100 spiders"

They also lose killstreak when changing world. I don't want that, I want to only lose killstreak when they take damage from a mob/ other player.

**Comment by Rocologo** [comment]
I cant see that you players should loose killstreak when they get an achievement??? 

About the second one, yes they loose killstreak if they flee to another world.... I think this behavior is the correct one. (No cheating - jumping to other worlds)

**Comment by Nesseley** [comment]
We have multiple survival worlds with the same inventory. Atleast let us toggle if we want to loose the killstreak on world-change or not :/
