### ISSUE TITLE
Flame effect.

### ISSUE THREAD

**Issue by En0tS** [Rocologo/MobHunting#352]
https://ibb.co/ftUGd7

https://www.spigotmc.org/threads/mobhunting.46937/page-156#post-2893251

**Comment by Rocologo** [comment]
I have found the problem. When I first saw the picture it was on my phone, and I was not able to see the two spiders, I could only see the flames. So I though it was a grinding marker. After looking at the picture once more, trying to fix the bug, I realized that it looks like a BonusMob

So I checked your config.yml and found this

# This is the chance (% chance 0-100) that a bonus mob will spawn.
bonus-mob-chance: 100.0

This means that everytime you kill a mob you spawn a BonusMob (with flames). You should not set it to 100, set it to 5

The 5 out of 100 will be a BonusMob with flames.
 
This is not a bug :-) I close the ticket
