### ISSUE TITLE
Duping of money bags

### ISSUE THREAD

**Issue by Mayzone** [Rocologo/MobHunting#355]
The player doing this is in survival and has almost no permissions.

I open a normal double chest and i hold shift pressing bag of gold in my inventory slot 1-9. This creates another bag in inventory slot while the one i put in chest is still there, i then keep doing this 5times or so and stack the money in the chest and when done, ill drag the money bag that is in the chest and hold it over outside the chest gui and press esc and now that stacked money is dropped outside the chest.

Usually in the beginning of trying this the money will disappear either in inventory or chest, or just totally delete all the money but if i keep trying, it suddenly stays in chest.

mobhunter version: 5.4.6
bagofgold: 1.0.6
spigot version 1.12.2

**Comment by Rocologo** [comment]
I cant reproduce this??? 

When I shift click on the item in slot 1-9 , it is immediately removed from the slot and place in the double chest.

**Comment by Rocologo** [comment]
Please test on V5.5.0, I have made some changes which might affect this one. But I cant reproduce the problem so I cant test if it is fixed either

**Comment by Rocologo** [comment]
Can you still make duplicates?  When using V 5.5.3?

**Comment by Rocologo** [comment]
Please check V5.5.6 ?

**Comment by Rocologo** [comment]
No response. Ticket closed
