### ISSUE TITLE
Your server is running version v1_12_R1 on every login

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#356]
On every player login it shows the message from the title.
Also when I perform /mh reload it says the same:

26.02 12:33:30 [Server] INFO Sikatsu issued server command: /mh reload
26.02 12:33:30 [Server] INFO Your server is running version v1_12_R1
26.02 12:33:30 [Server] INFO Your server is running version v1_12_R1

Perhaps some leftover debug?

**Comment by Rocologo** [comment]
Correct! It should have been a debug information to myself. I have removed the information in next release.

**Comment by Sikatsu** [comment]
Thanks!

**Comment by Rocologo** [comment]
V5.5.0 released
