### ISSUE TITLE
Drophead:true on conversion 5.4.6 > 5.4.7

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#358]
Spigot 1.12.2
MH 5.4.7-b577

Auto-conversion yields
- mobs.*.head.drophead:true

for all mobs. I'm pretty sure that I configured for no head drops ever. What is the conversion rule?

5.4.6 config.yml
[http://whitedog.straight8.com/drops/config.yml](http://whitedog.straight8.com/drops/config.yml)

**Comment by Rocologo** [comment]
There is no auto conversion for the head. Because the field did not exist in the old config.

**Comment by Rocologo** [comment]
There is no auto conversion for the head. Because the field did not exist in the old config.

**Comment by Rocologo** [comment]
In the old config the head was made using "mobhunt head give....." I cant convert from this?

**Comment by SlimeDog** [comment]
In 5.4.6 config, what does
- mobs.*-head-prize: '0'

represent?

**Comment by Rocologo** [comment]
Only the value when the head is dropped. I cant use this as a test.

But I could check the run_cmd for "mobhunt head give" and if found I set 
mobs.*.head.drophead:true
if not
mobs.*.head.drophead:false

**Comment by SlimeDog** [comment]
That sounds right.

**Comment by Rocologo** [comment]
Build 578 is ready in 2 min

https://fractal.lindegaard.one:8181/job/MobHunting/

:-)

**Comment by Rocologo** [comment]
Thank you for the help with the testing. I REALLY appreciate this!!! Its impossible for me to test all compbinations.

**Comment by Rocologo** [comment]
@SlimeDog do you think I can make a release now?

**Comment by Rocologo** [comment]
V5.5.0 released
