### ISSUE TITLE
Heads Collection lore support

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#363]
Is there any option to change the lore of the heads people receive from killing mobs?
So people know from which plugin it is.

**Comment by Sikatsu** [comment]
It also seems wither heads from MobHunting change with the resourcepack, are they identical to normal wither heads and can they be used to create a wither?

**Comment by Rocologo** [comment]
Yes, WitherSkeleton heads are not fake, they are build in like the Ender Dragon, Zombie, skeleton and the spider. So instead of making "skins" on a stve head, i use the build in heads. But add the normal lores, so I know the value and so on.

**Comment by Sikatsu** [comment]
Hm, I see. Should disable it for wither skeletons then. And is there any way to change the name or lore of the heads found? So they know from which plugin it is.

**Comment by Rocologo** [comment]
I don't understand why this is a problem?

**Comment by Sikatsu** [comment]
Because they can easily farm wither skeleton heads to create a wither. And the other one isn't a problem but a feature request.

**Comment by Rocologo** [comment]
Then lower the chance to get a wither skeleton head ???

**Comment by Rocologo** [comment]
Some would say this is a feature and not a problem.

**Comment by Sikatsu** [comment]
It's a feature request actually? Option to add a lore to these heads.

"Head found fron killing mobs."

Op zo 4 mrt. 2018 21:20 schreef Rocologo <notifications@github.com>:

**Comment by Rocologo** [comment]
But why, I need to understand why if it is important. You can just lower the chance to get a wither head?

The heads can be used to create withers no matter the Lores. So why? :-)

**Comment by Sikatsu** [comment]
No, see it as a seperate thing. We got multiple plugins where you can gain
heads from. Just thought it'd be cool if it had a lore.

Op ma 5 mrt. 2018 om 20:21 schreef Rocologo <notifications@github.com>:

**Comment by Rocologo** [comment]
Did you know that you can always recognize a MobHunting reward if it is placed on the ground? If you hit it, it will show the name and the value. I dont think the other plugins does this?

**Comment by Rocologo** [comment]
Maybe I could add a Lore called "MobHunting Reward", I have also thought about adding the owner of the reward. (Owner = player who picked up the item, but owner could also be the player who killed the mob (if the head is a mob and not a bag))

hmm....

**Comment by Rocologo** [comment]
Next release will have this :-) Your request is not forgotten

**Comment by Rocologo** [comment]
Added in new releases
