### ISSUE TITLE
chat spamming

### ISSUE THREAD

**Issue by xHuginx** [Rocologo/MobHunting#364]
the new update is spamming chat with every kill as you get a item and skull. 
but no item or skull is received. 

![b3d7eba87b46178312326bcd90fd1d80](https://user-images.githubusercontent.com/37051489/36951285-bd8b876a-1fb6-11e8-99f1-024b54307e9d.png)

[config.txt](https://github.com/Rocologo/MobHunting/files/1779018/config.txt)

also get a NPE error :(
[NPE_error.txt](https://github.com/Rocologo/MobHunting/files/1779029/NPE_error.txt)

**Comment by Rocologo** [comment]
Please text v5.5.4

**Comment by xHuginx** [comment]
What ever you did in 5.5.4 fixed the NPE error but still getting the spam on every kill.
Noticed skull is only received when the blue text is shown. 
![497d332240839b2b43cd9c650f0ed3c1](https://user-images.githubusercontent.com/37051489/36973046-470ace0a-2026-11e8-86d5-2b3dc6df7090.png)
but this (you got a "mob" skull and iron ingot) spams on every kill. its not isolated to 1 mob I'v killed every mob type to test it. 

only thing im questioning here is your configs example area at the top. I see a string cmd for pex. is the new update dependent on pex permissions to function correctly?
if that is the case i dont use pex, i use luckperms.

**Comment by Rocologo** [comment]
Its not a permission problem. Could you please post your config.yml ? (on Pastebin.com)

**Comment by xHuginx** [comment]
https://pastebin.com/JzMbs7xU

**Comment by Rocologo** [comment]
`  spider:
    enabled: true
    message: **You got a Spider skull and an Iron ingot.**
    money:
      amount: 5.5:10.5
      chance: 1.0
    commands:
    - chance: '0.05'
      cmd: give {player} Iron_ingot 1
    head:
      drophead: true
      value: '0'
      chance: 0.05
      message: §aThe §1{killed} §adropped a skull on the ground`

You get this message because "message" tells so.  You need to clear the text. 

`  message: '' `

**Comment by xHuginx** [comment]
thank you should let every one know with version 5.5.4 they need to remove that message line to prevent the spamming :)

**Comment by Rocologo** [comment]
Well as of 5.5.0 I announced that you had to review the messages :-)

In V5.5.5 i have decided to make a better message. The first one was bad. I agree. It was stupid to convert an exsting message into that field.

**Comment by xHuginx** [comment]
its cool i rather help find the issues and test solutions rather then cry and complain, lol. any ways i found that the npe error only happens if you attempt to change the config and do "mh reload" in console. but if i do a full server stop then start. i dont get the npe error :)

**Comment by Rocologo** [comment]
Im very happy that you helped! Its very time consuming to do the testing, and I spend a lot of time on my test-server instead of my real server (mc.lindegaard.one)  although a handful of server owners help me with the testing. 

When somebody report a NPE error or anyother error I always try to solve it. And I dont delete the ticket until is is solved, (or if  the player who reported the issue stops responding)

Your should always create a ticket if you get an NPE error. I will always try to solve it. NPE errors are typically not that hard to solve.

Thank for you help.
