### ISSUE TITLE
Config file is rewritten on startup

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#365]
Spigot 1.12.2
MH 5.5.3

The config.yml file is backed up and rewritten on each server restart. The backup file does not contain the empty messages
> message: ''

in fact, the message: lines are missing altogether.

On server restart, the default message are written into the config.yml. Consequently, I edit the config.yml during the startup process, in order to (re)create empty messages.

It is not clear why the file needs to be rewritten by the plugin, rather than just read, and an additional concern that it does not match the backups. (I have not tested whether the latest backup file could be used to replace a (damaged) config.yml.)

I would much prefer that the file was simply parsed, and any errors reported in the console/log.

**Comment by Rocologo** [comment]
I hope 5.5.4 solves the issues with config.yml ones and for all

**Comment by Rocologo** [comment]
I hope 5.5.4 fixes this

**Comment by SlimeDog** [comment]
Spigot 1.12.2
MH 5.5.5

config.yml is still rewritten on startup. On first restart, after update to 5.5.5, the mobs.*.message nodes were missing entirely, not the
>    message: ''

as I had edited them.

On the next restart the messages were replaced with new ones:
>    message: You killed a §1{killed}

On the next restart, after I replaced the messages with
>    message: ''

the messages nodes were missing entirely again.

On the next restart the messages were replaced with new ones:
>    message: You killed a §1{killed}

This cycle continues, alternating between no message nodes and the new ones.

Please give a configuration option to not rewrite the configuration file on startup (or any other time). I will add new configuration nodes myself (it would be helpful if you supplied the default configuration in the plugin or on the web site, but I can manage that, as discussed in separate issue).

**Comment by Rocologo** [comment]
Confirmed. In release 5.5.6 

message: ''

Will not be removed anymore. I tried to save some lines in the config.  I cant both have a default value "You killed ..." and remove empty lines.

**Comment by SlimeDog** [comment]
You could save a lot of config lines by having a default section at the top. Then only differences from defaults would have to be noted. :)

**Comment by Rocologo** [comment]
I know I could save a lot of code :-) 

Normally my config works well. I'm just having troubles with this major change i did. There have been moments where I regret that I started this change :-)

V5.5.6 is released

**Comment by Rocologo** [comment]
And alot of time too :-)

**Comment by SlimeDog** [comment]
Thanks for speedy response. I'll check 5.5.6.

IMHO, the complexity contributes to the code and time spent. The config is much simpler than 5.4.x, though, and that is very much appreciated.

**Comment by SlimeDog** [comment]
Spigot 1.12.2
MH 5.5.6

Confirm that while config.yml is still being rewritten on each startup, the empty messages
> message: ''

remain intact. Thank you.

**Comment by Sikatsu** [comment]
If I remove the line and do /mh reload it doesn't change anything however on 5.5.6.

**Comment by Rocologo** [comment]
@Sikatsu This what @slimedogs says "it works now" :-)

**Comment by Sikatsu** [comment]
Hmm. I added message: "' and did a full server restart since /mh reload didn't work on it. Seems to work for now, but noticed it still changes something in the config since the size changed.

**Comment by SlimeDog** [comment]
I still see no reason for the file to be rewritten. Just parse it and leave it alone. Send any ERROR or WARN message to the console/log.

**Comment by Rocologo** [comment]
The config.yml is not a file in the jar. It is build EVERYTIME, this is why I can update all comments without changing the values. So the config.yml is rewritten everytime I cant change that. Sorry.

**Comment by SlimeDog** [comment]
I know. But it doesn't have to be that way, and it is not optimal. Other plugins manage to do so. However, I am going to try to not keep beating this dead horse. :)

**Comment by Rocologo** [comment]
Ha ha :-)

I think it is very use full that I am able to update comments, show me another olugin which can do the same. Normally my config works very well, but the 5.5.0 was a major change, where I had to change my AutoConfig as well, this has been very time consuming, but now I know how to make more improvements. 

Anyway the horse is dead starting to chance the config again now woukd be crazy. I need a bit of spare time now, watching some movies ;-)

**Comment by SlimeDog** [comment]
And there are plenty of good movies to watch. Catch up with the Oscars nominees and winners.

**Comment by Rocologo** [comment]
Yes I would love to see "The shape of water" :-)

**Comment by Sikatsu** [comment]
Three billboards on ebbing, missouri is a must see.

Op di 6 mrt. 2018 om 11:15 schreef Rocologo <notifications@github.com>:
