### ISSUE TITLE
Fly penalty not working

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#367]
Using 5.5.6, it seems the fly penalty is broken. I receive money from killing mobs while flying.

**Comment by Rocologo** [comment]
please show me the debug information from the console when you do a kill while flying

**Comment by Rocologo** [comment]
And what is your "flyingPenalty" in config.yml ?

**Comment by Rocologo** [comment]
Hello? :-)

**Comment by Sikatsu** [comment]
Could it be possible this got reset with the new config.yml?

FlyingPenalty is set to 1.0, which means it's disabled. I want them not to receive money at all when they use /fly.

**Comment by Rocologo** [comment]
Yes if i forgot to convert the old value, i will check

**Comment by Rocologo** [comment]
I checked, I do copy the old value.

this.penaltyFlying = mConfig0.penaltyFlying;

But maybe something went wrong when you helped me with all the testing :-)

**Comment by Sikatsu** [comment]
That's possible. Pretty sure it worked before, how do I disable receiving money now when fly is on?

**Comment by Rocologo** [comment]
set penalty to 0 its basically a multiplier
