### ISSUE TITLE
Error on Paper Spigot 1.12.2.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#369]
https://hastebin.com/yevasexoru.vbs

**Comment by Rocologo** [comment]
Have tried to make a message_type in config.yml ? 

What did you write?

**Comment by TheIntelloBox** [comment]
I wrote nothing. :x

**Comment by Rocologo** [comment]
Okay, which mob did you kill? And i would like to see the config section of this mob?

**Comment by TheIntelloBox** [comment]
This was in the console so I don't know. Here is my config : https://hastebin.com/aleviputit.coffeescript

**Comment by Rocologo** [comment]
Hmm.. I have tried different settings but I cant provoke a NPE error, so at the moment I dont know whats trigger this bug in the console????

**Comment by TheIntelloBox** [comment]
Have you tried with PWP ?

**Comment by Rocologo** [comment]
Nope. Im only one on my test server... so its hard to test. But thinkink of this i will check the source code again

**Comment by Rocologo** [comment]
I have three ticket with the same issue now :-) 

I hope the problem is solved in newest snapshot build 600 or newer

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Rocologo** [comment]
Please let me know if it works

**Comment by Rocologo** [comment]
fixed in 5.5.7

**Comment by TheIntelloBox** [comment]
Thanks ! :D
