### ISSUE TITLE
Keeps making backups of config.yml

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#371]
Hey, is it really neccesary to keep making backups of config.yml within the backup folder?

**Comment by Rocologo** [comment]
I can make a setting to let you choose? I like it, but I guess you dont ;-)

**Comment by Sikatsu** [comment]
My server restarts atleast each day, got like 10 files already that I don't really need since I got a local backup already. Plus, the config doesn't change each day that makes it really needed..

**Comment by Rocologo** [comment]
I made it because of the change in the config.yml... I guess I could remove it again, when most people has converted to V5.5.0+

**Comment by Sikatsu** [comment]
Which I understand, but I think it only needs to do that once, which is when you upgrade to the new configuration. Once you got the new configuration, I don't think it needs to make backups anymore everytime.

**Comment by Rocologo** [comment]
I like to have the config.yml because of all my testing, so I have added a setting in config where you can disable this.

Check general settings , "backup: false"

**Comment by Sikatsu** [comment]
Even with the setting on false it still makes backups.
