### ISSUE TITLE
Bug with BagOfGold - I want it to go directly into a players balance.

### ISSUE THREAD

**Issue by MadPaddyy** [Rocologo/MobHunting#375]
"drop_money_on_ground: true"
"drop_money_use_item_as_currency: false" 
Have tried both options as true and both as false.

Basically i want to be able to have all the money from killing mobs go directly to a players balance (vault) instead of a bagofgold item that they have to /mh bag sell, No matter what i do it keeps dropping a bag of gold item even though i havent got the dependency plugin installed and i have turned that feature off. Currently i cannot turn the feature for physical currency off, i dont know what im supposed to be doing.

**Comment by Rocologo** [comment]
Okay, then set
drop_money_on_ground: false

**Comment by Rocologo** [comment]
Or use my BagOfGold plugin, where the bagofgold is the balance

**Comment by MadPaddyy** [comment]
Sorry did it and it didnt work still getting the Bag Of Gold instead

**Comment by Rocologo** [comment]
Do you use my plugin BagOfGold?

**Comment by Rocologo** [comment]
please enable debug "/mh debug" and "/bag debug" kill a mob and show me the output in your console

Also show me your config.yml (use pastebin.com)

**Comment by MadPaddyy** [comment]
Hello sorry i just woke up, No i do not use your plugin Bag Of Gold and doing this now

**Comment by MadPaddyy** [comment]
https://pastebin.com/Nwb9521C

**Comment by Rocologo** [comment]
Thaks. I now i need to see your config.yml

**Comment by MadPaddyy** [comment]
I am sorry im having my entire server corrupting it might be my end for the issue, I dont know. Thankyou so much for helping me beforehand
