### ISSUE TITLE
Slime Bug still not resolved

### ISSUE THREAD

**Issue by Waterman1001** [Rocologo/MobHunting#378]
Hey Rocologo,
I have just tested the slime bug that I have reported earlier but it seems like it is still not fully fixed.
I can infinitly kill slimes after each other and there is no grinding spot created and I can just kill as many slimes as I want and earn money. The killstreak is indeed disabled, but I can still make a slime farm.

So I figured out the problem is not really the killstreak, but that there is no grinding spot created when killing a lot of slimes.

Hopefully you can fix it!

Thanks you so much :D

**Comment by Rocologo** [comment]
Slimes is different from other mobs, because they split. So I decided to make a rule, where the tiny slimes does not really count. But if you kill 20 slimes in the same spot a grinding spot will be created.

Cant you suggest a better idea?

**Comment by Waterman1001** [comment]
Well, Thats the problem. There is no grinding spot created.
I can just kill 40 slimes after each other without any problem
I like the way you are handeling it. It's a good way!

**Comment by Waterman1001** [comment]
![image](https://user-images.githubusercontent.com/19939623/37247189-e5d1000a-24b7-11e8-8179-971388fade25.png)

**Comment by Rocologo** [comment]
Okay, i will check the code again and see why you csn kill rhat many without grinding derection

**Comment by Waterman1001** [comment]
Thank you very much!
You're amazing :D 👍

**Comment by Rocologo** [comment]
Try V5.5.7 it should work now.
