### ISSUE TITLE
Value of heads from "drop_money_on_ground_itemtype: KILLED" does not survive server restart.

### ISSUE THREAD

**Issue by bc-hill** [Rocologo/MobHunting#385]
I have noticed that perhaps one in ten heads cannot be sold with `/mh money sell`

No errors in console.  I haven't noticed any common theme.  Heads appear to be the same as the rest:
![image](https://user-images.githubusercontent.com/7044511/37813656-53a40298-2e23-11e8-81a5-17f16a8bc5da.png)

`Mob Hunting Version5.5.7`

Can I provide any additional info?
Thank you.

Edit: It displays the `mobhunting.bagofgoldsign.hold_reward_in_hand` message, with these heads in hand.

**Comment by bc-hill** [comment]
Sorry, please disregard.  This only happens on server restart, which I can deal with. :)

**Comment by bc-hill** [comment]
I should not have closed this, as it will be a major issue when this server gets more players.

Heads with value that are obtained before server restart, cannot be sold after.

Version 5.6.0.  Spigot 1.12.2.  Thank you!

**Comment by Rocologo** [comment]
What do you mean with "KILLED" heads? Is it heads dropped from killed mobs, where you both get a money reward and a head or is the reward head of Killed mob with a value and maybe a head drop as well? 

Im not sure how to setup my test server to verify this issue?

**Comment by bc-hill** [comment]
Sorry I wasn't clear.  [Here's a config for you.](https://hastebin.com/duxevimiku.coffeescript)

**Comment by bc-hill** [comment]
OK, I have no idea what changed, but I am now unable to reproduce the issue.  Unsure if it was covered in a recent update, or if it was on my end.
I can now sell the skulls after the server has been restarted multiple times.
I will reopen if it magically starts again.
Thank you.
