### ISSUE TITLE
MyPet Issue

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#386]
It says MyPet compatibility is disabled in config.yml but it's not. 

Log: https://pastebin.com/ZieY19XK

enable_integration_mypet: true

**Comment by Rocologo** [comment]
Very strange. I will have to check this when I get home. My guess is that I have forgot a "not" somewere. (If this is the case you can change true to false, until I make a new release)

I will check this when Im back from home from work in some hours.

**Comment by Rocologo** [comment]
Fixed in build 611

https://fractal.lindegaard.one:8181/job/MobHunting/
