### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by MCTyler** [Rocologo/MobHunting#388]
The Basis of my Server, [CMI](https://www.spigotmc.org/wiki/cmi-holograms/), has added Hologram Support. Can you please add support for your holograms with this Plugin?

**Comment by Rocologo** [comment]
I cant find an API ? I will need an API to add support for these Holograms.

**Comment by Rocologo** [comment]
And I cant even find the CMI jar ?

**Comment by MCTyler** [comment]
[​IMG] ​
For developers who wants to use CMI as dependency for particular features and needs to have API to work with. You can download clean version of plugin from HERE. This version contains all methods used in original plugin but is stripped down from any actual code, so plugin will not work on actual server but will help to develop plugin of your own based on CMI engine. Github repository can be found HERE 

Custom CMI Events​

**Comment by Rocologo** [comment]
But I cant find CMI ??? you only send me the link for the Wiki?

**Comment by Rocologo** [comment]
Okay I got the JAR, buy where did you find the text with the API?

**Comment by MCTyler** [comment]
https://www.spigotmc.org/resources/cmi-ranks-kits-portals-essentials-mysql-sqlite-bungeecord.3742/

**Comment by MCTyler** [comment]
![capture](https://user-images.githubusercontent.com/6390898/38133017-08b21ff8-33d3-11e8-9774-7517706c974a.PNG)
Toward Bottom of the Page

**Comment by MCTyler** [comment]
If you want me to test a Demo Version, I would be happy to!

**Comment by Rocologo** [comment]
Thanks, I will see what I can do...

**Comment by Rocologo** [comment]
It is easy to hook into CMI, but I still need some basic methods. I have looked in the API, but it is big, so I will need the DEVS help. 

I created a ticket.

https://github.com/Zrips/CMI/issues/181

**Comment by MCTyler** [comment]
Yea, When I saw the Build Number of the API I figured this much. Zrips just needs to update the API. Hes pretty fast at Response!

**Comment by MCTyler** [comment]
CMI has pretty much made Essentials Obsolete!

**Comment by Rocologo** [comment]
Do you use my BagOfGold plugin too? I would like to know if it works with CMI.

**Comment by MCTyler** [comment]
I think that is why I DO NOT use BOG, but I will if it hooks!

**Comment by MCTyler** [comment]
I had to change the Drops to Item.

**Comment by MCTyler** [comment]
CMI has its own Economy

**Comment by Rocologo** [comment]
BOG should replace essentials economy completely and it should work with and plugin which uses a economy plugin. 

But if I hook into CMI it will of cause be able to do more. ANyway. Lets see what the DEV says.

**Comment by MCTyler** [comment]
k, i'll check back later.

**Comment by Rocologo** [comment]
Ok, it can be a problem that CMI has its own economy, if he does not use Vault.

**Comment by MCTyler** [comment]
No its Vault and this Injector....http://ltcraft.lt/wp-content/uploads/2018/02/CMIEInjector1.0.1.2.jar

**Comment by MCTyler** [comment]
You 2 are both passionate about the Game and your Plugins, Thats why I love you both!

**Comment by Rocologo** [comment]
Perfect, then BagOfGold should work with CMI, but I will have to check, since I mostly test with BOG enabled on my test server.

**Comment by MCTyler** [comment]
He added Support/API for your Holograms. Is it gonna work?

**Comment by Rocologo** [comment]
Hi @MCTyler

I have added support fort CMIHolograms, but I dont have CMI 7.6.2.0 so I cant test if it works. Please test build 624 or newer https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by MCTyler** [comment]
19:06:20] [Server thread/INFO]: [MobHunting] [ERROR] MobHunting could not register with [CMI] please check if [CMI] is compatible with the server [1.12.2-R0.1-SNAPSHOT]

**Comment by Rocologo** [comment]
Which version of CMI does you have?

I dont have CMI and I dont want to pay for plugins, so I cant test it. You MUST have CMI 7.6.2.0 or newer to use CMI holograms

**Comment by Rocologo** [comment]
@MCTyler Where cant I send you a message in private?

**Comment by Rocologo** [comment]
I made a stupid error, but this is fixed in build 626
https://fractal.lindegaard.one:8181/job/MobHunting/

I could really need a working jar :-)

**Comment by Rocologo** [comment]
WAIT I have found another problem

**Comment by Rocologo** [comment]
I need a working JAR v 7.6.2.0 before I make this work....

I cant test anything before I have working jar...

**Comment by Rocologo** [comment]
But it is okay to test buil 627 now

**Comment by MCTyler** [comment]
You can Email me at eodcraft.staff@gmail.com. I will try your latest build. Please email so I can get you what you need. This is ridiculous and you need this.

**Comment by MCTyler** [comment]
Amazing! Thank you so much!

**Comment by MCTyler** [comment]
Deleted and recreated in Game..Perfect!
