### ISSUE TITLE
MYSQL error

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#390]
Hey,

I have setup well my MYSQL but error : 

https://hastebin.com/itufohosig.sql

In my config there isn't the part "port".

**Comment by Rocologo** [comment]
Let me see the database section

**Comment by Rocologo** [comment]
Mysql uses port 3306

**Comment by TheIntelloBox** [comment]
Yeah but in the config I don't have this part

**Comment by Rocologo** [comment]
I ASKED for the database section.... :-)

just add the port to the hostname

  mysql:
    username: user
    password: password
    host: localhost:3306

**Comment by TheIntelloBox** [comment]
https://hastebin.com/bujekejevi.php

**Comment by Rocologo** [comment]
It looks like you have not set the hostname, username and password???

**Comment by Rocologo** [comment]
Have you create the database at all?

**Comment by Rocologo** [comment]
Have you created the database at all?

**Comment by Rocologo** [comment]
If you dont know how to use a MySQL database, you can just use Sqlite like this

  type: sqlite
  database_name: mobhunting

**Comment by Rocologo** [comment]
Did you solve your problem?

**Comment by TheIntelloBox** [comment]
With sqlite yes. ;) Ty !
