### ISSUE TITLE
Entity Heads Name keeps changing

### ISSUE THREAD

**Issue by MCTyler** [Rocologo/MobHunting#395]
I have a recipe plugin that relies on Head Drops to always Maintain a stable name I.E.
Before I used your Beta Download it was: 
§6§9Enderman Ect depending on the Mob
Now the Heads are being Named:
§a§9Enderman Ect

I need to keep these names consistent or People are not allowed to craft Spawners using the Head Drops.
Any ideas on how I can achieve this?

[14:27:51 INFO]: This server is running 'MobHunting 5.6.3-SNAPSHOT-B628'.

**Comment by Rocologo** [comment]
Hmm I not sure what you are talking about

But the mob names can be changed in the lang file.

I have not chanced colors for a while now, so I can explain what has happened when you installed the snapshot???

**Comment by MCTyler** [comment]
Yea kinda weird its adding the §a at the beginning. Wonder whats doing that? Maybe its the Recipe manager itself when I create the recipe.
