### ISSUE TITLE
Error from "NoSuchMethodError"

### ISSUE THREAD

**Issue by Osony** [Rocologo/MobHunting#404]
Hi, i have a bug, when i put your plugin and login on started server, i have this many errors
https://pastebin.com/m04sHkpN
If i set "disable-integration-protocollib" to true, i got another error
https://pastebin.com/UneuU4Zm
I use: 
Server core:
**Thermos 1.7.10 1614**
Plugins for this issue:
**MobHunting 5.2.3 (CB 1.7.9-R0.2)** (Try latest version - same)
**Vault 1.4.1-b436 (CB 1.7.9-R0.1)**
**ProtocolLib 3.6.5-b222**

commands work for me, but hunting are not
maybe i do somethink wrong?

**Comment by MCTyler** [comment]
Might be a tough one considering Thermos is Abandoned.

**Comment by Rocologo** [comment]
Yes, I only support MC 1.8 and newer because of the change to Java 8 in Minecraft 1.12

MC1.7.10 was made with Java 7 and I cant have to different development / test environments. This means that I cant fix bugs found in older versions of MobHunting. Sorry.
