### ISSUE TITLE
Remove messages in Config File

### ISSUE THREAD

**Issue by AsteriskDotHack** [Rocologo/MobHunting#405]
I do not what specific elements to be used in the config. I do not what to use the "message: §2[§8+§2] §r§7You killed a §2{killed}" tag but when i just don't put the code it defaults the message back to the original life that loaded. Is there a code Im missing somewhere that turns off the messages per kill or is it just a bug? Or not possible. 

`  blaze:
    enabled: true
    message: §2[§8+§2] §r§7You killed a §2{killed}
    money:
      amount: '10:15'
      chance: 1.0
    commands:
    - chance: '0'
      cmd: give {player} Iron_ingot 1
    head:
      drophead: true
      value: '10'
      chance: 0.05
      message: §2[§8+§2] §2{killed} §7dropped a skull!`

Im also having this problem with every variable. I have to have ome type of imput or it resets my whole file thus my my commands varrable is there but with a 0 chance.

**Comment by Rocologo** [comment]
Use 

message: ‘’

Instead of deleting the line

**Comment by MCTyler** [comment]
https://itunes.apple.com/us/app/vlc-for-mobile/id650377962?mt=8
