### ISSUE TITLE
MobArena issue

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#406]
Hey,

Some players are having issues with not receiving money anymore in the survival world.
I tried to catch some debug and found out that their kills are being blocked because MobHunting thinks they are still in the MobArena even tho they are not.

This is the debug I could catch: https://pastebin.com/CKLuUyJD

Player is definatly not in the MobArena and has relogged several times even.
It does seem a server restart solves the issue until they play MobArena again.

Hopefully I provided enough information for you to fix the issue.

**Comment by Rocologo** [comment]
Yes, i think i know whats wrong now. I will try to find a fix fast.

**Comment by Rocologo** [comment]
MobHunting has at least 9 different events to catch and I need to guess when they are called and used.
https://github.com/Rocologo/MobHunting/blob/d4c17492690f88f808dfbe713868059eb6110d03/src/one/lindegaard/MobHunting/compatibility/MobArenaCompat.java#L99

I hope I got it right, please test build  635 and let m know if the MobArena players is still having problems?

**Comment by Sikatsu** [comment]
I'll test it and let you know.

**Comment by Rocologo** [comment]
I hope it is fixed. I had to make a release V5.6.4

Is it fixed?

**Comment by Sikatsu** [comment]
I asked the player and never got a reply back. So I do think it's solved.

**Comment by Rocologo** [comment]
Okay, Thank you. I close this ticket now.
