### ISSUE TITLE
Bug with the placeholder {prize}. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#409]
Hey ! :D 

When someone kills a mob, he earns money but the message is : "Player earns {prize}€". :D 
So the placeholder is not working. :D 

Could you tell me how to fix it ? :D 

Thanks ! :D 
TheIntelloBox. :D

**Comment by Rocologo** [comment]
It looks fine to me, I cant see whats wrong. I cant test this the next days because im off on a mini vacation

**Comment by Rocologo** [comment]
So be patient :-)

**Comment by TheIntelloBox** [comment]
Hi ! :D No problem ! :D Thanks. :D

**Comment by TheIntelloBox** [comment]
Hey ! :D 

Could you tell me how to solve the problem ? :D 

Thanks ! :D

**Comment by Rocologo** [comment]
I have actually been looking at this, but I didt find the bug. It should work. I will have to do some live testing again. 

Could you please show me the full section the the mob you is testing on?

**Comment by TheIntelloBox** [comment]
Here is my config.yml: https://hastebin.com/ewipoyadoq.php ! :D 
And my en_US.lang: https://hastebin.com/kagiruluvi.sql ! :D 

Thanks. :D

**Comment by Rocologo** [comment]
Which mob are you testing on?

**Comment by Rocologo** [comment]
Please mention which bug I should test on? Have you tried on the Spider?

**Comment by Rocologo** [comment]
I cant find the text you mention in the spider settings??? 
`  # ### Spider settings ###
  spider:
    enabled: true
    message: Tu as tué un §1{killed}
    money:
      amount: 5.5:10.5
      chance: 1.0
    commands:
    - chance: '0.05'
      cmd: give {player} iron_ingot 1
    head:
      drophead: true
      value: '0'
      chance: 0.05
      message: §aThe §1{killed} §aa jeté une tête par terre`

**Comment by TheIntelloBox** [comment]
This text is in the en_US.lang.

**Comment by TheIntelloBox** [comment]
Should I delete the en_US.lang or the config.yml ? :D

**Comment by Rocologo** [comment]
No, you should not need to do so

**Comment by Rocologo** [comment]
It should work now out of the box, if you use lastest snapshot

**Comment by TheIntelloBox** [comment]
I'm back. :D (France are in finals of the Fifa World Cup 2018 in Russia ! :D)

https://cdn.discordapp.com/attachments/460816046501265417/466348142099562507/unknown.png

**Comment by Rocologo** [comment]
I guess you are french :-) Congratulations!

I see I will have to test this again :-( (When I am back from work)

**Comment by TheIntelloBox** [comment]
Thanks. :D

**Comment by TheIntelloBox** [comment]
Is the bug fixed ? :D

**Comment by Rocologo** [comment]
No I was not able to replicate the problem and I was busy fixing a serious problem. V1.1.4

**Comment by Rocologo** [comment]
I tested but i think it worked but i had no time to dive in and find the problem

**Comment by Rocologo** [comment]
Please confirm this is the lines we are talking about

mobhunting.moneydrop=Tu as droppé ${money}
mobhunting.moneygain=Tu as gagné ${prize}!

**Comment by TheIntelloBox** [comment]
mobhunting.moneygain=Tu as gagné ${prize}!

**Comment by Rocologo** [comment]
I cant still replicate the problem. Please enable debug **/mh debug**
and kill a mob and let me see the out in the console

**Comment by TheIntelloBox** [comment]
Hey,

https://hastebin.com/udumiyovuq.md

**Comment by TheIntelloBox** [comment]
?

**Comment by Rocologo** [comment]
I'm busy with the MC1.13 update, sorry. 

Also I was not able to replicate the problem. So its not that easy to fix. Your configuration must be diffrent from mine.

**Comment by Rocologo** [comment]
Maybe I should take a look at this again :-)

**Comment by TheIntelloBox** [comment]
What should I delete in the config or in the lang.yml ?

**Comment by Rocologo** [comment]
please let me see your lang.yml to check if you need to delete lines. Use pastebin

**Comment by Rocologo** [comment]
maybe you are missing a $ infront of {prize} somewhere ?

**Comment by TheIntelloBox** [comment]
https://hastebin.com/esaxalakol.sql

**Comment by Rocologo** [comment]
You have written the placeholder with a wrong format
this line is 
mobhunting.achievement.awarded.prize=Tu as été récompensé de {prize}€ !

should be
mobhunting.achievement.awarded.prize=Tu as été récompensé de ${prize}€ !

**Comment by Rocologo** [comment]
You must always use it like "${somename}"

**Comment by TheIntelloBox** [comment]
Could you add the possibility to change that ?

**Comment by Rocologo** [comment]
???? No, why should I do this???? You dont see the placeholder. You dont see the $ 

Check all the other placeholders...

**Comment by TheIntelloBox** [comment]
It makes no sense. In real life, you don't earn €1 but 1€

**Comment by Rocologo** [comment]
You have misunderstood how the placeholders work try

You have written the placeholder with a wrong format
this line is
mobhunting.achievement.awarded.prize=Tu as été récompensé de {prize}€ !

should be
mobhunting.achievement.awarded.prize=Tu as été récompensé de ${prize}€ !

you dont see the $ its a port of the placeholder

**Comment by TheIntelloBox** [comment]
Oh yes, sorry, I understand now, I'll try and tell you if it works

**Comment by Rocologo** [comment]
It does :-)
