### ISSUE TITLE
Achievements gui with Chest Commands

### ISSUE THREAD

**Issue by SuaWez** [Rocologo/MobHunting#41]
Just tried out the new GUI for Achievements in Chest Commands Gui, but it doesnt work, even I if think that I configured it well.

```achievements:
  COMMAND: 'mh achievements'
  NAME: '&5&lAchievements'
  LORE:
    - 'Cliccando, ti verranno mostrati i tuoi Achievements'
  ID: 277
  AMOUNT: 1
  ENCHANTMENT: knockback, 10; durability, 10
  POSITION-X: 7
  POSITION-Y: 3

**Comment by Rocologo** [comment]
What is Chest Commands? :-)

**Comment by Rocologo** [comment]
Do you get an error in the console which I can look at?

**Comment by Rocologo** [comment]
could you try if it makes a difference if you enter the command with full name:

>   COMMAND: 'mobhunt achievements'
>   NAME: '&5&lAchievements'
>   LORE:
>     - 'Cliccando, ti verranno mostrati i tuoi Achievements'
>   ID: 277
>   AMOUNT: 1
>   ENCHANTMENT: knockback, 10; durability, 10
>   POSITION-X: 7
>   POSITION-Y: 3

**Comment by SuaWez** [comment]
Will try soon!
It is a plugin that let you create a custom gui

**Comment by SuaWez** [comment]
No it doesn't work.
It appear for few seconds and after disappear (something like 0.3s)

**Comment by SuaWez** [comment]
Any fix? A week as gone..

**Comment by Rocologo** [comment]
No fix for now my priority has been to fix some bugs instead of adding support for another plugin. 

I will see if I can solve the problem, but tell me, have youasked the developer of chest commands if he know why this happens?

**Comment by SuaWez** [comment]
No I didn't, but I used other plugins that opens GUI, and they works..

**Comment by Rocologo** [comment]
I mean, "/mh achievements" works when you type it, so I dont know what to change to make it work with ChestCommands ???

**Comment by Rocologo** [comment]
So I have investigated this. I have added a debug line in my code so I can check if it is my plugin which close the GUI, and it is not. So it is ChestCommands which close both my inventory and the chest command inventory, so it is a bug in ChestCommands.

**Comment by Rocologo** [comment]
I have looked at the ticket for ChestCommands and it looks like the developer has stopped working on the plugin. I cant see he has fixed any bugs since start this year.

**Comment by SuaWez** [comment]
Okay thanks anyway for your help!

**Comment by Rocologo** [comment]
I have just learned that you also can use this plugin (https://www.spigotmc.org/resources/shop.8185/) for running comands. Maybe /mh achievements work here....
