### ISSUE TITLE
1.13 ItemMergeEvent error when moneydroponground merge

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#414]
https://pastebin.com/GP1QdXmS

This comes in console when money dropped on ground merges into one.

**Comment by Rocologo** [comment]
Build 680 should solve this bug (V6.0.1-SNAPSHOT)

https://fractal.lindegaard.one:8181/job/MobHunting/680/

Please test

**Comment by Rocologo** [comment]
https://fractal.lindegaard.one:8181/job/MobHunting/682/

**Comment by Nesseley** [comment]
This problem is fixed. :)
