### ISSUE TITLE
Implement message_type for money and head messages, too.

### ISSUE THREAD

**Issue by olekristian** [Rocologo/MobHunting#418]
![image](https://user-images.githubusercontent.com/634668/43925402-72621fcc-9c27-11e8-91ba-cf5df1b90612.png)

" Okay I see why.  I have only implemented "message_type" for the command message, (NOT the money message and the "head" message" .... Could you please create a ticket and the I will add this as well. But I cant do it tonight. "

Thanks!

**Comment by Rocologo** [comment]
Please test build 689

https://fractal.lindegaard.one:8181/job/MobHunting/689/

You will get a new block after first run

`mobs:

  # ### Default/Global settings ###
  # Possible message_type values: Chat, ActionBar, BossBar, Title, Subtitle, None
  default:
    message_type: ActionBar
    money:
      message_type: ActionBar
    head:
      message_type: ActionBar
`
