### ISSUE TITLE
MySql Error

### ISSUE THREAD

**Issue by cdmvirt** [Rocologo/MobHunting#423]
https://hastebin.com/azahejojej.shell

**Comment by cdmvirt** [comment]
https://hastebin.com/ohimumoseg.shell

**Comment by Rocologo** [comment]
Do you know how to drop the table "mh_Bounties" in your database ?

**Comment by Rocologo** [comment]
I think I have found another solution. But I have to test this first.

**Comment by Rocologo** [comment]
Please help me testing this build
https://fractal.lindegaard.one:8181/job/MobHunting/697/

**Comment by Rocologo** [comment]
That should not be needed :-)

I decided to drop the CONSTRAINT completely

PLease test build 700
https://fractal.lindegaard.one:8181/job/MobHunting/700/

**Comment by Rocologo** [comment]
Does it work now?

**Comment by cdmvirt** [comment]
will test sorry been busy :P

**Comment by Rocologo** [comment]
any news?
