### ISSUE TITLE
Cannot run the Plugin properly

### ISSUE THREAD

**Issue by zaxanq** [Rocologo/MobHunting#424]
Hi, I have a problem with running the Plugin, I am not sure what's the reason behind it.
Please see the console log of Server.
[https://pastebin.com/raw/BGiFvjnY](https://pastebin.com/raw/BGiFvjnY)

When I try to execute any command, like /mh kills for example, I get "An internal error occured while attempting to perform this command" information.

**Comment by iCrazykillerGR** [comment]
https://fractal.lindegaard.one:8181/job/MobHunting/ its been fixed and released here as a snapshot version. Also you have replicated an issue. Try the 694 build.

**Comment by zaxanq** [comment]
First of all, I am sorry for replicating the issue.
The 694 build did not help, the issue remains though I'm not sure if it's the same.
Executing commands like /mh kills or /mh head give results in "An internal error occured..." message.

The new console log:
[https://pastebin.com/raw/8zdGexPB](https://pastebin.com/raw/8zdGexPB)

**Comment by Rocologo** [comment]
Which server version do you use?

**Comment by Rocologo** [comment]
Older Minecraft versions 1.8-1.12.2 is only supported until V5.7.3-SNAPSHOT

https://fractal.lindegaard.one:8181/job/MobHunting/685/

**Comment by zaxanq** [comment]
Well, I use 1.12.2 and I initially downloaded V6.0.0 since the Game Version in the [MobHunting Files](https://dev.bukkit.org/projects/mobhunting/files) said 1.12 for that version. I will try downgrading the plugin to 5.7.3 and will let you know.

**Comment by zaxanq** [comment]
It works perfectly right now, thank you :)
