### ISSUE TITLE
[Request] Disable PVPTOGGLE on bounty creation

### ISSUE THREAD

**Issue by cdmvirt** [Rocologo/MobHunting#425]
We have pvp toggle and when you have random bounties the player hav PVP off so its pointles, any way to intergrate with [PVPTOGGLE](https://www.spigotmc.org/resources/pvptoggle.49112/), [PVPCONTROL](https://www.spigotmc.org/resources/pvpcontrol-universal-anti-combat-logging-pvp-manager-1-9-1-13.58162/) or [TOGGLEPVP](https://www.spigotmc.org/resources/togglepvp.44918/) so that when a Bounty is issued they get put into PVP for the duration of the bounty.

We have GriefPrevention so they can always stay on their claim but thats fine, eventually they will venture out.

**Comment by Rocologo** [comment]
I have looked at this, but I cant find the source code and the developer has not API I can use.

With this, I can do what you request.

**Comment by Rocologo** [comment]
No answer
