### ISSUE TITLE
Droppercentage bugged in 1.13?

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#426]
I believe that heads drop WAY to often, i got my configs set to 0.001 still gets heads like it was 20% chance to get them

**Comment by Rocologo** [comment]
Enable debug, kill one of the mobs which drops heads too oftens and let me see the output in the console.

**Comment by Nesseley** [comment]
https://pastebin.com/se58Ua4w

**Comment by Nesseley** [comment]
im config this is the setting i got for pig:
head:
      drophead: true
      value: '0'
      chance: 0.05

**Comment by Rocologo** [comment]
I cant reproduce the problem. Please try this build. I have added some debug information
https://fractal.lindegaard.one:8181/job/MobHunting/703/

Use "/mh debug"  and show me the output in the console

**Comment by Rocologo** [comment]
I need debug information to solve this.
