### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#428]

**Comment by Rocologo** [comment]
I didnt know spigot 1.13.1 was released. I will try to add this today

**Comment by TheIntelloBox** [comment]
Nice. :)

**Comment by Rocologo** [comment]
Have you found any bugs? Things not working?

**Comment by TheIntelloBox** [comment]
Nop, I just opened the issue because some big plugins are broken in 1.13.1. :)

**Comment by Rocologo** [comment]
I just imported 1.13.1 but i did not get any errors. So there is norhing to fix right now?

**Comment by TheIntelloBox** [comment]
Fantastic so ! :)

**Comment by Rocologo** [comment]
I have found a problem :-|

**Comment by TheIntelloBox** [comment]
Which ? :)

**Comment by Rocologo** [comment]
I dont think the heads and bags will work, until i update

**Comment by Rocologo** [comment]
Added in new releases
