### ISSUE TITLE
Getting killstreak from a spawner where there is grinding detected.

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#431]
Hey!

I have a problem where players can get killstreaks when killing mobs in a area where there is grinding detection.

Players should not get killstreaks if there is a grinding detected.

**Comment by Rocologo** [comment]
You have to be more specific on what exactly they are doing. I set killstreak to 0 in a lot of situations, if grinding is detected.

I need more information.

**Comment by Rocologo** [comment]
I think that killstreak will be set to 0 when you have killed 1/2 of the allowed maximum.
