### ISSUE TITLE
Leaderboard only able to be placed on south wall

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/MobHunting#433]
When creating a leaderboard, it seems to only work when placing on a south wall (e.g. player is facing south while  creating the wall).  Any other orientation causes the sign to be placed incorrectly.

See screenshot:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2018-08-29_12-45-12.png

Procedure I used:
1) Placed a middle sign as indicated by directions
2) Placed a sign to the left of the middle sign to be the top left corner
3) Placed a sign to the bottom right of the board to be the bottom right corner
4) Used worldedit to select those two corner signs
5) Removed the corner signs so they wouldn't be in the way of generating the leaderboard
6) Ran /mh leaderboard create total_kills alltime
7) Leaderboard command executed successfully, but signs were oriented in the opposite direction.

I did make a leaderboard on a south wall and it placed perfectly. Not sure if I'm doing something incorrectly to get it to face in the wrong direction.  I'm running Spigot 1.13 and MH 6.0.4

**Comment by Rocologo** [comment]
How strange :-) this must be related to the MC 1.13 update. I have not tested creating new leaderboards, only updating existing ones.

**Comment by braceyourself07** [comment]
No big deal since I have a south wall to place it on :P But just FYI.

**Comment by braceyourself07** [comment]
Actually I think this isn't a bug. I didn't fully understand how to layout the signs before creating the leaderboard.  I assumed that the plugin would create the signs for me so I didn't place all the blank signs.  I mean, technically it did place them for me, just not in the orientation that I wanted. 

So after watching the video (which I couldn't see because I was at work at the time), I placed it in the same pattern and it worked in any orientation.

My bad for not being thorough enough!  Looks like this works as it should!

**Comment by Rocologo** [comment]
I happy you found a workaround :-) but i think there is a problem so i will do some more testing.

**Comment by braceyourself07** [comment]
Well, like I said I don't think it's a bug really. The first time when I was getting the signs oriented the wrong way, I was doing this:

Screenshot:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2018-08-31_13-24-02.png

And the signs that weren't there ended up being the ones placed south only.  The directions perhaps could be made more clear to layout the signs like this:

Screenshot:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2018-08-31_13-25-38.png

And it works every time, no matter what direction it is facing.  So to me there is no more issue, I just wasn't using it properly.  The only thing being that the directions could probably be a little bit more clear, perhaps with a screenshot of how it's supposed to look before running the command and where to click to set the positions.

**Comment by Rocologo** [comment]
Finally I fixed it :-) I will make a release now.

**Comment by Rocologo** [comment]
released.

**Comment by braceyourself07** [comment]
Nice! Thanks!!
