### ISSUE TITLE
Selling MH heads in the sign shop.

### ISSUE THREAD

**Issue by incubus5150** [Rocologo/MobHunting#436]
I have given all heads a set value in the .jar. Using the [bag of gold] sign, I can sell 1 head at a time (only 1 head in my hand). But If the heads are stacked. It takes all the heads from the stack in your hand but only pays you for 1 head..  Using the 'sell all' sign will take all from your inventory of that head. again only paying for 1.  ideas?

**Comment by Rocologo** [comment]
??? What happened?
