### ISSUE TITLE
Mobhunt Sign shop

### ISSUE THREAD

**Issue by incubus5150** [Rocologo/MobHunting#437]
I have given all heads a set value in the .jar. Using the [bag of gold] sign, I can sell 1 head at a time (only 1 head in my hand). But If the heads are stacked. It takes all the heads from the stack in your hand but only pays you for 1 head.. Using the 'sell all' sign will take all from your inventory of that head. again only paying for 1. ideas?

**Comment by Rocologo** [comment]
Are you using my BagOfGold plugin too?

**Comment by Rocologo** [comment]
Fixed in build 702 or newer

https://fractal.lindegaard.one:8181/job/MobHunting/

Please test an confirm

**Comment by incubus5150** [comment]
the pay out is for each head taken. however the multiplier used is causing a extream increast in payout by the number of heads in the stack.. yes using bag of gold
((price x "number in stack" )  squared)
10 price and 10 in stack will pay out $1000
so a stack of say ,ender dragon heads, at $1000 will break the economy with the payout of $4,096,000
i didn't find a config for the sell price by number in stack.

**Comment by Rocologo** [comment]
:-( I will fix this first thing in the morning

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: incubus5150 <notifications@github.com>
Sendt: søndag, september 2, 2018 2:42 AM
Til: Rocologo/MobHunting
Cc: Rocologo; Assign
Emne: Re: [Rocologo/MobHunting] Mobhunt Sign shop (#437)


the pay out is for each head taken. however the multiplier used is causing a extream increast in payout by the number of heads in the stack.. yes using bag of gold
((price x "number in stack" ) squared)
10 price and 10 in stack will pay out $1000
so a stack of say ,ender dragon heads, at $1000 will break the economy with the payout of $4,096,000
i didn't find a config for the sell price by number in stack.

**Comment by Rocologo** [comment]
Fixed in build 705 (i found the bug in less than 2 minutes)
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by incubus5150** [comment]
new glitches continue to be found with the signs. not a complant. if heads didn,t stack, stacking will cause heads to not be sold. Even moving the stack in your inventory prevents them from selling.  Error msg " you must first hold bag of gold in your hand to sell it.

**Comment by Rocologo** [comment]
In creative mode?

**Comment by incubus5150** [comment]
Survival .  And no God mode..  if in creative any mob hunt head or gold bag
reverts to a head..

**Comment by incubus5150** [comment]
Update. misunderstanding on my part with the owner.  we are NOT running ,bags of gold, not sure that will have anything to do with the sign issue.. however, upon reading up on it. i believe we will be..  I apologize for the mistake.

**Comment by Rocologo** [comment]
I fixed and tested the bug where you didn't get the correct amount of money when you were selling stacked heads using a sign. The bug existed also in all other old versions include versions for Minecraft 1.12. :-)

The bug is only fixed in newer versions after build 702

**Comment by incubus5150** [comment]
The head / money pay issue is fixed.. however. If you put heads togther or
mess with a stack of heads in your inventory. The heads can't then be
sold.. even if it's just putting them into your hand to sell.. it seems if
you directly interact with the heads and move them they become unusable..
