### ISSUE TITLE
Configuration setting  mob_rob_from_player: does not allow percentage.

### ISSUE THREAD

**Issue by smashedbotatos** [Rocologo/MobHunting#438]
Under the penalty section of the config.yml there is a section labeled mob_rob_from_player. If set to 10 it will remove 10 currency from the player, if set to 10% it will NOT remove 10% of the player's currency. 

config.yml
'  penalty:

    # If a player flies at any point in a fight, this penalty will be applied
    flyingPenalty: 0.2

    # This is the penalty if the player gets killed by a mob.
    # Set mob_rob_from_player=10 to let the mob steal 10 dollars
    #  or 10% to let the mob steal 10% of the players balance.
    # Set mob_rob_from_player=0 to disable this
    mob_rob_from_player: 10%'

Console Output with debug on
`[12:41:37 INFO]: [MobHunting][Debug] Smashedbotatos died - Killstreak ended
[12:41:37 INFO]: [MobHunting][Debug] Smashedbotatos was killed by a Husk
[12:41:37 INFO]: [MobHunting][Debug] There is NO penalty for being killed by a Husk
[12:41:37 INFO]: [D] Smashedbotatos was slain by Husk`

**Comment by Rocologo** [comment]
You have written 

10%'

Remove the ' and it will work. Im am testing if it ends with %. But be cause you have written ' then it does not work

**Comment by smashedbotatos** [comment]
After changing the configuration to the following and restarting the server. 
` mob_rob_from_player: 15% `


I am still seeing the following result.
`[12:56:36 INFO]: [MobHunting][Debug] Smashedbotatos was killed by a Wolf
[12:56:36 INFO]: [MobHunting][Debug] There is NO penalty for being killed by a Wolf
[12:56:36 INFO]: [Death] Smashedbotatos was slain by Wolf
`
