### ISSUE TITLE
[DropMoneyOnGround] Drops the item - doesnt give the money

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#439]
Hey!

When killing mobs they sometime drop the items (i have ROSE_RED in config)
When picking it up you dont get the money.

Made this happen by killing a mob with my hand

This happens everytime if you have ROSE_RED in the inventory.

**Comment by Rocologo** [comment]
I have tested this, but I cant reproduce this issue...

Also it makes no sense, but I have tested this anyway....

**Comment by Rocologo** [comment]
No I dont think so

**Comment by Rocologo** [comment]
Show me the debug information from your console

**Comment by Rocologo** [comment]
I need the debug (/mh debug) information from your server log, when this happens, I cant fix this without.
