### ISSUE TITLE
[Server Crash] Crashing server onEntityPickupItemEvent

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#440]
https://pastebin.com/JyG0D4mj

**Comment by Rocologo** [comment]
Well it looks like  You are  using TheNewEconony in stead of Vault. 

MobHunting and BagOfGold does not use TheNewEconony.

So i cant really help you

**Comment by Nesseley** [comment]
I am using TheNewEconomy instead of iConomy and I am using vault. I am not using bagofgold

The plugin works and gives me money. Then suddently errors.

**Comment by Rocologo** [comment]
The crash report is hard to read, but it looks like it is TheNewEconony which does something before your server crashes. 

com.github.tnerevival.core.db.SQLDatabase.closeResult(SQLDatabase.java

But I cant guess what causes this.

**Comment by Nesseley** [comment]
I'l report on tne instead and see what they say
