### ISSUE TITLE
Ambiguous line in config.yml regarding fishing

### ISSUE THREAD

**Issue by braceyourself07** [Rocologo/MobHunting#442]
```
fishing:

  # Set this to true if you want to disable all fishing rewards / features.
  enable_fishing_rewards: true
```

My goal is to disable fishing rewards because players like to afk-fish and this result in huge amounts of gold.  The way this reads, I must set it to true to disable fishing rewards.  But the way the config line reads, it should be false.  What should I set this to in order to disable players receiving gold for fishing?

Thanks!

**Comment by Rocologo** [comment]
In the beginning the setting was called "disable_fishing_rewards" and it was false as default. Which was "negative" + "negative" so when I at some point decided to make a big review of all the settings I decided to change it to " enable_fishing_rewards: true" but I clearly forgot to change the "guide" 

If you dont what the player to get rewards you must set it to
 enable_fishing_rewards: false

I have changed the guide in next build.

**Comment by braceyourself07** [comment]
Oh I see thanks!!
