### ISSUE TITLE
Achievement of fishing fish

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#443]
Hello, when you catch a fish, mobhuntin tells it. If you throw that fish into a place with water, it will float and when you "fish" it will tell you again.
With this bug you can achieve achievements without effort.

I use version 6.0.5

Greetings.

**Comment by Rocologo** [comment]
Ah, this is a “bug” because of the new fish in minecraft 1.13. I think I know how to solve this.

You should disable fishing rewards until this is fixed

**Comment by Rocologo** [comment]
I have looked in to this problem and it is not as easy as I thought. Although it seems to e the same fish you catch over and over, it is technically not the same fish. Its not the same entity id, each time you catch a fish i has a new entity id. and I thought I could use the entity id to check if the player had cauth the fish before...

At the moment I dont know how to solve this.... :-(

**Comment by Rocologo** [comment]
I think I have found a solution. I only give a reward if fishingstate is "CAUGHT_FISH" and not when "CAUGHT_ENTITY". 

Please help me with the testing.
https://fractal.lindegaard.one:8181/job/MobHunting/713/

**Comment by Mundo-Minecraft** [comment]
This solved, good work works perfectly.
Whenever I report something, even if it is complicated, I solve it very quickly.

Greetings and thank you
