### ISSUE TITLE
Head shop

### ISSUE THREAD

**Issue by incubus5150** [Rocologo/MobHunting#444]
Earlier issue with the amount given per head is fixed. thank you for that.. new issue is that if you do anything to the heads.. in a stack.  ie. move them, split up the stack, put stack together.  then try to sell them. It says you don't have any in your hand.. only if the head drops into your hot-bar and all you need to do it select its position to have it in hand, does it work.

**Comment by Rocologo** [comment]
Which version are you on?

**Comment by incubus5150** [comment]
I tested the last version thats came out on the 8th. Sorry I don't have the
version number with me. But I tested it very early on the morning of the
9th, east coast US time. The issue was still there.

**Comment by incubus5150** [comment]
update: the version out on the 10th has the same error. players can't even open there inventory without the heads being unstable. if you just open and close inventory the problem occurred

**Comment by Rocologo** [comment]
I cant reproduce this anymore, please test on latest build

https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/

if you still can do this, I need you to tell me what you do step by step, so I know how to test this.

**Comment by incubus5150** [comment]
tested: fixed that issue.
mobs not dropping gold, removed bag of gold. sign still works properly, still no gold
did install new update of mcmmo. it has a bug in making claims. possible issue between them ?

**Comment by Rocologo** [comment]
Sorry i didnt get that???

**Comment by Rocologo** [comment]
use /mh debug /mh learn and kill a mob and let me see the output in the console.

**Comment by incubus5150** [comment]
this may be a stupid question..  mobhunt does or does not work with 1.13.1

**Comment by incubus5150** [comment]
https://pastebin.com/SFMXnidv

**Comment by Rocologo** [comment]
Its something with Worldguard, have you upgraded WG? Which version is you running?

**Comment by incubus5150** [comment]
We’re running version 7.0.0-beta01;01dfebe

**Comment by incubus5150** [comment]
It works.. thank you for all the time you put into this plugin..
