### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by ArtNRG** [Rocologo/MobHunting#446]
Paper version git-Paper-"f188863d" (MC: 1.13.1)
MobHunting v6.0.7
Error log: https://pastebin.com/raw/yKZUrLTg

**Comment by Rocologo** [comment]
This happens because you have entered a "chance" wrongly  for one of your mobs in the config.yml

**Comment by ArtNRG** [comment]
> This happens because you have entered a "chance" wrongly for one of your mobs in the config.yml

Can you help me to find where is it?
https://pastebin.com/raw/3ingAs75

**Comment by Rocologo** [comment]
Or maybe it is because you have disabled by removing the command

cmd: 

if you dont want a command you should enter

cmd: ''

**Comment by Rocologo** [comment]
but when you set the chance to 0 you dont need to remove the default command...

**Comment by ArtNRG** [comment]
After adding '' after cmd: and removing '' around chances all became ok.
