### ISSUE TITLE
Grinding penalty improvements

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#449]
Hey,

My players complain a lot about the grinding penalty.
For example when they kill 2 large slimes, leave and return an hour after to kill more slimes, they receive a warning about the grinding penalty. Maybe it should contain a timer of like 10 minutes? Or is there any other way to improve this system?

**Comment by Rocologo** [comment]
I have looked at this, and it is not that easy as I thought :-(

**Comment by Rocologo** [comment]
Hi Sikatsu

I have acutally works on this - on another ticket:
https://github.com/Rocologo/MobHunting/issues/555

It would be nice if you would help with the testing?

I close this ticket and keep the other one open.
