### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting v6.0.7

### ISSUE THREAD

**Issue by Gronsten** [Rocologo/MobHunting#450]
Just started recently, but not sure if any other plugins were updated.  Turned on debug and captured this output.  Please let me know if I can provide any additional info.

--Gronsten
[mobhunting.log](https://github.com/Rocologo/MobHunting/files/2434307/mobhunting.log)

**Comment by Rocologo** [comment]
Yes. Which version of WorldGuard do you use?

**Comment by Gronsten** [comment]
WorldGuard version 7.0.0-beta01;01dfebe

**Comment by Rocologo** [comment]
It seems that SK89 has changed something in the new Beta. Im working on this now.

**Comment by Rocologo** [comment]
It seems that SK89 has changed something in the new Beta. I had to recompile the plugin and update to WG 7.0.0 Beta 1.

I will release Mobhunting V6.0.8 in 15 min.
