### ISSUE TITLE
[request] Old versions bugs.

### ISSUE THREAD

**Issue by En0tS** [Rocologo/MobHunting#452]
I can't update my factions server to 1.13 right now because of some plugins that don't support it yet.
Old MobHunting and BagOfGold are good but it contains some problems like nullPointerException on death and gold bags with default name. So, could you update old versions of MobHunting and BagOfGold with bug fixes?

**Comment by Rocologo** [comment]
Updating the old 1.1.7 BagOfGold version is a no go, its too buggy and I will never make it work perfectly. I made big changes when i changed to 2.x

About MobHunting, make sure to use newest 5.7.3-snapshot, if you find a serious NPE bug I will try to fix it.
