### ISSUE TITLE
HappyHour indicator

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#454]
Hey,

It would be nice if you can add a HappyHour indicator in the top right corner of the screen and once you open your inventory. Which states how long the HappyHour still lasts for. Basically the same as speed effects and such.

**Comment by Rocologo** [comment]
To my knowledge its not posible to write text in the upper right corner

**Comment by Sikatsu** [comment]
Not text. An icon, like when you have a beacon effect on you. If you open
the inventory it will then say "HappyHour 10m" meaning 10 minutes left.

Op za 3 nov. 2018 22:49 schreef Rocologo <notifications@github.com>:

**Comment by Rocologo** [comment]
An icon? Do you have any examples ? Another plugin doing something.like this? 

I cant change the text in the inventory, its the inventory name and.just some display text.

**Comment by Sikatsu** [comment]
Nevermind about this.
