### ISSUE TITLE
stopped working altogether

### ISSUE THREAD

**Issue by incubus5150** [Rocologo/MobHunting#457]
updated servers to 1.13.2 and it just stopped.. tried updating essentials. no change.
https://ybin.me/p/fd97088d615e1e81#CqVh6Ovx3KfVjO8emH5k4YgUkz8y2GmsBQkXwaLRd4E=

**Comment by Rocologo** [comment]
Let me see your server.log from start to everything is loaded

**Comment by Rocologo** [comment]
Hello???? No answer?

**Comment by incubus5150** [comment]
local internet down in my area.. wasn't able to reply. will pass on your request to the server owner to get you the information you need.. sorry for the delay
