### ISSUE TITLE
ERROR ThrownPotion entity 3738 has no item?!

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#459]
Not sure why this out of nowhere pops up lately.

https://pastebin.com/1mTtX8XF

**Comment by Rocologo** [comment]
I dont not play with portions, so I dont think this is MobHunting. I see that you have removed the [TAG] from the plugins so you cant see if it is MobHunting or another plugin. 

I you log is says:
25.11 11:48:18 [Server] INFO Enabling MobHunting v6.0.8
But normally it says 
25.11 11:48:18 [Server][MobHunting] INFO Enabling MobHunting v6.0.8

Could you please check which plugin write this bug to the serverlog?

**Comment by Sikatsu** [comment]
Not something I did? It's by default. How do you even change that?

Op ma 26 nov. 2018 16:08 schreef Rocologo <notifications@github.com>:

**Comment by Sikatsu** [comment]
Yeah I use multicraft. For me it's default without the tag though... perhaps it shows within the server log, i'll investigate.

**Comment by Rocologo** [comment]
Ahh, i use multicraft and yes, multicraft filter the lig using regex expressions. You can find the regex in one of the configuration files. 

May be i can find the regex i use, because i see the plugin tag, which is very useful :-)
