### ISSUE TITLE
Soft dependency for mcMMO Horses plugin

### ISSUE THREAD

**Issue by mrfloris** [Rocologo/MobHunting#462]
Spigot 1.13.2, latest version of this plugin

Would it be possible to recognize certain other plugins, like mcMMO horses, so that when they spawn their pet horse.. they can't grind it for heads, extra money etc?

They spawn the horse, grind it to death, repeat..
View attachment 389136 

Plugin I am using:
https://www.spigotmc.org/resources/mcmmohorses.46301/

**Comment by Rocologo** [comment]
Hi mrfloris. Now I got some time to look at this. I dont know mcmmohorses, so you will have to help me here. From what I read at spigotmc, the player has to catch a horse first? or are they able to spawn a horse out of the air? I not sure how it works?

**Comment by Rocologo** [comment]
Hi again

I have basic integration to work now. We need to discus when the player get a reward for killing a McMMOHorse and when he doesn't. 

1) If Horse dies permanently I guess its okay that the player get a reward?

2) What if the player kills another mob while riding his horse? Should I add a multiplier then  ? f.ex. x0.9 because its easier to kill another mob while riding a McMMO horse ?

3) What if the Horse has godmode? and killes another mob?

I need your input!

**Comment by Rocologo** [comment]
Build 723 and never supports McMMOHorses.

https://fractal.lindegaard.one:8181/job/MobHunting/723/

Please help me with the testing.

I have adde to rules.
1) You dont get a reward if you have "permanent-death: false" in McMMOHorses config.yml
2) You dont get rewards for killing your own horses.

**Comment by mrfloris** [comment]
Fantastic, we're in the middle of an event right now, thank you so much for this. Once the event is over in 6 hours i have more time to test this and will report back. Very excited to try this.

**Comment by mrfloris** [comment]
It appears they can kill the horse, got no bag of gold for it (yay) and the head didn't drop (yay). The special kill progress does happen, and counts it as 1 / 100 horse kills (but I can live with that.. I guess, since there's a respawn cooldown that means they have to 100x cooldown just to level up.

It seems to work, they respawn the horse, kill it again, and kill streak 2/100, but no head dropped, no bag of gold dropped. So that's nice!

**Comment by Rocologo** [comment]
Added in V2.5.2

**Comment by mrfloris** [comment]
The latest mcMMO Horses must have changed something, was unable to run mobhunting successfully. had to rollback the horse plugin. Just an FYI, for when you have the time to see if their api call changed or whatever.
