### ISSUE TITLE
No money given with mob hunting

### ISSUE THREAD

**Issue by MamitaLena** [Rocologo/MobHunting#463]
Mobhunting was working well on my server but lately, it doesn't actually give the player any money even though it announces that they received it. On the console, it puts out the following error.
Is this a bug or do I need to do something to the config file? I have vault installed and also protocol lib. Thanks.

[Server] ERROR Could not pass event EntityDamageByEntityEvent to MobHunting v6.5.0
06.12 07:16:18 [Server] INFO org.bukkit.event.EventException: null
06.12 07:16:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:98) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:616) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:515) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:648) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1445) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:967) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1051) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1332) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1874) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
06.12 07:16:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
06.12 07:16:18 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.LocalPlayer.getCardinalDirection()Lcom/sk89q/worldedit/util/Direction;
06.12 07:16:18 [Server] INFO at one.lindegaard.MobHunting.compatibility.WorldGuardHelper.isAllowedByWorldGuard(WorldGuardHelper.java:96) ~[MobHunting-6.5.0.jar:?]
06.12 07:16:18 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDamage(MobHuntingManager.java:484) ~[MobHunting-6.5.0.jar:?]
06.12 07:16:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
06.12 07:16:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
06.12 07:16:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
06.12 07:16:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
06.12 07:16:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:18 [Server] INFO ... 23 more
06.12 07:16:20 [Server] ERROR Could not pass event EntityDamageByEntityEvent to MobHunting v6.5.0
06.12 07:16:20 [Server] INFO org.bukkit.event.EventException: null
06.12 07:16:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:98) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:616) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:515) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:648) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1445) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:967) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1051) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1332) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1874) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
06.12 07:16:20 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
06.12 07:16:20 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.LocalPlayer.getCardinalDirection()Lcom/sk89q/worldedit/util/Direction;
06.12 07:16:20 [Server] INFO at one.lindegaard.MobHunting.compatibility.WorldGuardHelper.isAllowedByWorldGuard(WorldGuardHelper.java:96) ~[MobHunting-6.5.0.jar:?]
06.12 07:16:20 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDamage(MobHuntingManager.java:484) ~[MobHunting-6.5.0.jar:?]
06.12 07:16:20 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
06.12 07:16:20 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
06.12 07:16:20 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
06.12 07:16:20 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
06.12 07:16:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[Spigot_1.13.2_1.jar:git-Spigot-a1ba5fe-b4230a9]
06.12 07:16:20 [Server] INFO ... 23 more

**Comment by Rocologo** [comment]
Have you checked the release notes? Are you running WorldGuard 7.0.0 bera 2 or newer?

**Comment by Rocologo** [comment]
no answer

**Comment by MamitaLena** [comment]
Yes I have tried the worldguard legacy 7.0.0 Beta 2 and the beta 1 but both
do the same.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Rocologo** [comment]
Please enable debug /mh debug and restart your server and let me see the server startup log

Please use pastebin.com

**Comment by Rocologo** [comment]
no answer
