### ISSUE TITLE
Config keeps getting deleted "defect config.yml detected"

### ISSUE THREAD

**Issue by ZaHecc** [Rocologo/MobHunting#464]
Not sure what I'm doing wrong but I've edited the plugin 3 seperate times and everytime in the console it tells me that "Defect config detected, deleted". That I have the wrong version but at the bottom it still says version 1? Not sure how I messed it up, here is the config file! 

https://pastebin.com/XWQX6XTX

**Comment by Rocologo** [comment]
Use a yaml validater to find the errors you have made

http://www.yamllint.com/

**Comment by Rocologo** [comment]
i guess you have solved your issue
