### ISSUE TITLE
Bags of gold drop weirdly

### ISSUE THREAD

**Issue by mrfloris** [Rocologo/MobHunting#467]
I keep forgetting you prefer github issue reports; sorry. 

https://www.spigotmc.org/threads/mobhunting.46937/page-183#post-3266978

Upgraded to latest 6.5.0 snapshot with the mcmmo horse support, and now when players kill say a spider from a spider spawner, it says the spider dropped $12,50 and another one $12,50

we didn't pick the bags up yet.. then type /money say we have $1000 in balance.

You walk to the corner, to get the bags that lie in the water, and it says  "you found $12,50" only 1 gets mentioned..
the bag of gold doesn't "disappear" from inventory it gets picked up and stays there. the bag of gold is now $25

/money again, and it says $1000 still.  (phew!, but it did just say we found $12,50, implying we just got paid out)

then we drop the bag of gold and walk onto it, and it says we found $25, we do /money and the balance is now $1025 (we got it, phew!)

So in the end, we did get the right amount, but ..
a- we dont want players to pick up the bag, before the upgrade they wouldn't it would just disappear and the money would be there in /money)
b- the extra msg without actually paying if confusing to players, they think they got paid, then give their friend teh bag who actually gets the money, or they /market it, etc.

i think we upgraded from MobHunting-6.0.8.jar to 6.5.0 -snapshot with mcmmo horses support.
and we're on 1.13.2, but almost a week behind on new jars

https://youtu.be/HAiSy3bbhgU

**Comment by Rocologo** [comment]
I cant remember if you use my BagOfGold plugin as well?

**Comment by mrfloris** [comment]
> I cant remember if you use my BagOfGold plugin as well?

Never had the use for it. No, I don't use it. Just MobHunting. 

What we've always had:  kill a mob, it drops a head (bag of gold) with a value on it. player walks onto it, and once it hits the inventory it goes away and they get the money into their /money balance. 

With the latest update it becomes an item in the inventory, and you have to throw it out a few times before it finally goes into /money

**Comment by Rocologo** [comment]
Hmm... To be honest, I simpley forgot this feature when I made the clean cut between BagOfGold and MobHunting, so I deleted the option in config.yml

I have added the feature again in newest snapshot

https://fractal.lindegaard.one:8181/job/MobHunting/724/

Please help me with the testing...

**Comment by mrfloris** [comment]
Do I need to re-add something manually to config.yml?

Because it still ends up as item in inventory and upon throwing it out it just does it like 12+ times really fast with popping noises and you dont get the money at all now. 

All the money is also ($1) for *everything* even players with bounty 5000, drops as $1 etc.
this update relaly broke loads of stuff, so this isn't the update im looking for :P

**Comment by Rocologo** [comment]
Ahh yes, this is default, you need to change

Drop-money-use-as-economy = false

I cant remember the exact name. Look in the drop money section

**Comment by Rocologo** [comment]
Fixed in V6.5.1. (I hope)
