### ISSUE TITLE
net.citizensnpcs.nms.v1_13_R2.entity.BatController$EntityBatNPC

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#468]
https://hastebin.com/hovamusacu.md

**Comment by Rocologo** [comment]
Is Citizens updated?

**Comment by Rocologo** [comment]
It actually doesnt look like a MobHunting error. Why do you think so?

**Comment by TheIntelloBox** [comment]
Yes I'm using the latest dev build.
