### ISSUE TITLE
skull stacking and selling

### ISSUE THREAD

**Issue by incubus5150** [Rocologo/MobHunting#471]
error of convenience. wither skelly skulls and fish heads wont stach. also the fish heads won't sell..  another issue is at times selling a stack will look like it sold the stack but only pays you for 1. then click where the stack was and they will show back up. minus that one. so in the end you get the money but the procedure to get it is annoying my players. this is not a major priority because the players still get there money and are understanding as to how big a pain in the butt coding plugins is with the 1.13 update

**Comment by Rocologo** [comment]
I need to know if you are using BagOfGold as well or if you only uses MobHunting?

**Comment by Rocologo** [comment]
I cant replicate this problem. I have tried to drop some heads using "/mh head drop cod" and when I picked them up, they stacked. Check the screenshot. So what did you do? 

![2019-01-12_09 18 32](https://user-images.githubusercontent.com/1008133/51071030-24f67280-164b-11e9-913d-a30c55ed45b0.png)

**Comment by incubus5150** [comment]
we didn't need to do anything. There not glitched heads. They didn't Stack
and when we forced them to stack..  (shift click) .. they then sold only 1
at a time.  Fish heads won't stack or sell if you catch them from fishing.
We are running mcmmo if that could create issues. The issue isnt that
important.  Would ask you to look in to the fish heads tho.

**Comment by Rocologo** [comment]
please upgrade to 6.7.4
