### ISSUE TITLE
InfernalMobs Issues

### ISSUE THREAD

**Issue by stifflered** [Rocologo/MobHunting#472]
Two issues here that I'm not sure are related:

1. My achievements aren't showing the InfernalMobs name that is in the lang file. Is there a way to either get the correct name to show or remove InfernalMobs from the achievements list entirely?

For reference, my lang file says this: "mobs.InfernalMobs_Illusioner.name=Infernal Illusioner"

2. My leaderboards don't show InfernalMobs kills unless I add the different Infernal_mobname to the config. But, when I restart the server, the config file gets all of the mobs I added erased. I'd like for my InfernalMobs_Kills leaderboards to be able to track the mobs that are killed and for those mobs to remain in the config.

**Comment by Rocologo** [comment]
I can replicate the problem
I tried to rename "mobs.infernal_spider.name=Infernal sPIDEr222"
and create a leaderboard /mh leaderboard create infernal_spider222 3 3 1 and the result was like i expected.
![2019-08-09_14 28 36](https://user-images.githubusercontent.com/1008133/62778978-29382080-bab2-11e9-8cbf-c544aa32a6fe.png)
