### ISSUE TITLE
1.7.10 Version?

### ISSUE THREAD

**Issue by Doritoz** [Rocologo/MobHunting#473]
Which version of mob hunting is compatible with thermos 1.7.10?

> [18:56:32] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v5.1.9
> org.bukkit.event.EventException
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
> 	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:360) [CraftEventFactory.class:1.7.10-1614.58]
> 	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1072) [sv.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
> 	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:145) [wf.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1399) [yz.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611) [nh.class:?]
> 	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
> 	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
> Caused by: java.lang.NoSuchFieldError: ARMOR_STAND
> 	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:640) ~[?:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
> 	... 18 more

**Comment by Rocologo** [comment]
I really cant remember anymore

I would try this list
https://dev.bukkit.org/projects/mobhunting/files?filter-status=1&filter-game-version=2020709689%3A490

And if I look at this page https://bstats.org/plugin/bukkit/MobHunting you might be lucky with one of the oldest versions. 4.4.x or so

**Comment by Doritoz** [comment]
4.9.5 not work :( 
do you have a mobs count plugin separate?

**Comment by Rocologo** [comment]
If you check this https://bstats.org/plugin/bukkit/MobHunting you will see one 1.7.10 server running, so one of the lidted versions should work. But i dont even have my 1.7.10 test server anymore so i cant check if

**Comment by Rocologo** [comment]
I realize that I will never be able to support 1.7.10, at the moment I can't even support 1.12.2. I have close this ticket. Sorry.
