### ISSUE TITLE
Admins unable to remove bounties

### ISSUE THREAD

**Issue by Zoneman1972** [Rocologo/MobHunting#475]
Using the command /mh bounty remove (playername) gives back the error that there is currently no bounty on that player when there actually is.
This affects both player applied bounties and random bounties.

**Comment by Rocologo** [comment]
Have you give yourself permission: mobhunting.bounty.admin ?

**Comment by Zoneman1972** [comment]
Yes I have. I am also opped which I thought would have made it work even
more.
It seems the only person that can remove the player applied bounty, is the
person that applied it.

**Comment by Zoneman1972** [comment]
After removing, restarting, reinstalling and restarting again, the issue is no longer there.
I can remove bounties now,
Sorry for inconvenience. I will close this issue.
Thanks for your time and help though, I do appreciate all your hard work you do on this plugin.
