### ISSUE TITLE
SQLITE_BUSY console error

### ISSUE THREAD

**Issue by ArtNRG** [Rocologo/MobHunting#477]
After upgrading from MobHunting 6.0.7 to MobHunting 6.5.1 (build 726) my console is spammed with this error: https://pastebin.com/raw/2nCypBnL

Paper version git-Paper-481 (MC: 1.13.2)

**UPD:** Few more console errors: 
  https://pastebin.com/raw/yyxM0xD8
  https://pastebin.com/raw/FBR9Suzd

**Comment by Rocologo** [comment]
If you still get SQLITE_BUSY your server must be too slow or maybe you have opened the file ???

**Comment by Rocologo** [comment]
Error 3 also show that you have a database problem. ???

**Comment by ArtNRG** [comment]
Ovh dedicated game server. The errors appear after the update and there were no errors before it. The file wasn't opened too.

**Comment by Rocologo** [comment]
Yes. I can try to see what happens when I load your database file on my test server.

**Comment by ArtNRG** [comment]
@Rocologo https://www.dropbox.com/s/4fqgr7w4ilpkmll/pets.db?dl=0

**Comment by Rocologo** [comment]
This is not the MobHunting database ???

**Comment by ArtNRG** [comment]
Sorry, here is the correct link: https://www.dropbox.com/s/d7s8iod1t1rlrtk/mobhunting.db?dl=0

**Comment by Rocologo** [comment]
I have downloaded your mobhunting.db file and tested it on my test server. No problems. MobHuting worked well.

**Comment by yannicklamprecht** [comment]
What OS do you use?
I think on Linux you won't get that error. 
Windows is locking files that are used.

**Comment by Rocologo** [comment]
I use Linux but I know that other Windows users gas not reported this problem.

Its correct that windows lock files for writing, i dont think this is the problem because then would other windows users complain alot too.

I do not have a windows test server up and running, so I cant test that senarie at the moment.

**Comment by ArtNRG** [comment]
The server OS is Debian GNU/Linux version 8 (jessie) build 4.9.78-xxxx-std-ipv6-64

**Comment by Rocologo** [comment]
Maybe you should switch to MySQL. Its a real database.

**Comment by ArtNRG** [comment]
https://pastebin.com/raw/tHPuFqBq

Simultaneous NullPointerException and SQLiteException.

**Comment by Rocologo** [comment]
Your server isnt fast enough
