### ISSUE TITLE
npc remove

### ISSUE THREAD

**Issue by anemul** [Rocologo/MobHunting#48]
Just after /mh npc create total_kills AllTime 1 for the first time , I realized I didn't make a pedestal for the NPC , so I tried to do /mh npc remove , but it does not remove , not even if I use npc id . No errors in the console , so it must be something that I am not understanding .

**Comment by anemul** [comment]
Nevermind , but for those having this issue in the future , just stand right as close to npc as possible , then use the command .

**Comment by Rocologo** [comment]
Or rightclick the NPC with a stick to select it. This is standard Citizens feature. Also it doesn't matter if you type /mh npc remove nnn or use the citizens command /npc remove nnn


Sent from Samsung tablet.

-------- Original message --------
