### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ArtNRG** [Rocologo/MobHunting#482]
Hey!
I'm not sure is it OK to post it here, but I have seen the "MH TaskThread" in the attached crash logs. 
Please help me to fix it.

https://pastebin.com/raw/rLSdUcTR
https://pastebin.com/raw/qe6TCvj3
https://pastebin.com/raw/ZaK2ZESH

Paper version git-Paper-564 (MC: 1.13.2)
MobHunting version 6.5.2-SNAPSHOT-B726

**Comment by Rocologo** [comment]
I need to see your server log on startup

**Comment by ArtNRG** [comment]
Sure. Here is the log: https://pastebin.com/raw/gjCbHPrq

**Comment by Rocologo** [comment]
Sorry. I forgot to ask you to enable debug first

/mh debug

This way I get information about which plugins, Mobhunting hook in to.

**Comment by ArtNRG** [comment]
Ok. Here it is: https://pastebin.com/raw/KPvhVNQ3

**Comment by Rocologo** [comment]
I cant see any errors :-(, but inwonder why you have disabled worldguard integration?

[22:54:35] [Server thread/INFO]: [MobHunting] Compatibility with WorldGuard is disabled in config.yml

**Comment by ArtNRG** [comment]
A lot of plugins are trying to hook into the worldguard and that plugins are maintained differently. Some of them need an older version of worldguard and some needs newer. I tired from choosing what I want more - the new features and bug fixing in some plugins in one pocket and the stable operating of other plugins in another pocket so I turned off that integration in every plugin where I actually don't use it.

**Comment by Rocologo** [comment]
Ahh. okay, its not a problem I just wondered. 

Ig Worldguard integration is enabled your players will not get rewards for killing mobs if the region has mob-damage deny

**Comment by Rocologo** [comment]
I see why you think it is MobHunting

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 9559  org.sqlite.core.NativeDB.column_int(JI)I (0 bytes) @ 0x00007f04da9539d8 [0x00007f04da9539a0+0x38]
J 103887 C2 org.sqlite.jdbc3.JDBC3ResultSet.getInt(I)I (22 bytes) @ 0x00007f04e0088fb8 [0x00007f04e0088f40+0x78]
j  org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(I)Z+2
j  org.sqlite.jdbc3.JDBC3ResultSet.getBoolean(Ljava/lang/String;)Z+6
J 74943 C1 one.lindegaard.MobHunting.storage.DatabaseDataStore.loadPlayerSettings(Lorg/bukkit/OfflinePlayer;)Lone/lindegaard/MobHunting/PlayerSettings; (221 bytes) @ 0x00007f04e055e50c [0x00007f04e055de60+0x6ac]
j  one.lindegaard.MobHunting.storage.asynch.PlayerSettingsRetrieverTask.run(Lone/lindegaard/MobHunting/storage/IDataStore;)Lone/lindegaard/MobHunting/PlayerSettings;+12
J 101957 C1 one.lindegaard.MobHunting.storage.asynch.PlayerSettingsRetrieverTask.run(Lone/lindegaard/MobHunting/storage/IDataStore;)Ljava/lang/Object; (6 bytes) @ 0x00007f04dff48c0c [0x00007f04dff48b80+0x8c]
j  one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run()V+82
v  ~StubRoutines::call_stub

I can see that the crash happended while MobHunting was trying to read playersettings from the database. Maybe there is a problem with the player? Check if this only happens with one specific player or all your players? If only one player I would try to open the the database and rename the player UUID (while the player is offline) and the ask the player to login again and see if the fixes the problem.

**Comment by ArtNRG** [comment]
Ok, I will check it.
By the way, is there some way to move the data into MySQL database without losing something?

**Comment by Rocologo** [comment]
Sorry, I have never made a conversion tool.... Create at seperate ticket on this and I will make it one of these days :-)

**Comment by ArtNRG** [comment]
The separate ticket is created: https://github.com/Rocologo/MobHunting/issues/483

**Comment by Rocologo** [comment]
I did not notice that it was you had the SQL_BUSY error. I am pretty sure these two tickets is connected. 

You have to investigate what it is that lock your database, it is not the plugin. I cant tell what it is. Maybe a conflict with another plugin??? I have no other users which has the same problem. If it is a conflict and you can find the plugin we might be able to fix the issue.

I think the SQL_BUSY error is the root cause for your server crash. 

Sorry that I cant help you better...

**Comment by ArtNRG** [comment]
The server is crashed twice today while loading user data from MH database. The players are common guys that playing often, other logins of that players were ok.
The MH database is used by MH only. Is it possible that some thread was locked and become a "zombie process" after the server restart?

**Comment by Rocologo** [comment]
If it was something in the plugin while loading playerdata, other users would had the problem too. 

Most of the other serverowners use sqlite so it is well tested. I use mysql myself and have no problems???

**Comment by Rocologo** [comment]
You have SO many plugins which I dont know, maybe your server has problems. Your should try to run "/timings" to check your server for timings problems.

**Comment by ArtNRG** [comment]
There are some performance problems but I can't see the reason in timings: https://timings.aikar.co/?id=714beec98564491e8d0d9f74de633faf#plugins

**Comment by Rocologo** [comment]
I would start disabling the "red ones" and complain to the developers: Wild, MyWarp, EntityDetection these three is responsible for lag on your server. You should think about the yellow ones too: MobOptimizier (I dont know what it optimizes - but it can give you some lag), ChatControl, Confiscate, AutoMessage

WorldEdit is yellow to, but I would not disable that plugin, its a must on most servers, but be aware of how many blocks you allow the players to move/copy/manipulate it can create lag.

As you see in the list MobHunting does not create lag. 

You have a BIG number of plugins, and if your server is not fast enough this alone can create lag - no matter if the plugins are all fine.

**Comment by Rocologo** [comment]
Can I close this one?

**Comment by ArtNRG** [comment]
Yep
