### ISSUE TITLE
Console error message

### ISSUE THREAD

**Issue by Zoneman1972** [Rocologo/MobHunting#485]
Hey Rocologo,

I have 1 player who likes to put bounties on other players and every time they log in I get the following error in the console.

https://pastebin.com/0CYxCJT1

This has only started happening with the last update.

**Comment by Rocologo** [comment]
I have not changed anything in the bounty methods for very long, so it not related to latest release.

I have made a fix for this bug in next release.

**Comment by Rocologo** [comment]
No answer
