### ISSUE TITLE
MH Bounty Admin Exempt Permission addition request

### ISSUE THREAD

**Issue by Zoneman1972** [Rocologo/MobHunting#486]
Hi there,

Can you please add a permission node to allow me to add players/Admins to be exempted from having player bounties applied to them?
As it stands, when players put a bounty on my admins, when the admin logs in in vanish mode, mobhunting still announces that they have a bounty on them, therefore alerting the other players that the admin is actually online.
Thanks

**Comment by Rocologo** [comment]
HI Zoneman

If the player is vanished with Essentials or VanishNoPacket the message will not be broadcasted. Do you use another plugin?
`if (n > 0 && hasOpenBounties(player)) {
					plugin.getMessages().playerSendMessage(player,
							plugin.getMessages().getString("mobhunting.bounty.youarewanted"));
					if (!EssentialsCompat.isVanishedModeEnabled(player)
							&& !VanishNoPacketCompat.isVanishedModeEnabled(player))
						plugin.getMessages().broadcast(plugin.getMessages()
								.getString("mobhunting.bounty.playeriswanted", "playername", player.getName()), player);
				}`

**Comment by Zoneman1972** [comment]
Yes I do use VanishNoPacket, but it is still announcing a message when I
have a bounty even when I log in in vanish mode.
I have attached a screenshot to show you the messages I get when I log in
http://prntscr.com/nc57nc

And this one from the players view
http://prntscr.com/nc5ahj

Thanks for looking into this.

**Comment by Rocologo** [comment]
hmm, yes I see. The second one should not apear... Please check if you you have disabled integration to VanishNoPacket in config.yml and please check the server log on restart use "/mh debug"  and check if MobHunting hookes in to VanishNoPacket on server start.

**Comment by Rocologo** [comment]
no answer
