### ISSUE TITLE
MobHunting and BossShopPro

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#490]
Hi, I'm doing tests with version 1.4. And something curious happens to me. With the plugin https://www.spigotmc.org/resources/bossshoppro-the-most-powerful-chest-gui-shop-menu-plugin.25699 (it is paid and is updated to version 1.4) when writing / shop the store works correctly but mobhunting indicates the following error: https://pastebin.com/eKhJYW29

Spigot version: CraftBukkit version git-Spigot-1eece4f-84400e6 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT

thanks and regards

**Comment by Mundo-Minecraft** [comment]
solved in the version MobHunting v6.5.4-SNAPSHOT-B778

Thank you

**Comment by Rocologo** [comment]
You shold not use build778, upgrade to newest build
