### ISSUE TITLE
Dropped gold should not be picked up in spectator

### ISSUE THREAD

**Issue by Maximvdw** [Rocologo/MobHunting#493]
Bags of gold can currently be picked up by spectators. This should be a disabled or configurable behavior.
Scenario 1: A mod/admin following a player in spectator (invisible) will give away his/her location
Scenario 2: Minigames or combat tournaments with spectators. The spectators can simply steal the earnings from the people in combat

**Comment by Rocologo** [comment]
I have made a fix in newest version 6.5.6 where players is denied to pickup BagOfGold items when in Spectator mode. I hove this solves the problem. Please confirm.

**Comment by Maximvdw** [comment]
Gonna test is asap, will let you know the results

**Comment by Rocologo** [comment]
I had to do some changes. Please check again.

**Comment by Rocologo** [comment]
check V6.5.7

**Comment by Rocologo** [comment]
Fixed
