### ISSUE TITLE
Mob heads dupe(s)

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#495]
Method 1)

Whenever you use the fortune enchant to break heads from MobHunting, you'll get double the heads.

Method 2)

This one is a bit harder to reproduce, but it works.
For example, drop 3 heads, pick them back up, you'll receive 7.

When I first dropped one head, it showed the head name, when I dropped another, the name changed into 0,00 (as money) and when I picked it up, I got way more heads.

**Comment by Rocologo** [comment]
I dont know Fortune enchant? Is this a plugin or a standard enchantment? (Remember I dont play that much minecraft :-) ) Could you give me the link to the plugin you use, so I can test on my own test-server.

**Comment by Sikatsu** [comment]
We don't use any plugin enchants, only minecraft enchantments.

I also don't play minecraft a lot, so i'll just quote my players:

The Fortune enchantment increases the block drops from mining. For example, with the Fortune enchantment you will have a better chance of getting flint from gravel or an apple from a tree.

**Comment by Rocologo** [comment]
I guess I have to learn how to make that enchantment then :-)

**Comment by Sikatsu** [comment]
You can use essentials /enchant command to give it to yourself and test ^^

**Comment by Rocologo** [comment]
thanks :-)

**Comment by Rocologo** [comment]
I have tested the enchantment problem on my test-server using MC 1.14. At first Essenmtials throw an error, so I updated to newest version. 

https://ci.ender.zone/job/EssentialsX/

And this fixed the problem on my test-server. could you please check if Essentials is updated?

**Comment by Sikatsu** [comment]
I'm using the latest version of essentials for 1.13.2, also, what does essentials have to do with the issue? That's just an easy way to get the enchant to test the issue, the issue is also there without essentials.

**Comment by Rocologo** [comment]
Well, I enchanted a shovel and broke a Mobhunting head and then Essentials threw an error, which cause a problem in MobHunting

I will test on MC 1.13.2 too.

**Comment by Rocologo** [comment]
I have tested on 1.13.2 too and after updating Essentials I cant get any errors. Please try updating Essentials if you still have problems when you use an enchanted items to break a MobHunting head.

The problem merging MobHunting reward heads is fixed in newest build

https://fractal.lindegaard.one:8181/job/MobHunting/792/

**Comment by Sikatsu** [comment]
Can't reproduce it now. The 2 players that reported that one are not online currently.
I'll test the new version soon when I restart the server. (unless mobhunting works with plugman?)

**Comment by Rocologo** [comment]
I should work with plugman, but it long time since i tested that

**Comment by Sikatsu** [comment]
Seems fixed!

**Comment by Rocologo** [comment]
Thanks :-)
