### ISSUE TITLE
1.13.2 Mobs or Players wont drop heads OR bag of gold on death.. 

### ISSUE THREAD

**Issue by Jxsten** [Rocologo/MobHunting#497]
I noticed that mobs weren't dropping heads or any bags of gold when dying. I spawned tons of spiders and killed them all, none dropped anything but their natural loot (which I didn't realize I had to turn on in the config..) I then went into the config, and put that the spiders will drop both head and money. (chance: 1.0). They still don't drop any skulls or money.. This is occurring on spigot-1.13.2.jar, Mob hunting MobHunting-6.5.6.jar and BagOfGold-2.5.7.jar

note: Yes, I've  made sure everything was enabled too.

**Comment by Rocologo** [comment]
Please enable debug using "/mh debug" kill a mob and let me see the out in the server console. (and any errors if an error has been thrown)

**Comment by Jxsten** [comment]
Err, so i before I put just mobhunting in, and it wasn't working. After finding that it didn't work I put the bag of gold plugin in, and it still didn't work. I decided to take them both out, restart my server, then stopped my server. I then put them back into the server at the same time and then it started to work. 


I do want to suggest something. You should inform that natural drops from mobs are automatically disabled. 

Thank you for your time.

**Comment by Rocologo** [comment]
Hi again.

I dont remove natual drops unless, the player "cheats" (ex kill a mob where he is protected against damage) but you can configure this behavior in the config.yml. 

if you enable debug you will get the information in the server console, when a player kills a mob, and you will be able to see the reason for not getting a reward

if the player enable learn mode (/mh learn) the player will get a message telling him why he did not get a reward for killing a mob

So I think I AM telling this to you and the players ;-)

Feel free to suggest new features
