### ISSUE TITLE
Gringotts plugin problem (Not dropping/getting money from mobs)

### ISSUE THREAD

**Issue by Civok** [Rocologo/MobHunting#499]
Hello, I'm using Spigot 1.13.2 and ran into this problem when trying to combine Gringotts and MobHunting. No mobs are dropping money on kill. 
**Versions:**
_Gringotts v2.11.0-SNAPSHOT_
_MobHunting 6.5.6_
_Vault 1.7.2_

**Console:**
12.05 00:27:09 [Server] INFO [MobHunting][Debug] ======================== New kill ==========================
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Civok_3_Tears killed a Enderman (Minecraft)@(world1_the_end:263,49,2)
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Permission 'mobhunting.mobs.*' or 'mobhunting.mobs.ENDERMAN' not set, defaulting to True.
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Basic Prize=36.30 Emeralds for killing a Enderman
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Checking if player is grinding within a range of 15.0 blocks
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Area is whitelisted. Grinding not detected.
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Multiplier: Sneaky! = 2.0
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Civok_3_Tears has no Rank Multiplier
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Killstreak=48, level=4, multiplier=4.0
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Reward rounded to 290.41
12.05 00:27:09 [Server] INFO [MobHunting][Debug] RecordAchievement: hunting-level2-enderman has 142 kills
12.05 00:27:09 [Server] INFO [MobHunting][Debug] RecordKill: Civok_3_Tears killed a Enderman (Minecraft) Cash=290.41 Emeralds
12.05 00:27:09 [Server] INFO [MobHunting][Debug] Description to be send:You killed a Enderman
12.05 00:27:09 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v6.5.6
12.05 00:27:09 [Server] INFO org.bukkit.event.EventException: null
12.05 00:27:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:573) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(SourceFile:61) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.EntityEnderman.damageEntity(EntityEnderman.java:251) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1069) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1343) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1856) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
12.05 00:27:09 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
12.05 00:27:09 [Server] INFO Caused by: java.lang.IllegalAccessError: tried to access field org.gestern.gringotts.Configuration.currency from class one.lindegaard.MobHunting.rewards.RewardManager
12.05 00:27:09 [Server] INFO at one.lindegaard.MobHunting.rewards.RewardManager.dropMoneyOnGround_RewardManager(RewardManager.java:362) ~[?:?]
12.05 00:27:09 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1588) ~[?:?]
12.05 00:27:09 [Server] INFO at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
12.05 00:27:09 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
12.05 00:27:09 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
12.05 00:27:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.05 00:27:09 [Server] INFO ... 22 more

**I'm adding both config files as well if you want to have a look:**

[config Mobhunting.txt](https://github.com/Rocologo/MobHunting/files/3169945/config.Mobhunting.txt)

[config Gringotts.txt](https://github.com/Rocologo/MobHunting/files/3169946/config.Gringotts.txt)

Thank you very much for the help and keep up the good work!

**Comment by Civok** [comment]
**Update**

Tried to reinstall both Gringotts and MobHunting, money (Emeralds in this case) still doesn't work as _drop_money_on_ground: true_ 
but when I try _drop_money_use_item_as_currency: true_, then I normally get Money (Emeralds) into the vault chest.

**Console:**
12.05 16:56:26 [Server] INFO [MobHunting][Debug] ======================== New kill ==========================
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Civok_3_Tears killed a Enderman (Minecraft)@(world1_the_end:263,49,2)
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Permission 'mobhunting.mobs.*' or 'mobhunting.mobs.ENDERMAN' not set, defaulting to True.
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Basic Prize=26.17 for killing a Enderman
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Checking if player is grinding within a range of 15.0 blocks
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Area is whitelisted. Grinding not detected.
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Multiplier: Sneaky! = 2.0
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Civok_3_Tears has no Rank Multiplier
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Killstreak=41, level=4, multiplier=4.0
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Reward rounded to 209.36
12.05 16:56:26 [Server] INFO [MobHunting][Debug] RecordAchievement: hunting-level3-enderman has 436 kills
12.05 16:56:26 [Server] INFO [MobHunting][Debug] RecordKill: Civok_3_Tears killed a Enderman (Minecraft) Cash=209.36
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Description to be send:You killed a Enderman
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Civok_3_Tears got a reward (209.36)
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Command to be run:give Civok_3_Tears Iron_ingot 1
12.05 16:56:26 [Server] INFO Unknown item 'minecraft:'
12.05 16:56:26 [Server] INFO ...k_3_Tears Iron_ingot 1<--[HERE]
12.05 16:56:26 [Server] INFO [MobHunting][Debug] Did not drop a head: random(0.42480233917274823)>chance(0.33)
12.05 16:56:26 [Server] INFO [MobHunting][Debug] ======================= kill ended (37)=====================

**Comment by faelfreitas** [comment]
I have the same problem!

**Comment by Rocologo** [comment]
I have looked at the problem. I have to speak to the dev of gringotts to solve this issue. I hope he wants to help. He has changed something in his latest version.

**Comment by Rocologo** [comment]
I think this is fixed in V6.5.9 - The Emeralds was dropped on my test-server.
