### ISSUE TITLE
Spectator gamemode no longer working

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#501]
Hey,

I've upated from 6.5.5 to the devbuild for the mobhead dupe fix and now the spectator mode is no longer working, you can't move.

I've debugged for the past hour removing plugins that I updated yesterday and found out MobHunting is the cause. Using 6.5.5 this issue is not there.

**Comment by Rocologo** [comment]
I hope this is fixed in V6.5.7

**Comment by Sikatsu** [comment]
Will test in the morning. ~12 hours from now.

**Comment by Rocologo** [comment]
Please let me know if I solved this one.

**Comment by Sikatsu** [comment]
It's not solved sadly.

**Comment by Rocologo** [comment]
Fixed in v6.6.0 I hope :-)

**Comment by Sikatsu** [comment]
Will test soon and let you know!

**Comment by Rocologo** [comment]
Sorry for these bugs, its very hard to test all combinations of Mc 1.13.2 , 1.14.1 and with or withou BagOfGold and MobHunting - and then all the different configuration options.

**Comment by Sikatsu** [comment]
That's alright, i'll let you know once I tested it.

**Comment by Sikatsu** [comment]
This one is fixed :)

**Comment by Rocologo** [comment]
thanks.
