### ISSUE TITLE
Happy Hour time remaining command

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#506]
Hey,

Could you add a command that players can use to see the remaining happyhour time within the chat? The output of the command should be personal, unlike /mh happyhour which shows it for the whole server.

**Comment by Rocologo** [comment]
Its a good idea! I will make it.

**Comment by Rocologo** [comment]
What should the exact message to the player be?

**Comment by Sikatsu** [comment]
Happy Hour time remaining: %time%

Not too sure, english isn't my native language haha

**Comment by Rocologo** [comment]
I have the same problem :-)

Im testing with:

mobhunting.commands.happyhour.ongoing=§5Happy Hour is onging for ${minutesleft}.

_

**Comment by Sikatsu** [comment]
Not too sure about ''ongoing'', maybe ''Happy Hour will remain activated for ${minutesleft}.''?

**Comment by Rocologo** [comment]
hmm :-) I dontlike activated

What about : There is Happy Hour for the next 30 minutes

**Comment by Sikatsu** [comment]
Yeah wasn't too sure about activated either.

Happy Hour still lasts for 30 minutes
Happy Hour will remain active for 30 minutes

I mean, in the end it's your decision as a user can change it to his/her liking anyway :)

**Comment by Rocologo** [comment]
Where should I write the message?

1) playerchat
2) actionbar
3) as a title?

**Comment by Rocologo** [comment]
I think I have found a solution wait 10 minutes and you can test :-)

**Comment by Sikatsu** [comment]
I would say in the chat, or make it configurable.

**Comment by Rocologo** [comment]
I chose same style as the other messages. I think there is enough configurations in config.yml. Some server owners complain alot :-)

Try this build: https://fractal.lindegaard.one:8181/job/MobHunting/802/

**Comment by Sikatsu** [comment]
Is the command /mh happyhour ?

**Comment by Sikatsu** [comment]
And is it personal? It seems to use the old language lines?

**Comment by Sikatsu** [comment]
./mh happyhour is still server-wide and whenever you login on the server after 10 seconds (quite late) the same thing happens server-wide too everytime a player logs in.

**Comment by Sikatsu** [comment]
I still think a chat message would be better anyway, immediatly on login. Instead of a big title, looks quite messy in my opinion.

**Comment by Rocologo** [comment]
I tried that, the problem is that the message scrolled up, so the player could not see it. 

I will see what I can do.

**Comment by Sikatsu** [comment]
That's probably why most plugins with MOTD-like features have the delay configurable, in my case it would be immediatly visible, for other servers with lots of text it wouldn't be.

**Comment by Rocologo** [comment]
I have moved the message to the chat and delayed it 10 sec.

https://fractal.lindegaard.one:8181/job/MobHunting/803/

**Comment by Rocologo** [comment]
I have often thought about making a kind of scheduler, where Happy Hour event can be scheduled

**Comment by Sikatsu** [comment]
I'm using my console to schedule happy hours ^^

Is the command /mh happyhour personal now? Or is it still server-wide?

**Comment by Sikatsu** [comment]
The delay is still pretty big, no way to configure it? I would like to show it above my MOTD. http://prntscr.com/npj8l3

I think we're working on a feature from a different issue then this one here btw.

**Comment by Rocologo** [comment]
Its worldwide. There is currently no permission node for players to use. 

I have only the permission node for admins "mobhunting.happyhour" 

But maybe that is okay?

**Comment by Sikatsu** [comment]
Well, this issue we're talking in now is about a feature for players to use /mh happyhour and get a PERSONAL (not server-wide!) message in their chat.

**Comment by Sikatsu** [comment]
Also about the reminder:

1) Could the delay be configurable?
2) The time is not correct, it keeps saying 60 minutes (http://prntscr.com/npj9y9)

**Comment by Rocologo** [comment]
I dont know how to place the message in your MODT???

**Comment by Sikatsu** [comment]
If you make the delay configurable, I could set it to like 1 second, my MOTD is set to 2 I believe, so then it will show up above my MOTD.

**Comment by Sikatsu** [comment]
To be clear:

Reminder feature when a player logs in:

1) Could the delay become configurable instead of hard-coded 10 seconds?
2) The time seems to be behind on the /mh happyhour command

Command feature for players to see how much time remaining:

1) /mh happyhour should be personal, not server-wide
2) It should show a message in the chat with the time remaining.

**Comment by Rocologo** [comment]
1) Its rather easy to make the delay configurable, the problem is where to place this setting in the config.yml. Im afraid that it will drown in all the other settings - as there is currently no other "Happy hour section".

2) The "/mh happyhour" was originally made for admins, which wanted to tell the player about the event. But since this is announced when the player joins, I guess that it can be made personal and only used by admins then.

**Comment by Sikatsu** [comment]
1. Not sure where exactly it would fit, but it would be really nice if you can make it configurable, 10 seconds seems quite much at the moment.

2. I understand where the intentions of /mh happyhour where for, however, players would prefer a personal command to use so they can check how long it lasts whenever they want.

**Comment by Rocologo** [comment]
I need to make a mobhunting.happyhour.admin permission node then. (To start / stop / restart the happy hour).

**Comment by Sikatsu** [comment]
Sounds right, and then mobhunting.happyhour for players to use /mh happyhour and see the remaining time for themselves.

I love the happy hour system in this plugin, some more love to it is welcome :D

**Comment by Rocologo** [comment]
You got your Happyhour section in config.yml and a new permission node "mobhunting.happyhour.admin"

Please help me with the testing.

https://fractal.lindegaard.one:8181/job/MobHunting/804/

I need to go to bed now... :-)

**Comment by Sikatsu** [comment]
I'll test now, goodnight though ^^

**Comment by Sikatsu** [comment]
It says Bounty Settings instead of Happy Hour Settings: http://prntscr.com/npjyjw

Definatly an issue here: http://prntscr.com/npk0ce

First message is the login-reminder, second is from /mh happyhour. The time is not the same.

**Comment by Sikatsu** [comment]
After the happy hour, there was no title message saying it ended.

When using /mh happyhour it says: http://prntscr.com/npk2oo

**Comment by Rocologo** [comment]
I guess I was to tired when I made the last changes.  Laptop is closed, I will fix it in the morning.

**Comment by Sikatsu** [comment]
No worries, for now I can't find more issues.

**Comment by Rocologo** [comment]
Godmorning... here is the new build: https://fractal.lindegaard.one:8181/job/MobHunting/805/

**Comment by Sikatsu** [comment]
Will test it soon again!

**Comment by Sikatsu** [comment]
All fixed!
