### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by arizrain1** [Rocologo/MobHunting#51]
Can you please help me with this.  Love the plugin, but its crashing us with this.    https://www.zerobin.net/?1a672e6bcfd19404#R8jKmeWPstKLTMd5Njvx/yXd33VvozcVqKmaRirRCJw=

we are version 1.9.2 spigot

**Comment by arizrain1** [comment]
https://www.zerobin.net/?1a672e6bcfd19404#R8jKmeWPstKLTMd5Njvx/yXd33VvozcVqKmaRirRCJw=

**Comment by arizrain1** [comment]
https://www.zerobin.net/?bfadbbb8ac53157e#Zf4qaeQFUk2vlhLZjQesaRPhtr7Rcw1FP6Mhvn7pzfg=


The plugin seems to be working.... but the console is a mess :s

**Comment by Rocologo** [comment]
fixed in v3.1.3
