### ISSUE TITLE
Grinding penalty slimes / magma cubes

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#511]
Players are annoyed by the grinding penalty on slimes / magma cubes. 

Is this something that can be solved or improved?

**Comment by Rocologo** [comment]
The "problem" is the splitting nature. At the moment the problem is solved by allowing them to kill 2x mobs when it is slimes/magma cubes.

**Comment by Sikatsu** [comment]
And how do I do that exactly?

**Comment by Rocologo** [comment]
In sorry you cant change that. It's hard to tell which method is best for slimes and magma cubes

**Comment by Darcion** [comment]
in mythicmobs you can change vanilla mobs, here you can prevent them to split. maybe a feature for mobhunting?

**Comment by Rocologo** [comment]
MobHunting does not change any mob or how they act. MobHunting only pay a reward for killing the mob, if theplayer does not cheat. 

So no, I dont want to add a feature preventing the slimes to split.
