### ISSUE TITLE
PlaceholderAPI (New method) for 1.12.2 updates/support

### ISSUE THREAD

**Issue by Someone-NEW** [Rocologo/MobHunting#514]
Here we go, just like you say i open new ticket for this problem, i hope you can and will update it

@Rocologo I just paste here to inform you while PlaceholderAPI will be updated to new final system AND we used 1.12.2 server version i will be realy happy if you can support this old version with new updates too, for example now this: [21:56:52 WARN]: [PlaceholderAPI] MobHunting is currently using a deprecated method to hook into PlaceholderAPI. This will be disabled after the next update. Please consult [Rocologo] and urge them to update it ASAP.

Im using now realy old version without any new fixes and update to be work with that 1.12.2 version, now we need PlaceholderAPI update, thank you very much.

**Comment by Rocologo** [comment]
Hi I became sick this weekend. :-( but from your point of view it was good. I have spend 2 hole days in bed - while adding support for Minecraft 1.12.2 in Version 6.6.8 

I have tested against 1.12.2 for hours but I warn you! The are rather many changes from 5.7.3 to 6.6.8 so you MUST make a backup of the MobHunting folder (and the BagOfGold folder if you use BagOfGold) and if you use MySQL you should make a backup of the MobHunting/BagOfGod tables as well.

If you have a test server, you should start there.....

**Comment by Rocologo** [comment]
PS. Create a new ticket if you find bugs (when)
