### ISSUE TITLE
Remove the REALLY ANNOYING "You killed a §1{killed}"

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#515]
I removed every instance of "You killed a §1{killed}", why on earth is there a message every time you kill a mob? this is SOOOO annoying. But each reboot its just overwriting my configs and putting the message back!!!
Im using 
MobHunting-5.7.3-SNAPSHOT-B685.jar on the latest Paper 1.12.2.

How on earth do I stop these messages showing each time you kill a mob?

**Comment by Rocologo** [comment]
Instead of deleting lines in the config files you must   use two '

Like 

Message: ''

**Comment by FrozenBeard** [comment]
Ah! Let me give this a try, its driving all my users insane.

**Comment by Rocologo** [comment]
You have also a /mh mute command
