### ISSUE TITLE
Startup hangs on 1.14.2

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#516]
Might be related to my configuration, but how to fix?

https://pastebin.com/j3Dy7h8s

**Comment by Rocologo** [comment]
I have only tested with EssentialsX

**Comment by Sikatsu** [comment]
That is essentialsX, don't think it has to do with essentials though. The server just refuses to boot further, I am forced to remove the jar to boot the server. There is definatly something wrong that I hope we can find a fix for soon.

**Comment by Sikatsu** [comment]
This is on paper 1.14.2, nor 6.6.1 or 6.6.3 worked.

Paper link: https://papermc.io/

**Comment by Sikatsu** [comment]
It works fine on 1.13.2, only happens on 1.14.2. Hoping for a fix so we can have happy hour again :)

**Comment by Sikatsu** [comment]
Removing rewards.yml fixed this issue.. odd though

**Comment by Rocologo** [comment]
Hmm... rewards.yml contains all the bags that players had placed in your worlds. Deleting this file will make their bag invalid and have a value of 0. 

I would rather find the bug :-)

**Comment by Sikatsu** [comment]
That's odd, as I don't use bags? Or does it mean all heads from mobs?

**Comment by Rocologo** [comment]
Ah. It also contains all the heads given as a reward,  when they are placed as a block
