### ISSUE TITLE
Option to change the color of {bonuses} placeholder

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#517]
It shows pink by default, but it doesn't fit with my server colour scheme.

http://prntscr.com/nw7sbj

**Comment by Rocologo** [comment]
I think you can change the color in the lang file

bonus.happyhour.name=Happy Hour

to

bonus.happyhour.name=§aHappy Hour

?

**Comment by Sikatsu** [comment]
I tried, but it seems hardcoded.

**Comment by Rocologo** [comment]
You should be able to overrule this

return ChatColor.LIGHT_PURPLE + MobHunting.getInstance().getMessages().getString("bonus.happyhour.name");

**Comment by Sikatsu** [comment]
Well.. it didn't work when I tried, that's odd.

**Comment by Rocologo** [comment]
bonus.happyhour.name=§bHappy Hour

worked fine on my test server

![2019-07-06_20 05 51](https://user-images.githubusercontent.com/1008133/60759695-b1e21d80-a029-11e9-9346-56832d49a573.png)
