### ISSUE TITLE
MobHunting placeholder errors with ChatControl

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#523]
I think there is a small compatibility issue between MobHunting and ChatControl.
I want to display the amount of mobs they killed within ChatControl.

Error log:

https://pastebin.com/t3iABu8q

**Comment by Rocologo** [comment]
I hope this is fixed in next release, but I dont know how to test it.

**Comment by Sikatsu** [comment]
Well, I will test it and let you know ^^
