### ISSUE TITLE
Console error from latest update Version 6.6.9

### ISSUE THREAD

**Issue by Zoneman1972** [Rocologo/MobHunting#524]
Hey rocologo,

I updated MobHunting today and now i'm getting this error everytime someone kills a mob.
http://prntscr.com/o5w453
Cheers,
Zonemann

**Comment by Rocologo** [comment]
HI there

I need the full error text to solve the issue. Incl. "Caused by".... which tells me where in the code the job fails...

**Comment by Rocologo** [comment]
fixed in v6.7.4
