### ISSUE TITLE
fishing event error on MobHunting-6.7.3-SNAPSHOT-B831.jar

### ISSUE THREAD

**Issue by stw222** [Rocologo/MobHunting#528]
[https://pastebin.com/yUsdbf8W](https://pastebin.com/yUsdbf8W)

**Comment by stw222** [comment]
should probably provide more info:

paper-107 1.14.2

plugins:
- actionbar api
- announcer
- arnorstand tools
- async world edit
- better sleep
- buycraftx
- chunk spawner limiter
- citizens
- core protect
- crazy auctions
- discordSRV
- dynmap
- editable signs
- essentialsx
- greifprevention
- head database
- heads plus
- holographic displays
- HorseTPWithMe
- marriage master
- matrix
- mcmmo classic
- mineable spawners
- mob capture
- mobhunting
- multiverse core
- multiverse inventories
- multiverse netherportals
- multiverse portals
- multiverse signportals
- nerf phantoms
- openinv
- permissionsex
- placeholder api
- plot2dynmap
- plotsquared
- protocol lib
- server list plus
- tab
- tempfly
- vault
- voting plugin
- wildernesstb
- world edit
- world guard


config:

[https://pastebin.com/62emSjbG](https://pastebin.com/62emSjbG)

**Comment by Rocologo** [comment]
Jo, i need full error text. Including the lines which say "caused by" they tell me exactly which lines in my code causes the problem.

**Comment by stw222** [comment]
i dont see one for MH, only holographic displays.
here a larger portion of the log: [https://pastebin.com/W17CNj8y](https://pastebin.com/W17CNj8y)

**Comment by Rocologo** [comment]
Are you on a Paper server?

PLease try to disable Achievements in config.yml and let me know the result?

**Comment by stw222** [comment]
yes, we are on paper-107 1.14.2
that is the problem, the error comes when someone gets a reward from killing or fishing. and we do want the reward feature.

 i temporarly disabled it and the action bar setting below it but im still getting an action bar error:

[https://pastebin.com/FWnhLfru](https://pastebin.com/FWnhLfru)

**Comment by stw222** [comment]
i would like to be able to have both enabled though

**Comment by stw222** [comment]
but something needs to be done because we are getting abnormally large log files

**Comment by stw222** [comment]
the server was last restarted about 18 hours ago and we have almost a 12mb log file

**Comment by Rocologo** [comment]
Did you disable achievements?

**Comment by stw222** [comment]
yes i did

**Comment by stw222** [comment]
i updated to the newest mh version, 6.7.4 and i currently dont see any errors. i would still like to see an actual fix eventually instead of just a temporary fix like "disabled achievements on paperspigot servers"

**Comment by Rocologo** [comment]
Well the problem is that PaperSpigot and Advancements API does not work together. Im not the developer of these two so I cant do anything about that. Sorry.

**Comment by Rocologo** [comment]
Said in another way. AdvancementsAPI does ONLY work with Spigot. 

https://github.com/AdvancementAPI/AdvancementAPI/blob/master/src/main/java/io/chazza/advancementapi/AdvancementAPI.java

Because it uses bungee TextComponent.

**Comment by stw222** [comment]
so what do you use it for in this plugin that we will be missing out on?

**Comment by Rocologo** [comment]
I use it to show all the Achivements in the advancements window, but you dont really need it. Your players can get a better view using /mh achievements

I made te Advancements feature on a request, but i prefer /mh achivements my slef

**Comment by Rocologo** [comment]
I use it to show all the Achivements in the advancements window, but you dont really need it. Your players can get a better view using /mh achievements

I made the Advancements feature on a request, but i prefer /mh achivements
