### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by Pwnzeye** [Rocologo/MobHunting#531]
https://pastebin.com/L0WsdZ8H

1.13.2 Paperspigot
When I kill a mob and apparently when mobs spawn (MythicMobs)

**Comment by Rocologo** [comment]
Which version of MythicMobs does you use?

**Comment by Pwnzeye** [comment]
> 
> 
> Which version of MythicMobs does you use?

4.6.1

**Comment by DaLeberkasPepi** [comment]
i get the same errors with [MythicMobs] Loading MythicMobs v4.5.9-2586

![](https://cdn.discordapp.com/attachments/584383851854561292/597534577283563520/unknown.png)

**Comment by Rocologo** [comment]
This is fixed in V6.7.5, which will be released today. Until then you can disable Advancements in config.yml

Advancements is only supported on SpigotMC servers.

**Comment by Rocologo** [comment]
V6.7.5 released
