### ISSUE TITLE
Queue = 1

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#532]
Spigot 1.13.2 final or 1.14.3 latest
MobHunting 6.7.6-SNAPSHOT-B840

Console/log filled with repeats of
```
[08:22:00] [Craft Scheduler Thread - 50/INFO]: Queue = 1
```

**Comment by Rocologo** [comment]
Are you sure this is from mobhunting? It does not look like the debug information  I make?

**Comment by SlimeDog** [comment]
Seems to be, based on isolation of three recently-updated plugins. But if it not identified. :(

I'll run isolation again.

**Comment by Rocologo** [comment]
I might be me, because I have improved the message queue for the action bar messages...

**Comment by SlimeDog** [comment]
I think it's someone else. Apologies.
