### ISSUE TITLE
Weird leaderboard bug?

### ISSUE THREAD

**Issue by SoraShiunin** [Rocologo/MobHunting#533]
On every sign I destroy, I get the message "The leaderboard was removed".
I don't want every sign to be a leaderboard.

**Comment by Rocologo** [comment]
I can not reproduce this problem. It does not happen on my test server. I need more information to solve your issue. 

Do you get any errors in the console?

Any errors in your log when you start the server? 

try enable debug information before you destoy a sign using "/mh debug" and check the console for information, after destroying the sign

**Comment by SoraShiunin** [comment]
No errors. I will try /mh debug.

**Comment by Rocologo** [comment]
do you still have problems with the leaderboards?

**Comment by Waterman1001** [comment]
I can confirm that I have this problem as well.
It happened after I created a leaderboard in my Survival world.
Every sign that is attached to a wall, that I break now gives me the same message 'The leaderboard was removed'. It is kind of annoying haha.
The command I used was: "/mh leaderboard create Total_Kills AllTime".
The leaderboard by the way works just fine.

**Comment by Rocologo** [comment]
Problem identified. I will see if I have time to fix this tonight.

**Comment by Rocologo** [comment]
fixed in next release

**Comment by Rocologo** [comment]
Released
