### ISSUE TITLE
Super annoying "You gained £0!" for EVERY MOB KILL.

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#536]
Another super annoying addition, I updated today hoping all the console spam was gone, but thats another issue.
Today introduced a SUPER annoying message every time you kill a mob "You gained £0!" Why on earth would anyone pay people to kill mobs in the first place? I have this set to 0 on all mobs, there should not be a message at all.
how do I stop this really really really annoying message showing each time you kill a mob?

**Comment by FrozenBeard** [comment]
Jesus Christ this is annoying, how do I turn it off? Every single player is moaning about it. Why would this be a good idea?

**Comment by Rocologo** [comment]
You can't turn it off. It's a bug, it's not meant to be so. I will see if I can find some time tonight and fix this.

**Comment by Rocologo** [comment]
And you can rool 2 versions bag if you prefer that.

**Comment by Rocologo** [comment]
I have simply not tested a kill of a mob with no reward.

**Comment by Rocologo** [comment]
Can you please post your config.yml so I am sure test the same conditions?

**Comment by FrozenBeard** [comment]
God i've not used pastebin over gist in forever:
https://pastebin.com/UgzBeqjL

**Comment by Rocologo** [comment]
I dont mind that you use something else than Pastebin. Its just than some people try to put the config here at Github, which gives a bad result.

I your case i found to two errors in your config.yml 

Check these settings:

```
  # Rounding of rewards when you uses a range or %. (ex creeperPrize=10:30) the reward.
  # All numbers except 0 can be used.
  # Set rounding_reward=1 if you want integers. IE. 10,11,12,13,14...
  # Set rounding_reward=0.01 if you want 2 decimals 10.00, 10.01, 10.02... integers.
  # Set rounding_reward=5 if you want multipla of 5 IE. 10,15,20,25...
  # Set rounding_reward=2 if you want multipla of 2 IE. 10,12,14,16...
  reward_rounding: 0.0
 
  # This is the minimum reward which will which will be paid to the player 0.01 will be fine
  # in most installation, but Gringott users who want very low rewards (like 0.001  for killing
  # a mob) will have to lower the minimum reward. Remember that some multipliers are less than 1
  #  and grinding detection and penalties. The minimum_reward should therefor be less than 10%
  #  of smallest reward. In the Gringotts example minimum_reward should be 0.0001 or 0.00005.
  minimum_reward: 0.0
```
You can NOT set "reward_rounding" down to 0 , I have written this in the text ;-) 

and if you say that "minimum_reward: 0.0" it gives you the result that you complain about - if minimum_reward is 0 the plugin announces the reward EVEN if the reward is 0. You should probably set this to f.ex. "0.01" depending on what currency you use.

**Comment by Rocologo** [comment]
So In this case where you complain about bugs this is actually you who has changed default values to something which will give you problem and your players will complain! 

I cant help you here, change the values to something meaningful.

**Comment by FrozenBeard** [comment]
I don't want to give ANY currency to any players for something as stupid as killing a mob, everything is 0 to try and disable any mention of currency, its such a sketchy thing to do try and reward people for killing mobs.
Im only using this plugin for head drops.

**Comment by Rocologo** [comment]
Well the plugin is a "kill a mob an get a reward" plugin and not a "head drop" plugin. You are the only one who can't understand the minimum thing, and it's you who dont understand because you dont use the plugin as intended. Anyway - In newest release I have decided to test if someone dont understand how it works and set it to 0. 

It was never my intention to make a plugin where you didn't get rewards ;-)

One the problems about the flexibility in this plugin is that it's more than many users can handle.
