### ISSUE TITLE
"Could not pass event PlayerFishEvent to MobHunting v6.8.0"

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#541]
https://pastebin.com/QL1VdENz

On the latest Paper build

**Comment by Rocologo** [comment]
I think you have written a "non number" in chance: in one of the fishes in config.yml?

Please confirm or show me your config.yml?

**Comment by Rocologo** [comment]
I found the bug. The chance must be a string. Check this 
```
    - chance: '0.2'
      message_type: ActionBar
      cmd: give {player} Iron_ingot 1
      message: You got an iron ingot!
```

**Comment by Rocologo** [comment]
Hello?
