### ISSUE TITLE
ERROR Plugin MobHunting v6.8.0 has failed to register events for class one.lindegaard.MobHunting.rewards.MoneyMergeEventListener because org/bukkit/event/entity/ItemMergeEvent does not exist.

### ISSUE THREAD

**Issue by DingoX-YT** [Rocologo/MobHunting#542]
I get this issue when starting up the server. Not sure if it's a server version issue? I'm running 1.8 spigot. Thank you

**Comment by Rocologo** [comment]
Im pretty sure that Item mergeEvent was introduced in MC 1.8 and I dont get this error on my own 1.8 test server. maybe your MC 1.8 build is too old? 

Im using this build:

https://github.com/Rocologo/Main/blob/master/lib/craftbukkit-1.8-R0.1-SNAPSHOT.jar

**Comment by Rocologo** [comment]
Hello???
