### ISSUE TITLE
Grinding detection Problem

### ISSUE THREAD

**Issue by HalcyonAzure** [Rocologo/MobHunting#543]
First of all, thank you for writing such an excellent plugin, but my server recently encountered a bit of BUG, probably as follows:
1. Create an Enderman Farm
2. Open an opening under Enderman Farm and let some Enderman fall into the void.
3. Grinding detection is not activated.

When the opening is closed, the Grinding test will work normally, which may be related to the detection distance?

Also, if assisting killing rewards is enabled and a longer timeout is set, the player only needs to attack the monster once, even if it is killed due to falling void or other non-player reasons, it can still be rewarded. I wonder if a function can be added to detect the final cause of death of the monster is caused by players?XD

**Comment by Rocologo** [comment]
Oh, Its new to me that you can make an Enderman farm. I will have to investigate this. I hope I can find a video on youtube.

I dont detect the distance, I check if the mob dies from fall-damage and the I track how many mobs dies in the same area within a timeframe. 

I will have to check what the Enderman dies of, when it fall into the void.

**Comment by Rocologo** [comment]
I could really need some help making a Enderman farm? are you able to make one and save it as a hole world or as a Worldedit schematic ?

**Comment by HalcyonAzure** [comment]
> I could really need some help making a Enderman farm? are you able to make one and save it as a hole world or as a Worldedit schematic ?
I made an Enderman Farm at End on this map, at - 863 27 - 177.
https://1drv.ms/u/s!AjSD72ei4QKwjTjsFs3EY20JbMv7?e=amVS13

**Comment by Rocologo** [comment]
Thanks. Im testing a fix now! Its not working 100% yet, but Im pretty sure I will find a solution.

**Comment by Rocologo** [comment]
I can now detect the Enderman farm and the Area gets blacklisted automatically. BUT I dont understand how the farm works and how the player harvest pearls? 

I had to improve /mh checkgrinding and /mh cleargrinding as well so I could re-test the auto-blacklisting. 

I hope you can help with the testing?

**Comment by HalcyonAzure** [comment]
> I can now detect the Enderman farm and the Area gets blacklisted automatically. BUT I dont understand how the farm works and how the player harvest pearls?
> 
> I had to improve /mh checkgrinding and /mh cleargrinding as well so I could re-test the auto-blacklisting.
> 
> I hope you can help with the testing?

the principle of the enderman farm I have writen in the map,the Enderman will attack endermite automatically，so when there is an Enderman spawned seeing the endermite,it will rush to it and be hurt by the height,so that the player could hit it easily and get the exp or pearls.The player who has the farm now considers the pearls as a kind of trash, I'm not care about it yet.I'd like to help you with the test,but I don't always have time so It can take a long time for me to give you a response sometimes.

**Comment by Rocologo** [comment]
I have no rush and you are the only one who has asked for this feature - so far. :-)

My time is limited too. I have a family who not always understand the time I can use on coding on my Minecraft plugins. :-) 

As for the farm: If the Enderman does not die from the fall and the player starts to kill the wunded enderman the normal grinding routine should stop the rewards after 10-20 kills and then the spot should be blacklisted. I think this works ?

If the enderman fall into the void, what happens to the peal then? How does the player get the pearls? (He cant go to the void and pick them up) so how does he get the pearls?

**Comment by HalcyonAzure** [comment]
> I have no rush and you are the only one who has asked for this feature - so far. :-)
> 
> My time is limited too. I have a family who not always understand the time I can use on coding on my Minecraft plugins. :-)
> 
> As for the farm: If the Enderman does not die from the fall and the player starts to kill the wunded enderman the normal grinding routine should stop the rewards after 10-20 kills and then the spot should be blacklisted. I think this works ?
> 
> If the enderman fall into the void, what happens to the peal then? How does the player get the pearls? (He cant go to the void and pick them up) so how does he get the pearls?

It seems that I may not have made myself clear.  I'll try to record a video to show the problems I have encountered. Besides, as a Minecraft player and a server owner, I appreciate and understand the time you spent on Minecraft: -D

**Comment by Rocologo** [comment]
V6.8.2 contains ender man farm detection. I have troet to limit The spamming with debug info when a farm is detected,  but it is hard.
