### ISSUE TITLE
Could not pass event MythicMobSpawnEvent to MobHunting v6.8.0

### ISSUE THREAD

**Issue by develephant** [Rocologo/MobHunting#546]
Stack trace: [https://pastebin.com/rEJwdKEs](url)

**Comment by Rocologo** [comment]
Which version of Mythic Mobs do you use?

**Comment by develephant** [comment]
Hi. I am using this version [Mythic Mobs](https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/)

**Comment by Rocologo** [comment]
That is the Free V4.6.5 I assume?

I will test this version on my test server.

**Comment by Rocologo** [comment]
Hmm. I can reproduce this. I tried to kill a SkeletalKnight, but I didnt get any errors. Do you know which mobs has been killed? Is it an custom mob or one of the standard mobs?

**Comment by Rocologo** [comment]
And please show me a few lines from the serverlog just before the error happens?

**Comment by Rocologo** [comment]
Problem found and fixed in next release

**Comment by Rocologo** [comment]
Released

**Comment by develephant** [comment]
Thanks!
