### ISSUE TITLE
Could not pass event BlockPhysicsEvent to MobHunting v6.8.2

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#551]
Console error: https://pastebin.com/gQd7yBKS

Config: https://pastebin.com/X7DXNFsS

**Comment by Rocologo** [comment]
I need the last part of the error, beginning with cause by .... it tells me the linenumbers where the problem is.

**Comment by Weasel-Beans** [comment]
I updated the paste of the error, is that good?

**Comment by Weasel-Beans** [comment]
My server has crashed twice today, and I think the last time it was from this error. I've updated the paste with the errors during the crash

**Comment by Rocologo** [comment]
Yes I see. It's looks like some kind of loop which can make the server crash. 

What did  you do to start this error?

**Comment by Rocologo** [comment]
Also try to enable debug to give me more information 

/mh debug

**Comment by Rocologo** [comment]
I might have found a solution (i still dont understand how you ended up in this situation)

Please test V6.8.5

**Comment by Weasel-Beans** [comment]
Okay I've updated my server, I have no idea what triggers it though, since it doesn't happen that often. It usually doesn't lead to a crash either. I'll let you know if I see it again

**Comment by Rocologo** [comment]
Okay, I wait some days and then I close the ticket if you dont see the bug again. I you see the bug later the ticket can be re-opened
