### ISSUE TITLE
Error on use /mobhunt achievements

### ISSUE THREAD

**Issue by YuriNMDS** [Rocologo/MobHunting#552]
`18.08 08:03:43 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66)
18.08 08:03:43 [Server] ERROR com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:130)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
18.08 08:03:43 [Server] ERROR sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
18.08 08:03:43 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
18.08 08:03:43 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
18.08 08:03:43 [Server] ERROR sun.net.NetworkClient.doConnect(NetworkClient.java:175)
18.08 08:03:43 [Server] ERROR java.net.InetSocketAddress.<init>(InetSocketAddress.java:220)
18.08 08:03:43 [Server] ERROR java.net.InetAddress.getByName(InetAddress.java:1077)
18.08 08:03:43 [Server] ERROR java.net.InetAddress.getAllByName(InetAddress.java:1127)
18.08 08:03:43 [Server] ERROR java.net.InetAddress.getAllByName(InetAddress.java:1193)
18.08 08:03:43 [Server] ERROR java.net.InetAddress.getAllByName0(InetAddress.java:1277)
18.08 08:03:43 [Server] ERROR java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
18.08 08:03:43 [Server] ERROR java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
18.08 08:03:43 [Server] ERROR java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
18.08 08:03:43 [Server] ERROR Stack:
18.08 08:03:43 [Server] ERROR PID: 34 | Suspended: false | Native: true | State: RUNNABLE
18.08 08:03:43 [Server] ERROR Current Thread: Server thread
18.08 08:03:43 [Server] ERROR ------------------------------
18.08 08:03:43 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
18.08 08:03:43 [Server] ERROR ------------------------------
18.08 08:03:43 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
18.08 08:03:43 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-172 (MC: 1.14.4) ---`

This happens when you use the command for the first time.

**Comment by Rocologo** [comment]
I cant replicate the problem. I have made a server from scratch but I got no crash. I think you have had some kind of network problem. or something. Do you still have this error or was it a one time error?

**Comment by YuriNMDS** [comment]
Well, i blocked the command for the players, this still have, my database don't is in MySQL, it's MariaDB, maybe this is the problem?

**Comment by Rocologo** [comment]
I dont know, I have never used MariaDB, but the error text look more like it is a communication problem with some Minecraft servers (YggdrasilAuthenticationService).
