### ISSUE TITLE
Heads pop when a block updates beside them

### ISSUE THREAD

**Issue by Busted11290** [Rocologo/MobHunting#553]
Heads placed down as decorations are popping off when a block update happens beside them.  

Replicating:
Place the head down then place anything beside them except another head and the head will get dropped.  Or any block updating such as a noteblock being played, furnace update, opening a chest, etc...

No errors are in console log.  I am not sure what is causing this.

**Comment by Rocologo** [comment]
Thank you for the report. If I can replace this (and the description seems clear to me) then I can fix this.

**Comment by Rocologo** [comment]
Please help with testing

I have tried to test Flowing water, Furnace, Piston, Redstone, Nodeblock, Presure plate. They all seems to work now.

https://fractal.lindegaard.one:8181/job/BagOfGold/335/

**Comment by Busted11290** [comment]
Is BagOfGold required for this to work on MobHunting?  I had seen it was optional, I am not using any economy parts of it, just wanted the heads for players to gather and trade.

Using MobHunting on Paper with EssentialsX.

**Comment by Rocologo** [comment]
BagOfGold is an Economy Plugin. MobHunting is not. If you dont use the BagOfGold plugin the players will get bags which the can sell using bagofgold signs before they get their money for the kill.

I think it's more fun to use the BagOfGold plugin so the bags ARE your money. But it's up to you.

**Comment by Rocologo** [comment]
The two.plugins is not dependent on each other but they do of cause work together

**Comment by Rocologo** [comment]
I assumed that you were using bagofgold, but you can test on newest MobHunting build too. I have made the same changes in MobHunting as I did in bagofgold

**Comment by Busted11290** [comment]
Seems to be working now with the new Build #913.
