### ISSUE TITLE
lore edit issue

### ISSUE THREAD

**Issue by mechcalvin** [Rocologo/MobHunting#558]
Hello, been using this for a long time, however is it possible to setup log when player exchange their bag of money using sign? I have players use change lore method to edit the bag of gold and exchanged over 1 trillion amount of money, i need to close my server to shut down this bug

**Comment by Rocologo** [comment]
I have added a Hash value to the BagOfGold which makes it harder to chnage the value. BUT it is not 100% safe. 
OBS. You should Install ProtocoLib (https://www.spigotmc.org/resources/protocollib.1997/)  before you install the new version. This your players CANT see the hidden Lores and it makes it very very hard to chnage the vakue.

**Comment by Rocologo** [comment]
https://fractal.lindegaard.one:8181/job/BagOfGold/lastSuccessfulBuild/
https://fractal.lindegaard.one:8181/job/MobHunting/lastSuccessfulBuild/

**Comment by mechcalvin** [comment]
Thanks, but is that lore still in second line? if yes they don't need to know but run the same command to change second line to hidden: amount

**Comment by Rocologo** [comment]
Yes, the lore is still in the seconds line, but if they only change the second line, the plugin will discover this and set the value to 0. 

I have added an extra hidden line and calculated a hash value. If the hash value does not match the item value will be set to 0.

**Comment by Rocologo** [comment]
ProtocolLib will hide the Hash value for the player, so they cant change the value in line 2.

**Comment by mechcalvin** [comment]
sounds great, i will do some testing, yet when you say it is not 100%, in what limit player might able to hack it?

**Comment by Rocologo** [comment]
The problem is that they can copy all the hidden line from a more expensive BagOfGold to a less expensive BagOfGold (inclusive the very long hash value) 
![image](https://user-images.githubusercontent.com/1008133/64373995-284bcd80-d023-11e9-8423-e42ddf027cb3.png)

I thing the is a problem with MobHeads with a value. I need to do more testing on this.

**Comment by mechcalvin** [comment]
Hmmmm, but if they can't see the hash then they can't copy it unless they find a way to do it, i will also do some testing with admin perms and normal player perms, thanks anything for the solution, even it is not perfect it rises the bar since it was super easy with setlore commands

**Comment by Rocologo** [comment]
Exactly.

**Comment by Rocologo** [comment]
Please test newest release
