### ISSUE TITLE
Sniper multiplier

### ISSUE THREAD

**Issue by Raivs** [Rocologo/MobHunting#56]
If you have your bow in your offhand (mc 1.9+) and shoot mobs, the sniper and pro sniper multiplier are not triggered.

Would be great if that could be fixed!

**Comment by Rocologo** [comment]
I have newer tested that multiplier. It was made by the previous developer. I will test and fix the bug.

**Comment by Rocologo** [comment]
Fixed in V3.2.0

Thank you for reporting this!
