### ISSUE TITLE
Mods Support

### ISSUE THREAD

**Issue by projectrpgmv** [Rocologo/MobHunting#560]
Does Mobhunting support mods monster? lika Crimson Knight on Thaumcraft or  Naga on The Twilight Forest ?

I'm using Mohist for Forge and Craftbukkit 1.12.2

**Comment by Rocologo** [comment]
I dont Think MobHunting works with Forge

**Comment by projectrpgmv** [comment]
Ohh, okay, I think Mobhunting can handle custom mobs from mods. 
Because I'm using Mobhunting on myserver with mods, If I kill Mobs from Vanilla like a Cow or horse, it's work, even it horse or cow from Animamia mods, but if I try kill mobs from Tahumcraft like Crimson Knight, its not work and doesn't have message on console, (debug message on)

**Comment by Rocologo** [comment]
If MobHunting dont recoqnice the Mob plugin it will detect the mob as the Minecraft Entity (ex Cow and Horse) 

MobHunting does only recoqnice CraftBukkit/Spigot plugin. Forge Mods are written another way, and there can MobHunting not recoqnice Forge Mods. Forge and Spigot are very different, so I cant support Forge too.
