### ISSUE TITLE
Parent POM is outside of VCS 

### ISSUE THREAD

**Issue by Narimm** [Rocologo/MobHunting#562]
Generally with OS projects particularly ones where you have moved a library written by someone else into a parent library (MAIN) and then referenced a file outside the build tree is going to break the build for anyone trying to compile it themselves.

Can I suggest your "MAIN" repo should not be a parent it should be a Library dependency.
In this way maven can correctly resolve it and git checkouts will be able to build it.

From my point of view having to checkout your MAIN repo just so I can get a working build is annoying.  

My suggestion is move the NMS MAIN library to become a dependency rather than a parent.

**Comment by Rocologo** [comment]
I dont know how to do this, so I can compile the plugin in both eclipse and with Jenkins.

**Comment by Rocologo** [comment]
I NOT very familiar with Maven, but I would like to make it the right way. So I need more detailed instructions / help.
