### ISSUE TITLE
Console Error EntityDeathEvent

### ISSUE THREAD

**Issue by mamilicalmir** [Rocologo/MobHunting#564]
Hello from Philippines! My name is Almir Mamilic!

I keep getting this 2 errors in my Craftbukkit Paper Spigot 1.8.8 console, https://pastebin.com/qFfhVT4W and https://pastebin.com/MkApJScy

Here's a list of my plugins, http://prntscr.com/p12dbj

I do not know what's causing the problem, but I hope you can help me Sir.

**Comment by mamilicalmir** [comment]
More info to be added
Version /ver: http://prntscr.com/p12sq0
I'm using FactionsUUID plugin

**Comment by mamilicalmir** [comment]
And sir, is it possible for you to fix this? http://prntscr.com/p12zz6
Thank you so much

**Comment by Rocologo** [comment]
This is fixed in newest builds
https://fractal.lindegaard.one:8181/job/BagOfGold/lastSuccessfulBuild/
https://fractal.lindegaard.one:8181/job/MobHunting/lastSuccessfulBuild/

**Comment by mamilicalmir** [comment]
I will try and test it tomorrow Sir, thank you

**Comment by Rocologo** [comment]
please update to newest releases.
