### ISSUE TITLE
Placed heads not dropping when broken.

### ISSUE THREAD

**Issue by Busted11290** [Rocologo/MobHunting#566]
Placing a head down and then trying to pick it up again results in the head only being broken.

Server: Paper
Plugins:
- MobHunting
- Vault
- EssentialsX w/Chat & Spawn

On a fresh server, all default configs.
https://youtu.be/zDbgvKc-Q1I

Here is a with the mh debug running, same setup.
https://youtu.be/EdSF_3s8XVo

**Comment by Rocologo** [comment]
Please test this build
https://fractal.lindegaard.one:8181/job/MobHunting/958/

**Comment by Rocologo** [comment]
Please test v6.9.5. Broken heads should be fixed now. Please try some new heads as old heads might already be broken now and I cant fix them if they is already broken.
