### ISSUE TITLE
Money does not fall from the mobs

### ISSUE THREAD

**Issue by Leon-CZ** [Rocologo/MobHunting#570]
Hi I need help with the plugin. If I kill monsters, no money will fall out of them. I have the basic plugin settings. I didn't change anything. Is it possible that this plugin does not work with another plugin? Which other plugins are most likely to be responsible for this "bug"? Thanks

**Comment by Rocologo** [comment]
Try enable debug

/mh debug

Kill a mob and check the console output

**Comment by Rocologo** [comment]
Død you Sølve tour problem?
