### ISSUE TITLE
Error 6.8.9

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#571]
Console is being spammed by this error: https://pastebin.com/EJAB7PS4

**Comment by Rocologo** [comment]
Do you still get this error? 

I need the last part of the error too. (the one starting with Caused by......)

**Comment by Sikatsu** [comment]
Not as often, but I still get this error yes. https://pastebin.com/2TiXxLvf

**Comment by Rocologo** [comment]
hmm im not sure about what triggers this error and I dont see this on my own servers, so I need your help.

I have added some debug information. Could you please test this build? 

https://fractal.lindegaard.one:8181/view/MainProject/job/MobHunting/948/

**Comment by Sikatsu** [comment]
Hey, you released 6.9.1 after the testbuild and using 6.9.1, I am being spammed again: https://pastebin.com/kZEQ6HVD

**Comment by Rocologo** [comment]
Please test this snapshot and let me know if it works:

https://fractal.lindegaard.one:8181/job/MobHunting/950/

**Comment by Sikatsu** [comment]
Seems fixed (for now at least)
