### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by anemul** [Rocologo/MobHunting#572]
https://pastebin.com/s0Wy0EV7 I was hitting the mob with a cobblestone block and knocked him off the edge of the skyblock island .

**Comment by Rocologo** [comment]
Please test this snapshot and let me know if it works:

https://fractal.lindegaard.one:8181/job/MobHunting/950/

**Comment by anemul** [comment]
It appears to have fixed the problem , where as I was getting errors every other mob or so , now I do not see any .
