### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting

### ISSUE THREAD

**Issue by Busted11290** [Rocologo/MobHunting#573]
Not sure what is causing it but console has been getting these errors. 

https://pastebin.com/UP9y7kj6

**Comment by Rocologo** [comment]
Please test this snapshot and let me know if it works:

https://fractal.lindegaard.one:8181/job/MobHunting/950/

**Comment by Busted11290** [comment]
Seems to be working now, no error and it is paying for kills like it should.
