### ISSUE TITLE
Issue with mobheads

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#575]
When a player applies a mobhead in their gear slot, they can't get rid of it unless they die.

http://prntscr.com/pdpshg

**Comment by Rocologo** [comment]
I thought this was disabled. Do you know how they get it on?

**Comment by Sikatsu** [comment]
Just the normal way.

**Comment by aenaveen** [comment]
Same problem on my server, its really becoming a problem when players keep messaging me on discord to come remove their heads. I removed 15 heads then got tired of it and disabled head drops. They wear it like a pumpkin the normal way and they cannot remove it from there, although /head works when they holding pumpkin so the pumpkin replaces it and they can remove the pumkin from the slot in inventory unlike the mobhead.

**Comment by Rocologo** [comment]
I need to know if you are using  my BagOfGold plugin as well?

**Comment by Sikatsu** [comment]
No, using CMI.

**Comment by Rocologo** [comment]
I need to know if you are using  my BagOfGold plugin as well?

**Comment by Rocologo** [comment]
Ok I will test without BagOfGold

**Comment by Rocologo** [comment]
V6.9.3 fixes the issue partly. MobHunting Mob heads will be taken off automatically. IE. they cant be worn at all now.

**Comment by Sikatsu** [comment]
That's good.

**Comment by Rocologo** [comment]
Well it did not :-( 

Please test this snapshot.

**Comment by Rocologo** [comment]
https://fractal.lindegaard.one:8181/job/MobHunting/958/

**Comment by Rocologo** [comment]
Please test v6.9.5. Broken heads should be fixed now. Please try some new heads as old heads might already be broken now and I cant fix them if they is already broken.

**Comment by Sikatsu** [comment]
This seems to be resolved.
