### ISSUE TITLE
Mobheads from spawners

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#576]
Not all mobspawners drop mobheads, but I noticed that chicken spawners DO. Is there a way to disable it for all mobs?

**Comment by Rocologo** [comment]
PS. I dont deny the mobspawners to drop heads. I only deny the player to get money for heads froms spawners

**Comment by Sikatsu** [comment]
Hmm I see. Because only the chicken spawners seem to drop heads.

**Comment by Rocologo** [comment]
okay, but I dont chnage the behavior of the spawners. So it must be something else?

**Comment by Sikatsu** [comment]
Not sure, but it's only happening for chicken spawners, all the default minecraft spawners don't seem to drop mobheads.
