### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by wisnia834** [Rocologo/MobHunting#579]
Hey! I don't know where to post it to you but:

Here is msgs in Polish language i made. You can add it to autodownload! :P 

[Polish MobHunting.zip](https://github.com/Rocologo/MobHunting/files/3712454/Polish.MobHunting.zip)

**Comment by Rocologo** [comment]
Thank you VERY much. Next release will contain your translation!

**Comment by wisnia834** [comment]
2 questions in same topic if I can.
1) Is there option to turn off msg of "you killed mob" and "you got 5.00 bag of gold" on chat ?
2) If I type /help there is so much command and i cant read them all.  You should give option like /help 2 /help 3 etc.

**Comment by wisnia834** [comment]
Pefect! Thanks!
