### ISSUE TITLE
Error on Server Startup

### ISSUE THREAD

**Issue by Waterman1001** [Rocologo/MobHunting#58]
Hii,
When starting up my server I get an error message in the console. Any ideas how to fix this? I am using Minecraft version 1.9.2 and MobHunting version 3.1.9.
Thanks in advance for your help :)

Error:

15.06 00:22:36 [Server] INFO Enabling MobHunting v3.1.9
15.06 00:22:36 [Server] INFO Enabling compatibility with Essentials (TeamCity)
15.06 00:22:36 [Server] INFO Enabling compatibility with WorldEdit (6.1.2;b3fbe8b)
15.06 00:22:36 [Server] INFO Enabling compatibility with WorldGuard (6.1.2-SNAPSHOT;1653-65e48d1)
15.06 00:22:36 [Server] INFO Enabling compatibility with Citizens (2.0.17-SNAPSHOT (build 1362))
15.06 00:22:36 [Server] INFO Enabling compatibility with MobArena (0.97.1)
15.06 00:22:36 [Server] INFO Enabling compatibility with LibsDisguises (9.0.6)
15.06 00:22:37 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
15.06 00:22:37 [Server] Startup Done (21.356s)! For help, type "help" or "?"
15.06 00:22:37 [Server] INFO Starting GS4 status listener
15.06 00:22:37 [Server] INFO Query running on 178.20.170.79:25640
15.06 00:22:37 [Server] INFO Top signs are being updated
15.06 00:22:37 [Server] INFO Checking for new updates...
15.06 00:22:37 [Server] INFO Created the winners map!
15.06 00:22:37 [Server] WARN Exception in thread "Craft Scheduler Thread - 6" 
15.06 00:22:37 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin MobHunting v3.1.9 generated an exception while executing task 135
15.06 00:22:37 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
15.06 00:22:37 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
15.06 00:22:37 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
15.06 00:22:37 [Server] INFO at java.lang.Thread.run(Unknown Source)
15.06 00:22:37 [Server] INFO Caused by: java.lang.NullPointerException
15.06 00:22:37 [Server] INFO at one.lindegaard.MobHunting.MetricsManager$26.getValue(MetricsManager.java:251)
15.06 00:22:37 [Server] INFO at org.mcstats.Metrics.postPlugin(Metrics.java:419)
15.06 00:22:37 [Server] INFO at org.mcstats.Metrics.access$4(Metrics.java:354)
15.06 00:22:37 [Server] INFO at org.mcstats.Metrics$1.run(Metrics.java:227)
15.06 00:22:37 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
15.06 00:22:37 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
15.06 00:22:37 [Server] INFO ... 3 more

**Comment by Rocologo** [comment]
Fixed in V3.2.0

Thank you for reporting this!
