### ISSUE TITLE
Support 1.15

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#584]
Hey, is an update for 1.15 in the works? :)

**Comment by Rocologo** [comment]
Hi Sikatsu

I have not been working on my plugins for quite some time (I have been moving from one house to another) but now it is Xmas and I think I will get some time to improve my plugins.

I am almost done with the 1.15.1 update. 

I need testing before I make a release but I hope I can make it today

**Comment by Sikatsu** [comment]
Understandable! Thanks for working on it though, appreciated!

**Comment by Sikatsu** [comment]
@Rocologo 

It's throwing a lot of warnings: https://pastebin.com/zka3p608

**Comment by Rocologo** [comment]
No these warnings is not from MobHunting

**Comment by Sikatsu** [comment]
Oh, sorry then. It was in the middle of the mobhunting startup.

**Comment by Rocologo** [comment]
Yes. I saw the same when I did the initial testing on 1.15 I had to disable alot of plugins to find the problem. I thing it was modern**** something. But I'm not 100% sure

**Comment by Sikatsu** [comment]
modern lwc?

**Comment by Rocologo** [comment]
Yes correct Try to disable this one first and then.look for an update

**Comment by Sikatsu** [comment]
This one is resolved.
