### ISSUE TITLE
MobHunting slowing startup

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#588]
Hey,

It seems MobHunting is making my server startup much slower. 
It hangs like half a minute to find the economy plugin I believe.

https://pastebin.com/hqKdftUA

Could you look into this, so I can perform restarts quicker?

**Comment by Sikatsu** [comment]
This seems to be because of the rewards.yml file, on a new server this doesn't happen.

**Comment by Rocologo** [comment]
Well, when you start a server with alot of Rewards placed in ground around in the world, all the rewards is read from the rewards.yml file... I dont think I can change this

**Comment by Rocologo** [comment]
How many rewards do you have in the file?

**Comment by Sikatsu** [comment]
That is indeed the case. I reset the file and now it starts up fast. But eventually it extended the startup time by a minute. Is there no way to make it read the rewards faster?

**Comment by Rocologo** [comment]
Maybe I can load the Rewards asyncroniously... Let me think ...

**Comment by Rocologo** [comment]
This build might solve the problem. Could you please check? (I dont have that many rewards placed so it becomes a problem)

https://fractal.lindegaard.one:8181/job/MobHunting/990/

**Comment by Sikatsu** [comment]
At the moment since I recently reset it nor do I, but I will update and let
you know if it ever becomes a problem again ^^

Op za 25 apr. 2020 23:47 schreef Rocologo <notifications@github.com>:

**Comment by Rocologo** [comment]
are you aware that all placed rewards on ground will loose its value when you delete the rewards.yml file?

**Comment by Sikatsu** [comment]
Hmm, I wasn't. What sort of value?

Op za 25 apr. 2020 23:58 schreef Rocologo <notifications@github.com>:

**Comment by Rocologo** [comment]
The dropped BagOfGold items or Mobs heads. They usually have a value and can be sold if you have added MobHunting Signs for this.

https://www.spigotmc.org/wiki/mobhunting-bag-of-gold/

**Comment by Sikatsu** [comment]
Ah, but I don't use mobhunting bagofgold or signs, so they don't really
have a value. In this case it's also on an old server that is soon to be
deleted. Thanks for the headsup though!

Op zo 26 apr. 2020 00:04 schreef Rocologo <notifications@github.com>:

**Comment by Rocologo** [comment]
Okay. Lets close this ticket then for now.
