### ISSUE TITLE
Cmd-run-frequency/-base ratios

### ISSUE THREAD

**Issue by JCNetworks** [Rocologo/MobHunting#59]
This is not a major problem more of a concern. Say if I wanted to make it quite hard to get a reward by killing a mob, so I do;
chicken-cmd-run-frequency: 1
chicken-cmd-run-frequency-base: 100
This does make it a lot harder to get the reward, but I have noticed that every player that is new to killing chickens (or whenever I restart the server) gets the reward on the 1st, 2nd, 3rd kill etc, THEN after that first reward it becomes hard to get it again (like 1:100 should be). The rewards I would like to give are permissions, so it just seems too easy to get them right now if the first time they try they get it, even though I am attempting to make the ratio hard.
Thanks for this plugin though, it is really amazing!

**Comment by Rocologo** [comment]
Hmm... I use the standard java random number generator, maybe it does not work that well or maybe. I will google this and see if others are having problems to.

**Comment by Rocologo** [comment]
I have changed the way I produce random numbers in next release (V3.2.3) I not sure it will make a big difference and I could not find any errors in my source code either.

**Comment by JCNetworks** [comment]
Thanks very much Rocologo. I hope it's a little better, if not perhaps it's just me. I really appreciate the support <3 :)
