### ISSUE TITLE
Mob Heads/BagoGold displays random numbers and text

### ISSUE THREAD

**Issue by ssjgokillo** [Rocologo/MobHunting#590]
![bag](https://user-images.githubusercontent.com/58497267/71772955-dc962b80-2f11-11ea-919b-7cc66f289ef7.png)

All mob heads and bags of gold display random purple text when we hover over them.

**Comment by Rocologo** [comment]
You need to install ProtocolLib to remove the purple text

**Comment by ssjgokillo** [comment]
Ugh, I'm a dummy. I could have swore I had downloaded that. Thanks for that, great plugin as always! :)
