### ISSUE TITLE
Question timings

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#592]
What exactly is this event? http://prntscr.com/qlf49u
It shows quite high and i'm pretty sure I don't use leaderboards?

**Comment by Rocologo** [comment]
It is called when a chunk is loaded and the I check if a mobhu6 sign is in the chunk and if it should be loaded.

**Comment by Sikatsu** [comment]
Any way to disable that? As I don't have signs in my world from mobhunting at all. ^^
