### ISSUE TITLE
Error on enabling the MobHunting plugin

### ISSUE THREAD

**Issue by DinoTK** [Rocologo/MobHunting#593]
Hello! Today I open my server, where I already uses mobhunting for a while, and this happened to me...

`[MobHunting] Enabling MobHunting v6.9.9
10.01 18:26:03 [Server] INFO [MobHunting] Your config version is 1
10.01 18:26:03 [Server] INFO [MobHunting] Existing config.yml loaded.
10.01 18:26:03 [Server] INFO [MobHunting] Config.yml was backed up to plugins/MobHunting/backup/config.yml.bak66
10.01 18:26:03 [Server] ERROR Error occurred while enabling MobHunting v6.9.9 (Is it up to date?)
10.01 18:26:03 [Server] INFO java.lang.NullPointerException: null
10.01 18:26:03 [Server] INFO at one.lindegaard.Core.config.AutoConfig.saveConfig(AutoConfig.java:260) ~[?:?]
10.01 18:26:03 [Server] INFO at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:148) ~[?:?]
10.01 18:26:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-645]
10.01 18:26:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
10.01 18:26:03 [Server] INFO [MobHunting] Disabling MobHunting v6.9.9`

**Comment by Rocologo** [comment]
It looks like something is wrong with your config.yml ?
