### ISSUE TITLE
HappyHour permissions

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#594]
I wanted to give my players the permission to do /mh happyhour and see how long it still lasts for.

Today I noticed players could just start happy hours themselves. Could that permission be split into 2? One to start the happyhour and one to see the remaining time?

**Comment by Rocologo** [comment]
The permision is already there

mobhunting.happyhour

Doesnt it work? Are you that you playes dont have this permission?

**Comment by Sikatsu** [comment]
If I give them mobhunting.happyhour, they can start happyhour as well.

**Comment by Sikatsu** [comment]
@Rocologo 

Any news on this? Also the message that shows how long happyhour is still running for when you login, is linked to mobhunting.happyhour, which you can also start happyhour with. Dangerous to give to players.

**Comment by Sikatsu** [comment]
Friendly ping, I'm not sure if this project got abondened, but please let me know if there won't be an update in the forseeable future so I can look for an alternative. @Rocologo

**Comment by Sikatsu** [comment]
By any chance you can slip in a fix for this one and make seperate permissions? @Rocologo

**Comment by Rocologo** [comment]
Yes. Show you would like to have a permission

mobhunting.happyhour.admin
and 
mobhunting.happyhour

hmmm

I just checked my code and it looks like I have already this ??? May I did this before my dev. enviromment broke and never published this.

´´´
if (sender.hasPermission("mobhunting.happyhour.admin")) {

...

} else {
					plugin.getMessages().senderSendMessage(sender,
							ChatColor.RED + plugin.getMessages().getString("mobhunting.commands.base.nopermission", "perm",
									"mobhunting.happyhour.admin", "command", "happyhour <min> <multiplier>"));
	
				}´´´

**Comment by Sikatsu** [comment]
Not sure, but I gave them mobhunting.happyhour so they can see the message ''HappyHour is running for <time>'' when they login, and so they can check manually with the command. But with that permission, they can also start happyhour. so yeah...

**Comment by Rocologo** [comment]
Hmmm.... I see I will have to look at this again

**Comment by Sikatsu** [comment]
Thanks a lot, it's one of the most requested thing on my server. They really want to be able to see how long it still runs for, with a command or when they join.

**Comment by Rocologo** [comment]
Please test newest build
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Sikatsu** [comment]
This matter seems fixed now!
