### ISSUE TITLE
The config file is resetting

### ISSUE THREAD

**Issue by faelfreitas** [Rocologo/MobHunting#596]
when I change the config file and use the command /mh reload, the file simply resets and I lose my settings.
I tried to stop the server, replace the config file and start again but it doesn't work .

Mob Hunting version: 6.9.9
Spigot version: 1.15.1

**Comment by Rocologo** [comment]
Denied. I have tried to do this
1) start the server.
2) Change this setting in both BagOfGold config.yml and MobHunting config. save the changes and the do a /bag reload /mh reload 
3) checked that the settings had the new value, which they did

So unless you explain what you do, I cant fixe a problem which I cant reproduce and cant see.
