### ISSUE TITLE
Support for mythic mobs not working.

### ISSUE THREAD

**Issue by tacocoma** [Rocologo/MobHunting#598]
I've set up my config so that every mob is disabled. I found the generated Mythicmobs file from mobhunting for coding in the mythic mobs. I put in my mob list. I go in game and kill a mythic mob and nothing happens. I check the console and it says that my mythic mobs is outdated. I'm using the latest version of both plugins. Therefore it must be an outdated connection coming from this plugin. Please update and fix the connection.

**Comment by Rocologo** [comment]
I will release 7.0.0 today where I have testet 1.15.2 with MythicMobs 4.7.2 (The Free version)
