### ISSUE TITLE
Configuration does not include WANDERING_TRADER or TRADER_LLAMA

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#599]
MobHunting 6.9.9-b965 (and previous)

config.yml does not include any entries for Trader entities.

**Comment by Rocologo** [comment]
I agree... this will be added as soon as possible. Do you know in which minecraft version they were added?

**Comment by SlimeDog** [comment]
https://minecraft.gamepedia.com/Wandering_Trader#History

**Comment by Rocologo** [comment]
I have added TraderLlama and Wndering trader now in both plugins
https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
Please help me with the testing. :-)

**Comment by SlimeDog** [comment]
I do not use **BagOfGold**, so I cannot test it. I will test wandering entities in **MobHunting**, but it isn't very complicated.

We have discussed this before, but it is really annoying not to have a generated default _config.yml_ in the JAR. The ability to check differences between versions is extremely onerous without that feature. My usual simple process is:
- unzip the JAR
- compare _config.yml_ and language files with the saved files from the previous release
- stop the server
- make any changes to the active _config.yml_ and language files, based on the comparisons
- update the JAR
- start the server

Without the embedded config.yml, I have to:
- stop the server
- **_save the "active" plugins/MobHunting directory to /tmp/X/_**
- update the JAR
- **_start the server, in order to generate the default config.yml_**
- **_stop the server_**
- **_save the new plugins/MobHunting/ directory to /tmp/Y/_**
- **_move the "active" MobHunting directory back into place_**
- compare the files in _/tmp/X/_ and _/tmp/Y/_
- make any changes to the active _config.yml_ and language files, based on the comparisons
- start the server

Double the number of steps, to do something that should be relatively simple (for most plugins, it takes a few minutes). Please reconsider.

**Comment by Rocologo** [comment]
Well, I just use the system which the original developer made, and to be honest I dont have the time to make this the way you would like to have this. Also I think it is smart that missing settings is autocreated. 

You could use the config.yml backup feature this way you would get a copy of the config.yml each time you restart your server. and then you could compare with the previous one. 

I see a lot of plugins where new settings is not autocreated and you have to find the new settings your self that is very annoying too :-)

**Comment by SlimeDog** [comment]
> it is smart that missing settings is autocreated.

Agreed. The two are not incompatible. If the config.yml existed, one could choose my method, or just let it do what it does now, or any combination of the two. The benefit of my method, is that I edit the values from the defaults to get what I want, before I start the server.

> I see a lot of plugins where new settings is not autocreated and you have to find the new settings your self that is very annoying too :-)

All my plugins are of that type. :)
Of course, changes to configuration files are listed in the update announcements.

**Comment by SlimeDog** [comment]
Wandering Trader seems to interact with MH 7.0.5-SNAPSHOT-B984 correctly. Per above, I cannot test BagOfGold.
