### ISSUE TITLE
Double messages with money drop enabled

### ISSUE THREAD

**Issue by SpaZMonKeY777** [Rocologo/MobHunting#60]
So if you enable the config option to have money drop on the ground, it triggers two different message events when a mob is killed and drops money. Here are the 2 messages from the locale file that get displayed: http://pastebin.com/CTYUQdAX

Is there a way to disable the first one from displaying? That's the one that shows in chat as soon as the money drops, but doesn't mean the player actually got the money yet and could be confusing. The second message is good though, as it only displays when the money is picked up :)

Or maybe a way to disable certain messages from the locale?

**Comment by Rocologo** [comment]
In next release I have removed 

mobhunting.moneygain=You gained ${prize}!

if drop_money_on_ground is true in config.yml, becuase the money is not gained until they are picked up.

**Comment by Rocologo** [comment]
V3.2.3 released
