### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting v6.9.9

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#600]
Error: https://pastebin.com/hq6WvFWY

Config: https://pastebin.com/RwA5Aven

Timings: https://timings.aikar.co/?id=640c287cf9ad427a9c33f945d4afff33

**Comment by Rocologo** [comment]
This is the same problem as this one. https://github.com/Rocologo/MobHunting/issues/622. I close this ticket and keep the other open until one of you confirm that the problem i solved.

I should be fixed in newest build here:

https://fractal.lindegaard.one:8181/job/MobHunting/
