### ISSUE TITLE
Warnings in console when starting the server in 1.15.2

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#601]
This appears on server start: https://pastebin.com/rzBBM09D

https://www.spigotmc.org/threads/spigot-bungeecord-1-15-2.414068/

"API: Please do not use the ItemStack class to hold Materials that are not items (Material.isItem() == false). This is nonsensical behaviour and will not be supported in a future version."

**Edit**: This does not occur when MH is the only plugin enabled, but it does when EssentialsX is as well.

Timings: https://timings.aikar.co/?id=7074eadc88f34cd3a1809730a1faec44#plugins

**Edit 2**: The issue was seemingly resolved by removing the 'rewards.yml' file. Something about that file was the cause of the warnings.

**Comment by Sikatsu** [comment]
I have the same issue. @Rocologo you here bro?

**Comment by Rocologo** [comment]
You should not remove the rewards.yml file. All bags and heads will loose their value if you do so. 

I have not seen this bug on my own test server so its hard to find... 

I dont think I use the ItemStack calls to hold other items than the allowed ones. The Bag and the MobHunting heads are all normal ItemStack made with normal Material 

Matrial.isItem() on a Bag should return true, but I will check that.

**Comment by Sikatsu** [comment]
Spigot made some changes about the ItemStack, could it be related?

https://www.spigotmc.org/threads/spigot-bungeecord-1-15-2.414068/

**Comment by Rocologo** [comment]
I dont think so. I do not use ItemStacks other than normal items. The MobHunting Rewards and BagOfGold Items is completely normal Player_Head Items with a DisplayName and some lores. Its not something special.

**Comment by Rocologo** [comment]
Do you still have this error? I dont see this on my own servers when I start my servers.

**Comment by Sikatsu** [comment]
I see this on my old server, with an older world from 1.13. MobHunting also hangs over there on database connection, takes like 20 seconds before it moves on. On a fresh server this is not the case.

**Comment by Rocologo** [comment]
Ahh but the heading in this ticket says 1.15.2 so I have not tested on a old 1.13 server. Most people has upgraded now. 

Only 2.5 % use minecraft 1.13
![image](https://user-images.githubusercontent.com/1008133/79264452-e75b4780-7e94-11ea-886f-34748f886a32.png)

**Comment by Rocologo** [comment]
And this is one of the reasons why I keep fighting for bstats data :)

**Comment by Sikatsu** [comment]
I am running 1.15.2, but the world is from 1.13, so it has been force upgraded a couple of times. ^^

**Comment by Rocologo** [comment]
Ahhh , I dont have a test server with this combo... although I have 15 test servers to spin up and 1 production server :-)

**Comment by Weasel-Beans** [comment]
I'm not 100%, but I don't recall seeing this issue recently. Something may have changed with spigot/paper to make these errors appear less. I was also using an upgraded 1.13/1.14 server.

**Comment by Rocologo** [comment]
Actually my testworld is from MC 1.9 og 1.10 or so. I use the same basic world because I the dont need to create new areas for all the diffentings I need to test. one day I can let you in on my latest test server and let so see how must I am testing :-)
