### ISSUE TITLE
Leaderboard in chat

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#604]
Hey, i'd like a leaderboard within the chat instead of only in a hologram. 

Would be nice if it also supports multiple pages with 10 results per page. ^^

@Rocologo Are you still around bro?

**Comment by Rocologo** [comment]
Hi Sikatsu. yes Im here, but I have to admit that Im not very active in here at the moment. I will make an update for 1.15.2 now, and try to fix some bugs, but I will not add new features at the moment.

**Comment by Sikatsu** [comment]
Alright, hope you can look into this in the future.

@Rocologo If you have time tho, could you look into the grinding penalty? We could make it a paid job, if it helps for motivation?

**Comment by Sikatsu** [comment]
Hmm, it seems /mh top is already a thing. Like /mh top total_kills alltime 10.

I will close this ticket for that reason. @Rocologo
