### ISSUE TITLE
Grinding penalty bugs

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#605]
@Rocologo

With only the speed grinding enabled, if I fly a few blocks away it just completely resets the timer.

Also, with these settings: https://pastebin.com/nT2AB3z8

After 10 mobs, with each mob the reward decreases and after 20 it completely stops.
Is this not configurable? Not sure whether it's related to the speed grinding setting or the area, but something is off and not working correctly.

Hoping you can check into this soon!

I sent you a discord message a while ago, in case you're interested to go over this with me.

**Comment by Sikatsu** [comment]
So what I'm trying to achieve is that the grinding penalty doesn't start so quick. But it doesn't seem to be configurable, because to whatever setting I set it too, the behaviour stays the same.

**Comment by Rocologo** [comment]
Was is enable_grinding_detection set to in your config?

**Comment by Sikatsu** [comment]
It's set to True

**Comment by Rocologo** [comment]
Please only report one problem on each ticket. So I dont mix thinks up :-) 

Lets start with your speedgrinding problem :-)

**Comment by Rocologo** [comment]
So if you kill one mob and and then start flying you say that the counter resets?

**Comment by Sikatsu** [comment]
Ah, but it both has to do with the grinding penalty. One being the speed grinding, other being the area grinding.

Speedgrinding; lets say you hit the cap and you no longer receive money, fly or walk away a few chunks and the timer is reset. I think it should remember the speedgrinding timer per-player.

**Comment by Rocologo** [comment]
Yes, i understand, but the two features are separeted in the code and I have to understand whats trigger the problem you see. You dont need to create another ticket, but lets start with your biggest problem first?

**Comment by Rocologo** [comment]
Okay I will test this used case again: "Speedgrinding; lets say you hit the cap and you no longer receive money, fly or walk away a few chunks and the timer is reset. I think it should remember the speedgrinding timer per-player."

It should newer reset just by flying

**Comment by Sikatsu** [comment]
I'm not sure if it's related to flying, walking could do the same. But it just resets the speed grinding timer, so it's quite easy to bypass. Walk away a few chunks and get back to your grinding spot.

**Comment by Rocologo** [comment]
remember is is 20 mobs within 120 sec timeframe (your config) 

If you kill 15 mobs in the first minut then 10 mobs in second minute, then you will hit the limit (20) 

But if you the wait 1 minute (flying / walking away) then the 15 mobs is removed from memory and you will be allowed to kill 10 more mobs in the 3 minute. 

The code uses seconds, but it is easier to understand when I explain with minutes :-)

**Comment by Sikatsu** [comment]
But I wasn't able to higher the limit, whatever I changed it too, it stayed like that. And it's still easy bypass too.

**Comment by Rocologo** [comment]
Are you able to kill more than 20 mobs with 120 seconds?

**Comment by Sikatsu** [comment]
I would like to set the mob limit higher, but after 20 it still stops giving money.

**Comment by Rocologo** [comment]
Yes. You have "no_of_mobs: 20" in your config, so you are not allowed to kill more than 20 within the timeframe (120 sec in your case) If you change the timeframe to 240 seconds, the players will only be able to kill 20 mobs within 240 seconds (half as much)

**Comment by Sikatsu** [comment]
I do get how it works, but even tho when I changed it, it still decreased money after 10 mobs and stopped giving money when it hit 20. Even if I set it to like 50 mobs.

**Comment by Rocologo** [comment]
Sounds like you are doing sometings wrong or mix the two grinding checks. This is my code for testing speedgrinding. I use what every you have entered in the config :-) Could you provide me with debug information from the console when this is happening?

`	public boolean isPlayerSpeedGrinding(LivingEntity killer, LivingEntity killed) {
		long starttime = System.currentTimeMillis();
		Iterator<Entry<Integer, GrindingInformation>> itr = killed_mobs.entrySet().iterator();
		List<Integer> to_be_deleted = new ArrayList<Integer>();
		int n = 0;
		long sum = 0;
		long avg_time = 0;
		ExtendedMob mob = plugin.getExtendedMobManager().getExtendedMobFromEntity(killed);
		while (itr.hasNext()) {
			GrindingInformation gi=itr.next().getValue();
			if (killer==null) {
				return false;
			}
			if (gi==null || gi.getKiller()==null) {
				continue;
			}
				
			if(!killer.equals(gi.getKiller()))
				continue;

			if (starttime > gi.getTimeOfDeath() + (1000L * plugin.getConfigManager().speedGrindingTimeFrame)) {
				// delete after x min
				to_be_deleted.add(gi.getEntityId());
				continue;
			}

			n++;
			sum = sum + (starttime - gi.getTimeOfDeath()) / 1000L;
			avg_time = sum / (long) n; // sec.

		}
		for (int i : to_be_deleted) {
			killed_mobs.remove(i);
		}
		plugin.getMessages().debug("GrindingManager: average kill time=%s", avg_time);
		if (avg_time != 0 && (n >= plugin.getConfigManager().speedGrindingNoOfMobs
				&& avg_time < plugin.getConfigManager().speedGrindingTimeFrame)) {
			plugin.getMessages().debug("GrindingManager: %s %s was killed in less than %s sec - player is grinding", n,
					mob.getMobName(), plugin.getConfigManager().speedGrindingTimeFrame);
			return true;
		} else
			return false;
	}`

**Comment by Sikatsu** [comment]
Hey, as i'm writing from my phone, it might be better if I get back to this issue once i'm home later today. I will provide you better information regarding the issue I was having.

Thanks for looking into this though. I hope we find a proper solution soon.

**Comment by Sikatsu** [comment]
Tested the speed grinding. I was not able to reproduce the ''Flying/walking away a few chunks it resets the timer''

However. once I hit the mob cap and it started to give me 0.8 grinding penalty and I teleported to another world, went killing mobs there, each time it just said 0.8 grinding penalty, it didn't decrease anymore.

As soon as I teleported back to the overworld and started killing mobs again, it went to 0.7 and decreased further.

------
About the grinding area:

With these settings, after 10 mobs the amount decreases and after 20 mobs the money reward stops. This doesn't seem to be configurable. I would expect that mobs start to decrease at 40 and stop rewarding at 50 with the below settings.
`  area:
    detect_grinding_areas: true
    grinding_detection_range: 15
    grinding_detection_number_of_death: 50
    disable_natural_item_drops_on_player_grinding: false
    disable_natural_xp_drops_on_player_grinding: false
    blacklist_player_grinding_spots_as_server_worldwide_spots: false`

**Comment by Sikatsu** [comment]
@Rocologo Hmm and is there no way to detect slimes and handle it differently?

**Comment by Sikatsu** [comment]
@Rocologo 

Some debug;

When I waited 5 to 10 minutes and started killing mobs again:
https://pastebin.com/DxFtAXvU

Waiting another 10 minutes:
https://pastebin.com/u5apJsFz

I have a feeling that in the beginning everything works fine, but after a while the timer isn't as accurate anymore.

**Comment by Sikatsu** [comment]
@Rocologo Apparently when you relog, the speed grinding penalty will be reset. Could you look into relogging? ^^

**Comment by Rocologo** [comment]
It was only the logoff/login problem i fixed. 

I have not looked at the hole ticket.  It takes alot of time to test this, and I dont know if I am doing the same as you do.

**Comment by Sikatsu** [comment]
I know that's the only thing you fixed, theres more issues regarding the grinding penalties though. Information is up here, but take your time!

**Comment by Rocologo** [comment]
Let talk about the other Grinding issues you experience. one at a time, so we don't get confused. 

I know now you are correct. I found this piece of code ... its more than 5 years old from the original developer!!! :-) 

```	public double getDampnerMultiplier() {
		if (dampenedKills < 10)
			return 1.0;
		else if (dampenedKills < 20)
			return (1 - ((dampenedKills - 10) / 10.0));
		else
			return 0;
	}```

It will be fixed now.

**Comment by Sikatsu** [comment]
Awesome! It's been a while, so if you need me to do any testing please let me know.

**Comment by Rocologo** [comment]
I will do the initial testing :-) and then I will ask you to help!

**Comment by Rocologo** [comment]
I have spend MANY hours today in rewriting the Area and Speed grinding code. (It was probaly a mess because of so many small changes. So I decied to rewrite the code to make i more clear.

I hope it all works now. I have testet the Area grinding, teh speeding grinding and Whitelist and blacklist... It seems to work now.

Im only working on one bug now. I used to show the grinding area by spawning particles around the area, but seems not to work any more :-(

**Comment by Rocologo** [comment]
https://fractal.lindegaard.one:8181/job/MobHunting/991/

**Comment by Sikatsu** [comment]
I'll test it out tomorrow! It's a bit late now ^^

Good work!

**Comment by Sikatsu** [comment]
I haven't been able to test myself, but a tester of mine said that after a
minutes of not killing any mobs, it would immedietly say "Mob grinding
detected". I'll test myself later today!

Op zo 26 apr. 2020 21:16 schreef Rocologo <notifications@github.com>:

**Comment by Rocologo** [comment]
I will need the debug information from the console, to see whats going on. This way I hope I will be able see whats going on.

I have added more debug information than last time you tried.

Also I will need a fresh copy of you grinding settings in the config.yml, so I can test with the same settings.



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: Sikatsu <notifications@github.com>
Dato: 27.04.2020 11.51 (GMT+01:00)
Til: Rocologo/MobHunting <MobHunting@noreply.github.com>
Cc: Rocologo <Rocologo@hotmail.com>, Mention <mention@noreply.github.com>
Emne: Re: [Rocologo/MobHunting] Grinding penalty bugs (#605)


I haven't been able to test myself, but a tester of mine said that after a
minutes of not killing any mobs, it would immedietly say "Mob grinding
detected". I'll test myself later today!

Op zo 26 apr. 2020 21:16 schreef Rocologo <notifications@github.com>:

**Comment by Sikatsu** [comment]
Lets first do speed grinding. Using the settings below!

After 20 mobs within 2 minutes, in the actionbar it will say ''Mob Grinding Detected'', then a pause in the actionbar before it will continue to say ''<amount> * grinding penalty 0.9''. Most players already killed another mob, and will never be able to see that second message. So according to some players it's a bit confusing. After another 10 mobs, messages will stop being displayed and no money will be rewarded anymore. However, it never seems to reset, or atleast doesn't give any indicator on how long it takes before they can get money rewards again.

```
  # Speed grinding detection.
  # Limit the number of mobs which can be killed with in a given timeframe
  speed_grinding:
    detect_speed_grinding: true
    time_frame: 120.0
    no_of_mobs: 20
```

**Comment by Sikatsu** [comment]
I am not able to test the area grinding. I disabled speed grinding and enabled area grinding, but I think the speed grinding still didn't reset for me.

**Comment by Rocologo** [comment]
Thanks for you help! 

No wonder that you could not disable Speeding Grinding! When I rewote the code I forgot to add that test :-( Its added now. Also I found a bug in the speed grinding test, and I added a more detailed and easier to understand debug information. 

```
[20:08:05] [Server thread/INFO]: [MobHunting][Debug] Rocologo has killed 1 Creeper in 0 seconds. Average is 0 and limit is 24.0
[20:08:05] [Server thread/INFO]: [MobHunting][Debug] Rocologo is not Speed Grinding
......
[20:08:14] [Server thread/INFO]: [MobHunting][Debug] Rocologo has killed 2 Creeper in 8 seconds. Average is 4 and limit is 24.0
[20:08:14] [Server thread/INFO]: [MobHunting][Debug] Rocologo is not Speed Grinding
.......................
[20:08:16] [Server thread/INFO]: [MobHunting][Debug] Rocologo has killed 3 Creeper in 11 seconds. Average is 3 and limit is 24.0
[20:08:16] [Server thread/INFO]: [MobHunting][Debug] Rocologo is not Speed Grinding
......................
[20:08:19] [Server thread/INFO]: [MobHunting][Debug] Rocologo has killed 4 Creeper in 22 seconds. Average is 5 and limit is 24.0
[20:08:19] [Server thread/INFO]: [MobHunting][Debug] Rocologo is not Speed Grinding
.............
[20:08:24] [Server thread/INFO]: [MobHunting][Debug] Rocologo has killed 5 Creeper in 39 seconds. Average is 7 and limit is 24.0
[20:08:24] [Server thread/INFO]: [MobHunting][Debug] Rocologo is Speed Grinding. No rewards paid
```
Please test this build: https://fractal.lindegaard.one:8181/job/MobHunting/993/

**Comment by Rocologo** [comment]
Hmmm something is still wrong :-( I have to test more

**Comment by Rocologo** [comment]
I almost dont dare to say it again :-) But I think it works now

https://fractal.lindegaard.one:8181/job/MobHunting/997/

And I go to bed now, so more updates today

**Comment by Sikatsu** [comment]
I'll do some testing first thing in the morning. Will let you know!

**Comment by Sikatsu** [comment]
Does the penalty always start when half of the limit is reached? Since it only counts from ''Penalty 0.9'' to Penalty 0.0''

https://pastebin.com/PsWSs9CZ

I've also got some complains from people getting negative money, I have yet to reproduce this myself though.

**Comment by Sikatsu** [comment]
Here it says I am not speed grinding, after I disabled area grinding. However I do not get any money

Debug: https://pastebin.com/R7p85aDm

**Comment by Rocologo** [comment]
You are mixing the questions. So it is hard to answer :-)

First Area Grinding: Yes the penalty start when half of the limit is reached. The penalty is a linear reduction when 50% of the limit is reached. This is what I try to write in the debuinformation

`Checking kills in this area. DampenedKills=2. Penalty begins at 15. Max is 30`

Yes the penalty can be negavtive. It depends what the player kills. The debug will tell you which modifiers which can be negative (I cant remember). This can also happen if f.ex. set reward for killing a horse to -10$

/mh checkgrinding works on my test server. I have an area where I test this. I have tested whitellist, blacklist, cleargrinding and checkgrinding. 

The grinding can be server wide, the is a config for this. So it depends on your setup. 

If you want to start over and remove all detected area you can delete the blacklist.yml file and restart (or maybe reload???) This should remove all blacklist areas

**Comment by Rocologo** [comment]
And the Speedgrinding debug

You have only killed 3 mobs so you are not speedgrinding. 

But I don understand why it says

`Multiplier: Grinding Penalty = 0.0`

I have have to dig into that.

**Comment by Sikatsu** [comment]
Ah, I tried to dedicate the first message to area grinding and the second to speedgrinding.

I thought it would start 10 before the limit, like the configuration stated rather then 50%. ^^

Hmm, I've never had it take money from a players balance until the recent changes though.

The /mh checkgrinding only works if it's set as a server-wide grinding area then I assume?

I meant the area-grinding seems to be the whole world. I can not get rid of the penalty on me wherever I go. Might also be related to my second message about speed grinding and it being stuck somehow?

**Comment by Rocologo** [comment]
1) I will need the debug information to explain why it takes money :-) 

2) Area grinding show not be hole world :-) I have to admit that I have only tested in the same area all the time on my test-server. I will test this when I get home (I'm on work now)

**Comment by Sikatsu** [comment]
I have yet to reproduce this myself, but a couple of players PM'ed me that they got negative money.

It shouldn't be the whole world, but unless I'm broken somehow, it doesn't actually reset for me. Take your time!

**Comment by Rocologo** [comment]
This build fixes the bug where if says 

`Multiplier: Grinding Penalty = 0.0`

It should not calculate the modifier when area grinding is deactivated.

https://fractal.lindegaard.one:8181/job/MobHunting/998/

**Comment by Sikatsu** [comment]
That seems fixed, but when I reach the limit and move to another area it still applies. So I do think it's not an area, but the whole world that's being counted for.

Also this debug line seems rather confusing, what do you mean with avg kill time 3 must greater than 6?

`[17:47:57 INFO]: [MobHunting] [Debug] Sikatsu has killed 23 Zombie in 76 seconds. Avg.kill time 3 must greater than 6.0 when 20 mobs is killed.`

**Comment by Rocologo** [comment]
Yes I have tested area grinding again and I agree, when the limit is reached you cant kill anywhere :-( I will fix this now.

**Comment by Sikatsu** [comment]
Here it says ''Mob grinding detected'' then it shows how much money without a grinding penalty.
I personally think it's better to show ''%money% * grinding penalty 0.9'' until the limit is reached, where it will then say ''Mob grinding detected''

Currently it says ''Mob grinding detected'' with a small pause and then ''%money * grinding penalty 0.9'', but if you kill fast enough there is no way to see how much money you received.
[bug.zip](https://github.com/Rocologo/MobHunting/files/4547208/bug.zip)

**Comment by Sikatsu** [comment]
How is it going?

**Comment by Rocologo** [comment]
Im building a new jar file for you to test now.

**Comment by Rocologo** [comment]
Its building now
https://fractal.lindegaard.one:8181/job/MobHunting/999/

**Comment by Rocologo** [comment]
Okay only 5 min this time

Ready for testing https://fractal.lindegaard.one:8181/job/MobHunting/999/

**Comment by Rocologo** [comment]
I have not worked at the messages... the bugs had to be fixed first

**Comment by Sikatsu** [comment]
No worries, understandable. Will test!

**Comment by Sikatsu** [comment]
Well, it sort of works.. but, it doesn't remember the area. When I kill a mob a few blocks away it will reset the grinding penalty to 0 and I can return back to the old area without a grinding penalty.

**Comment by Rocologo** [comment]
Well it says 

`Kill not within 15.0 blocks from previous kill. Dampened Kills reset to 0`

If you kill 10 mobs one place and then 1 15 blocks away, the counter will reset. This is how it should work.

**Comment by Sikatsu** [comment]
I'm testing it among some players, and they have darkrooms of like 200 by 200. They never experience the grinding penalty anymore this way. What settings would you suggest in that case?

**Comment by Rocologo** [comment]
Its not about settings. They way it work is the same as it always has been. I would not recommend to make the range very large, as it would hurt normal players.

I have no idea about how to catch grinding in a big darkroom.

**Comment by Sikatsu** [comment]
Hmm, I see. We'll have to see how to catch that though, as now the grinding penalty is easy bypassable. ^^

**Comment by Sikatsu** [comment]
I see slimes are being handled differently now? Looking at this debug: https://pastebin.com/n5L1UYTG

**Comment by Sikatsu** [comment]
I think the ''comments'' near the area-grinding section need to be updated as well. 
Especially the ''If number of kills exceeds 10'' ^^

**Comment by Rocologo** [comment]
Yes. I agree. The messages needs an review, but I would like to remove the bugs first.

Slimes and (the ones from nether, cant remember the name now) is handled diffent (player is allowed to kill twice as many) this is because of the the splitting nature. If I didnt do that, the player would easily be caught for grindind, just because he had to kill the baby-slimes after killing the big one.

**Comment by Rocologo** [comment]
Have you found any bugs yet?

**Comment by Sikatsu** [comment]
So far not yet, nor any complains. Will test myself too in a bit.

This error spams in the console though since the devbuild: https://pastebin.com/Nuuu2Q9T

**Comment by Rocologo** [comment]
This is actually a bug you have found, I will fix it now and make a new snapshot

**Comment by Sikatsu** [comment]
Awesome. And for speed grinding there is no such thing as that it starts giving less money when halfo f the limit is reached?

**Comment by Rocologo** [comment]
okay, I was now aware off a problem with Plugman. I check that at some point.

**Comment by Sikatsu** [comment]
Definitely allows for easier testing ^^

I'll get back on this soon.

**Comment by Sikatsu** [comment]
Also, this is the error from plugman: https://pastebin.com/dbhMFz7N

**Comment by Rocologo** [comment]
I think you can load and unload MobHunting with Plugman in build 1001

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Sikatsu** [comment]
Seems fixed, so far no one else reported issues yet.

![image](https://user-images.githubusercontent.com/5664135/80753076-f137a880-8b2c-11ea-9eeb-d73f7b570bce.png)

**Comment by Rocologo** [comment]
Notice the comment i mad "Could not register MobHunting flag in Worldguard. If you use this the flag might not work after using PlugMan, I have not had time ti test this.

**Comment by Sikatsu** [comment]
I noticed it, I have no idea what mobhunting flags do, so I don't use it either ^^

**Comment by Sikatsu** [comment]
Other then the messages being a bit vague, I am not able to find bugs at the moment. Have you found anything?

**Comment by Rocologo** [comment]
Not on the grindig side.

Could we please take the texts in a new ticket :-D

**Comment by Sikatsu** [comment]
Of course, you can close this one for now. I'll inform you through a new ticket if any issues arise.
