### ISSUE TITLE
new version 7.0.0 wont load says it needs updated

### ISSUE THREAD

**Issue by Shewolf1896** [Rocologo/MobHunting#608]
`10.02 18:56:18 [Server] INFO [MobHunting] Enabling MobHunting v7.0.0
--
72 | 10.02 18:56:18 [Server] INFO [MobHunting] Your config version is 1
73 | 10.02 18:56:18 [Server] INFO [MobHunting] Existing config.yml loaded.
74 | 10.02 18:56:18 [Server] INFO [MobHunting] Config.yml was backed up to plugins/MobHunting/backup/config.yml.bak151
75 | 10.02 18:56:18 [Server] ERROR Error occurred while enabling MobHunting v7.0.0 (Is it up to date?)
76 | 10.02 18:56:18 [Server] INFO java.lang.NullPointerException: null
77 | 10.02 18:56:18 [Server] INFO at one.lindegaard.Core.config.AutoConfig.saveConfig(AutoConfig.java:260) ~[?:?]
78 | 10.02 18:56:18 [Server] INFO at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:148) ~[?:?]
79 | 10.02 18:56:18 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-99]
80 | 10.02 18:56:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-99]
81 | 10.02 18:56:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-99]
82 | 10.02 18:56:18 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-99]
83 | 10.02 18:56:18 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-99]
84 | 10.02 18:56:18 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-99]
85 | 10.02 18:56:18 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-99]
86 | 10.02 18:56:18 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-99]
87 | 10.02 18:56:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
88 | 10.02 18:56:18 [Server] INFO [MobHunting] Disabling MobHunting v7.0.0`

**Comment by Rocologo** [comment]
My best guess is that your config.yml is broken
