### ISSUE TITLE
Bounties Configuration

### ISSUE THREAD

**Issue by marvinej** [Rocologo/MobHunting#611]
config setting

# Set to true if you want to disable players to be able to put bounties on each other.
enable_player_bounties: true 

does not do anything regardless of its true/false setting. players are still able to set bounties
also your wording in the comment doesn't make sense. setting it to false should be to disable it. why does it say set to true to disable it?

**Comment by Rocologo** [comment]
Only Players with permission mobhunting.bounty can add bounties to other players.

**Comment by Rocologo** [comment]
enable_player_bounties: true  is used for enabling /mh bounty

enable_player_bounties: false  is used to disabling /mh bounty
