### ISSUE TITLE
Github Wiki is incomplete

### ISSUE THREAD

**Issue by marvinej** [Rocologo/MobHunting#612]
your wiki says click here for permissions and doesn't have a link. it also looks generally incomplete.

**Comment by marvinej** [comment]
I made some changes to improve it for you. If you want i can continue in my free time.

**Comment by Rocologo** [comment]
Hi Marvin

You are VERY welcome to paticipate and help. If you make improvments in the source code, please make sure that the code can compile when I make a pull.
