### ISSUE TITLE
Suggestion: Make Metrics Optional

### ISSUE THREAD

**Issue by marvinej** [Rocologo/MobHunting#613]
Some people don't like to give metrics. For privacy and professionalism i would suggest making this optional instead. I personally don't care and leave metrics on, but i can see why some people may want the option.

**Comment by hashashin** [comment]
@marvinej I personally simply redirect bstats.org to localhost, fast and easy.

**Comment by Rocologo** [comment]
At collected data i anonymous not even you IP address can be traced. 

If I wanted it would be SO easy to collect personal data and post it where ever I want, but I dont... When you allow a delveroper to run java code on your server you allow him to open, read and write and even delete important files on your server...

So I dont understant why you worry about annonymous data which tells me how many servers is using my plugin I make for free
