### ISSUE TITLE
It's possible to take player heads out of the bounty menu

### ISSUE THREAD

**Issue by BurgessYT** [Rocologo/MobHunting#614]
When you run /mh bounty open the GUI, anyone can just take infinite copies of the head of a player with a bounty from the pop-up GUI menu.
version spigot 1.12.2

**Comment by Rocologo** [comment]
This is the same problem as reported here: https://github.com/Rocologo/MobHunting/issues/591

and sadly I have to tell you that I dont have a solution to this problem. I close this ticket and keep the the old one open.
