### ISSUE TITLE
Unexpected exception while parsing console command "mobhunt reload"

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#621]
This appeared while typing '/mobhunt reload' or '/mh reload':

https://pastebin.com/0KtiqQkS

Timings: https://timings.aikar.co/?id=cede815bf41046dc8371464a3d1822fb

Config: https://pastebin.com/dFiJpvsw

**Comment by Rocologo** [comment]
It looks like something is wrong with your lang file. Have you changed the file?

**Comment by Weasel-Beans** [comment]
Haven't altered it at all no

**Comment by Rocologo** [comment]
The error happens while the plugin tries to read the lang file. So could you please try to rename the file and restart the server so it will be recreated?

**Comment by Weasel-Beans** [comment]
Which one, en_US.lang?

**Comment by Rocologo** [comment]
Yes. Thank you

**Comment by Rocologo** [comment]
Do you still have this problem? Or can the ticket be closed?

**Comment by Weasel-Beans** [comment]
I did what you said, and it seems to be good now. Thanks.
