### ISSUE TITLE
DOES NOT WORK: disable_money_rewards_from_mobspawners_and_eggs: true

### ISSUE THREAD

**Issue by LordRamma** [Rocologo/MobHunting#623]
Mobhunting reward break blocking for spawners mobs is not working.

DOES NOT WORK: disable_money_rewards_from_mobspawners_and_eggs: true

Minecraft version 1.15.2

Plugin version 7.0.4

config: https://pastebin.com/fJsGX1r6

**Comment by Rocologo** [comment]
Please explain how I test this? I can reproduce the error?

Are you sure that the area is not whitelisted?

**Comment by LordRamma** [comment]
disable_money_rewards_from_mobspawners_and_eggs: true

this option just doesn't work. The rewards and money continue to drop from spanking mobs.
v. 1.15.2
v.plugin 7.0.4
paper 144

**Comment by Rocologo** [comment]
You assume that I am a master in Minecraft :-) I dont know how to make a spawer in a world :-) 

(or I cant remember :-) ... I newer really play minecraft anaymore, just maintaining my two plugins :-) )

I know it works on eggs :-) but I cant remember how to make a spawner.


Also you can help if you use "/mh debug" kill one or two mobs from the spawer and show me the output in the server console. It might tell whats going on.

**Comment by Sikatsu** [comment]
I am not able to replicate this. The setting works fine for me on a similiar setup but a newer paper version.
