### ISSUE TITLE
When placed heads of players are broken, they disappear

### ISSUE THREAD

**Issue by Momshroom** [Rocologo/MobHunting#624]
My players can properly pick up placed mob heads, but when they break player heads, the player head simply disappears.

MobHunting 7.0.4, 
Paper 1.15.2 (build 146)

**Comment by Rocologo** [comment]
I hope this is fixed now. Please help me with the testing at get back to me.

https://fractal.lindegaard.one:8181/job/BagOfGold/388/
https://fractal.lindegaard.one:8181/job/MobHunting/981/
