### ISSUE TITLE
Player heads not dropping after being placed [mh 7.0.4]

### ISSUE THREAD

**Issue by stw222** [Rocologo/MobHunting#625]
for some reason when my players (or even I) break a playerhead that is placed down, it doesnt drop as an item when obtained via pvp. if an item is obtained via killing a mob, it can be placed down and them picked up

config: [https://pastebin.com/rBWd2jJJ](https://pastebin.com/rBWd2jJJ)

if any other info is needed, just ask

**Comment by Rocologo** [comment]
I hope this is fixed now. Please help me with the testing at get back to me.

https://fractal.lindegaard.one:8181/job/BagOfGold/388/
https://fractal.lindegaard.one:8181/job/MobHunting/981/

**Comment by stw222** [comment]
at first glance it seems to be working

Ill tell my server members to try and break it

**Comment by stw222** [comment]
according to my players, it seems to be working correctly
