### ISSUE TITLE
Logs from MobHunting (BlockPlaceEvent)

### ISSUE THREAD

**Issue by MaxIsV** [Rocologo/MobHunting#636]
![image](https://user-images.githubusercontent.com/58142896/80915244-b5355b00-8d59-11ea-85ff-a870be66d8a3.png)

timings show that this process takes quite a large  % of the time in 7 seconds: https://timings.aikar.co/?id=ddbfb2e7c46d452389fee6ab2fa46305

**Comment by Rocologo** [comment]
This build fixes the problem. (I think) 

https://fractal.lindegaard.one:8181/job/BagOfGold/407/

**Comment by MaxIsV** [comment]
> This build fixes the problem. (I think)
> 
> https://fractal.lindegaard.one:8181/job/BagOfGold/407/

This is a BagOfGold plugin, I do not use it

**Comment by Rocologo** [comment]
Ahh sorry wrong link I posted. But I have made same fix in MobHunting but I can't remember if I made a new build and I'm in bed now so you will have to wait until I get up again.

**Comment by Rocologo** [comment]
Same fix for MobHunting
https://fractal.lindegaard.one:8181/job/MobHunting/1008/
