### ISSUE TITLE
The server cannot stop due to MobHunting

### ISSUE THREAD

**Issue by MaxIsV** [Rocologo/MobHunting#638]
Hello. Recently, I had a problem on the server that it could not stop. It just hung on the moment MobHunting turned off. I transferred a copy of the plugin and its folder to the test server, but there was no such problem.

When I removed MobHunting from the server, it stopped hanging during the stop.

Server ver: paper-1.12.2
Plugin ver: MobHunting-7.0.9-SNAPSHOT-B1008
![82NVxS1](https://user-images.githubusercontent.com/58142896/82055975-f159ab80-96c9-11ea-8239-2c05b9f87531.png)

**Comment by Rocologo** [comment]
Please enable debug mode and then show me the server log when you stop your server

**Comment by MaxIsV** [comment]
> Please enable debug mode and then show me the server log when you stop your server

I will do it later so as not to interrupt the gameplay now. Unfortunately, I could not achieve such a problem on the test server.

**Comment by MaxIsV** [comment]
this is log after stop command: https://pastebin.com/NbkUzQeV

**Comment by MaxIsV** [comment]
I turned on debug-mode and stopped the server, here is the log: https://pastebin.com/NbkUzQeV

(I re-wrote this message)

**Comment by MaxIsV** [comment]
@Rocologo hey ⇑

**Comment by Rocologo** [comment]
I have not forgotten this. But I have made some big changes which i need to finish before i can fix this one. I hope i can make a release tomorrow

**Comment by MaxIsV** [comment]
@Rocologo ._.

**Comment by Rocologo** [comment]
This is fixed in build 1049

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by MaxIsV** [comment]
> This is fixed in build 1049
> 
> https://fractal.lindegaard.one:8181/job/MobHunting/

I just installed this version and my server began to hang immediately after start, and then crashed. As soon as I removed mobhunting-7.5.0-1051, then everything became good.
