### ISSUE TITLE
EntityDeathEvent

### ISSUE THREAD

**Issue by AtomFTW** [Rocologo/MobHunting#640]
20.05 18:54:05 [Server] INFO [MobHunting] [Debug] ======================== New kill ==========================
20.05 18:54:05 [Server] INFO [MobHunting] [Debug] iAtom killed a Skeleton (Minecraft)@(IridiumSkyblock:-847,2,294)
20.05 18:54:05 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v7.0.8
20.05 18:54:05 [Server] INFO org.bukkit.event.EventException
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$null$3(EntitiesListener.java:269) ~[?:?]
20.05 18:54:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
20.05 18:54:05 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/registry/FlagConflictException
20.05 18:54:05 [Server] INFO at one.lindegaard.MobHunting.compatibility.WorldGuardCompat.isAllowedByWorldGuard(WorldGuardCompat.java:71) ~[?:?]
20.05 18:54:05 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:896) ~[?:?]
20.05 18:54:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO ... 12 more
20.05 18:54:05 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.registry.FlagConflictException
20.05 18:54:05 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at one.lindegaard.MobHunting.compatibility.WorldGuardCompat.isAllowedByWorldGuard(WorldGuardCompat.java:71) ~[?:?]
20.05 18:54:05 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:896) ~[?:?]
20.05 18:54:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
20.05 18:54:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
20.05 18:54:05 [Server] INFO ... 12 more

**Comment by rockbyo5** [comment]
getting the same issue. worked before on the server.

**Comment by Rocologo** [comment]
Fixe in build 1049

https://fractal.lindegaard.one:8181/job/MobHunting/
