### ISSUE TITLE
Just sraight up doesn't work?

### ISSUE THREAD

**Issue by FerbFloo** [Rocologo/MobHunting#643]
I used this plugin before (and absolutely loved it btw), but now all it seems to do is output "/mh command" whenever i want to use any /mh command. The payment doesn't work at all :/ Playing on 1.15.2 (and i know it works on that version because i used it before). Possibly just me being a derp.

**Comment by Rocologo** [comment]
I cant tell what you have done wrong, but you need to study your server.log on restart. enable debug using /mh debug and show me the log, if you want my help.
