### ISSUE TITLE
worldgroups.yml ?

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#649]
Spigot 1.15.2
MobHunting 7.5.0-b1024

In the log
```
[18:22:48] [Server thread/INFO]: [BagOfGold] World:world_skyblock was missing in the worldgroups.yml file. It has beed added to the default group. Please review the worldgroups.
```
Neither plugins/MobHunting/ nor plugins/BagOfGold/ contains a worldgroups.yml file.

Please explain.

**Comment by Rocologo** [comment]
This should be fixed too. The file is created in the BagOfGold folder - it is used in both plugins.

**Comment by SlimeDog** [comment]
Message no longer appears, but file does not contain an entry for world_skyblock. However, I have bounties disabled, so maybe that's OK.

**Comment by Rocologo** [comment]
While cleaning up in the code i found the bug. try build 1049 or later and world_skyblock will be created in the default group (buy my guess is that you want to move it?)

**Comment by SlimeDog** [comment]
What is the impact of world_skyblock being in the default group, or not?

**Comment by Rocologo** [comment]
the worldgroups isonly used for Bounties and BagOfGold used as an Economy... so the answer is none.

**Comment by Rocologo** [comment]
MobHunting is not controlling economy sharing. BagOfGold Economy is.

**Comment by SlimeDog** [comment]
OK. Thanks.

**Comment by Rocologo** [comment]
V 7.5.0 Released. I close this ticket now.
