### ISSUE TITLE
Messages spamming 'MobHunting not enabled in this world'

### ISSUE THREAD

**Issue by blazex224** [Rocologo/MobHunting#65]
This isn't necessarily a bug, but I have been trying for a while now to figure out how to remove this message. I disabled MobHunting in some worlds, and every time a player kills a mob it gives them the message 'MobHunting is disabled in this world', and it tends to spam people. I've already tried revoking the MobHunting permissions in those worlds and nothing changes. I'm just wondering how I can remove this message, thanks!

**Comment by Rocologo** [comment]
The message is removed from the player screen in V3.2.6, but is kept in the Server console
