### ISSUE TITLE
NPE on server start

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#658]
Spigot 1.16.1
MH 7.5.0-SNAPSHOT-B1054 updated from 7.5.0-SNAPSHOT-B1051

On server start:
```
[05:11:19] [Server thread/ERROR]: Error occurred while enabling MobHunting v7.5.0-SNAPSHOT-B1054 (Is it up to date?)
java.lang.NullPointerException: null
        at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:142) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar-2020-06-30-2152:git-Spigot-4d9262c-3b9cf0f]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Rocologo** [comment]
Fixed in B1055. (sometimes you are faster than me to test my builds :-) )

**Comment by SlimeDog** [comment]
> sometimes you are faster than me to test my builds

Think about testing them **before** posting them.

**Comment by Rocologo** [comment]
Well you are using my development builds. The Jenkins server is a part of my testing environment. If you are tired of testing (which I would understand) then you should wait until I publish on Spigotmc.org.

**Comment by Rocologo** [comment]
And I do test before I push to Github and my Jenkins server. I mostly test with BOTH plugins running and in this case the bug was only seen when you only use MobHunting.

**Comment by SlimeDog** [comment]
Thanks. Please include "using MobHunting without BagOfGold economy" in the test suite. A lot of bugs in the last two weeks seem to fall into that area.

**Comment by Rocologo** [comment]
I know, but I am using BagOfGold myself so this is my main test. I agree that there has been many bugs the past two weeks, but also I had some NPE bugs before that for more than a month. 

I think you forget that you forget that Im working on this for free and in my limited sparetime.Two plugins, with both Sqlite and MySQL support and integration to about 50 plugins is a pretty heavy job. The bags used in both plugins is rather complex where I need to take care of  alot of player actions. 

I know my bStats and I also know that my absence the past 1½ month has made 30% of the users to leave. Its annoyning but thats how it is, I have been busy on my work, which I of cause need to prioritize. 

Anyway - I think the two plugins is more or less stable again now. (You have not reported any new serious bugs yet :-) ) 

Going forward I will still need help from people who wants to help me with the testing, Im not able to do this myself and do it with a proper quality. You have always been helping me and I appreciate that very much, but I understand I you think the past 14 days has been a pain and that you might need a break.

**Comment by SlimeDog** [comment]
I don't mind testing. I have servers and time dedicated to that task, because I need plugins to work in production. I appreciate that Spigot plugins are labors of love, and I believe strongly that school, work, and life come first.

Having said that, rigorous testing is part of software development, whether professionally or as a volunteer. If you know that the software must pass tests before release, you think more about what goes into the code. The pressure to release should be balanced against quality testing. As examples, NPE and file-not-found and database-locked and disabled-on-start errors should be caught in pre-release testing. When you add new functionality, you should know that it works correctly in the most common environments, which in the case of MH includes both with and without BoG.

**Comment by Rocologo** [comment]
You know I have not even announced a 1.16 version on spigotmc. I have not told anyone that i was working on a big update, its only a few users like you who is downloading snspshots before i release a stable version. 

When you use my snspshots you need to be prepared on bugs and testing otherwise you should wait until i release a stable version on spigotmc.

I am trying to do a proper test but your latest bugreport was a snaphot i had not even tested myself nither asked you to test. So maybe you should not install the snspshot as fast as i build a new one.

**Comment by SlimeDog** [comment]
I'll bear that in mind. Thanks. But why the rush to post untested code to GitHub? It isn't like you're engaged in shared development.

**Comment by Rocologo** [comment]
When i have done initial testing on my laptop i push the code to Github. This trigger the building process on the jenkins server and the i start testing on my own server mc.lindegaard.one 

You could also argue that i should test on all mc 1.8 - 1.15.2 versions. I should test on a fresh install and test the upgrade process on both Sqlite and Mysql, but i dont have the time to do this.

**Comment by SlimeDog** [comment]
I could make that argument, but what's the point? As per above, life takes priority. And the contribution of MH is very much appreciated. It is a main driver for me.

**Comment by Rocologo** [comment]
And I promise to try to make less bugs and better testing:-) 

If you dont find any new serious bugs i will make first 1.16 release on spigotmc tomorrow

**Comment by SlimeDog** [comment]
MH B1055 is working great. But remember that I do not test BoG at all. :)

**Comment by Rocologo** [comment]
Luckily I have tested with BoG because I use it on my own server and the new code which has caused so much pain is mostly shared code, so I think I can make a release now. I will start building the release versions now.

**Comment by Rocologo** [comment]
7.5.0 Released. I close the open tickets now.
