### ISSUE TITLE
Keeps server in limbo whenever I try to restart it

### ISSUE THREAD

**Issue by tyrantkoala** [Rocologo/MobHunting#661]
MobHunting] Disabling MobHunting v7.5.0
05.07 18:21:07 [Server] WARN Exception in thread "MH TaskThread" java.lang.NullPointerException
05.07 18:21:07 [Server] WARN at one.lindegaard.Core.storage.DatabaseDataStore.getPlayerId(DatabaseDataStore.java:375)
05.07 18:21:07 [Server] WARN at one.lindegaard.Core.storage.DataStoreManager.getPlayerId(DataStoreManager.java:97)
05.07 18:21:07 [Server] WARN at one.lindegaard.MobHunting.storage.SQLiteDataStore.saveBounties(SQLiteDataStore.java:294)
05.07 18:21:07 [Server] WARN at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:45)
05.07 18:21:07 [Server] WARN at one.lindegaard.MobHunting.storage.asynch.StoreTask.run(StoreTask.java:12)
05.07 18:21:07 [Server] WARN at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:334)
05.07 18:21:08 [Server] INFO [MobHunting] Closing database connection.

**Comment by tyrantkoala** [comment]
Just updated it to 7.5.0 yesterday

**Comment by FabioZumbi12** [comment]
Seems to be related with #659

**Comment by Rocologo** [comment]
Correct. This is caused by the same SQL error
