### ISSUE TITLE
MobHunting errors on server shutdown

### ISSUE THREAD

**Issue by Momshroom** [Rocologo/MobHunting#665]
Using MobHunting 7.5.0 on paper 79 (1.16.1)
https://paste.gg/p/Momshroom/0a8a12829a7a4aeb8005fc8424550701

**Comment by Weasel-Beans** [comment]
Same issue on 1.15.2 I think. It takes way too long after it claims it's shutting down the database connection, then gives this error.

**Comment by Rocologo** [comment]
This is the same error as #659 

https://github.com/Rocologo/MobHunting/issues/659

Please tryu newest build:

**Comment by Rocologo** [comment]
https://fractal.lindegaard.one:8181/job/MobHunting/
