### ISSUE TITLE
Error on second startup with MobHunting 7.5.0 in 1.16.1

### ISSUE THREAD

**Issue by Momshroom** [Rocologo/MobHunting#666]
On second startup in 1.16.1 (paper 79) with MobHunting 7.5.0, I get this error:
https://paste.gg/p/Momshroom/a4a173da0b92451599585ce2cd84368a
I am not using bag of gold.

**Comment by Rocologo** [comment]
You must have chnaged something in the configuration file? I would check the file using an online yaml  checker 

Ex

https://yamlchecker.com/
