### ISSUE TITLE
Money farm with magma spawners

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#667]
Since 1.16 you can get magma cube spawners, but once you kill the bigger ones the smaller ones will give you money. So they can now use this as a money farm.

**Comment by Rocologo** [comment]
hmm.... I dont know how to solve this... I have no way of detecting that the small ones come from a parent which come from a cube spawner ...

**Comment by Sikatsu** [comment]
Hmm, might disable money from magma cubes until then as a workaround!

**Comment by Rocologo** [comment]
I have been investigating the SPAWN reason. The Magacube has 3 sizes. Large, Medium and Small. If I spawn a LARGE one the children (MEDIUM size) is detected as if they come from a SPAWNER too, but when I the kill one of the MEDIUM size Magacubes, their children is not detected as if they come from a SPAWER. 

The only thing I could do is to deny the splitting when the mother is marked as a SPAWNER, but I not sure if I like to do that? What do you think?

**Comment by Sikatsu** [comment]
That changes the vanilla gameplay I assume, so I am not sure about that either. But currently everyone uses it for a money farm, so that's also a problem. Maybe a toggle?

**Comment by Rocologo** [comment]
Exactly, this is why I dont like it. The slimes/Maga Cubes should spilt like they are meant to be. 

Adding a setting in config where you could deny spiltting when the Slime / Maga Cube is from an Egg/Spawener would not be that hard.

**Comment by Sikatsu** [comment]
It could work, if there is no other way ^^

**Comment by Rocologo** [comment]
Unfortunately I dont see any other way :-(

You can try this build:

https://fractal.lindegaard.one:8181/job/MobHunting/1067/

Check deny_slime_and_maga_cube_to_spilt on config.yml

**Comment by Sikatsu** [comment]
Seems to work ^^

**Comment by Sikatsu** [comment]
@Rocologo 

Seems to also break natural slimes and magma cubes, not from spawners :(

**Comment by Sikatsu** [comment]
Are you here?

**Comment by Rocologo** [comment]
Sorry. I have been away from my plugin some days. 

It is fixed in https://fractal.lindegaard.one:8181/job/MobHunting/1068/

**Comment by Sikatsu** [comment]
Thank you! I will test!
