### ISSUE TITLE
Stackmob 5.2.2 integration Error with mobhunting 7.5.0

### ISSUE THREAD

**Issue by Cloman** [Rocologo/MobHunting#668]
when the mentioned 2 plugins have been installed i am receiving following error:
https://hastebin.com/punaqibude.nginx

Also all rewards even when no error has been thrown are being cancelled

**Comment by SoulDoesDrugs** [comment]
I have the same issue, I use StakcMobs, which is ready for 1.16 but doesn't give rewards when killing stacked mobs.

**Comment by Rocologo** [comment]
The Dev of MobStack must have changed something in his API. You can disable the integration until I find out what he has changed.

**Comment by Rocologo** [comment]
Please help me with the testing. (I dont use StackMob my self) and I am on work so I cant test now.

https://fractal.lindegaard.one:8181/job/MobHunting/lastSuccessfulBuild/

**Comment by Cloman** [comment]
> Please help me with the testing. (I dont use StackMob my self) and I am on work so I cant test now.
> 
> https://fractal.lindegaard.one:8181/job/MobHunting/lastSuccessfulBuild/

done a few test ... till now looks good.
