### ISSUE TITLE
Error when kill mob with new update

### ISSUE THREAD

**Issue by Bossbirdyman51** [Rocologo/MobHunting#669]
HI,
When a player kill a mob i have this error :
https://pastebin.com/9y43rUR6

**Comment by Rocologo** [comment]
com.connorlinfoot.actionbarapi.ActionBarAPI.sendActionBar(ActionBarAPI.java:79)

Its a problem with ActionBarAPI. Have you upgraded it?

**Comment by Rocologo** [comment]
I would recommend you to use Titlemanger instead.

**Comment by Bossbirdyman51** [comment]
Okay Thx i use https://www.spigotmc.org/resources/titlemanager.1049/#:~:text=A%20Spigot%20plugin%20for%20sending%20titles%2C%20setting%20the,for%20your%20player%20list%20and%20a%20scoreboard%20sidebar.

**Comment by Rocologo** [comment]
I use the same
