### ISSUE TITLE
Help with achievements.

### ISSUE THREAD

**Issue by groblerawr** [Rocologo/MobHunting#671]
i cant get achievements to work at all with debug mode on i get [achievements blocked] achievements are disabled for player and i have tried being op and still get the message killing any mobs, i have protocol lib installed and have essentialsx and vault on a paperspigot server with the newest version of mobhunting.
[latest.log](https://github.com/Rocologo/MobHunting/files/4943254/latest.log)

**Comment by Rocologo** [comment]
It was a bug. For some reason the acheivements was not loaeded at all when the player joined. 

Fixed in Build 1066

https://fractal.lindegaard.one:8181/job/MobHunting/
