### ISSUE TITLE
Money dupe glitch

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#672]
I forgot to mention this bug, I had to disable the /mh command because of it. 

https://www.youtube.com/watch?v=UoqCy9_UnxM&feature=youtu.be

**Comment by Sikatsu** [comment]
The /mh money buy <amount> is just really glitchy with the bags and such. Sometimes they disappear, sometimes you can duplicate. I would like to disable this command, but it disables /mh in it's whole

**Comment by Rocologo** [comment]
I agree this is not good. I dont like the number of bags grow when you merge the bags, so this is what I will change. 

This one will take some time because I need to test both plugins at the same time.

**Comment by Sikatsu** [comment]
Thank you!

**Comment by Rocologo** [comment]
I have spend hours on this :-( I works alot better now. 

https://fractal.lindegaard.one:8181/job/MobHunting/1069/

**Comment by Rocologo** [comment]
I forgot to mention that it is only BagOfGold Ím having a small problem with. I have currently not found bugs in MobHunting, and I have done a lot og merging, splitting, swapping and so on... but it is really hard to test all combinations. :-|

**Comment by Rocologo** [comment]
I think this is solved with the InventoryDragEvent I found today.

**Comment by Sikatsu** [comment]
It seems to be solved :)
