### ISSUE TITLE
Error with /mh money shop

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#673]
I don't use this, but while testing for my other ticket I encountered this error: https://pastebin.com/tPsVgx1e

**Comment by Rocologo** [comment]
Yes, I know integration to Shop does not work. It something I have tried to make work, but I didnt succeed and the DEV was not very helpful :-| I should propably remove the command.

**Comment by Rocologo** [comment]
I have disabled the BossShop in next build. I will not continue on this command for now. I dont have the time.

**Comment by Sikatsu** [comment]
Yeah, I don't think I need it anyway ^^
