### ISSUE TITLE
Error occurred while enabling MobHunting v7.5.2 (Is it up to date?)

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#674]
This appeared on startup:

https://pastebin.com/ntGtNFzG

It was working fine, then when I updated QuickShop and nothing else, it broke completely. I am unable to use MobHunting on my server anymore, which is a problem. I've already tried going back a version or two on paper and MH, but neither helped at all.

Timings v2:

https://timings.aikar.co/?id=2c35437141ee4937bd0de317253f990c

**Comment by Rocologo** [comment]
I have no idea about what has happened. It looks like something is looping, but there is no references into my code? The only guess I have is that something is wrong with one of the YAML files (configurations files) and I would start checking your config files (all the yaml formated files) using an online tool like this:

https://codebeautify.org/yaml-validator

**Comment by Weasel-Beans** [comment]
I checked all of the YML files using that, and they all appear valid. However I didn't edit any of them or even update the plugin right before this happened. It was like it was working one moment, then on restart it somehow broke like this.

**Comment by Weasel-Beans** [comment]
Okay I transferred the files to my test server and saw the issue continue there. I then deleted the BagOfGold folder in it's entirety, and the plugin started enabling like it should. This fixed the issue.

I don't use BagOfGold or MobHunting heads, is there any reason why I shouldn't do the same thing to fix it on my live server?

**Comment by Rocologo** [comment]
The BagOfGold folder contains shared infoformation. If you delete this folder you will loose alot of you settings and user statistics.

Did you not check the yaml files in the BagOfGold folder?

**Comment by Weasel-Beans** [comment]
I just did. Here's one that seems to have issues:

https://paste.gg/p/Weasel%20Beans/2cf8ed511cbb43108e26416d0bc8d1a8

**Comment by Rocologo** [comment]
I don understand how you ended up with alot of 

*id001:

in your reward.yml file ??? But this is the problem. Maybe you have deleted a world??, but still i dont understand...

If this is because you have delted a world, you can just delete the rewards manually, the ones containing ***id001:**

**Comment by Weasel-Beans** [comment]
I haven't deleted any worlds, or manually edited that file. I have no idea how that appeared there either.

**Comment by Rocologo** [comment]
Hmm. I seen no other solution than either manually delete the broken sections, but this will make the rewards loose their value. The alternative is to see if you can fix the sections by changing the 

***id0001:** with **world:**

Its not something I can fix in the code.
