### ISSUE TITLE
Spider on the ceiling, drops on the floor above

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#675]
Spigot 1.16.1
MobHunting 7.5.3-SNAPSHOT-B1067

It's a small thing, but
- Spider is hanging from the ceiling
- Room is three blocks high (probably higher would also work)
- Ceiling is one block high, with accessible space above
- Player kills the spider with one stroke, so it dies at the ceiling
- BagOfGold "drops" on the floor above

**Comment by Rocologo** [comment]
So, I drop the item EXACTLY where the mobs dies, but I can choose to spawn the item in two ways. 
1) DropItem
2) DropItemNaturally 
Until now I have been using Naturally (the only difference is a random offset - which explains your observation) I think naturally looks better, but in next release I have changed to 1) so let me know what you think is best.

I will make an official release in a moment.

**Comment by SlimeDog** [comment]
I imagine that random offset was the issue. Amusing that there was a random offset in Y.

I will test throughout the day, and let you know. Since it's random, it will take a large number of tests to feel confident of a result.

**Comment by Rocologo** [comment]
Just make it clear. I removed the random offset. The random offset makes the item fall a little which mskes it look natural

**Comment by SlimeDog** [comment]
Ah. Thanks for the clarification.

**Comment by SlimeDog** [comment]
`dropItem` seems to work fine. Possible alternatives:
- Use `dropItem` only for entities that hang from ceilings or are flying near the ceiling, otherwise use `dropItemNaturally`.
- MC and/or Spigot could fix `dropItemNaturally` so that it does not exhibit the questionable behavior.
- Don't worry about it -- it works fine as-is.
