### ISSUE TITLE
Mobhead glitching (again)

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#679]
When you stack heads, and you then remove them from your inventory slot, it will turn into one head and the others are lost.
With this I mean the heads that drop from mobs.

**Comment by Sikatsu** [comment]
Player made a video: https://www.dropbox.com/s/bsn74t5vh2ajrk0/Minecraft_%201.16.1%20-%20Multiplayer%20%283rd-party%20Server%29%202020-07-30%2014-49-13.mp4?dl=0

**Comment by Sikatsu** [comment]
@Rocologo Any news regarding this?

**Comment by Rocologo** [comment]
This is fixed in 1073 too

https://fractal.lindegaard.one:8181/job/MobHunting/1073/

**Comment by Sikatsu** [comment]
This one seems to be fixed, unless one of my players must be able to reproduce it somehow, but I can't ^^

**Comment by Rocologo** [comment]
I close this for now :-)
