### ISSUE TITLE
java exceptions

### ISSUE THREAD

**Issue by meoso** [Rocologo/MobHunting#68]
i keep getting these:
`[xx:xx:xx ERROR]: Could not pass event CreatureSpawnEvent to MobHunting v3.3.1`

server is up to date:
`[xx:xx:xx INFO]: This server is running CraftBukkit version git-Spigot-af982fc-0df416d (MC: 1.10.2) (Implementing API version 
1.10.2-R0.1-SNAPSHOT)`

**Comment by Rocologo** [comment]
You need to show me the full stack trace error, before I can fix the error?

**Comment by meoso** [comment]
is this right? http://pastebin.com/TZvz62ZE

**Comment by Rocologo** [comment]
Yes, this is perfect. I will look at this error in the morning.

**Comment by Rocologo** [comment]
This error is because you have removed a number from the config.yml. check your prize for all mobs.

**Comment by Rocologo** [comment]
And Show me your config.yml, so i can change the plugin to handle the error better

**Comment by meoso** [comment]
That makes sense -- I moved the config to generate a new one and it was/is going through edits. The new one definitely caused the exception.  This is my latest config, but it probably changed since the error.  http://pastebin.com/2uxeNaU6

**Comment by Rocologo** [comment]
This line has an error
giant: :1.6:2.2

It should be
giant: 1.6:2.2

**Comment by Rocologo** [comment]
This block is missing some spaces

>   disable-achievements-in-worlds:
>  - welcome
>   - welcome_nether
>   - welcome_the_end

**Comment by meoso** [comment]
than might be a paste issue, but i did find this:
`giant: :1.6:2.2`  should be `giant: 1.6:2.2`

**Comment by Rocologo** [comment]
I cant answer your question because its not completely clear to myself. 

Its defined in the YAML standard, so you must use Google to get your answer :-) 

PS. In V3.3.3 i will catch if someone has made the same "typo" error like you had. So I close the issue now.
