### ISSUE TITLE
ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.5.2

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#681]
Timings report: https://timings.aikar.co/?id=459ec5acf1854b8097a87b064ac6b56e

Console Spam: https://pastebin.com/uS3TmVkB

This spams my console sometimes. I think it's related to the Nether being loaded on 1.15.2, and the changes between the mob names.

**Comment by Rocologo** [comment]
Fixed in build 1074

https://fractal.lindegaard.one:8181/job/MobHunting/
