### ISSUE TITLE
Hoppers can pickup dropped money item

### ISSUE THREAD

**Issue by SpaZMonKeY777** [Rocologo/MobHunting#69]
So after officially launching our new survival world and having this plugin setup to drop gold nuggets as the 'money' drop from varying monsters.

Some of my players reported that their dark room spawner setups would sometimes drop money (not a big deal), but their hoppers they kill them over are sucking up the gold nuggets and allowing them to have the actual item, rather than the money it should give them upon picking up manually. This seems like a pretty straightforward bug, as I don't think the placeholder money item should be able ot be picked up via hoppers lol.

**Comment by Rocologo** [comment]
I need somebody to either teach me to make such a "dark room spawner" or even better logon to my server and build one for me, (or make a schematic)  so I can learn how they work and try to find a way to catch the "killings" so they don't spawn money/items.

Are you able to help me here? Maybe you could make a schematic of one the "dark room spawners" which your players has made?

Solving the problem by deny hoppers to collect the items will only solve a part of the problem, but it will not solve the real problem. Mobs generated from spawers should not give money/items at all, but it is unfortunately very hard to detect.

I hope you can help me, so I can get a "Dark room spawner on my server"?

**Comment by Rocologo** [comment]
Hello?

**Comment by Rocologo** [comment]
This is removed in V3.3.6
