### ISSUE TITLE
Bag o Gold - stuck in helmet slot

### ISSUE THREAD

**Issue by marvinej** [Rocologo/MobHunting#691]
if you get a bag of gold in your helmet slot, the only way to get it off yourself is to kill yourself (I did from fall dmg) and when you re-spawn, before collecting your grave, put on a helmet.

**Comment by Rocologo** [comment]
How do you get a BagOfGold in the Helmet slot?

**Comment by marvinej** [comment]
We use AngelChest on my server and when a player retrieves their items, it fills the inventory and puts their armor on. As bag of gold is a head model it tends to stick it in the head slot.
