### ISSUE TITLE
[Question] About Rank multipliers

### ISSUE THREAD

**Issue by rybuilder23** [Rocologo/MobHunting#694]
Hello i want to give my players for a duration of a hour the permission with luckyperms

* mobhunting.multiplier.hasVoted

but when i use debug mode its says that i dont have the rank multiplier

https://pastebin.com/SrFwkh4S
i use paper 185 latest ( 1.16.2 )
and 
mobhunting V7.5.7 

any ideas why i dont have the rank multiplier?
i have the permission

-rybuilder23

**Comment by Rocologo** [comment]
I assume you are giving the player this reward using a command ? Please show me the section in config.yml ?

**Comment by Rocologo** [comment]
You can always test your command running the command in the console. Have you tried this?

**Comment by rybuilder23** [comment]
In the config

http://prntscr.com/uswube

mobhunting.multiplier.hasVoted

i gave the permssions to myself using luckyperms.  /lp user rybuilder23 permission set mobhunting.multiplier.hasvoted true 

then i turned debug on and kilt a wild pig
in my console it says 
https://pastebin.com/geXeFa2H

its says that i have no Rank Multiplier.
but i gave the perm to myself.

**Comment by Rocologo** [comment]
Unfortunately I dont know LuckyPerms, but when MobHunting says that you have no Rank Multiplier it is because LuckyPerms cant find the permission you have added. So you need the check that you actually have the permission "mobhunting.multiplier.hasVoted". I cant help here because I dont know LuckyPerms. I use Permissionsex and here it works fine.

**Comment by rybuilder23** [comment]
i gave myself the permission on luckyperms and it doest not work.
i checked with Permissionsex en there it works fine.

**Comment by Rocologo** [comment]
Then i think  it is a bug in luckyperms. Although i have never tried luckyperms.

**Comment by rybuilder23** [comment]
No longer using this plugin.
