### ISSUE TITLE
Database error "PublicKeyRetrieval"

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#698]
Good afternoon, I recently updated my server by installing Ubuntu server 20.04LTS (previously 18.04). It has mysql 8 installed. Plugins cannot access the database indicating "Public Key Retrieval is not allowed". 

In all the plugins I have been able to put a directive where the database is specified a directive. But mobhunting did not let me, it keeps giving error. I have put it in all the plugins like this and it works "database_name: MMCabezas?allowPublicKeyRetrieval=true".

Is there a solution for this problem? Thank you.

**Comment by Rocologo** [comment]
Adding "?allowPublicKeyRetrieval=true" to the hostname should work. This is my code:

dataSource.setDatabaseName(Core.getConfigManager().databaseName + "?autoReconnect=true&useSSL="
					+ Core.getConfigManager().databaseUseSSL);

Which error do you get?
