### ISSUE TITLE
Console error, MobHunting not working.

### ISSUE THREAD

**Issue by sveTlys** [Rocologo/MobHunting#699]
Hi, as the title says, all of the sudden MobHunting is not working on my minecraft dedicated server. I'm running a Paper server 1.16.3 #216. Here is the error from the console when the server is trying to run MobHunting:

> 07.10 08:54:07 [Server] INFO Enabling MobHunting v7.5.7
> 07.10 08:54:07 [Server] INFO Your config version is 1
> 07.10 08:54:07 [Server] INFO Existing config.yml loaded.
> 07.10 08:54:07 [Server] INFO Config.yml was backed up to plugins/MobHunting/backup/config.yml.bak8
> 07.10 08:54:08 [Server] INFO BagOfGold is not installed on this server
> 07.10 08:54:08 [Server] INFO Enabling compatibility with MobHunting (7.5.7)
> 07.10 08:54:09 [Server] ERROR Error occurred while enabling MobHunting v7.5.7 (Is it up to date?)
> 07.10 08:54:09 [Server] INFO java.lang.NullPointerException: null
> 07.10 08:54:09 [Server] INFO at one.lindegaard.Core.rewards.Reward.read(Reward.java:257) ~[?:?]
> 07.10 08:54:09 [Server] INFO at one.lindegaard.Core.rewards.RewardBlockManager.load(RewardBlockManager.java:131) ~[?:?]
> 07.10 08:54:09 [Server] INFO at one.lindegaard.Core.rewards.RewardBlockManager.<init>(RewardBlockManager.java:39) ~[?:?]
> 07.10 08:54:09 [Server] INFO at one.lindegaard.Core.Core.<init>(Core.java:57) ~[?:?]
> 07.10 08:54:09 [Server] INFO at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:143) ~[?:?]
> 07.10 08:54:09 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-216]
> 07.10 08:54:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
> 07.10 08:54:09 [Server] INFO Disabling MobHunting v7.5.7

**Comment by Rocologo** [comment]
It looks like your rewards.yml file is broken. Try check the contents with an online yaml checker

**Comment by sveTlys** [comment]
> It looks like your rewards.yml file is broken. Try check the contents with an online yaml checker

Hi, thanks for the reply.

I can't find the rewards.yml; I've also used a fresh one MobHunting jar with the last version after deleting the others jar and configs, I can't still see that rewards.yml if its supposed to be inside of the folder that the plugin creates. 

If its not supposed to be inside of that plugin folder where I can find it?

**Comment by Rocologo** [comment]
Check the Bagofgold folder ;-)

**Comment by Rocologo** [comment]
Did you solve you error?
