### ISSUE TITLE
We need a compatibility with latest worlguard for mc 1.10 :(

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#70]
if we have the latest wg
[00:16:35 INFO]: [MobHunting] Enabling compatibility with WorldGuard (**6.1.3**-SNAPSHOT;**1680**-2aaa142)
[00:16:35 ERROR]: Error occurred while enabling MobHunting v3.3.4 (Is it up to date?)

so mh not finish to load completly (mh is broken), i know you already know that but no issue open about that so i created this :)

**Comment by Rocologo** [comment]
Wg 6.1.3 is a development version and is not stable. Let me ask why you have upgraded to 6.1.3? 

MH works fine on WG6.1.2

**Comment by Rocologo** [comment]
PS 6.1.3 + mh 3.3.4 works fine on mc.lindegaard.one but it does not work on my test server. When wg6.1.3 is being released in a stable version i will fix the problem.

**Comment by Rocologo** [comment]
Also I have contacted the developer of WorldGuard but he just said that CustomFlags are not supported :-( and didnt give me any advise to fix this. SO I have to wait for official release of 6.1.3

**Comment by Rocologo** [comment]
Fixed in V3.3.5
