### ISSUE TITLE
Kills Database not saving

### ISSUE THREAD

**Issue by SkullzMeister** [Rocologo/MobHunting#702]
I'm having an issue where the database doesn't seem to be saving any kills. MasterMobhunters just say NO KILLS, and the '/mh top total_kills alltime' command just returns "no results".

I've already tried deleting the database and restarting, as well as doing that along with setting the database version to 0 in the config and still nothing has worked

**Comment by readme55** [comment]
i have the same problem. Heres my post from spigot:

im having the same issue as DeadeyeSkunk and SkullzMeister. Data is written into the database (sqlite, i checked) but its not loaded. So leaderboard is empty and /mh top TotalKills AllTime also saying "no results found".

Update: I switched from sqlite to mysql and now got some errors in log:

1.12 15:49:44 [Server] WARN one.lindegaard.Core.storage.DataStoreException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`customer_149197_mh`.`mh_Daily`, CONSTRAINT `mh_Daily_Player_Id` FOREIGN KEY (`PLAYER_ID`) REFERENCES `mh_Players` (`PLAYER_ID`) ON DELETE CASCADE)
01.12 15:49:44 [Server] WARN at one.lindegaard.MobHunting.storage.MySQLDataStore.savePlayerStats(MySQLDataStore.java:279)

**Comment by Espinete1987** [comment]
Me the same, waiting for solution since July...

**Comment by ohioaschwar** [comment]
Has a fix been found for this yet?  I'm having a similar issue.
-I can create leaderboards using MobHunting but they show no data
-/mh kills shows some data but it seems to get overwritten on the next login
-/mh top - "No results for all time", "No results for This Week,"
using SQLite

Likewise, the citizens2 npc banker in Bagofgold doesn't have any selectable options in his dialog.  I'm including this here in case these issues co-occurring are relevant.

Also using EssentialsX, Luckyperms, Protocollib, Multiverse-core, perworldinventory

Any ideas?

**Comment by Espinete1987** [comment]
> Has a fix been found for this yet? I'm having a similar issue.
> -I can create leaderboards using MobHunting but they show no data
> -/mh kills shows some data but it seems to get overwritten on the next login
> -/mh top - "No results for all time", "No results for This Week,"
> using SQLite
> 
> Likewise, the citizens2 npc banker in Bagofgold doesn't have any selectable options in his dialog. I'm including this here in case these issues co-occurring are relevant.
> 
> Also using EssentialsX, Luckyperms, Protocollib, Multiverse-core, perworldinventory
> 
> Any ideas?

Buddy, i finally found something that was too obvius, but i dont know why nobody offered... even Rocologo should have offered this...
[url=https://ibb.co/Njnq9KL][img]https://i.ibb.co/6PJSHF4/Hall-of-game14leaderboards.jpg[/img][/url]

Just find another Leaderboard plugin, i have used https://www.spigotmc.org/resources/%E2%9C%85-alonsoleaderboards-1-8-1-16-%E2%80%A2-signs-heads-armorstands-npc-placeholders-developerapi.84267/ its a bit tricky to understand how to do it but i have all what i wanted finally!

**Comment by ohioaschwar** [comment]
I might have to try that one out...but I was hoping that the solution would be something other than 'find a different plugin.'
