### ISSUE TITLE
MobHunting and Citizens Error

### ISSUE THREAD

**Issue by J-SHarper** [Rocologo/MobHunting#703]
With MobHunting and [Citizens](https://www.spigotmc.org/resources/citizens.13811/)/[Sentinel](https://www.spigotmc.org/resources/sentinel.22017/) installed, every time an NPC dies, MobHunting spams the console with this [error](https://paste.md-5.net/utefiniyes.cs). 

Server: Paper-211
MobHunting: 7.5.7
Citizens: 2.0.27-b2143
Sentinel: 2.2.0-SNAPSHOT-b375.jar

**Comment by Rocologo** [comment]
I have tested what happens when I kill an NPC on my test-server. I dont get this error, so you must do something else than I do. 

Could you please elaborate about, what you mean by "an NPC dies" how?

**Comment by Rocologo** [comment]
Could you please help me with the testing and try newest snapshot? https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by J-SHarper** [comment]
Yes! I’ll give it a shot, thanks

**Comment by J-SHarper** [comment]
Updated to the latest snapshot - I'll let you know if it reoccurs. On the one right before it (1099) it was spamming this error: https://paste.md-5.net/ufalorevus.cs.

We have sentinels set up to attack monsters, so I can only assume it is happening every time a sentinel NPC is killed by a monster
