### ISSUE TITLE
Console hude warn: IllegalStateException: Asynchronous Async Chunk Load!

### ISSUE THREAD

**Issue by MaxIsV** [Rocologo/MobHunting#705]
Hello, not too long ago, I created a similar issue where you told me to clear the **/BagOfGold/rewards.yml** file, after which the error was gone. But then it reappeared: https://pastebin.com/ECtrmArJ

I only inserted a small part of the error, since it is repeated thousands of times.

Also, when the server is turned off, MobHunting turns off for a very long time. After these messages, I have to wait about 5 minutes:
**[20:40:34] [Server thread / INFO]: [MobHunting] Disabling MobHunting v7.5.7
[20:40:35] [Server thread / INFO]: [MobHunting] Closing database connection.**

MobHunting-7.5.7
PaperSpigot-1.12.2

**Comment by Rocologo** [comment]
I think this is fixed in newest release.
