### ISSUE TITLE
Don't Get Money

### ISSUE THREAD

**Issue by ColbyPlayz** [Rocologo/MobHunting#71]
I'm on my 1.10.2 Spigot Server with the latest version of MobHunting. Whenever I kill a mob or person, I get no money!

Also, this is unrelated, but is there a way to not give player skulls on drop!

**Comment by ColbyPlayz** [comment]
this is a message I get in the config. idk if it helps:

Could not pass event PlayerMoveEvent to MobHunting v3.3.5

**Comment by Rocologo** [comment]
Do you see any errors in the console? 

Try to do 

/mh learn

/mh debug 

Kill a spider and let me see the result in the console.

**Comment by Rocologo** [comment]
And yes its up to you if your players get a head or something else. Check the settings in config.yml. change the run commands or the frequency

**Comment by ColbyPlayz** [comment]
the only error i see is:

Could not pass event PlayerMoveEvent to MobHunting v3.3.5

**Comment by ColbyPlayz** [comment]
i use mcprohosting so the console has a lot in it

**Comment by ColbyPlayz** [comment]
heres the console:

ERROR Could not pass event PlayerMoveEvent to MobHunting v3.3.5
19.07 18:52:39 [Server] INFO ... 23 more
19.07 18:52:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
19.07 18:52:39 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
19.07 18:52:39 [Server] INFO at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[?:?]
19.07 18:52:39 [Server] INFO at one.lindegaard.MobHunting.MobHunting.onMobDeath(MobHunting.java:752) ~[?:?]
19.07 18:52:39 [Server] INFO Caused by: java.lang.NullPointerException
19.07 18:52:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntitySpider.m(EntitySpider.java:45) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityMonster.m(EntityMonster.java:32) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:240) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1744) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.Entity.m(Entity.java:303) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityInsentient.U(EntityInsentient.java:180) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.U(EntityLiving.java:191) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityMonster.damageEntity(EntityMonster.java:48) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:911) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.die(EntityLiving.java:1008) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:391) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:39 [Server] INFO org.bukkit.event.EventException
19.07 18:52:39 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v3.3.5
19.07 18:52:38 [Server] INFO ... 24 more
19.07 18:52:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
19.07 18:52:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
19.07 18:52:38 [Server] INFO at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
19.07 18:52:38 [Server] INFO at one.lindegaard.MobHunting.MobHunting.onMobDamage(MobHunting.java:567) ~[?:?]
19.07 18:52:38 [Server] INFO Caused by: java.lang.NullPointerException
19.07 18:52:38 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
19.07 18:52:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1578) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.EntityMonster.damageEntity(EntityMonster.java:48) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:826) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-a9631d2-67b2424]
19.07 18:52:38 [Server] INFO org.bukkit.event.EventException

**Comment by ColbyPlayz** [comment]
Could any plugins be messing with it?

**Comment by ColbyPlayz** [comment]
?

**Comment by ColbyPlayz** [comment]
i think slimefun is messing with it
it hasnt before though so did the update bring something

**Comment by Rocologo** [comment]
Please test latest succesful build here on my Jenkins Server
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Nesseley** [comment]
I have the same problem. 
Tested with the latest build (3.3.6), Vault and iConomy.
(Vault and iConomy works with ChestShop, so its not them thats wrong)

No error in console, not even when I type commands or kill mobs.

**Comment by Nesseley** [comment]
Plugins like Orebfuscator and holographic displays makes mobhunting not work.

**Comment by Rocologo** [comment]
@Nesseley have you tried to use /mh learn and /mh debug?

**Comment by Rocologo** [comment]
And I use Holographic Dislays on my own server without problems. I dont think there is a conflict?

**Comment by Nesseley** [comment]
It seems like I dont have permission to get money by default.
Right now I have a non edited Config, fresh installed plugin.
Config: http://pastebin.com/9zQXjZcQ 

I give myself perms to /mh debug, and the perms to get money (mobhunting.enable), and I still dont have permission for eighter of them. (I've tried restarterting the server too)

**Comment by Nesseley** [comment]
Edit: I fixed the problem by giving the perm: mobhunting.mobs.*
Wierdly enough now my /mg debug permissions works too...

Tried removing mobhunting.mobs.* too se what happened, now I can use /mh debug.

I dunno what is wrong, but mobhunting.mobs.* + mobhunting.enable fixes the problem.

**Comment by Rocologo** [comment]
Hi 

Mobhunting.enable should be enough. If the player dont have Mobhunting.mobs.* it will default to true. And this works fine on my test server. Maybe its the permission plugin? I test with PermissionsEx what do you use?

**Comment by Nesseley** [comment]
I run bungeeperms for permissions :)

**Comment by Rocologo** [comment]
This seems to be solved now? Try V3.3.6
