### ISSUE TITLE
Mobhunting gives incompatibility warning with newer Towny versions

### ISSUE THREAD

**Issue by Momshroom** [Rocologo/MobHunting#712]
`[09:43:11 INFO]: [MobHunting] Your version of Towny (0.96.7.1) is not complatible with this version of MobHunting, please upgrade.  `

MobHunting version 7.5.8-SNAPSHOT-B1100

Paper version git-Paper-446 (MC: 1.16.5)

**Comment by Rocologo** [comment]
Do you still have this problem?
