### ISSUE TITLE
/mh mute doesnt stop notifications

### ISSUE THREAD

**Issue by krustymk** [Rocologo/MobHunting#72]
As the title says
cheers

**Comment by Rocologo** [comment]
Which notifications?

**Comment by krustymk** [comment]
? if it mutes notifications shouldn't it mute all? (apart from Admin only ones)
**Enemy Bleeding**
There is no rewards for killing this mob
are 2 that spring to mind

**Comment by krustymk** [comment]
![spam](https://cloud.githubusercontent.com/assets/5390088/17114298/32ea6308-52a6-11e6-89fb-5dd6cbb3487e.jpg)

**Comment by Rocologo** [comment]
You are in learning mode. Disable with /mh learn

**Comment by krustymk** [comment]
Thanks
