### ISSUE TITLE
MobHunting 8.0.0 not compatable with LuckPerms 5.3.47

### ISSUE THREAD

**Issue by datsme** [Rocologo/MobHunting#721]
Cannot use in game commands or control panel commands.
Tried mh version, mobhunt version, help mobhunt etc all commands return same: "/mh command" 
However players are still getting drops. Though all other commands do not work.
For testing I only have Luckperms v5.3.47, Mobhunting v8.0.0, Vault v1.7.3-b131, & ProtocolLib  v4.7.0-SNAPSHOT-b526 on Paper version git-Paper-79 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a831634)
I am the op/owner and have added  - mobhunting.* in my LuckPerms "users" file but it still does not work.

**Comment by datsme** [comment]
Updated LuckPerms to v5.3.50 and still has the same issue.

**Comment by SlimeDog** [comment]
ProtocolLib has not been update to 1.17.1 yet.
