### ISSUE TITLE
JDBC driver error

### ISSUE THREAD

**Issue by Blank517** [Rocologo/MobHunting#726]
**Java Version** _(aarch64)_
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)
```
**Error**
`java.lang.NoClassDefFoundError: com/mysql/jdbc/jdbc2/optional/MysqlDataSource`

**Plugins**
MobHunting-8.0.4.jar
ProtocolLib-4.7.0.jar
Vault-1.7.3-b131.jar

**Logs**
[Hastebin: latest.log](https://hastebin.com/enudukiteh.yaml) 

**Possible fix**
[StackOverflow _ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource_](https://stackoverflow.com/a/39961651)

**Comment by Rocologo** [comment]
You are having a problem with your MySQL database. com/mysql/jdbc/jdbc2/optional/MysqlDataSource is not to be included in any plugin.
