### ISSUE TITLE
MONEY DUPE

### ISSUE THREAD

**Issue by weedorpy** [Rocologo/MobHunting#727]
Hello! 
I am having a problem on the server finding a way to dupe money.
What you have to do is simply put money in the money bag, then divide them each and throw them on the ground, when you put the money bags together, you multiply, for example if you divide 10k and throw them on the ground, it gives you 15k.

◆ MobHunitng 8.0.4
◆ Purpur-1.17.1-1393
◆ Config.yml - Pastebin
      https://pastebin.com/UWQD1ztG
◆ Duping money:
      https://drive.google.com/file/d/1wd7uZVMvE-zAPg9sH5k7nA8bMdvKiPEf/view?usp=sharing

I take this opportunity to tell you that I have the plugin translated into Spanish and I am willing to share the translated file with the community and with you. 👍

**Comment by Rocologo** [comment]
This is fixed in BagOgGold 4.1.4 and MobHunting 8.1.1

**Comment by weedorpy** [comment]
Hello! i tested de new release and have this result.

This server is running Purpur version git-Purpur-1565 (MC: 1.18.1)

When I have money, and I buy, for example 10k of bagofgold, it deducts me from my balance and when I throw the money on the ground it deducts the money again, when I pick up the money, it gives me what the bagofgold should give me, but it does not give me back the money that I deducted when I put the bagoflgold. The video speaks for itself.
https://drive.google.com/file/d/10QDnN5SiGJPUSN3nMi3cdEEpqMRotJWz/view?usp=sharing


We are hype with the new update to the new version, we eagerly hope that the plugin is stable to use it again on our server.
Previously I was working on a full translation into Spanish, my community is a big fan of the plugin so we would like to provide the full translation to the plugin.

**Comment by weedorpy** [comment]
Hello good! again. I apologize for the previous report, the plugin no longer has an error when duplicating and also does not have that error when changing these values ​​in the `config.yml`

  drop_money_on_ground: true
  drop_money_use_item_as_currency: true

This is the video where I show that there is no duplication of money
https://drive.google.com/file/d/136HV7E9bXRJr4Q_oqVoV8am3mniewqWG/view?usp=sharing
This is the

**Comment by Rocologo** [comment]
I need to know if you also use my other plugin BagOfGold or if it is only MobHunting?

**Comment by weedorpy** [comment]
just MobHunitng. Not usign BagOfGold
