### ISSUE TITLE
Panilla blocking BagOfGold NBT?

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#728]
It looks like [Panilla](https://www.spigotmc.org/resources/panilla-prevent-hacked-items.65694/) is not happy with an NBT tag in BagOfGold. Panilla provides the opportunity to accept specific NBT, but I don't know what it is. Is there a way to find out, or could you just post it. For references, the Panilla configuration entry is
```
# Whitelist NBT tags from being checked
# Keep in mind some NBT tags vary between Minecraft versions
#     (eg: ench on 1.12 vs Enchantments on 1.13)
nbt-whitelist:
#  - Enchantments
```

**Comment by Rocologo** [comment]
I dont know Panilla, but I guess it is Panilla that should change something? Isnt it?

**Comment by SlimeDog** [comment]
Trying to get PowerNBT updated to MC 1.19.x, so I can capture the NBT. See https://github.com/SlimeDog/PowerNBT/issues/1
