### ISSUE TITLE
% symbol for robbing not working

### ISSUE THREAD

**Issue by Dy-oh** [Rocologo/MobHunting#729]
Hi, I'm using the plugin on 1.18. player rob and mob rob seem to work fine for normal number integers and ranges ex. 50:200 so when a mob kills you it takes between 50 and 200 dollars, but as soon as I make it a % so 10% where of you die a player or mob takes 10% of your money it stops working. Is there a symbol or formatting I can use instead of % to bypass this bug while it's being fixed as It's a core feaure I want for my server.

**Comment by Rocologo** [comment]
Please show me which setting you are changing? 

I think I have made it possible to steal from another player (PVP robbing) but I cant remember that I have made it possible for a Mob to rob a Player? Have i? :-D

**Comment by Rocologo** [comment]
The idea is that when the money is dropped as rewards (bag of gold) then the player can loose ALL his money in his inventory along with the other items in his inventory.
