### ISSUE TITLE
bagofgold sell signs no longer working.

### ISSUE THREAD

**Issue by gerardvanschip** [Rocologo/MobHunting#731]
I'm on paperspigot 155 with MobHunting-8.0.6 and while dropping bags of gold works players can no longer sell them using signs. The /mh bag sell still works and the signs convert type to green Bag Of gold meaning that works.

I checked the discussion for the plugin and no one mentions that, saw someone talking about the head sell sign no longer working, maybe related?

**Comment by Rocologo** [comment]
I have test that I can sell both MobHeads and BagOfGold items on my test-server (SpigotMC) I dont have a PaperSpigot to test with.

please notice that it is two different signs you use when you sell heads and bags.
