### ISSUE TITLE
Automatic sale of coins

### ISSUE THREAD

**Issue by GeneralViski** [Rocologo/MobHunting#732]
Is it possible to somehow make it so that when selecting money, they are immediately added to the money from essentials? To not be stored in a person's inventory

**Comment by Rocologo** [comment]
Yes, Check this section

`# ########################################################################
# DropMoneyOnGround for servers WITHOUT the BagOfGold plugin installed
# ########################################################################
dropmoneyonground:

  # When a player get a money reward for a kill, the money will go directly
  # into his pocket. If you set dropMoneyOnGround=true the reward will 
  # dropped on ground to be picked up by the player.
  # Negative rewards will always be taken from the player. 
  # 
  # OBS Notice if you have the BagOfGold plugin installed these settings will be 
  # overruled by the settings in BagOfGold config.yml !!!
  drop_money_on_ground: true

  # If you dont want to use BagOfGold (https://dev.bukkit.org/projects/bagofgold) 
  # as you economy plugin, but still want to bags to be dropped on the ground, 
  # you can set this to true and then the player will be able to pick up the bags 
  # and use MobHunting signs to sell the Bags and get the money this way.
  drop_money_use_item_as_currency: true`

set  "drop_money_on_ground: **false**"
