### ISSUE TITLE
Unable to change text colour of config placeholder {killed} for most mobs.

### ISSUE THREAD

**Issue by dfeneck** [Rocologo/MobHunting#733]
Strangely enough, it works for Magma Cubes, just not most other mobs.

I've attached a picture that shows the config, and the results.
Note the same happens for the drop head text too.
![Config Example](https://user-images.githubusercontent.com/78724526/159113569-62a7f932-0f84-439f-9f7d-28296303a27f.jpg)

**Comment by Rocologo** [comment]
This is probably because of your colorcode in the MobNames in the language file. 

mobs.ZombiePigman.name=§9Zombie Pigman 

which says it should be blue.
