### ISSUE TITLE
Wrong name in the dropped money message when using Bags of Gold.

### ISSUE THREAD

**Issue by dfeneck** [Rocologo/MobHunting#734]
My Gringotts currency is Diamonds, however I have MobHunting dropping Bags of Gold for money, but when it does it calls them the Gringotts currency name instead of the defined bag of gold name. See picture attached:
![image](https://user-images.githubusercontent.com/78724526/159115244-1fe3d073-c826-4ce6-a502-9d22afa9eb59.png)

I believe the name is coming from Gringotts config.yml instead of the MobHunting generated BagofGoldCore.yml. (as I don't have Bags of Gold jar installed)

**Comment by Rocologo** [comment]
If you economy plugin is Gringotts then MobHunting should use the currency names from your Gringotts plugin, not from the BagOfGoldCore.yml unless you have some special configuration of MobHunting which I dont know of?
