### ISSUE TITLE
Leaderboard: Wither Skeleton Kills (All Time) isn't working

### ISSUE THREAD

**Issue by dfeneck** [Rocologo/MobHunting#735]
We've definitely killed some Wither Skeletons by now, and the leaderboards aren't updating. All other leaderboards are so far working fine I think so far.

* Also, while I'm here, could I ask for an update to the color of your text, it would be good if the whole mob name was blue, as you can see with the Wither Skeleton, only line 2 is blue, 3 and 4 change back to white (or dye color in this case)

![image](https://user-images.githubusercontent.com/78724526/159115392-3a0a85e9-99a1-4f50-bf03-477fcc928df3.png)

**Comment by Rocologo** [comment]
I have changed the way I handle color in your "Ender Dragon kils" ticket and the updating should not have anything to do with the type of the Mob. So I need you to try to destroy the leaderboard and create it again, and see if the leaderboard is updating. Also notice that there is a delay. The leaderboard show the number of killed mobs SAVED TO DISK :-)
