### ISSUE TITLE
Cannot Create Leaderboards of any kind, with any plugin

### ISSUE THREAD

**Issue by Vindrys** [Rocologo/MobHunting#739]
Hi first off let me say thank you, your plugin has been detrimental to the creation of my first server and I can't wait to utilize it to it's full potential. I am unfortunately having one minor bug where I cannot create any Leaderboards with or without plugins for Holograms or Holographic Displays, I can't even seem to make Leaderboards on Signs. If you could please assist me in this endeavour I would be greatly appreciative, this leaderboard system is the VERY LAST piece of the puzzle before I can start play testing my server. I'm looking to create leaderboards that show; Most Kills that Day, Total BagsOfGold from all players that day, Wither Kills and a special MysticMobs boss named Rocky kill as well. I've installed all the necessary plugins to make everything work (Vault, ProtocolLib, BagsOfGold, Essentialsx/Spawn) together to create a sort of RPG game mode where players can "Win" by achieving one of the aforementioned conditions above. After I get the Leaderboards figured out all I need is to figure out how to slap a timer on it to make it it's own game mode!!

**Comment by Rocologo** [comment]
The command to create Leaderboards is

/mobhunt leaderboard create <stattype> <period> <horizontal?> <width?> <high>?

You will need to have permission: mobhunting.leaderboard

https://www.spigotmc.org/wiki/mobhunting-commands-permissions/
