### ISSUE TITLE
1.19 Mobhunting issue with mtranslationtables

### ISSUE THREAD

**Issue by Michael-A-Sloan** [Rocologo/MobHunting#746]
Hello I'm running the post updated paper 1.19 server.

I just updated the MobHunting plugin and am getting errors when people join the game.

Here is what it says anytime someone joins. https://pastebin.com/w3GPvGkt

**Comment by Michael-A-Sloan** [comment]
Yep and still the same thing. idk if it impeads the gameplay any but I know I see it each time.

**Comment by Airijko** [comment]
I have the same issue

**Comment by Rocologo** [comment]
Fixed in release 8.1.5
