### ISSUE TITLE
The server won't stop

### ISSUE THREAD

**Issue by Innesity** [Rocologo/MobHunting#747]
Hi. The server will stuck on disabling mobhunting and never stop itself after you will kill the server on pterodactyl. Can you please fix this? 
![Screenshot_19](https://user-images.githubusercontent.com/59732057/178608587-190b1218-cece-456f-90c2-6c0d8814cb1c.png)

**Comment by Rocologo** [comment]
This is probably because another database operation happened earlier in the server log. I need to see this error?

**Comment by Innesity** [comment]
> This is probably because another database operation happened earlier in the server log. I need to see this error?

https://mclo.gs/594mH1s -- this is the full log.

**Comment by Innesity** [comment]
@Rocologo Hey. Can you take a look, please?

**Comment by Rocologo** [comment]
I'm on vacation without my computer. You should look for SQL errors in the server log, to find the root cause for why the plugin can't stop.



Sendt fra Samsung Galaxy S10+



-------- Oprindelig besked --------
Fra: Innesity ***@***.***>
Dato: 24.07.2022 13.08 (GMT+03:00)
Til: Rocologo/MobHunting ***@***.***>
Cc: Rocologo ***@***.***>, Mention ***@***.***>
Emne: Re: [Rocologo/MobHunting] The server won't stop (Issue #747)


@Rocologo<https://github.com/Rocologo> Hey. Can you take a look, please?

**Comment by loherlihy** [comment]
Hey there wanted to jump in, I am having the same issue ever since updating to 1.19. Sometimes It will disable Mobhunt later on in the shutdown process. Worst case scenarios Mobhunt will be the first plugin to be disabled meaning all plugins beyond it will not be shutdown correctly. This has happened only a few times but has reset entire plugins. My log looks essentially the same as Innesity: Ending in  [MobHunting] Disabling MobHunting v8.1.5

I have searched for sql errors and as of now have found none. The server will not restart properly when being online for quite a few hours. If the server has only been online for a couple hours it will reset normally.

Thanks in advance!

**Comment by Rocologo** [comment]
Sorry for the big delay. I have not had time to look at it because of vacation. 

I have checked the full log. I need you to enable debug so I can get more information

/mh debug

and the I would like to see a new log?

**Comment by Rocologo** [comment]
The end of the log is fine, for now.

**Comment by Innesity** [comment]
> Sorry for the big delay. I have not had time to look at it because of vacation.
> 
> I have checked the full log. I need you to enable debug so I can get more information
> 
> /mh debug
> 
> and the I would like to see a new log?

I will try later tonight and come back with the log to you :)

**Comment by Innesity** [comment]
Started debugging, will provide the full log later this evening, when the Cloud System will restart all subservers

**Comment by Innesity** [comment]
> Sorry for the big delay. I have not had time to look at it because of vacation.
> 
> I have checked the full log. I need you to enable debug so I can get more information
> 
> /mh debug
> 
> and the I would like to see a new log?

https://mclo.gs/Gr2MRKt -- here is the new log

**Comment by Rocologo** [comment]
Thank you. This line conform that it is because of MobHunting.

<html><body>

  | [03:00:35] [Server thread/INFO]: [MobHunting] [Debug] waitForEmptyQueue: Waiting for 607+0 tasks to finish before closing connections.
-- | --

</body>
</html>

It tells me that MobHunting cant save to the database. 607 updates is waiting before MobHunting will continue. This usually happens when you see an SQL error in the log. In your case I dont see any SQL errors so maybe MobHunting dont have permission to write to the Database? Are you using MySQL og Sqlite ? If you use MySQL you should try to re-grant permissions .

1) are you using MySQL or Sqlite ?
2) Please show me the "beginning" of the server log, so I can check what MubHunting is doing and chack that it seems to be okay.

**Comment by Innesity** [comment]
> Thank you. This line conform that it is because of MobHunting.
> 
>   | [03:00:35] [Server thread/INFO]: [MobHunting] [Debug] waitForEmptyQueue: Waiting for 607+0 tasks to finish before closing connections.
> It tells me that MobHunting cant save to the database. 607 updates is waiting before MobHunting will continue. This usually happens when you see an SQL error in the log. In your case I dont see any SQL errors so maybe MobHunting dont have permission to write to the Database? Are you using MySQL og Sqlite ? If you use MySQL you should try to re-grant permissions .
> 
> 1. are you using MySQL or Sqlite ?
>    1.5) If you are using MySQL check the SQL permissions
>    1.6) If you are using Sqlite, try to stop the server. Rename MobHuning.db to MobHunting.db.bak and start the server. This will regenerate the database and database tables but also reset player stats! This will tell you if there is a problem with the database.
> 2. Please show me the "beginning" of the server log, so I can check what MubHunting is doing and chack that it seems to be okay.

The log is very big because of debugging, so I uploaded on my OneDrive account. Here is the link: https://1drv.ms/u/s!AsF-5OgB6mTPgYQi7VqXfleVEA4AMQ?e=m8bGQu

Note that I will delete the log after 6 hours because of security issues that may appear by sharing IPs and other things. I am using SQLite. I wanted to move to MySQL, but I don't know if there's a way to migrate data without any loss.

**Comment by Rocologo** [comment]
Unfortunately you cant migrate data :-( but Sqlite should work anyway. Make sure that MobHuting.db is writeable and not write protectet or something.

You can send the beginning of the log to my personal email if that better. Its 

rocologo AT hotmail.com

**Comment by Innesity** [comment]
> Unfortunately you cant migrate data :-( but Sqlite should work anyway. Make sure that MobHuting.db is writeable and not write protectet or something.
> 
> You can send the beginning of the log to my personal email if that better. Its
> 
> rocologo AT hotmail.com

I sent the email.

**Comment by Rocologo** [comment]
I have actually found a MobHunting error in the log file you send me. This is probably the reason for the problem.  I cant tell why you get at ConcurrentModification on your server and I dont get it on my server, but now I have something to look at when I get home from work. 

[15:11:26] [BGC StoreThread/WARN]: Exception in thread "BGC StoreThread" java.util.ConcurrentModificationException
[15:11:26] [BGC StoreThread/WARN]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[15:11:26] [BGC StoreThread/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
[15:11:26] [BGC StoreThread/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
[15:11:26] [BGC StoreThread/WARN]: 	at MobHunting-8.1.5.jar//one.lindegaard.Core.rewards.RewardBlockManager.save(RewardBlockManager.java:83)
[15:11:26] [BGC StoreThread/WARN]: 	at MobHunting-8.1.5.jar//one.lindegaard.Core.storage.DataStoreManager$StoreThread.run(DataStoreManager.java:236)

**Comment by Rocologo** [comment]
I have actually found a MobHunting error in the log fthis is probably the reason for the problem.  I cant tell why you get at ConcurrentModification on your server and I dont get it on my server, but now I have something to look at when I get home from work. 

[15:11:26] [BGC StoreThread/WARN]: Exception in thread "BGC StoreThread" java.util.ConcurrentModificationException
[15:11:26] [BGC StoreThread/WARN]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[15:11:26] [BGC StoreThread/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
[15:11:26] [BGC StoreThread/WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
[15:11:26] [BGC StoreThread/WARN]: 	at MobHunting-8.1.5.jar//one.lindegaard.Core.rewards.RewardBlockManager.save(RewardBlockManager.java:83)
[15:11:26] [BGC StoreThread/WARN]: 	at MobHunting-8.1.5.jar//one.lindegaard.Core.storage.DataStoreManager$StoreThread.run(DataStoreManager.java:236)

**Comment by Innesity** [comment]
> I have actually found a MobHunting error in the log file you send me. This is probably the reason for the problem. I cant tell why you get at ConcurrentModification on your server and I dont get it on my server, but now I have something to look at when I get home from work.
> 
> [15:11:26] [BGC StoreThread/WARN]: Exception in thread "BGC StoreThread" java.util.ConcurrentModificationException [15:11:26] [BGC StoreThread/WARN]: at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) [15:11:26] [BGC StoreThread/WARN]: at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630) [15:11:26] [BGC StoreThread/WARN]: at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628) [15:11:26] [BGC StoreThread/WARN]: at MobHunting-8.1.5.jar//one.lindegaard.Core.rewards.RewardBlockManager.save(RewardBlockManager.java:83) [15:11:26] [BGC StoreThread/WARN]: at MobHunting-8.1.5.jar//one.lindegaard.Core.storage.DataStoreManager$StoreThread.run(DataStoreManager.java:236)

Okay. Take your time man, and thanks for your help!

**Comment by Rocologo** [comment]
Your welcome. It was exactly errors like this I was looking for. Its always a problem to find error which I dont see on my own Two servers and this one I have never seen, but I think I know how to solve it.

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: Stefan ***@***.***>
Sendt: 12. august 2022 12:42
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [Rocologo/MobHunting] The server won't stop (Issue #747)


I have actually found a MobHunting error in the log file you send me. This is probably the reason for the problem. I cant tell why you get at ConcurrentModification on your server and I dont get it on my server, but now I have something to look at when I get home from work.

[15:11:26] [BGC StoreThread/WARN]: Exception in thread "BGC StoreThread" java.util.ConcurrentModificationException [15:11:26] [BGC StoreThread/WARN]: at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) [15:11:26] [BGC StoreThread/WARN]: at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630) [15:11:26] [BGC StoreThread/WARN]: at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628) [15:11:26] [BGC StoreThread/WARN]: at MobHunting-8.1.5.jar//one.lindegaard.Core.rewards.RewardBlockManager.save(RewardBlockManager.java:83) [15:11:26] [BGC StoreThread/WARN]: at MobHunting-8.1.5.jar//one.lindegaard.Core.storage.DataStoreManager$StoreThread.run(DataStoreManager.java:236)

Okay. Take your time man, and thanks for your help!

**Comment by Rocologo** [comment]
Please test this snapshot and see if the ConcurrentModificationException disapears. And if you still have problems with closing the server.

https://jenkins.lindegaard.one/job/MobHunting/121/

Let me know the result :-)

**Comment by NeverGrowUp** [comment]
Can confirm that im getting a similar issue as above on our production server. Although we never see the "ConcurrentModificationException" error. But i notice that the `rewards.yml` in BoG does not update periodically as defined by `save_period: 6000` in `bagofgoldcore.yml`

Testing locally with the above snapshot, i can confirm the save period now works. Although testing locally i've never had the problem of it just hanging on shutdown. (but does happen on live server everytime, and need to soft kill the session.)

Will endeavour to test on our live server tomorrow.

**Comment by NeverGrowUp** [comment]
Sorry. My burst above may have been misleading. The updated build 121 you linked above seems to have fixed the issue. (for us)
Tested on our live server and all seems to be going ok, and getting successful shutdowns. Also now seeing the periodic saves of `[BagOfGoldCore][MobHunting] [Debug] Saved 966 rewards to disk` as defined by `save_period: 6000` in `bagofgoldcore.yml`.

So, so far so good!! Thx

**Comment by Rocologo** [comment]
Perfect. I will see if I can make a release tonight or tomorrow so this bug can be fixed for others too. Thank you for your help.

**Comment by Rocologo** [comment]
Version 8.1.7 released with this fix

**Comment by AlohaLegend** [comment]
Hello, popping into this closed thread. I had this issue during this period - See above. Everything has worked since this release. Then yesterday after making no chances to mobhunt it started happening again. Now my server will not shut down correctly. I see there is an error with my customitemslib. I will be deleting the customitemslib config folder to see if a fresh install config might resolve the situation(I have done this before). I'm currently running the latest paper build 1.19.3. If you need anything else from me let me know. Thanks in advance.

**Comment by Rocologo** [comment]
I need to see the error you talk about? 

In most cases this type of error cased bu an SQL error. Please check your server log for errors and show me the error

**Comment by AlohaLegend** [comment]
Update on this - I was going to run a mh debug restart but it would seem that deleting the customitemslib folder resolved the issue. Will update if it happens again.
