### ISSUE TITLE
Heads

### ISSUE THREAD

**Issue by SinistersGrin** [Rocologo/MobHunting#752]
Not sure if this is the place for this but no discord i could find.

doesn't matter the mod we kill or the player we kill it always drops a Steve head, sometime with a very long Lore and others just normal lore, but tis always a Steve head

this is on a 1.19.2 paper server

**Comment by Rocologo** [comment]
The Lores can be removed if you install protocollib 

But you must have a problem if all heads become a Steve head??? 

Please enable debug mode start your server and check the server log for errors.
