### ISSUE TITLE
MobHeads default to Steve head in inventories.

### ISSUE THREAD

**Issue by Tehelee** [Rocologo/MobHunting#76]
Chests containing the ExtendedMobHead skulls reset the skull to a Steve skull after close / open.
Skulls also reset in player inventories after logout / login.
Skulls are only persistent if placed on walls.

**Comment by Rocologo** [comment]
I have worked on the head. Its better but not perfect. Some of the skulls will reset after a disconnect. This is a limitation in Minecraft and the Minecraft give commend which I use in this plugin to give heads. 

Try V3.3.6
