### ISSUE TITLE
/mobhunt command

### ISSUE THREAD

**Issue by johnsoia** [Rocologo/MobHunting#760]
When I try to do a command all I get is /mobhunt command

**Comment by Kanbale** [comment]
omg i got the same issue :( How to solve it at all ? i couldnot even use /mh debug!

|[23:01:38] [MH StoreThread/WARN]: Exception in thread "MH StoreThread"
|[23:01:38] [MH StoreThread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin 
|attempted to register task while disabled
|[23:01:38] [MH StoreThread/WARN]: 	at 
|org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:479)
|[23:01:38] [MH StoreThread/WARN]: 	at
|org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:147)
|[23:01:38] [MH StoreThread/WARN]: 	at 
|org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:130)
|[23:01:38] [MH StoreThread/WARN]: 	at 
|org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:113)
|[23:01:38] [MH StoreThread/WARN]: 	at one.lindegaard.MobHunting.storage.DataStoreManager
|$StoreThread.run(DataStoreManager.java:300)

i got these in my console

**Comment by Rocologo** [comment]
I looks like you are having a database problem, and that there is no write access to the database?

**Comment by Kanbale** [comment]
my database type is sqlite, i delete mobhunting.db and restarted the server, it could create a new one. 
I changed the database version from 0 to 1, and restarted the server. But it didnt try to edit the db file. The last edited date of the database was not changed. There were no Warn or Error in my console after the restart.
Besides, why does database affect all my command? Every command I tried returns '/mh commad' and has no effects.

**Comment by Rocologo** [comment]
Why did you change the database version to 1?

**Comment by Kanbale** [comment]
I want to check if it has access to edit the database

**Comment by Kanbale** [comment]
Now i changed it to 0 again. This time I used PlugmanX to reload the plugin. There are no Warn now. But I still cannot use any commands

**Comment by Rocologo** [comment]
You should not change this value, only in special cases

**Comment by Rocologo** [comment]
I cant guess what you exactyly have done but if you have an empty new database file, you should be able to set the version to 8

**Comment by Kanbale** [comment]
ok, i changed it to 8 now. I reload the plugin and still get the same issue.
btw. the /mh command issue existed before I changed this version. :(

**Comment by Kanbale** [comment]
oh, my plugin version is 5.7.2. I saw that the newer version didnt suppert 1.12Game, did it?

**Comment by Rocologo** [comment]
Make sure debug is enabled and the restart the server and let me see the full server log. Use pastebin.com or similar  I need to see what other information you get. The error text in the end does not tell why you are having problems

**Comment by Rocologo** [comment]
It is very long time since I tested Mc 1.12 so I don't know. My focus is the newest version, because the are so few people who uses 1.12

**Comment by Kanbale** [comment]
It seems that /mh debug didnt work

**Comment by Rocologo** [comment]
![image](https://github.com/Rocologo/MobHunting/assets/1008133/fa37739b-aa40-48ef-931b-857d997a14fc)

My plugin is made for Spigot and Craftbukkit servers and you are using Forge. I dont think this will ever work, and I can see that you are having TONS of errors in you server log which is casued by the same problem. That you use spigot/craftbukkit plugins on a Forge server. 

the commands are not working becase the plugin fails before it is started. Because og Forge. 

Im sorry I cant help you with Forge.

**Comment by Kanbale** [comment]
I tried the newest version. It didnt support 1.12Game. But v7.5.7 DID run successfully in my server. I can use commands without any error this time. Soooo weird isn't it?

**Comment by Rocologo** [comment]
It is not the version number, It is forge.

**Comment by Kanbale** [comment]
omg Here it wrote 1.6.5! That was 1.16.5 infact

**Comment by Kanbale** [comment]
So sorry for wasting you so much time. My Bad TAT

**Comment by Rocologo** [comment]
No worries.

**Comment by Kanbale** [comment]
Thanks a lot :)

**Comment by Rocologo** [comment]
@Kanbale Thank for your donation :-) That wasn't needed. I do this for fun and it is a kind of hobby for me. But thank you anyway :-)
