### ISSUE TITLE
Exception caused by Tardis integration (MobHunting v3.3.6)

### ISSUE THREAD

**Issue by meoso** [Rocologo/MobHunting#78]
Disabled TardisWeepingAngels integration, yet Exception still occurs at startup:

` disable-integration-tardis-weeping-angels: true `

`[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-af8198d-8cc5958 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)`

Exception Stack:  http://pastebin.com/pXTPDHdv

**Comment by meoso** [comment]
A+ 3.3.7 did not have exception at startup.

**Comment by Rocologo** [comment]
I did alot of testing before the 3.3.6 release because the new infegration. The only thing i forgot to test was, if TARDISWeepingAngels was NOT installed. The only change in v3.3.7 is a fix for this.
