### ISSUE TITLE
Mobs can pickup money items

### ISSUE THREAD

**Issue by SpaZMonKeY777** [Rocologo/MobHunting#79]
So on my server, we have it set so mobs can drop gold nuggets as the 'money item' for them to pick up and gain money.

But with certain mobs, like zombies, if they walk over the items, they can sometimes pick them up. And when killed, they drop the actual gold nugget on the ground as well. Hoping this can be fixed, so my players don't abuse this :P

**Comment by Rocologo** [comment]
I have actually spend some time on this problem, but unfortunately it is VERY VERY limited what can be done about this. I will look at it again but Im pretty sure that I cant do anything because Bukkit/Spigot does not support this

**Comment by Rocologo** [comment]
I have Googled the problem. And it cant be solved. The Bukkit API only handle PlayerPickupItemEvent but it has not EntityPickupEvent and there I can do anything about this problem.

I will need to close this ticket - unsolved. :-(

**Comment by Rocologo** [comment]
https://www.spigotmc.org/threads/solved-no-entity-item-pickup-event.59891/

**Comment by SlimeDog** [comment]
I have seen zombies pick up Bag of Gold items and wear them as heads. When I kill them, they drop the bag (along with the reward for killing them), which I pick up into inventory. If I drop the bag on the ground (Q), I can pick it up and gain the reward. I think this is an acceptable behavior.
