### ISSUE TITLE
Reload breaks plugin.

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#8]
This ticket is more of a personal whim, I'd like to reload this plugin on-the-fly with PlugMan, however it's not possibile for a NPE.
This NPE reflects over Kill messages, breaking the plugin.

There might be 2 other bugs with Citizens Integration and MySQL Statements executed after plugin disabling.

http://pastebin.com/6S2RMwQU

**Comment by Rocologo** [comment]
I guess I have to look at PlugMan.

**Comment by Rocologo** [comment]
See [Ticket 9](https://github.com/Rocologo/MobHunting/issues/9)

**Comment by Rocologo** [comment]
I have found the problem. Next release V2.8.8 can be reloaded with Plugman without errors. Let me know if there is other problems. I close the ticket now.
