### ISSUE TITLE
Metrics error with Bounties

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#82]
Hello, I get [THIS](http://pastebin.com/JQ3FqWnn) error every 5 minutes because of an NPE with Metrics system.

I think this is caused because the Bounty Module doesn't start when reloading plugin, causing the check to not return 0 (as config says is not disabled), but the BountyManager is not started, so it gives an NPE.

**Comment by Maxetto** [comment]
Same NPE is printed too on [PlayerDeathEvent](http://pastebin.com/qGFRV14m).

So yeah, Bounty Module is not loaded when activated via a Reload

**Comment by Rocologo** [comment]
Correct. Bounties was not loaded for online players when reloaded so BountyManager was null and returned an NPE. 

This should be fixed in this newest version (Build 79 or newer) on my Jenkins Server.

**Comment by Maxetto** [comment]
The NPE is fixed, however the BountyCommand doesn't seem to be loaded in the reload.

31.07 15:45:04 [Server] INFO CONSOLE issued command: /mh bounty
31.07 15:45:04 [Server] INFO Nessun comando specificato: /mh <command>
31.07 15:45:04 [Server] INFO Alcuni comandi validi sono:
31.07 15:45:04 [Server] INFO achievements, select, debug, learn, update, mute, checkgrinding, version, head, help, database, leaderboard, reload, top, cleargrinding, whitelistarea, region

After a reload, the bounty command is correctly loaded.

**Comment by Maxetto** [comment]
In latest Dev version permissions doesn't work anymore (Event after a full restart).

It only works when you have "*" as permission.

- mobhunting.bounty
- mobhunting.cmd
- mobhunting.enable
- mobhunting.learn
- mobhunting.listachievements
- mobhunting.mobs.*
- mobhunting.mute

**Comment by Maxetto** [comment]
Besides that I cannot use commands, rewards are given, but they doesn't show in ActionBar (With ActionBarAPI)

**Comment by Maxetto** [comment]
Another issue:

With Debug Mode, if a player leaves and you have BattleArena, [THIS](http://pastebin.com/tiwPdfwL) error is printed.

**Comment by Maxetto** [comment]
Sent a PR trying to fix the ActionBarAPI bug.

**Comment by Rocologo** [comment]
The Bounty - reload problem is fixing in V3.3.8

**Comment by Rocologo** [comment]
It not that good that you are bundling the issues - then I don't see when you report "new" problems. 

Anyway. I misunderstood the reload problem. I though it was /reload and not /mh reload you were talking about. The bouties and player settings are now read from the database for online players if you do a / mh reload. Please try /mh reload in Build 84 or newer in the jenkins server.

http://jenkins.lindegaard.one:8180/job/MobHunting/

I have some problems with the ActionBar because there are more than one plugin with that name. Could you please send me a Link to the one you are using. 

As of you permission problem - I have not changed anything in the permission system. Maybe you have made an error on your server?

**Comment by Maxetto** [comment]
I'm using v1.4.2 of this ActionBarAPI: https://www.spigotmc.org/resources/actionbarapi-1-8-1-9-1-10.1315/

As permission, it doesn't seem so. Permissions are OK, they are the same as in plugin.yml and inside code. They worked before, but now works partially (only commands not works).

**Comment by Rocologo** [comment]
I have just tested MobHunting+PermissionsEx and it works on both my test server and my PROD server??? 

If I dont have permission "mobhunting.mobs.*" in my permission file i get the message in the console log.

> [15:25:13 INFO]: [MobHunting][Debug] Permission 'mobhunting.mobs.*' or 'mobhunting.mobs.ZOMBIE' not set, defaulting to True.

And I got the reward.

I also tried to remove a permission to kill spiders and that worked too.

> - -mobhunting.mobs.Spider

I didnt get a reward when killing a spider and I got a learn message in the BossBar that I had no permission.

**Comment by Rocologo** [comment]
I use the same ActionBarAPI but version 1.5.2 (I don't know if this makes a difference). 

And the ActionBarAPI works fine. I get the "You found xx$" in the ActionBar. ???

**Comment by Rocologo** [comment]
The BattleArena error is fixed in Build 84 too. I was a simple typo-error.

**Comment by Maxetto** [comment]
I get the rewards too, but I can't use commands and I don't know why. PEX Debug shows nothing relative to MobHunting permissions.

Regarding the ActionBarAPI, I'll try with the build with my fix and report back.

**Comment by Maxetto** [comment]
The Permissions Bug is something related to the plugin.yml.

By removing every mention of "mobhunting.cmd" permission, everything works fine.

**Comment by Rocologo** [comment]
I sorry to say that it is a bit hard to understand what you write - maybe you have tested too much and "forget" to tell me small details. 

> I get the rewards too, but I can't use commands (and I don't see Achievement progress) and I don't know why. PEX Debug shows nothing relative to MobHunting permissions.

I only use permissions for to allow the player to use "/mh achievements". I don't think the permissions has any influence on WHAT you actually see in the GUI/List.

For EDIT3 - I just tested "/mh achivements" on my server and I see all started achievements in one inventory and all "not-started-achievements" in the second inventory. So you need to explain in details whats wrong. (And this has nothing to do with permissions).

**Comment by Rocologo** [comment]
I looked at the mobhunting.cmd permission - which is only mentioned in plugin.yml and is used when/if you don't have a permission plugin. I dont know which effekt it has - if you put "mobhunting.cmd" in your permissions.yml - I would have said that it has no effekt, but it seems that it has given you some problems.

**Comment by Maxetto** [comment]
With or without the "mobhunting.cmd" permission is the same.

Maybe I just have to do a full restart of the server, instead of using /mh reload.

Will try tonight

**Comment by Maxetto** [comment]
No. Still nothing fixed.

Can't use /mh commands. Tried with all permissions, no permissions, * wildcard and just the permission for /mh bounty command.

Achievements doesn't show neither in GUI or in chat. But they are still active and completable and they are broadcasted fine.

Bounties are lost after a restart.

Might it be a failed update of the database? I have no more ideas.

**Comment by Rocologo** [comment]
If you cant use "/mh archivements" at all then i has nothing to do with the database. you only need "mobhunting.archivements" to use the command - no matter the output. 

I think I need to see your permissions file to understand how it looks. 

If you type "/mh" no more the output should be like this - and then you should see the /mh commands you have permission to use.
![2016-08-01_18 32 18](https://cloud.githubusercontent.com/assets/1008133/17301262/5d905a8e-5816-11e6-91e7-34eb63ae935f.png)

**Comment by Rocologo** [comment]
PS. fix only one problem at a time. :-) don't make a lot of changes before each test. 

I need to understand if "/mh" gives you something like the above, because it tells me if there is a problem with your permission file. If the list is empty there is a problem with your permissions.

**Comment by Maxetto** [comment]
I solved the issue with permissions.

I had "mobhunting.learn" negated, and it also negated the "mobhunting.cmd" permission.

However I don't want to give permission to use "/mh learn".

**Comment by Maxetto** [comment]
So it's only missing the empty Achievement list and the bug with Inventory that can both be discussed in the other Ticket.

I'll close this.
