### ISSUE TITLE
Picking money drops doesn't give gringotts.

### ISSUE THREAD

**Issue by samchelini** [Rocologo/MobHunting#83]
Hey,

I have been trying to get money drops to work with gringotts but there is an annoying issue. When I kill a mob, the money drops on the ground, but it doesn't go in my inventory when I pick it up. The only thing I have changed in the config is:
drop-money-on-ground: true
drop-money-on-ground-item: EMERALD
drop-money-on-ground-text-color: GREEN

Also, I can see the emeralds and emerald blocks when they drop, but there is no text above them. And mobhunting works fine with gringotts when drop-money-on-ground is false.

**Comment by Rocologo** [comment]
This is fixed in V3.3.8 :-)

**Comment by Rocologo** [comment]
PS. There is currently now text above Gringotts Items, because it will confuse Gringotts. So I cant make that for you.
