### ISSUE TITLE
Mobhunting not installing new jar on update

### ISSUE THREAD

**Issue by krustymk** [Rocologo/MobHunting#85]
Hi, the last couple of updates have disabled the old jar but not installed the new one
any ideas?
Top plugin by the way :) love it!!

**Comment by Rocologo** [comment]
Sounds strange. I have to do some testing.

**Comment by Rocologo** [comment]
Curse.com had changed something on their website which broke my updater.

This is fixed in next release. (which means that your NEXT update will fail too...) but NEXT NEXT will work again.

**Comment by Rocologo** [comment]
Or you can try build 89 or newer on my jenkins server and then the updater will work again

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by krustymk** [comment]
Thanks for looking, ive stopped the auto update for the time being as a temp fix.
Thanks for a great plugin and quick fix :)
How can i buy you a drink or pizza or what ever you have? I see no button?

**Comment by Rocologo** [comment]
I know its hard to find :-)

https://paypal.me/rocologo

**Comment by Rocologo** [comment]
I guess you are Jason?

**Comment by krustymk** [comment]
Yh thats me :)

**Comment by Rocologo** [comment]
Then I say thank you very much! I'm very happy that someone appreciate the hard work. I have spend much more time on the plugin than you can imagine! Development is only my hobby. I'm engineer an love to make thing work.
