### ISSUE TITLE
Husk and Zombie stats stacking

### ISSUE THREAD

**Issue by zaxanq** [Rocologo/MobHunting#86]
Hey, one of the issue we found is the fact that if you kill a Husk, you get +1 mob kills to both Zombie_Kills and Husk_Kills. If the issue was previously submitted, then I apologize. :)

**Comment by Rocologo** [comment]
It has not been reported

Have you checked if there is the same problem with Stray ans Skeleton?

**Comment by zaxanq** [comment]
I just checked it and no, it doesn't add one to Skeleton kills when I kill a Stray.

**Comment by Rocologo** [comment]
I just killed a Husk and it did not add one to Zombie_kills ???

**Comment by zaxanq** [comment]
Oh, I made a mistake. I didnt mean Zombie_Kills as in /mh top Zombie_Kills, but in achievements. If I kill, the count is bigger by one.
http://imgur.com/a/96xIC

**Comment by Rocologo** [comment]
Okay, now i found the bug. i should be fixed in build 90 if you want to help testing.

**Comment by Rocologo** [comment]
Fixed in v3.3.9
