### ISSUE TITLE
No Sniper "Bonus" edit possibility in config

### ISSUE THREAD

**Issue by zaxanq** [Rocologo/MobHunting#87]
Hey, I've found it odd that you can't change multiplier about "Sniper", judging by the green color, "Sniper" bonus. If you shoot a mob with bow, the multiplier is set to 0.7, unless it's from far distance. Giving the option in config would be great! :)

**Comment by Rocologo** [comment]
You have the setting in config its called far-shot doesnt it work?

**Comment by zaxanq** [comment]
If I shoot from a really far distance, I get Pro-Sniper (in my case it's x1.3), if from close range, it's normal kill. But mid range is an "Sniper", x0.7.
http://imgur.com/a/Q3adq

**Comment by Rocologo** [comment]
I found the bug. Going forward sniper will be calulated as half of far-shot like this
bonus = 1 + ((far-shot-1)/2) in your case this will be 1.15

**Comment by Rocologo** [comment]
Fixed in V3.3.9
