### ISSUE TITLE
No heads given to certain players

### ISSUE THREAD

**Issue by zaxanq** [Rocologo/MobHunting#88]
Another issue I've found is the fact that myself with name "Dzonas" can receive both items (in this case emeralds) and mob heads, but other player, on the same server, in the same time, called "Meow." (probably the issue lies in the  dot?) only receives emeralds. There is notification about receiving the head, but it is not in the inventory. The inventory is not full. Please fix it:)

[edit]
It's certain now, as we checked her with other name, without the dot and it worked just fine.

**Comment by Rocologo** [comment]
Okay - thats a strange bug. Im using minecraft give command to give heads, if the give command dont support the . I cant fix this problem. I will investigate.

**Comment by zaxanq** [comment]
If I try to give "Meow." a head by command it says that this player is not online. Thanks in advance for future patches :)

**Comment by Rocologo** [comment]
if you get the error "Meow. is not online" then I have problem. It should work and I cant see any errors. 

It tells me that Bukkit.getOfflinePlayer(name)has this bug and I cant fix bukkit errors.

**Comment by zaxanq** [comment]
Okay then. If by any chance you can, please report this bug to them (you're a mod developer so I guess you can). Thanks for help.
