### ISSUE TITLE
Could not pass event EntityDeathEvent 

### ISSUE THREAD

**Issue by Alphexon** [Rocologo/MobHunting#9]
Error Log: http://pastebin.com/b5MgGbfC
Configuration: http://pastebin.com/fPdxB6HG

**Spigot Version:** 1.9.2 R0.1
**Plugin Version:** 2.8.6

This error occurs whenever I kill a monster to get money. This error only occurs after loading the plugin into the server using PlugMan. Loading on startup works fine.

**Comment by Maxetto** [comment]
Related to mine ticket:
https://github.com/Rocologo/MobHunting/issues/8

You need a full restart ATM.

**Comment by Rocologo** [comment]
I think I have found the problem when you reload the plugin. My PlayerSettings was empty after a reload while it should have contained all online players and their settings. I have added code in my plugin, so it now read playerSettings from the database onEnabled / reload if there is players online.

I dont know if this fixes all problems onReload so please post new errors.

I will release V2.8.7 later today.

**Comment by Maxetto** [comment]
Still [NOT](http://pastebin.com/3gksFVvD) working.
This time is an "UnsupportedOperationException".

I seem to get Rewards after a /mh reload, but other players still have errors.

Using the official Spigot 1.8.8 version.

**Comment by Rocologo** [comment]
Okay I will make the test on my 1.8.8 test server, to see if I can reproduce this error.

**Comment by Rocologo** [comment]
I have found the problem. Next release V2.8.8 can be reloaded with Plugman without errors. Let me know if there is other problems.
