### ISSUE TITLE
PVP can set the beheading of chance?

### ISSUE THREAD

**Issue by xyblues** [Rocologo/MobHunting#90]
I don't want the player to be sure to get the heads of others.
Sorry for my poor English

**Comment by Rocologo** [comment]
I will add parameters to config.yml so you can control the change of getting a player head in next release.

**Comment by Rocologo** [comment]
I finally found some time to add this feature. 

Please test Build 108 or newer on my Jenkins server http://jenkins.lindegaard.one:8180/job/MobHunting/ and get back to me if it works. Default chance is set to 50%

Install the snapshot JAR file and restart server

If you want a lower chance than 50% you will have to edit config.yml and restart the server once more.

Please get back to me and confirm if the fix works.

**Comment by xyblues** [comment]
Thank you very much. It works very well.
Sorry to reply so late, I have something to go out.
