### ISSUE TITLE
NoSuchMethodError: org.bukkit.entity.Zombie.getVillagerProfession()

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#91]
In latest version, with Spigot 1.8.X (and probably 1.9.X), you get this error everytime someone kills a Zombie.
This is due to the non-existance of Husk Zombie in versions prior to 1.10.

http://pastebin.com/4bqPUGTZ

**Comment by Rocologo** [comment]
Fixed in V3.4.0  - I hope :-)

**Comment by Maxetto** [comment]
Fix confirmed.
