### ISSUE TITLE
Some permissions not working

### ISSUE THREAD

**Issue by ReaperAngels** [Rocologo/MobHunting#95]
Hi. On spigot 1.10, using pex. When I give mobhunting.listachievements, players still get "Insufficient permission". This after a full restart. Same for bounty, and some others. As owner I can do all of the commands, so I'm assuming there is something missing? from the permissions. Hope to hear from you soon.

Ragards,

**Comment by Rocologo** [comment]
Hi there, you forgot to tell me WHEN it happens? What are your users trying to do when the get "Insufficient permission". Which command are they executing?

**Comment by ReaperAngels** [comment]
Hi. When they try to execute something innocent like /mh bounty (player) (amount) or most importantly /mh achievements.

**Comment by Rocologo** [comment]
Your players need "mobhunting.enable" to use MobHunting in general and to use /mh bounty the will need "mobhunting.bounty"

"mobhunting.listachievements" is for /mh achievements

**Comment by ReaperAngels** [comment]
This is from my pex file.
    - mobhunting.enable
    - mobhunting.learn
    - mobhunting.bounty
    - mobhunting.listachievements
    - mobhunting.top
    - mobhunting.mob.cow
    - mobhunting.mob.rabbit
    - mobhunting.mob.sheep
    - mobhunting.mob.pig
    - mobhunting.mob.chicken

**Comment by Rocologo** [comment]
It looks fine, but as a test you should give the players 

- mobhunting.mob.*

and check if this is your problem. I have not tested the individual mob permissions lately. Maybe you have found a bug. 

Is it your intension that the only get rewards if they kill a cow, rabbit, sheep, pig or a chicken? (Because this is what you have put in your permissions).

**Comment by ReaperAngels** [comment]
They actually get rewards for all mobs except those. OK, tested, still insufficient permissions. And I removed the cow, chicken, sheep, etc from pex and just added mobhunting.mobs.*

**Comment by Rocologo** [comment]
Just set the prize to 0 in config.yml if you dont want the players to get rewards for killing passive mobs. This is default by the way.

Could you please write the exact error message when they dont have permission, because if they dont have permission to do /mh bounty .... the error will be something like

"You do not have permission (mobhunting.bounty) to use /mh bounty"

And please check the server console for errors. Also try to enable debug with "/mh debug" and check the console.

**Comment by Rocologo** [comment]
Just to make it clear. Mobhunting does never respond "Insufficient permission" so if this is the error text they get it is from another plugin.

**Comment by Rocologo** [comment]
This is completely wrong by the way!!! :-)

- -mobhunting.whitelist
- -mobhunting.select
- -mobhunting.leaderboard
- -mobhunting.top
- -mobhunting.checkgrinding
- -mobhunting.head
- -mobhunting.learn.other
- -mobhunting.version
- -mobhunting.update
- -mobhunting.reload
- -mobhunting.region
- -mobhunting.npc
- -mobhunting.unmute
- -mobhunting.mute
- mobhunting.*

**Comment by Rocologo** [comment]
Maybe you could show me your complete permissions.yml file and let me check it. (Mobhunting part only)

Please use pastebin.com so I get the raw file.

**Comment by ReaperAngels** [comment]
Oh, I agree that to negate all the OP permissions is totally wrong. And it will be PEX that give the "Insufficient Permissions". However, the negating was done to see if there was a problem with the permissions, or something else. It was not something else. I can do all the commands. And I am OP on the server. With the permissions on the spigot page, my test player, Mclagger,  gets "Insufficient Permissions". 
http://pastebin.com/index/KqbhDZNP

**Comment by ReaperAngels** [comment]
I had chatcontrol installed. removed it and it started to work. So I would surmise you have an incompatibility

**Comment by Rocologo** [comment]
Ahhh, do you have a link for that plugin? Then I will see if it is something I can fix.

**Comment by Rocologo** [comment]
Actually I think it is a problem with chatcontrol. I can not see how i can fix that chatcontrol blocks mobhunting?

**Comment by Rocologo** [comment]
Or if you have configured chatcontrol yourself, and changed the files in the rules folder, then you can easily breake something, which never can be fixed in MobHunting or anyother plugin.

**Comment by Rocologo** [comment]
Are you still having problems?
