### ISSUE TITLE
Leaderboards not refreshing.

### ISSUE THREAD

**Issue by danimors** [Rocologo/MobHunting#96]
I have set up a few Citizens2 npcs, and put in the proper commands. Even when you right click them though, they never seem to refresh.  

The players that have gone out of their way to kill sheep and other mobs, do not show up on the npc, and they do not have OP, nor fly, nor are in a region.

**Comment by danimors** [comment]
*it seems that only the passive mobs are causing an issue.

**Comment by Rocologo** [comment]
Try enabling debug mode and learn mode before killing a passive mob, and check console output for information.

/mh debug
/mh learn

**Comment by danimors** [comment]
Nothing happens. In console, nor in game. It's only when I am killing the passive mobs...

**Comment by danimors** [comment]
13.09 15:33:44 [Server] INFO [MobHunting][Debug] random double=0.10676034967073733 < chance=0.0
13.09 15:33:44 [Server] INFO [MobHunting][Debug] KillBlocked PhantomSyndrome: Gained money was less than 1 cent (grinding or penalties) (x2.0§f * Difficulty)

**Comment by danimors** [comment]
It is a random passive in the wild.

**Comment by danimors** [comment]
Nevermind. I figured out the issue! Thank you so much!
