### ISSUE TITLE
Achievements failed to load from MySQL

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#98]
Hi, I have a problem where this happens if the server is up for maybe 6-8 hours and the plugin dcs from mysql.

Ingame:
https://gyazo.com/2725c19a0d2179ce4db5a42413f0b0c9

Console error:
http://pastebin.com/GxyzCg2j

**Comment by Rocologo** [comment]
Hi, this happens if your connection between the Minecraft server and your MySQL server is broken. I can happen if your SQL server is different from your Minecraft server and you are having a network problem. 

I already use "AutoReconnect=true" as recommended.

> DriverManager.getConnection(
> 					"jdbc:mysql://" + MobHunting.getConfigManager().databaseHost + "/"
> 							+ MobHunting.getConfigManager().databaseName + "?autoReconnect=true",
> 					MobHunting.getConfigManager().databaseUsername, MobHunting.getConfigManager().databasePassword);

**Comment by Rocologo** [comment]
You could try to change wait_timeout like others has done http://stackoverflow.com/questions/5060106/losing-connection-to-mysql-after-a-while-and-not-reconnecting

**Comment by Nesseley** [comment]
You are right, the problem is now fixed by my host.
They edited wait_timeout.

Thank you alot! :)
